import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,BriefcaseBusiness,Building2,Check,Mail,RefreshCw,Send,ShieldCheck,UserPlus,Users,X} from 'lucide-react';
import type {CommunityMember} from '../../types/repaidians';
import type {NetworkConnection,NetworkConnectionsPage,NetworkPreferences,NetworkRecommendation,NetworkRecommendationsPage} from '../../types/repaidiansNetwork';
import {decideRecommendation,networkConnections,networkPreferences,networkRecommendations,subscribeNetworkReads,updateConnection,updateNetworkPreferences} from '../../services/repaidiansNetworkService';
import {Avatar,tradeName} from './common';
import './professional-network.css';

export function useNetworkResource<T>(key:string,load:(force:boolean,signal:AbortSignal)=>Promise<T>,enabled=true){
  const loader=useRef(load);loader.current=load;
  const [state,setState]=useState<{key:string;data:T|null;busy:boolean;error:string}>({key,data:null,busy:enabled,error:''});
  const [revision,setRevision]=useState(0),sequence=useRef(0),controller=useRef<AbortController|null>(null),mounted=useRef(true);
  const refresh=useCallback(async(force=true)=>{
    if(!enabled)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;const stamp=++sequence.current;
    setState(prior=>({key,data:prior.key===key?prior.data:null,busy:true,error:''}));
    try{const data=await loader.current(force,abort.signal);if(mounted.current&&sequence.current===stamp&&!abort.signal.aborted)setState({key,data,busy:false,error:''});}
    catch(error){if(mounted.current&&sequence.current===stamp&&!abort.signal.aborted)setState(prior=>({...prior,data:[401,403,404].includes((error as {status?:number}).status||0)?null:prior.data,busy:false,error:(error as Error).message}));}
  },[key,enabled]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++;controller.current?.abort();};},[]);
  useEffect(()=>subscribeNetworkReads(()=>setRevision(value=>value+1)),[]);
  useEffect(()=>{void refresh(false);return()=>{sequence.current++;controller.current?.abort();};},[refresh,revision]);
  return {...(state.key===key?state:{key,data:null,busy:enabled,error:''}),refresh};
}
export function NetworkError({error,onRetry}:{error:string;onRetry?:()=>void}){return error?<div className="rp-network-error" role="alert"><p>{error}</p>{onRetry&&<button onClick={onRetry}>Retry</button>}</div>:null;}
export function NetworkPerson({member,onOpenMember}:{member:CommunityMember;onOpenMember?:(id:string)=>void}){
  const label=<><Avatar member={member}/><span><strong>{member.name}</strong><small>{member.headline||tradeName(member.trade)}{member.city?' · '+member.city:''}</small></span></>;
  return onOpenMember?<button className="rp-network-person-title" onClick={()=>onOpenMember(member.id)} aria-label={'Open '+member.name+' profile'}>{label}</button>:<div className="rp-network-person-title">{label}</div>;
}
export function ConnectionActions({connection,busy,onAction}:{connection:NetworkConnection;busy:boolean;onAction:(action:'request'|'accept'|'decline'|'cancel'|'remove')=>void}){
  return <div className="rp-network-actions">{connection.status==='incoming'?<><button className="rp-network-primary" disabled={busy} onClick={()=>onAction('accept')}><Check size={16} aria-hidden="true"/>Accept connection</button><button className="rp-network-secondary" disabled={busy} onClick={()=>onAction('decline')}><X size={16} aria-hidden="true"/>Decline</button></>:connection.status==='outgoing'?<button className="rp-network-secondary" disabled={busy} onClick={()=>onAction('cancel')}>Cancel invitation</button>:connection.status==='connected'?<button className="rp-network-secondary" disabled={busy} onClick={()=>onAction('remove')}>Remove connection</button>:connection.canRequest?<button className="rp-network-primary" disabled={busy} onClick={()=>onAction('request')}><UserPlus size={16} aria-hidden="true"/>Connect</button>:null}</div>;
}
function uniqueBy<T>(items:T[],id:(item:T)=>string){return [...new Map(items.map(item=>[id(item),item])).values()];}

export interface ProfessionalNetworkProps {accountKey:string;authenticated:boolean;onOpenMember?:(id:string)=>void;onDiscover?:()=>void;onJobs?:()=>void;onCompanies?:()=>void;}
export function ProfessionalNetwork(props:ProfessionalNetworkProps){
  const [mode,setMode]=useState<'connections'|'incoming'|'outgoing'|'recommendations'>('connections');
  return <section className="rp-professional-network" aria-label="Professional network"><header className="rp-network-heading"><div><span className="rp-network-eyebrow">People. Work. Progress.</span><h2>My network</h2><p>Build professional connections and share the work you know.</p></div><Users size={25} aria-hidden="true"/></header><nav className="rp-network-links" aria-label="Network and hiring">{props.onDiscover&&<button className="rp-network-secondary" onClick={props.onDiscover}><UserPlus size={16} aria-hidden="true"/>Find people</button>}{props.onJobs&&<button className="rp-network-secondary" onClick={props.onJobs}><BriefcaseBusiness size={16} aria-hidden="true"/>My jobs</button>}{props.onCompanies&&<button className="rp-network-secondary" onClick={props.onCompanies}><Building2 size={16} aria-hidden="true"/>Companies</button>}</nav>{!props.authenticated?<p className="rp-network-empty">Sign in to manage your professional connections, invitations and recommendations.</p>:<><div className="rp-network-tabs" role="group" aria-label="Network views">{([{id:'connections',label:'Connections'},{id:'incoming',label:'Invitations'},{id:'outgoing',label:'Sent'},{id:'recommendations',label:'Recommendations'}] as const).map(tab=><button key={tab.id} aria-pressed={mode===tab.id} onClick={()=>setMode(tab.id)}>{tab.label}</button>)}</div>{mode==='recommendations'?<RecommendationsPanel key={props.accountKey} {...props}/>:<ConnectionsPanel key={props.accountKey+':'+mode} {...props} mode={mode}/>}<NetworkPreferencesPanel key={props.accountKey} accountKey={props.accountKey}/></>}</section>;
}
function ConnectionsPanel({mode,accountKey,onOpenMember,onDiscover}:ProfessionalNetworkProps&{mode:'connections'|'incoming'|'outgoing'}){
  const resource=useNetworkResource<NetworkConnectionsPage>(accountKey+':connections:'+mode,(force,signal)=>networkConnections(mode,'',force,signal)),[extra,setExtra]=useState<NetworkConnectionsPage|null>(null),[moreBusy,setMoreBusy]=useState(false),[mutation,setMutation]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  const gate=useRef(false),moreGate=useRef(false),alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  const items=uniqueBy([...(resource.data?.items||[]),...(extra?.items||[])],item=>item.memberId),members=new Map([...(resource.data?.members||[]),...(extra?.members||[])].map(member=>[member.id,member])),cursor=extra?extra.nextCursor:resource.data?.nextCursor;
  const act=async(id:string,action:'request'|'accept'|'decline'|'cancel'|'remove',connection:NetworkConnection)=>{
    if(gate.current)return;gate.current=true;setMutation(id);setError('');setMessage('');
    try{await updateConnection(id,action,connection.version);if(!alive.current)return;setExtra(null);await resource.refresh();setMessage(action==='accept'?'Connection accepted.':action==='remove'?'Connection removed.':action==='decline'?'Invitation declined.':action==='cancel'?'Invitation cancelled.':'Invitation sent.');}
    catch(e){if(alive.current)setError((e as Error).message);}finally{gate.current=false;if(alive.current)setMutation('');}
  };
  const more=async()=>{if(!cursor||moreGate.current)return;moreGate.current=true;setMoreBusy(true);setError('');try{const page=await networkConnections(mode,cursor);if(alive.current)setExtra(prior=>({items:[...(prior?.items||[]),...page.items],members:[...(prior?.members||[]),...page.members],nextCursor:page.nextCursor,connectionsCount:page.connectionsCount}));}catch(e){if(alive.current)setError((e as Error).message);}finally{moreGate.current=false;if(alive.current)setMoreBusy(false);}};
  return <><div className="rp-network-section-title"><h3>{mode==='connections'?<Users size={18} aria-hidden="true"/>:mode==='incoming'?<Mail size={18} aria-hidden="true"/>:<Send size={18} aria-hidden="true"/>}{mode==='connections'?'Your connections':mode==='incoming'?'Invitations to connect':'Invitations you sent'}</h3><button className="rp-network-icon" aria-label="Refresh connections" disabled={resource.busy||!!mutation} onClick={()=>{setExtra(null);void resource.refresh();}}><RefreshCw size={17} aria-hidden="true"/></button></div><NetworkError error={resource.error} onRetry={()=>void resource.refresh()}/><NetworkError error={error}/>{message&&<p className="rp-network-status" role="status">{message}</p>}{resource.busy&&!resource.data&&<p className="rp-network-empty" role="status">Loading your network…</p>}{mode==='connections'&&resource.data&&<p className="rp-network-note">{resource.data.connectionsCount.toLocaleString()} accepted connection{resource.data.connectionsCount===1?'':'s'}</p>}<div className="rp-network-list" aria-busy={resource.busy}>{items.map(item=>{const member=members.get(item.memberId);if(!member)return null;return <article className="rp-network-person" key={item.memberId}><NetworkPerson member={member} onOpenMember={onOpenMember}/>{item.note&&<p className="rp-network-person-message">{item.note}</p>}<ConnectionActions connection={item} busy={!!mutation||resource.busy} onAction={action=>void act(item.memberId,action,item)}/>{mutation===item.memberId&&<span className="rp-network-note" role="status">Updating connection…</span>}</article>;})}</div>{!resource.busy&&!resource.error&&!items.length&&<div className="rp-network-section"><p className="rp-network-empty">{mode==='connections'?'Your accepted professional connections will appear here.':mode==='incoming'?'No invitations waiting for your response.':'No pending invitations sent.'}</p>{onDiscover&&<button className="rp-network-secondary" onClick={onDiscover}>Explore professionals<ArrowRight size={16} aria-hidden="true"/></button>}</div>}{cursor&&<button className="rp-network-secondary rp-network-more" disabled={moreBusy||!!mutation} onClick={()=>void more()}>{moreBusy?'Loading…':'More connections'}</button>}</>;
}
function RecommendationsPanel({accountKey,onOpenMember}:ProfessionalNetworkProps){
  const [mode,setMode]=useState<'pending'|'received'|'written'>('pending');
  return <><p className="rp-network-note">Recommendations are written by connections. You approve received recommendations before they appear on your profile.</p><div className="rp-network-tabs" role="group" aria-label="Recommendation views">{([{id:'pending',label:'For your approval'},{id:'received',label:'Received'},{id:'written',label:'Written'}] as const).map(tab=><button key={tab.id} aria-pressed={mode===tab.id} onClick={()=>setMode(tab.id)}>{tab.label}</button>)}</div><RecommendationList key={accountKey+':'+mode} accountKey={accountKey} mode={mode} onOpenMember={onOpenMember}/></>;
}
function RecommendationList({accountKey,mode,onOpenMember}:{accountKey:string;mode:'pending'|'received'|'written';onOpenMember?:(id:string)=>void}){
  const resource=useNetworkResource<NetworkRecommendationsPage>(accountKey+':recommendations:'+mode,(force,signal)=>networkRecommendations(mode,'',force,signal)),[extra,setExtra]=useState<NetworkRecommendationsPage|null>(null),[busy,setBusy]=useState(''),[moreBusy,setMoreBusy]=useState(false),[error,setError]=useState(''),gate=useRef(false),moreGate=useRef(false),alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  const items=uniqueBy([...(resource.data?.items||[]),...(extra?.items||[])],item=>item.id),members=new Map([...(resource.data?.members||[]),...(extra?.members||[])].map(member=>[member.id,member])),cursor=extra?extra.nextCursor:resource.data?.nextCursor;
  const decide=async(item:NetworkRecommendation,action:'approve'|'decline'|'retract')=>{if(gate.current)return;gate.current=true;setBusy(item.id);setError('');try{await decideRecommendation(item.id,action,item.version);if(alive.current){setExtra(null);await resource.refresh();}}catch(e){if(alive.current)setError((e as Error).message);}finally{gate.current=false;if(alive.current)setBusy('');}};
  const more=async()=>{if(!cursor||moreGate.current)return;moreGate.current=true;setMoreBusy(true);setError('');try{const page=await networkRecommendations(mode,cursor);if(alive.current)setExtra(prior=>({items:[...(prior?.items||[]),...page.items],members:[...(prior?.members||[]),...page.members],nextCursor:page.nextCursor}));}catch(e){if(alive.current)setError((e as Error).message);}finally{moreGate.current=false;if(alive.current)setMoreBusy(false);}};
  return <><NetworkError error={resource.error} onRetry={()=>void resource.refresh()}/><NetworkError error={error}/>{resource.busy&&!resource.data&&<p className="rp-network-empty" role="status">Loading recommendations…</p>}<div className="rp-network-list" aria-busy={resource.busy}>{items.map(item=>{const member=members.get(mode==='written'?item.recipientId:item.authorId);return <article className="rp-network-recommendation" key={item.id}>{member&&<NetworkPerson member={member} onOpenMember={onOpenMember}/>}<small>{item.relationship} · {item.status==='approved'?'Approved by recipient':item.status==='pending'?'Awaiting recipient approval':item.status==='declined'?'Declined':'Retracted'}</small><p>{item.text}</p><div className="rp-network-actions">{mode==='pending'&&item.status==='pending'?<><button className="rp-network-primary" disabled={!!busy} onClick={()=>void decide(item,'approve')}>Approve on my profile</button><button className="rp-network-secondary" disabled={!!busy} onClick={()=>void decide(item,'decline')}>Decline</button></>:(item.status==='approved'||item.status==='pending')&&<button className="rp-network-secondary" disabled={!!busy} onClick={()=>void decide(item,'retract')}>{mode==='written'?'Retract recommendation':'Remove from profile'}</button>}</div>{busy===item.id&&<span className="rp-network-note" role="status">Updating recommendation…</span>}</article>;})}</div>{!resource.busy&&!resource.error&&!items.length&&<p className="rp-network-empty">{mode==='pending'?'No recommendations waiting for your approval.':mode==='written'?'Visit a connection’s profile to write a recommendation.':'Approved recommendations from your connections will appear here.'}</p>}{cursor&&<button className="rp-network-secondary rp-network-more" disabled={moreBusy||!!busy} onClick={()=>void more()}>{moreBusy?'Loading…':'More recommendations'}</button>}</>;
}
export function NetworkPreferencesPanel({accountKey}:{accountKey:string}){
  const [open,setOpen]=useState(false);
  return <section className="rp-professional-profile" aria-label="Professional network preferences"><details className="rp-network-editor" onToggle={event=>setOpen(event.currentTarget.open)}><summary><ShieldCheck size={18} aria-hidden="true"/>Network preferences</summary>{open&&<PreferencesForm key={accountKey} accountKey={accountKey}/>}</details></section>;
}
function PreferencesForm({accountKey}:{accountKey:string}){
  const resource=useNetworkResource<{preferences:NetworkPreferences}>(accountKey+':network-preferences',(force,signal)=>networkPreferences(force,signal)),[draft,setDraft]=useState<NetworkPreferences|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),alive=useRef(true),gate=useRef(false);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);useEffect(()=>{if(!draft&&resource.data)setDraft(resource.data.preferences);},[resource.data,draft]);
  return <><NetworkError error={resource.error} onRetry={()=>void resource.refresh()}/>{!draft&&resource.busy&&<p role="status" className="rp-network-empty">Loading privacy preferences…</p>}{draft&&<form className="rp-network-form" onSubmit={async event=>{event.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);setError('');setSaved(false);try{const result=await updateNetworkPreferences(draft);if(alive.current){setDraft(result.preferences);setSaved(true);}}catch(e){if(alive.current)setError((e as Error).message);}finally{gate.current=false;if(alive.current)setBusy(false);}}}><label>Connection invitations<select value={draft.connectionPrivacy} disabled={busy} onChange={event=>{setDraft({...draft,connectionPrivacy:event.target.value as NetworkPreferences['connectionPrivacy']});setSaved(false);}}><option value="everyone">Allow professional invitations</option><option value="nobody">Do not receive invitations</option></select></label>{([{id:'allowEndorsements',title:'Skill endorsements',note:'Allow accepted connections to endorse skills on your profile.'},{id:'allowRecommendations',title:'Written recommendations',note:'Allow accepted connections to write recommendations for your approval.'},{id:'networkNotifications',title:'Network notifications',note:'Receive updates for invitations, endorsements and recommendations.'}] as const).map(option=><label className="rp-network-check" key={option.id}><input type="checkbox" checked={draft[option.id]} disabled={busy} onChange={event=>{setDraft({...draft,[option.id]:event.target.checked});setSaved(false);}}/><span>{option.title}<small>{option.note}</small></span></label>)}<p className="rp-network-note">Turning off endorsements or recommendations removes earlier items from public view. Turning them on again does not restore earlier items.</p><button className="rp-network-primary" disabled={busy} aria-busy={busy}>{busy?'Saving…':'Save network preferences'}</button>{saved&&<p className="rp-network-status" role="status">Network preferences saved.</p>}<NetworkError error={error}/></form>}</>;
}
