import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,BadgeCheck,Check,Grid3X3,Film,MessageCircle,Star,UserPlus} from 'lucide-react';
import type {CommunityMember,CommunityPost,Trade} from '../../types/repaidians';
import {storeMedia,trades,updateAvatar,updateProfile} from '../../services/repaidiansService';
import {Avatar,EmptyState,Media,tradeName} from './common';
export function Profile({account,member,self,posts,following,followingCount,followersCount,onBack,onFollow,onMessage,onBook,onCreate,onPublication,onBlock}:{account:string;member:CommunityMember;self:boolean;posts:CommunityPost[];following:boolean;followingCount:number;followersCount:number;onBack:()=>void;onFollow:()=>void;onMessage:()=>void;onBook:()=>void;onCreate:()=>void;onPublication?:(id:string)=>void;onBlock?:()=>void}) {
  const [name,setName]=useState(member.name),[trade,setTrade]=useState<Trade>(member.trade),[bio,setBio]=useState(member.bio),[error,setError]=useState(''),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[grid,setGrid]=useState<'all'|'video'>('all');
  const authored=posts.filter(p=>p.authorId===member.id),portfolio=authored.flatMap(p=>p.media.map((media,i)=>({media,id:p.id+'-'+i,publicationId:p.id,caption:p.caption}))).filter(p=>grid==='all'||p.media.kind==='video');
  return <section className="rp-profile">
    <div className="rp-profile-title"><button className="rp-back" onClick={onBack} aria-label="Back to community"><ArrowLeft size={23}/></button><h2>{member.handle||member.name}{member.reviewed&&<BadgeCheck size={19} aria-label="Reviewed Repaido professional"/>}</h2></div>
    <header className="rp-profile-header"><Avatar member={member} size="large"/><div className="rp-profile-stats"><div><strong>{member.postsCount??authored.length}</strong><small>posts</small></div><div><strong>{followersCount.toLocaleString()}</strong><small>followers</small></div><div><strong>{followingCount.toLocaleString()}</strong><small>following</small></div></div></header>
    <div className="rp-profile-details"><strong>{member.name}</strong><span className="rp-muted">{tradeName(member.trade)}{member.role?' · '+member.role:''}</span><p className="rp-profile-bio">{member.bio||'Building something worth sharing.'}</p>{(member.completedTasks!=null||member.rating!=null)&&<div className="rp-work-credentials">{member.completedTasks!=null&&<span><Check size={14}/>{member.completedTasks.toLocaleString()} completed jobs</span>}{member.rating!=null&&<span><Star size={14}/>{member.rating.toFixed(1)} work rating</span>}</div>}</div>
    {!self&&<div className="rp-profile-actions"><button className={following?'rp-secondary':'rp-primary'} aria-pressed={following} onClick={onFollow}>{following?<Check size={16}/>:<UserPlus size={16}/>} {following?'Following':'Follow'}</button><button className="rp-secondary" onClick={onMessage}><MessageCircle size={16}/>Message</button><button className="rp-secondary rp-book-profile" onClick={onBook}>Book service<ArrowUpRight size={16}/></button></div>}
    {!self&&onBlock&&<div className="rp-profile-safety"><button onClick={onBlock}>Block member</button></div>}
    {self&&<details className="rp-edit-profile"><summary>Edit profile</summary><form onSubmit={async e=>{e.preventDefault();if(saving||uploading)return;setSaving(true);setError('');setSaved(false);try{await updateProfile(account,name,trade,bio);setSaved(true);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}><label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading||saving} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('');setSaved(false);setUploading(true);try{if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('Choose a JPG, PNG or WebP profile photo.');if(file.size>2*1024*1024)throw new Error('Choose a profile photo up to 2 MB.');const [photo]=await storeMedia([file]);await updateAvatar(photo.url);setSaved(true);}catch(error){setError((error as Error).message);}finally{setUploading(false);}}}/><small className="rp-fine">JPG, PNG or WebP, up to 2 MB. Your new photo saves immediately.</small>{uploading&&<span role="status">Uploading your photo…</span>}</label><label>Name<input required maxLength={80} value={name} onChange={e=>{setName(e.target.value);setSaved(false);}}/></label><label>Your trade<select value={trade} onChange={e=>{setTrade(e.target.value as Trade);setSaved(false);}}>{trades.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>About your work<textarea rows={3} maxLength={500} value={bio} onChange={e=>{setBio(e.target.value);setSaved(false);}}/></label><button className="rp-primary" disabled={saving||uploading} aria-busy={saving}>{saving?'Saving…':'Save profile'}</button>{saved&&<p role="status">Profile saved.</p>}{error&&<p className="rp-error" role="alert">{error}</p>}</form></details>}
    <div className="rp-portfolio-tabs" role="group" aria-label="Portfolio content"><button aria-pressed={grid==='all'} onClick={()=>setGrid('all')}><Grid3X3 size={21}/><span>Posts</span></button><button aria-pressed={grid==='video'} onClick={()=>setGrid('video')}><Film size={21}/><span>Videos</span></button></div>
    {portfolio.length?<div className="rp-portfolio">{portfolio.map(item=><figure key={item.id}>{onPublication?<button className="rp-portfolio-open" aria-label={'Open '+item.media.kind+' by '+member.name+(item.caption?': '+item.caption.slice(0,100):'')} onClick={()=>onPublication(item.publicationId)}><Media asset={item.media}/></button>:<Media asset={item.media}/>} {item.media.kind==='video'&&<Film className="rp-portfolio-kind" size={20} aria-label="Video"/>}</figure>)}</div>:<EmptyState title={self?'Your work. Your story.':'A portfolio in the making'} onCreate={self?onCreate:undefined}>{self?'Share a photo or video and build a portfolio people can explore.':'This professional’s published work will appear here.'}</EmptyState>}
  </section>;
}
