import {useEffect,useRef,useState} from 'react';
import {Heart,MessageCircle,Pause,Play,Volume2,VolumeX,ArrowUpRight} from 'lucide-react';
import type {CommunityMember,CommunityReel} from '../../types/repaidians';
import {Author,EmptyState,LocalLabel,Media} from './common';
export function Reels({reels,likes,memberFor,onLike,onComments,onProfile,onBook,onCreate,suspended=false}:{reels:CommunityReel[];likes:string[];memberFor:(id:string)=>CommunityMember;onLike:(id:string)=>void;onComments:(id:string)=>void;onProfile:(id:string)=>void;onBook:(reel:CommunityReel)=>void;onCreate:()=>void;suspended?:boolean}) {
  const [muted,setMuted]=useState(true);
  if(!reels.length)return <EmptyState title="The craft behind the result" onCreate={onCreate}>Bring your work to life with a vertical video. Share your process, a useful tip or a transformation.</EmptyState>;
  return <div className="rp-reels" aria-label="Work videos">{reels.map(reel=><ReelCard key={reel.id} reel={reel} member={memberFor(reel.authorId)} liked={likes.includes(reel.id)} muted={muted} suspended={suspended} onMute={()=>setMuted(v=>!v)} onLike={()=>onLike(reel.id)} onComments={()=>onComments(reel.id)} onProfile={()=>onProfile(reel.authorId)} onBook={()=>onBook(reel)}/>)}</div>;
}
function ReelCard({reel,member,liked,muted,suspended,onMute,onLike,onComments,onProfile,onBook}:{reel:CommunityReel;member:CommunityMember;liked:boolean;muted:boolean;suspended:boolean;onMute:()=>void;onLike:()=>void;onComments:()=>void;onProfile:()=>void;onBook:()=>void}) {
  const ref=useRef<HTMLElement>(null),[active,setActive]=useState(false),[paused,setPaused]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.classList.contains('reduce-motion')),[hidden,setHidden]=useState(document.hidden),[heart,setHeart]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setActive(entry.isIntersecting&&entry.intersectionRatio>.6),{threshold:[0,.6,1]});if(ref.current)observer.observe(ref.current);const visibility=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',visibility);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',visibility);clearTimeout(timer.current);};},[]);
  const doubleLike=()=>{if(!liked)onLike();setHeart(true);clearTimeout(timer.current);timer.current=setTimeout(()=>setHeart(false),750);};
  return <article ref={ref} className="rp-reel" onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('button'))doubleLike();}}><Media asset={reel.media} active={active&&!hidden&&!suspended} paused={paused||suspended} muted={muted} loop/>{heart&&<Heart className="rp-big-heart" size={84} fill="currentColor" aria-hidden="true"/>}
    <div className="rp-reel-top"><span>Works</span><div><button onClick={onMute} aria-label={muted?'Unmute work video':'Mute work video'}>{muted?<VolumeX size={22}/>:<Volume2 size={22}/>}</button><button onClick={()=>setPaused(v=>!v)} aria-label={paused?'Play work video':'Pause work video'}>{paused?<Play size={22}/>:<Pause size={22}/>}</button></div></div>
    <div className="rp-reel-actions"><button className={liked?'rp-liked':''} onClick={onLike} aria-pressed={liked} aria-label={liked?'Unlike work video':'Like work video'}><Heart size={29} strokeWidth={1.6} fill={liked?'currentColor':'none'}/>{(reel.likeCount??0)>0&&<span>{reel.likeCount!.toLocaleString()}</span>}</button><button onClick={onComments} aria-label="Work video comments"><MessageCircle size={29} strokeWidth={1.6}/>{(reel.commentCount??0)>0&&<span>{reel.commentCount!.toLocaleString()}</span>}</button></div>
    <div className="rp-reel-info"><Author member={member} onOpen={onProfile}/><LocalLabel sample={reel.sample}/><p>{reel.caption}</p><button className="rp-reel-book" onClick={onBook}>Book a service<ArrowUpRight size={16}/></button></div>
  </article>;
}
