import {useState} from 'react';
import {ArrowUpRight,BriefcaseBusiness,Clock,LockKeyhole,MapPin,Users} from 'lucide-react';
import type {CommunityMember,CommunityTender} from '../../types/repaidians';
import {communityRequest} from '../../services/repaidiansService';
import {Author,Avatar,EmptyState,money,tradeName} from './common';
export function Tenders({tenders,bids,paid,selfId,memberFor,onProfile,onBid,onContact,onCreate}:{tenders:CommunityTender[];bids:string[];paid:boolean;selfId:string;memberFor:(id:string)=>CommunityMember;onProfile:(id:string)=>void;onBid:(id:string)=>Promise<boolean>;onContact:(tender:CommunityTender)=>Promise<string|null>;onCreate:()=>void}) {
  const [contacts,setContacts]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[applicants,setApplicants]=useState<{tenderId:string;members:CommunityMember[];bids:{id:string;authorId:string;note:string}[]}|null>(null);
  if(!tenders.length)return <EmptyState title="Build a crew. Make a start." onCreate={onCreate}>Post a clear site requirement with its scope, budget and deadline.</EmptyState>;
  const run=async(id:string,action:()=>Promise<void>)=>{setBusy(id);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
  return <div className="rp-tenders"><div className="rp-board-intro"><BriefcaseBusiness size={24}/><div><h2>Find your next collaboration.</h2><p>Crew requirements & subcontract opportunities.</p></div></div>{error&&<p className="rp-error" role="alert">{error}</p>}{tenders.map(tender=>{
    const closed=tender.deadline<=Date.now(),hasBid=bids.includes(tender.id),owned=tender.authorId===selfId;
    return <article className="rp-tender" key={tender.id}><header><span className="rp-trade-badge">{tradeName(tender.trade)}</span><span className="rp-muted">{closed?'Closed':'Open brief'}</span></header><h3>{tender.title}</h3><p>{tender.details}</p>
      <div className="rp-tender-facts"><span><MapPin size={15}/>{tender.location}</span><span><Users size={15}/>{tender.slots} {tender.slots===1?'position':'positions'}</span><span><Clock size={15}/>{closed?'Closed':'Closes '+new Date(tender.deadline).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'})}</span></div>
      <div className="rp-tender-budget"><small>Listed budget</small><strong>{money(tender.budgetRupees)}</strong></div><Author member={memberFor(tender.authorId)} onOpen={()=>onProfile(tender.authorId)}/>
      <div className="rp-tender-actions">{owned?<button className="rp-primary" disabled={busy===tender.id} onClick={()=>void run(tender.id,async()=>{const data=await communityRequest<{bids:{id:string;authorId:string;note:string}[];members:CommunityMember[]}>('/bids/'+encodeURIComponent(tender.id));setApplicants({tenderId:tender.id,...data});})}>View applicants<Users size={16}/></button>:<button className="rp-primary" disabled={closed||hasBid||busy===tender.id} onClick={()=>void run(tender.id,async()=>{await onBid(tender.id);})}>{hasBid?'Interest submitted':closed?'Tender closed':'Submit interest'}<ArrowUpRight size={16}/></button>}<button className="rp-secondary" disabled={busy===tender.id} onClick={()=>void run(tender.id,async()=>{const contact=await onContact(tender);if(contact!==null)setContacts(old=>({...old,[tender.id]:contact}));})}><LockKeyhole size={16}/>Contact</button></div>
      {paid&&contacts[tender.id]!==undefined&&<p className="rp-notice">{contacts[tender.id]||'No contact details have been provided.'}</p>}
      {applicants?.tenderId===tender.id&&<section aria-label="Tender applicants"><h4>Submitted interest</h4>{!applicants.bids.length&&<p className="rp-muted">No applicants yet.</p>}{applicants.bids.map(b=>{const member=applicants.members.find(m=>m.id===b.authorId);return <button className="rp-member-row" key={b.id} onClick={()=>onProfile(b.authorId)}>{member&&<Avatar member={member}/>}<span><strong>{member?.name||'Community member'}</strong><small>{b.note||'Interested in your brief'}</small></span></button>;})}</section>}
    </article>;
  })}</div>;
}
