// Development-only visual fixture; never part of the production entry or public directory.
import {createRoot} from 'react-dom/client';
import {useState} from 'react';
import {AgentTaskWorkspace} from '../src/components/AgentTaskWorkspace';
import {JobSummaryCard} from '../src/components/OperationalJobs';
import {Modal} from '../src/components/ui';
import {TaskRecordContent,type RecordRow} from '../src/components/WorkerRecords';
import type {Job} from '../src/services/operations';
import '../src/styles.css';
import '../src/design-system.css';
import '../src/components/operations.css';
const state=new URLSearchParams(location.search).get('state')||'arrived';
const previewParams=new URLSearchParams(location.search);
document.documentElement.dataset.theme=previewParams.get('theme')==='dark'?'dark':'light';
document.documentElement.style.fontSize=previewParams.get('text')==='200'?'200%':'100%';
document.documentElement.classList.toggle('reduce-motion',previewParams.get('motion')==='reduce');
const job={id:'local-qa-task',visit_id:'local-qa-visit',version:1,state,service_name:'LOCAL QA · Appliance repair',category:'appliance',city:'Test city',starts_at:new Date().toISOString(),starts_epoch:Date.now()/1000,total_paise:49900,base_price_paise:49900,reminder_at:Date.now()/1000,offer_expires_at:Date.now()/1000+300,server_time:Date.now()/1000,distance_metres:25,payment_status:'pay_after_service',payout_status:'held',allowed_actions:state==='arrived'?['start']:state==='in_progress'?['propose_parts','schedule_follow_up','submit_completion']:state==='en_route'?['position','stop_tracking']:state==='offered'?['accept','decline']:[],blockers:[],penalties:[],events:[],scopes:[],procurement_version:3,evidence_summary:{has_before:['in_progress','completion_pending','completed'].includes(state),has_after:['completion_pending','completed'].includes(state),has_forgotten_info:false,before_omission_reason:'',count:0}} satisfies Job;
const record:RecordRow={id:'local-only-record',service_name:'LOCAL QA · Electrical inspection',state:'completed',starts_at:'2026-09-28T08:00:00Z',completion_notes:'Local fixture: inspection and agreed checks recorded. No real customer or work.',payment_status:'pay_after_service',payout_status:'held',generated_at:1790600000,terms:{free_cancel_before_start:true,reminder_grace_seconds:600,late_departure_percent:20,version:'LOCAL-TEST'},settlement_policy:{version:'LOCAL-TEST'},penalties:[{code:'MISSED_REMINDER',status:'pending_settlement_review',current_percent:10,assessed_at:1790600000}],parts_assessments:[],review:{rating:4,text:'Local layout fixture. Not a real review.'},events:['BookingRequested','AssignmentOffered','accept','depart','WorkerArrived','start','submit_completion','accept_completion','review'].map((event_type,i)=>({event_id:String(i),event_type,occurred_at_server_time:1790600000+i*600}))};
function Preview(){const [pdfNotice,setPdfNotice]=useState('');const cards=new URLSearchParams(location.search).get('view')==='cards';const [open,setOpen]=useState(!cards);if(previewParams.get('view')==='records')return <main className="operations ops-worker"><h1>Local-only records fixture</h1><button onClick={()=>setOpen(true)}>Open sample record</button>{open&&<Modal title="Task records" className="agent-tool-sheet" onClose={()=>setOpen(false)}><TaskRecordContent data={record} busy={false} onDownload={()=>setPdfNotice('Local preview only. No PDF API was called.')}/><p role="status">{pdfNotice}</p></Modal>}</main>;if(cards)return <main className="operations ops-worker"><h1>Local-only completed task preview</h1><p>Fixture data, not a real task or achievement.</p><div className="ops-actions"><label>Text size<select defaultValue="100" onChange={e=>document.documentElement.style.fontSize=e.target.value+'%'}><option>100</option><option>200</option></select></label><label><input type="checkbox" onChange={e=>document.documentElement.dataset.theme=e.target.checked?'dark':'light'}/>Dark</label></div><div className="agent-jobs-rail"><JobSummaryCard job={{...job,state:'completed',service_name:'Electrical safety & wiring inspection'}} worker onOpen={()=>setOpen(true)}/><JobSummaryCard job={{...job,state:'cancelled'}} worker onOpen={()=>setOpen(true)}/></div>{open&&<Modal title="Completion report" className="agent-tool-sheet" onClose={()=>setOpen(false)}><p>Local UI fixture. Production loads the authenticated task report, payment status and PDF.</p></Modal>}</main>;return <main><h1>Development-only visual fixture</h1><button onClick={()=>setOpen(true)}>Open sample task</button>{open&&<AgentTaskWorkspace job={job} busy={false} error="" onClose={()=>setOpen(false)} onRefresh={async()=>{}} onRun={async()=>undefined} onShare={async()=>{}} onStop={async()=>{}}/>}</main>;}
createRoot(document.getElementById('root')!).render(<Preview/>);
if(import.meta.env.DEV)void import('../src/dev/uiAudit').then(m=>m.startUiAudit());
