import assert from 'node:assert/strict';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import {mkdtemp,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),backend=resolve(web,'../backend'),origin=process.env.BRAND_PREVIEW_ORIGIN||'http://127.0.0.1:5187';
assert(['localhost','127.0.0.1'].includes(new URL(origin).hostname));
const work=await mkdtemp('/tmp/repaido-brand-app-'),port=8044,api='http://127.0.0.1:'+port,report=[];let browser,log='';
const server=spawn(resolve(backend,'.venv/bin/python'),['-m','uvicorn','main:app','--host','127.0.0.1','--port',String(port)],{cwd:backend,env:{...process.env,REPAIDO_STORAGE:'sqlite',REPAIDO_DB:work+'/test.db'},stdio:['ignore','pipe','pipe']});for(const s of [server.stdout,server.stderr])s.on('data',d=>log+=d);
try{for(let i=0;i<100;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:465,height:850},reducedMotion:'reduce'});
 await page.route('**/@vite/client',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/new WebSocket\(/g,'new PreviewSocket(');await route.fulfill({response,body:'class PreviewSocket { addEventListener(){} removeEventListener(){} send(){} close(){} }\n'+body});});
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());try{const response=await route.fetch({url:api+u.pathname+u.search});await route.fulfill({response});}catch{await route.abort();}});
 await page.goto(origin+'/');await page.locator('.android-bottom-nav').waitFor();await page.evaluate(()=>document.fonts.ready);await page.addScriptTag({path:require.resolve('axe-core')});
 async function audit(name){for(const theme of ['light','dark'])for(const [width,scale] of [[465,100],[320,200],[1440,100]]){await page.setViewportSize({width,height:850});await page.evaluate(scale=>document.documentElement.style.fontSize=scale+'%',scale);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(350);const result=await page.evaluate(async()=>{const a=await window.axe.run(document.body,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']},rules:{'color-contrast-enhanced':{enabled:true}}});return {fonts:[...document.querySelectorAll('h1,h2,h3,p,button,input,select,label,small,strong')].filter(el=>el.getClientRects().length&&!getComputedStyle(el).fontFamily.includes('Poppins')).map(el=>el.tagName+': '+el.className),overflow:document.documentElement.scrollWidth>innerWidth+1,violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))};});report.push({name,theme,width,scale,...result});await page.screenshot({path:work+'/'+name+'-'+theme+'-'+width+'-'+scale+'.png',fullPage:true});}await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});await page.setViewportSize({width:465,height:850});}
 for(const name of ['Explore','Services','Bookings','Hire','Market']){await page.locator('.android-bottom-nav').getByRole('button',{name,exact:true}).click();await page.waitForTimeout(500);await audit(name);}
 await page.locator('.android-bottom-nav').getByRole('button',{name:'Bookings',exact:true}).click();
 for(const name of ['Visits','Home plans','Hiring','Contracts','Rides']){await page.getByRole('group',{name:'Booking service type'}).getByRole('button',{name,exact:true}).click();await page.locator('.booking-sign-in').waitFor();assert.equal(await page.locator('.booking-sign-in').getByRole('heading').textContent(),({'Visits':'Sign in to view your bookings','Home plans':'Sign in to see your plans','Hiring':'Sign in to see your hiring requests','Contracts':'Sign in to manage your contracts','Rides':'Sign in to manage rides'})[name]);assert.equal(await page.locator('.booking-sign-in').getByRole('button').count(),1);assert.equal(await page.getByRole('alert').count(),0);await audit('Guest-'+name.replaceAll(' ','-'));}
 await page.locator('.android-bottom-nav').getByRole('button',{name:'Market',exact:true}).click();
 for(const name of ['B2B Wholesale','Contracts','Cabs & cars','Sell scrap']){await page.getByRole('tablist',{name:'Marketplace destination'}).getByRole('tab',{name,exact:true}).click();await page.waitForTimeout(500);await audit(name.replaceAll(' ','-'));}
 await writeFile(work+'/report.json',JSON.stringify(report,null,2));assert.deepEqual(report.filter(r=>r.overflow||r.fonts.length||r.violations.length),[], 'Screen accessibility failures; see '+work+'/report.json');console.log('Passed: '+report.length+' screen/theme checks. '+work);
}catch(e){console.error(e);console.log(log.slice(-500));process.exitCode=1;}finally{await browser?.close();server.kill('SIGTERM');await writeFile(work+'/report.json',JSON.stringify(report,null,2));console.log(work);}
