import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp(resolve(tmpdir(),'repaido-suites-')),api='http://127.0.0.1:8054',origin='http://127.0.0.1:5187';
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/business_suites_api.py',work+'/test.db','8054'],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser;for(const stream of [server.stdout,server.stderr])stream.on('data',d=>log+=d);
const checks=[],errors=[],writes=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
async function call(path,uid,body,method){const r=await fetch(api+'/operations/local-business'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+uid,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
async function open(page,mode,uid='worker',portal=false){await page.goto(origin+'/tests/business-suites-preview.html?mode='+mode+'&uid='+uid+(portal?'&portal=1':''));if(mode==='technician')await page.locator('.worker-welcome-compact').waitFor();else await page.getByRole('heading',{name:mode==='driver'?'Driver suite':mode==='scrap_owner'?'Scrap collection suite':'Cab owner suite',exact:true}).waitFor();}
async function tab(page,name){
 const nav=page.getByRole('navigation',{name:/suite navigation/});
 if(await page.locator('.suite-cab_owner').count()){
  if(['Shared rides','Cab bookings','Self-drive'].includes(name)){await nav.getByRole('button',{name:'Bookings',exact:true}).click();await page.getByRole('navigation',{name:'Booking types'}).getByRole('button',{name,exact:true}).click();return;}
  if(['Payments','Account'].includes(name)){await nav.getByRole('button',{name:'More',exact:true}).click();await page.locator('.suite-menu>button').filter({has:page.getByText(name,{exact:true})}).click();return;}
  name=name==='Fleet & rates'?'Fleet':name==='Overview'?'Home':name;
 }else if(await page.locator('.suite-scrap_owner').count()){if(['Schedule','Account'].includes(name)){await nav.getByRole('button',{name:'More',exact:true}).click();await page.locator('.suite-menu>button').filter({has:page.getByText(name,{exact:true})}).click();return;}name=name==='Overview'?'Home':name;
 }else if(await page.locator('.suite-driver').count())name=name==='Cab journeys'?'Cab rides':name==='Shared journeys'?'Shared rides':name==='My vehicles'?'Vehicles':name;
 await nav.getByRole('button',{name,exact:true}).click();
}
async function pinnedNavigation(page){
 const nav=page.locator('.suite-workspace .suite-navigation');if(!await nav.count())return;
 assert.equal(await nav.getByRole('button').count(),5);
 const bounds=await nav.boundingBox(),size=page.viewportSize();assert(Math.abs(bounds.y+bounds.height-size.height)<2,'navigation is pinned to the viewport');
 for(const button of await nav.getByRole('button').all())assert(await button.evaluate(e=>{const b=e.getBoundingClientRect();return document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)?.closest('button')===e;}),'navigation button remains reachable');
}
async function variants(page,name){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});for(const width of [320,465,1440])for(const theme of ['light','dark'])for(const scale of [100,200]){await page.setViewportSize({width,height:850});await page.evaluate(({theme,scale})=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=scale+'%';},{theme,scale});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow '+width+' '+scale);if(name!=='business-launcher')await pinnedNavigation(page);const violations=await page.evaluate(async()=>(await window.axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']},rules:{'color-contrast-enhanced':{enabled:true}}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));assert.deepEqual(violations,[],name+' accessibility '+width+' '+theme+' '+scale);await page.screenshot({path:work+'/'+name+'-'+width+'-'+theme+'-'+scale+'.png',fullPage:true});}await page.setViewportSize({width:465,height:850});await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});checks.push(name+' responsive / AAA contrast');}
try{
 for(let i=0;i<120;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:465,height:850},reducedMotion:'reduce'});
 await context.route('**/@vite/client',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/new WebSocket\(/g,'new PreviewSocket(');await route.fulfill({response,body:'class PreviewSocket { addEventListener(){} removeEventListener(){} send(){} close(){} }\n'+body});});
 await context.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(!['GET','HEAD'].includes(request.method()))writes.push(url.pathname);try{const response=await route.fetch({url:api+url.pathname+url.search});await route.fulfill({response});}catch{await route.abort().catch(()=>{});}});
 const page=await context.newPage();page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push(e.message));
 await open(page,'cab_owner');await page.getByRole('button',{name:/New booking requests 1/}).waitFor();await variants(page,'owner-overview');await pinnedNavigation(page);assert.equal(await page.locator('.suite-quick-actions').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.suite-navigation').getBoundingClientRect().top),true,'owner service shortcuts fit without scrolling');await tab(page,'Schedule');await page.getByLabel('Schedule month').waitFor();await tab(page,'Payments');await page.getByRole('heading',{name:'Collections & owner transfers'}).waitFor();await page.getByRole('navigation',{name:'Breadcrumb'}).getByRole('button',{name:'More',exact:true}).click();await page.locator('.suite-menu>button').filter({has:page.getByText('Account',{exact:true})}).click();await page.getByRole('heading',{name:'Business profile'}).waitFor();checks.push('five pinned owner destinations; booking groups, schedule, payments and account are reachable');
 await tab(page,'Fleet & rates');await page.getByText('OD01AB1234',{exact:false}).waitFor();await variants(page,'owner-fleet');
 await page.getByRole('button',{name:'Edit vehicle & rates'}).click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');
 await tab(page,'Self-drive');await page.getByRole('heading',{name:'Self-drive rentals'}).waitFor();assert.equal(await page.getByText('₹500.00 advance received',{exact:false}).count(),0);await variants(page,'owner-rentals');
 await tab(page,'Cab bookings');await page.getByRole('button',{name:'Accept request',exact:true}).click();await page.getByText('accepted',{exact:true}).first().waitFor();checks.push('owner accepts a customer cab request');
 await open(page,'driver');assert.equal(await page.getByRole('button',{name:'Fleet & rates',exact:true}).count(),0);await variants(page,'driver-overview');assert.equal(await page.locator('.suite-menu').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.suite-navigation').getBoundingClientRect().top),true,'driver schedule and vehicle shortcut fit without scrolling');await tab(page,'My vehicles');await page.getByText('Test sedan',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add vehicle',exact:true}).count(),0);checks.push('same-phone driver sees accepted assignment, no owner controls');await tab(page,'Cab journeys');await page.getByRole('button',{name:'Depart for pickup',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Accept request',exact:true}).count(),0);await variants(page,'driver-journeys');assert.equal(await page.locator('.business-record>.business-actions').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.suite-navigation').getBoundingClientRect().top),true,'journey controls clear the bottom bar');assert.equal(await page.getByRole('button',{name:'Depart for pickup',exact:true}).evaluate(e=>e.getBoundingClientRect().top<document.querySelector('.journey-tracking').getBoundingClientRect().top),true,'driver actions precede the map');await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));await pinnedNavigation(page);await tab(page,'Account');assert.equal(await page.locator('.suite-panel-title').evaluate(e=>document.activeElement===e),true,'panel changes focus the new heading');assert.equal(await page.locator('.suite-breadcrumb [aria-current=page]').innerText(),'Account');checks.push('driver navigation remains visible after scrolling; actions above maps; breadcrumbs and keyboard focus follow the destination');
 await open(page,'scrap_owner');await page.getByRole('button',{name:/New collection requests 1/}).waitFor();await variants(page,'scrap-overview');await tab(page,'Collections');await page.getByRole('button',{name:'Accept request',exact:true}).click();await page.getByText('accepted',{exact:true}).first().waitFor();await tab(page,'Inspection');await page.getByRole('button',{name:'Record inspection & weight',exact:true}).waitFor();await variants(page,'scrap-inspection');checks.push('same phone opens scrap requests and weighing, no transport modules');
 await page.getByRole('button',{name:'Record inspection & weight',exact:true}).click();const weighing=page.locator('dialog[open]').last();await weighing.getByLabel('Grade / condition').fill('Clean dry steel');await weighing.getByLabel('Gross weight (kg)').fill('10.5');await weighing.getByLabel('Container / tare (kg)').fill('0.5');await weighing.getByLabel('₹ per kg').fill('25');await weighing.getByLabel('Scale identifier / calibration reference').fill('fixture-scale-123');await weighing.getByLabel('Inspection notes').fill('Fixture material checked and scale zeroed.');await weighing.getByLabel('Actual weighing photo').setInputFiles(resolve(web,'public/images/icon-vehicle.png'));await weighing.getByRole('button',{name:'Send weighed quote',exact:true}).click();await page.getByRole('heading',{name:'Weighed quote',exact:true}).waitFor();const scrapRow=(await call('/scrap','customer')).collections[0];assert.equal(scrapRow.evaluation.total_paise,25000);await call('/scrap/'+scrapRow.id+'/commands','customer',{action:'agree',expected_version:scrapRow.version,command_id:crypto.randomUUID()});await tab(page,'Payments');await page.getByRole('button',{name:'Record customer payment',exact:true}).click();const payment=page.locator('dialog[open]').last();await payment.getByLabel('Payment reference').fill('fixture-transfer-123');await payment.getByLabel('Notes',{exact:true}).fill('Fixture agreed amount paid to the customer.');await payment.getByRole('button',{name:'Confirm paid',exact:true}).click();await page.getByText('payment reported',{exact:true}).waitFor();const reported=(await call('/scrap','customer')).collections[0];await call('/scrap/'+reported.id+'/commands','customer',{action:'received',expected_version:reported.version,command_id:crypto.randomUUID()});checks.push('private weighing photo upload, approved quote, actual payment entry and customer receipt');
 await open(page,'cab_owner','worker',true);assert.equal(await page.getByRole('heading',{name:'Cab owner suite',exact:true}).count(),1);await page.getByRole('button',{name:'Business apps',exact:true}).click();await page.getByRole('link',{name:/Scrap collector.*Open your app/}).waitFor();await variants(page,'business-launcher');assert.equal(await page.getByRole('combobox',{name:'Work desk'}).count(),0);checks.push('contractor phone enters requested cab app without role override; separate app links');await page.keyboard.press('Escape');await pinnedNavigation(page);await tab(page,'Self-drive');await variants(page,'owner-portal-rentals');await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));assert.equal(await page.locator('.business-record').last().evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.suite-navigation').getBoundingClientRect().top),true,'last record clears the bottom navigation in the real portal');checks.push('real worker portal has one cab navigation bar and unobscured records');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=scrap_owner&uid=worker2');await page.getByRole('heading',{name:'Application under review'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Scrap collection suite'}).count(),0);checks.push('pending extra role cannot open approved suite');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=mobility&uid=customer');await page.getByRole('button',{name:/Shared ride Join/}).waitFor();await variants(page,'customer-travel');await page.getByRole('button',{name:/Self-drive rental Choose/}).click();await page.getByText('Self-drive rental',{exact:true}).first().waitFor();checks.push('customer shared, chauffeured, self-drive choices are distinct');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=scrap&uid=customer');await page.getByRole('button',{name:'history',exact:true}).click();await page.getByRole('list',{name:'Collection progress',exact:true}).waitFor();await variants(page,'customer-scrap');
 // Real multi-booking queues verify selection, direct schedule entry and role boundaries.
 const ownerVehicle=(await call('/partner?role=cab_owner','worker')).vehicles[0];
 const driverVehicle=(await call('/partner?role=cab_owner','worker2')).vehicles[0];
 const pickup={lat:21.4934,lng:86.9135},dropoff={lat:21.5434,lng:86.9635};
 for(const [vehicle,owner,count,days] of [[ownerVehicle,'worker',3,10],[driverVehicle,'worker2',2,20]])for(let i=0;i<count;i++){
  const starts_at=Date.now()/1000+(days+i)*86400;
  const quote=await call('/quotes','customer',{vehicle_id:vehicle.id,pickup,dropoff,starts_at,ends_at:starts_at+3600,mode:'cab',trip:'one_way'});
  const row=await call('/rides','customer',{quote_ids:[quote.id],pickup_address:'Queue pickup entrance '+i,dropoff_address:'Queue destination entrance '+i,phone:'9876543210',request_id:crypto.randomUUID(),consent:true});
  if(owner==='worker2')await call('/rides/'+row.id+'/commands',owner,{action:'accept',expected_version:row.version,command_id:crypto.randomUUID()});
 }
 await open(page,'cab_owner');await tab(page,'Cab bookings');const picker=page.getByLabel('Booking to manage');await picker.waitFor();assert.equal(await picker.locator('option').count(),4);assert.equal(await page.locator('.business-records>.business-record').count(),1);
 const first=await picker.inputValue();await page.getByRole('button',{name:'Next booking',exact:true}).click();assert.notEqual(await picker.inputValue(),first);await page.getByRole('button',{name:'Previous booking',exact:true}).click();assert.equal(await picker.inputValue(),first);
 const rows=(await call('/rides','worker')).rides;const requested=rows.find(row=>row.mode==='cab'&&row.state==='requested');await picker.selectOption(requested.id);await page.getByRole('button',{name:'Decline',exact:true}).click();await page.waitForFunction(id=>document.querySelector('.business-record-picker select')?.value!==id,requested.id);assert.equal(await page.locator('.business-records>.business-record').count(),1);
 const accepted=rows.find(row=>row.mode==='cab'&&row.state==='accepted'&&row.owner_id==='worker');await call('/rides/'+accepted.id+'/commands','customer',{action:'cancel',expected_version:accepted.version,command_id:crypto.randomUUID(),note:'Customer cancellation for fixture history check'});await page.getByRole('group',{name:'Booking state',exact:true}).getByRole('button',{name:'history',exact:true}).click();await page.getByText('cancelled',{exact:true}).waitFor();await page.getByRole('group',{name:'Booking state',exact:true}).getByRole('button',{name:'active',exact:true}).click();await picker.waitFor();const stableSelection=await picker.inputValue();const laterStart=Date.now()/1000+15*86400;const laterQuote=await call('/quotes','customer',{vehicle_id:ownerVehicle.id,pickup,dropoff,starts_at:laterStart,ends_at:laterStart+3600,mode:'cab',trip:'one_way'});await call('/rides','customer',{quote_ids:[laterQuote.id],pickup_address:'Late queue pickup entrance',dropoff_address:'Late queue destination entrance',phone:'9876543210',request_id:crypto.randomUUID(),consent:true});await page.waitForFunction(()=>document.querySelectorAll('.business-record-picker select option').length===3);assert.equal(await picker.inputValue(),stableSelection,'polling new requests preserves the selected booking');checks.push('all queued bookings stay accessible; previous/next and active/history select real records; closed selection recovers');
 for(let i=0;i<2;i++)await call('/shared','worker2',{request_id:crypto.randomUUID(),vehicle_id:driverVehicle.id,origin:pickup,destination:dropoff,origin_address:'Queue origin '+i,destination_address:'Queue destination '+i,starts_at:Date.now()/1000+(30+i)*86400,ends_at:Date.now()/1000+(30+i)*86400+3600,seats:2,price_paise:17500,pickup_mode:'meeting_point',terms:'One bag per seat. Pay the agreed fare directly to the owner.'});
 await open(page,'driver');await page.getByRole('button',{name:/Test sedan/}).click();await page.getByRole('button',{name:'Depart for pickup',exact:true}).waitFor();assert.equal(await page.getByLabel('Booking to manage').locator('option').count(),3);await page.getByRole('button',{name:'Depart for pickup',exact:true}).click();await page.getByText('on the way',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Accept request',exact:true}).count(),0);checks.push('Today opens the scheduled cab directly within a multi-record queue; driver departure works without owner controls');
 await tab(page,'Shared journeys');const sharedPicker=page.getByLabel('Shared ride to manage');await sharedPicker.waitFor();assert.equal(await sharedPicker.locator('option').count(),2);await sharedPicker.selectOption({index:1});const sharedId=await sharedPicker.inputValue();const selectedShared=(await call('/shared','worker')).departures.find(row=>row.id===sharedId);await page.getByRole('heading',{name:selectedShared.origin_address+' → '+selectedShared.destination_address,exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Publish a departure',exact:true}).count(),0);await variants(page,'driver-shared-queue');
 await page.setViewportSize({width:850,height:390});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await pinnedNavigation(page);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));await tab(page,'Cab journeys');await page.waitForFunction(()=>{const h=document.querySelector('.suite-panel-title').getBoundingClientRect(),n=document.querySelector('.suite-navigation').getBoundingClientRect();return h.top>=0&&h.bottom<n.top;});assert.equal(await page.locator('.suite-panel-title').evaluate(e=>e.getBoundingClientRect().top>=0&&e.getBoundingClientRect().bottom<document.querySelector('.suite-navigation').getBoundingClientRect().top),true,'switching between long panels returns to the breadcrumb and heading');await page.setViewportSize({width:465,height:850});await page.evaluate(()=>document.documentElement.style.fontSize='100%');checks.push('shared ride selection, AAA contrast and landscape text zoom retain usable navigation');
 await open(page,'cab_owner');await page.getByRole('navigation',{name:'Cab owner suite navigation'}).getByRole('button',{name:'More',exact:true}).click();await variants(page,'owner-more');
 await open(page,'scrap_owner');await pinnedNavigation(page);await tab(page,'Schedule');await page.getByLabel('Schedule month').waitFor();await tab(page,'Account');await page.getByRole('heading',{name:'Business profile'}).waitFor();checks.push('scrap has five pinned destinations and its schedule/account remain accessible');
 await open(page,'technician','worker',true);await page.locator('.worker-welcome-compact').waitFor();await variants(page,'agent-home');await page.getByRole('navigation',{name:'Worker navigation'}).getByRole('button',{name:'Calendar',exact:true}).click();await page.locator('.work-calendar-grid').waitFor();await variants(page,'agent-calendar');checks.push('agent cards, labels and calendar scale with text preferences and pass AAA contrast');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=network&uid=worker');await page.getByRole('button',{name:/Search tasks, people/}).click();await page.locator('.work-network').waitFor();
 for(const name of ['Discover','Connections','Inbox','Communities','Applications','Yearly plan']){await page.getByRole('navigation',{name:'Work network sections'}).getByRole('button',{name,exact:true}).click();await page.waitForTimeout(300);await variants(page,'network-'+name.replaceAll(' ','-'));}await page.keyboard.press('Escape');
 const before=writes.length;await open(page,'cab_owner');await pause(31000);assert.equal(writes.length,before);assert.equal(await page.getByText('Changes are saved',{exact:true}).count(),0);checks.push('idle polling performs no submissions or save popups');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=driver&uid=worker2');await page.getByRole('heading',{name:'Driver registration',exact:true}).waitFor();await page.getByLabel('Legal / business name').fill('Fixture additional driver');await page.getByRole('button',{name:/Business base & address/}).click();const map=page.locator('dialog[open]').last();await map.getByLabel('Latitude',{exact:true}).fill('21.4934');await map.getByLabel('Longitude',{exact:true}).fill('86.9135');await map.getByLabel('House, street and landmark').fill('Fixture driver business base 123');await map.getByLabel('City',{exact:true}).fill('Balasore');await map.getByLabel('I have checked that this pin marks my service entrance.').check();await map.getByRole('button',{name:'Confirm this location',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('input[type=file]').setInputFiles(resolve(web,'public/images/icon-vehicle.png'));await page.getByLabel('I own or am authorized to operate this business',{exact:false}).check();await page.getByRole('button',{name:'Submit for review',exact:true}).click();await page.getByRole('heading',{name:'Application under review'}).waitFor();assert.equal((await call('/partner?role=driver','worker2')).partner.status,'pending');assert.equal((await call('/partner?role=cab_owner','worker2')).partner.status,'approved');checks.push('same phone adds a documented second role; visible review status; existing approval intact');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks,work}));
}catch(error){console.error(error);console.error(log.slice(-1800));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify({checks,errors,writes},null,2));await browser?.close();server.kill('SIGTERM');console.log('Evidence: '+work);}
