import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp(resolve(tmpdir(),'repaido-suites-')),api='http://127.0.0.1:8054',origin='http://127.0.0.1:5187';
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/business_suites_api.py',work+'/test.db','8054'],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser;for(const stream of [server.stdout,server.stderr])stream.on('data',d=>log+=d);
const checks=[],errors=[],writes=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
async function call(path,uid,body,method){const r=await fetch(api+'/operations/local-business'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+uid,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
async function open(page,mode,uid='worker',portal=false){await page.goto(origin+'/tests/business-suites-preview.html?mode='+mode+'&uid='+uid+(portal?'&portal=1':''));await page.getByRole('heading',{name:mode==='driver'?'Driver suite':mode==='scrap_owner'?'Scrap collection suite':'Cab owner suite',exact:true}).waitFor();}
async function tab(page,name){await page.getByRole('navigation',{name:/suite navigation/}).getByRole('button',{name,exact:true}).click();}
async function variants(page,name){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});for(const width of [320,465,1440])for(const theme of ['light','dark'])for(const scale of [100,200]){await page.setViewportSize({width,height:850});await page.evaluate(({theme,scale})=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=scale+'%';},{theme,scale});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow '+width+' '+scale);const violations=await page.evaluate(async()=>(await window.axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));assert.deepEqual(violations,[],name+' accessibility '+width+' '+theme+' '+scale);await page.screenshot({path:work+'/'+name+'-'+width+'-'+theme+'-'+scale+'.png',fullPage:true});}await page.setViewportSize({width:465,height:850});await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});checks.push(name+' responsive / AAA contrast');}
try{
 for(let i=0;i<120;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:465,height:850},reducedMotion:'reduce'});
 await context.route('**/@vite/client',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/new WebSocket\(/g,'new PreviewSocket(');await route.fulfill({response,body:'class PreviewSocket { addEventListener(){} removeEventListener(){} send(){} close(){} }\n'+body});});
 await context.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(!['GET','HEAD'].includes(request.method()))writes.push(url.pathname);const response=await route.fetch({url:api+url.pathname+url.search});await route.fulfill({response});});
 const page=await context.newPage();page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push(e.message));
 await open(page,'cab_owner');await page.getByRole('button',{name:/New booking requests 1/}).waitFor();await variants(page,'owner-overview');
 await tab(page,'Fleet & rates');await page.getByText('OD01AB1234',{exact:false}).waitFor();await variants(page,'owner-fleet');
 await page.getByRole('button',{name:'Edit vehicle & rates'}).click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');
 await tab(page,'Self-drive');await page.getByRole('heading',{name:'Self-drive rentals'}).waitFor();assert.equal(await page.getByText('₹500.00 advance received',{exact:false}).count(),0);await variants(page,'owner-rentals');
 await tab(page,'Cab bookings');await page.getByRole('button',{name:'Accept request',exact:true}).click();await page.getByText('accepted',{exact:true}).first().waitFor();checks.push('owner accepts a customer cab request');
 await open(page,'driver');assert.equal(await page.getByRole('button',{name:'Fleet & rates',exact:true}).count(),0);await variants(page,'driver-overview');await tab(page,'My vehicles');await page.getByText('Test sedan',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add vehicle',exact:true}).count(),0);checks.push('same-phone driver sees accepted assignment, no owner controls');await tab(page,'Cab journeys');await page.getByRole('button',{name:'Depart for pickup',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Accept request',exact:true}).count(),0);await variants(page,'driver-journeys');
 await open(page,'scrap_owner');await page.getByRole('button',{name:/New collection requests 1/}).waitFor();await variants(page,'scrap-overview');await tab(page,'Collections');await page.getByRole('button',{name:'Accept request',exact:true}).click();await page.getByText('accepted',{exact:true}).first().waitFor();await tab(page,'Inspection');await page.getByRole('button',{name:'Record inspection & weight',exact:true}).waitFor();await variants(page,'scrap-inspection');checks.push('same phone opens scrap requests and weighing, no transport modules');
 await page.getByRole('button',{name:'Record inspection & weight',exact:true}).click();const weighing=page.locator('dialog[open]').last();await weighing.getByLabel('Grade / condition').fill('Clean dry steel');await weighing.getByLabel('Gross weight (kg)').fill('10.5');await weighing.getByLabel('Container / tare (kg)').fill('0.5');await weighing.getByLabel('₹ per kg').fill('25');await weighing.getByLabel('Scale identifier / calibration reference').fill('fixture-scale-123');await weighing.getByLabel('Inspection notes').fill('Fixture material checked and scale zeroed.');await weighing.getByLabel('Actual weighing photo').setInputFiles(resolve(web,'public/images/icon-vehicle.png'));await weighing.getByRole('button',{name:'Send weighed quote',exact:true}).click();await page.getByRole('heading',{name:'Weighed quote',exact:true}).waitFor();const scrapRow=(await call('/scrap','customer')).collections[0];assert.equal(scrapRow.evaluation.total_paise,25000);await call('/scrap/'+scrapRow.id+'/commands','customer',{action:'agree',expected_version:scrapRow.version,command_id:crypto.randomUUID()});await tab(page,'Payments');await page.getByRole('button',{name:'Record customer payment',exact:true}).click();const payment=page.locator('dialog[open]').last();await payment.getByLabel('Payment reference').fill('fixture-transfer-123');await payment.getByLabel('Notes',{exact:true}).fill('Fixture agreed amount paid to the customer.');await payment.getByRole('button',{name:'Confirm paid',exact:true}).click();await page.getByText('payment reported',{exact:true}).waitFor();const reported=(await call('/scrap','customer')).collections[0];await call('/scrap/'+reported.id+'/commands','customer',{action:'received',expected_version:reported.version,command_id:crypto.randomUUID()});checks.push('private weighing photo upload, approved quote, actual payment entry and customer receipt');
 await open(page,'cab_owner','worker',true);assert.equal(await page.getByRole('heading',{name:'Cab owner suite',exact:true}).count(),1);await page.getByRole('button',{name:'Business apps',exact:true}).click();await page.getByRole('link',{name:/Scrap collector.*Open your app/}).waitFor();await variants(page,'business-launcher');assert.equal(await page.getByRole('combobox',{name:'Work desk'}).count(),0);checks.push('contractor phone enters requested cab app without role override; separate app links');await page.keyboard.press('Escape');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=scrap_owner&uid=worker2');await page.getByRole('heading',{name:'Application under review'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Scrap collection suite'}).count(),0);checks.push('pending extra role cannot open approved suite');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=mobility&uid=customer');await page.getByRole('button',{name:/Shared ride Join/}).waitFor();await variants(page,'customer-travel');await page.getByRole('button',{name:/Self-drive rental Choose/}).click();await page.getByText('Self-drive rental',{exact:true}).first().waitFor();checks.push('customer shared, chauffeured, self-drive choices are distinct');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=scrap&uid=customer');await page.getByRole('button',{name:'history',exact:true}).click();await page.getByRole('list',{name:'Collection progress',exact:true}).waitFor();await variants(page,'customer-scrap');
 const before=writes.length;await open(page,'cab_owner');await pause(31000);assert.equal(writes.length,before);assert.equal(await page.getByText('Changes are saved',{exact:true}).count(),0);checks.push('idle polling performs no submissions or save popups');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=driver&uid=worker2');await page.getByRole('heading',{name:'Driver registration',exact:true}).waitFor();await page.getByLabel('Legal / business name').fill('Fixture additional driver');await page.getByRole('button',{name:/Business base & address/}).click();const map=page.locator('dialog[open]').last();await map.getByLabel('Latitude',{exact:true}).fill('21.4934');await map.getByLabel('Longitude',{exact:true}).fill('86.9135');await map.getByLabel('House, street and landmark').fill('Fixture driver business base 123');await map.getByLabel('City',{exact:true}).fill('Balasore');await map.getByLabel('I have checked that this pin marks my service entrance.').check();await map.getByRole('button',{name:'Confirm this location',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('input[type=file]').setInputFiles(resolve(web,'public/images/icon-vehicle.png'));await page.getByLabel('I own or am authorized to operate this business',{exact:false}).check();await page.getByRole('button',{name:'Submit for review',exact:true}).click();await page.getByRole('heading',{name:'Application under review'}).waitFor();assert.equal((await call('/partner?role=driver','worker2')).partner.status,'pending');assert.equal((await call('/partner?role=cab_owner','worker2')).partner.status,'approved');checks.push('same phone adds a documented second role; visible review status; existing approval intact');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks,work}));
}catch(error){console.error(error);console.error(log.slice(-1800));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify({checks,errors,writes},null,2));await browser?.close();server.kill('SIGTERM');console.log('Evidence: '+work);}
