import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),backend=resolve(web,'../backend');
const work=await mkdtemp(resolve(tmpdir(),'contracts-e2e-')),db=resolve(work,'contracts.db');
const python=resolve(backend,'.venv/bin/python'),port=Number(process.env.CONTRACTS_TEST_PORT||8032),apiOrigin='http://127.0.0.1:'+port;
const origin=process.env.CONTRACTS_PREVIEW_ORIGIN||'http://127.0.0.1:5187';
let server,browser,log='',succeeded=false;const errors=[];
function fixture(kind,id,body){
 const code='import json,os,sys\nos.environ["REPAIDO_DB"]=sys.argv[1]\nos.environ["REPAIDO_STORAGE"]="sqlite"\nimport main\nmain.operations_store.run(lambda u:u.put(sys.argv[2],sys.argv[3],json.loads(sys.argv[4])))';
 const result=spawnSync(python,['-c',code,db,kind,id,JSON.stringify(body)],{cwd:backend,encoding:'utf8'});assert.equal(result.status,0,result.stderr);
}
async function api(path,account,method='GET',body,status=200){
 const r=await fetch(apiOrigin+path,{method,headers:{...(account?{Authorization:'Bearer '+account.token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const data=await r.json();assert.equal(r.status,status,method+' '+path+': '+JSON.stringify(data));return data;
}
async function register(name){const account=await api('/auth/register',null,'POST',{name,email:name.toLowerCase().replaceAll(' ','.')+'@contracts.test',password:'isolated-contracts-test'},201);fixture('e2e_verified_phone',account.user.id,{phone:'+919876543210'});return account;}
async function newPage(account,mode='discovery',width=390){
 const context=await browser.newContext({viewport:{width,height:850},reducedMotion:'reduce'});
 await context.addInitScript(token=>{if(token)localStorage.setItem('repaido.token',token);},account?.token||'');
 await context.route('**/api/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:apiOrigin+url.pathname+url.search});await route.fulfill({response});});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/tests/contracts-preview.html?mode='+mode);return page;
}
async function layout(page){
 const result=await page.evaluate(()=>{
  const bad=[];if(document.documentElement.scrollWidth>innerWidth+1)bad.push('Document overflow');
  for(const el of document.querySelectorAll('.tender-market,.tender-opportunity,.contract-desk,.contract-card,.contract-dialog,.contract-form,.contract-hiring-dialog')){
   if(el.getClientRects().length&&el.scrollWidth>el.clientWidth+1)bad.push('Overflow '+el.className);
  }
  for(const el of document.querySelectorAll('button,input:not([type=checkbox]),select,textarea')){
   if(el.getClientRects().length&&el.getBoundingClientRect().height<31)bad.push('Compact target below32px: '+(el.getAttribute('aria-label')||el.textContent||el.name));
  }return bad;
 });if(result.length){await mkdir(resolve(web,'test-results'),{recursive:true});await page.screenshot({path:resolve(web,'test-results/contracts-layout-failure.png')});console.log(await page.locator('dialog[open]').evaluateAll(nodes=>nodes.map(node=>({width:node.clientWidth,scroll:node.scrollWidth,children:[...node.querySelectorAll('*')].filter(child=>child.getBoundingClientRect().right>node.getBoundingClientRect().right+1).map(child=>({tag:child.tagName,class:child.className,width:child.getBoundingClientRect().width,scroll:child.scrollWidth})).slice(0,12)}))));}assert.deepEqual(result,[]);
}
async function audit(page){
 await page.addScriptTag({path:require.resolve('axe-core')});
 const result=await page.evaluate(()=>window.axe.run(document.querySelector('main'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']}}));
 assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
}
const local=value=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
try{
 const code='import main,uvicorn,contract_work,time\nfrom fastapi import Header,Body\nfrom types import SimpleNamespace\noriginal=main.current_user\ndef verified(authorization: str=Header(default="")):\n user=original(authorization)\n claim=main.operations_store.run(lambda u:u.get("e2e_verified_phone",user["id"]))\n return {**user,**({"phone":claim["phone"],"phone_verified":True,"phone_authenticated":True} if claim else {})}\nmain.app.dependency_overrides[original]=verified\noffset=0\n@main.app.post("/e2e-clock")\ndef adjust(body:dict=Body(...)):\n global offset\n offset=body["seconds"]\n return {"offset":offset}\ncontract_work.time=SimpleNamespace(time=lambda:time.time()+offset)\nuvicorn.run(main.app,host="127.0.0.1",port='+port+')';
 server=spawn(python,['-c',code],{cwd:backend,env:{...process.env,REPAIDO_DB:db,REPAIDO_STORAGE:'sqlite'},stdio:['ignore','pipe','pipe']});
 server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
 for(let n=0;n<100;n++){try{if((await fetch(apiOrigin+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const guest=await newPage(null);await guest.getByRole('heading',{name:'No tenders published yet',exact:true}).waitFor();
 assert.equal(await guest.getByText('Illustrative demos').count(),0);assert.equal(await guest.locator('.tender-opportunity').count(),0);await layout(guest);await audit(guest);assert((await guest.locator('.tender-market>.business-page-header').boundingBox()).height<130,'Contract header stays lean on a phone');
 const owner=await register('Project Owner'),contractor=await register('Approved Lead'),agent=await register('Project Agent');
 for(const [account,isContractor] of [[contractor,true],[agent,false]])fixture('workers',account.user.id,{id:account.user.id,name:account.user.name,status:'approved',contractor_verified:isContractor,role:'technician',city:'Balasore',skills:['Electrical inspection'],categories:['electrician'],experience_years:4,completed_tasks:0,rating_count:0,rating_sum:0});
 const publisher=await newPage(owner,'workspace');await publisher.getByRole('button',{name:'Publish tender',exact:true}).click();
 const form=publisher.getByRole('dialog',{name:'Publish a tender',exact:true});await form.waitFor();
 const now=Date.now();await form.getByLabel('Project title',{exact:true}).fill('Actual electrical maintenance contract');await form.getByLabel('Scope & deliverables',{exact:true}).fill('Inspect circuits and replace the agreed damaged fixtures with documented safety checks.');
 await form.getByLabel('Site address',{exact:true}).fill('PRIVATE Workshop entrance Balasore');await form.getByLabel('Work starts (your local time)',{exact:true}).fill(local(now+3600000));await form.getByLabel('Work ends (your local time)',{exact:true}).fill(local(now+10800000));await form.getByLabel('Planned budget (₹)',{exact:true}).fill('25000');
 await form.getByLabel('City',{exact:true}).fill('Balasore');await form.getByLabel('Business sector',{exact:true}).selectOption('Electrical');await form.getByLabel('Bidding opens (your local time)',{exact:true}).fill(local(now-600000));await form.getByLabel('Bidding closes (your local time)',{exact:true}).fill(local(now+1800000));await form.getByLabel('Required agents',{exact:true}).fill('1');await form.getByLabel('Tender terms, eligibility & evaluation criteria',{exact:true}).fill('CONFIDENTIAL Evaluation requires a safe inspection plan and an accepted project crew.');
 await form.getByRole('checkbox').check();await form.getByRole('button',{name:'Save & continue',exact:true}).click();await form.waitFor({state:'hidden'});
 const tenders=(await api('/operations/contractor/published')).tenders;assert.equal(tenders.length,1);const tender=tenders[0];assert.equal(tender.budget_paise,2500000);
 await publisher.getByRole('dialog',{name:tender.title,exact:true}).waitFor();await layout(publisher);
 await guest.getByRole('button',{name:'Refresh opportunities',exact:true}).click();await guest.locator('.tender-opportunity').waitFor();await guest.getByRole('button',{name:'View opportunity',exact:true}).click();const summary=guest.getByRole('dialog',{name:tender.title,exact:true});await summary.waitFor();
 assert(!String(await summary.innerText()).includes('PRIVATE'));assert(!String(await summary.innerText()).includes('CONFIDENTIAL'));await summary.getByText('Full scope is available to approved contractors',{exact:true}).waitFor();await layout(guest);await guest.keyboard.press('Escape');
 const lead=await newPage(contractor);await lead.locator('.tender-opportunity').waitFor();await lead.getByRole('button',{name:'View opportunity',exact:true}).click();const full=lead.getByRole('dialog',{name:tender.title,exact:true});await full.getByText('PRIVATE Workshop entrance Balasore',{exact:true}).waitFor();await full.getByRole('button',{name:'Prepare team & bid',exact:true}).click();
 const workspaceTender=lead.getByRole('dialog',{name:tender.title,exact:true});await workspaceTender.getByRole('button',{name:'Prepare team',exact:true}).click();const plan=lead.getByRole('dialog',{name:'Prepare tender team',exact:true});await plan.getByRole('button',{name:'Save & continue',exact:true}).click();await plan.waitFor({state:'hidden'});
 const projectDetail=lead.getByRole('dialog',{name:tender.title,exact:true});await projectDetail.getByRole('button',{name:'Invite agent',exact:true}).click();const invitation=lead.getByRole('dialog',{name:'Invite a Repaido agent',exact:true});await invitation.getByLabel('Registered agent',{exact:true}).selectOption(agent.user.id);await invitation.getByLabel('Project role',{exact:true}).selectOption('member');await invitation.getByLabel('Agreed daily rate (₹)',{exact:true}).fill('1000');await invitation.getByLabel('Duties, hours, compensation & joining terms',{exact:true}).fill('Eight agreed work hours with safe equipment and the recorded daily compensation.');await invitation.getByRole('checkbox').check();await invitation.getByRole('button',{name:'Save & continue',exact:true}).click();await invitation.waitFor({state:'hidden'});
 let project=(await api('/operations/contractor/workspace',agent)).projects[0];assert.equal(project.team[0].status,'pending');assert.equal('budget_paise' in project,false);
 await api('/operations/contractor/projects/'+project.id+'/commands',agent,'POST',{expected_version:project.version,action:'accept',target_id:project.team[0].id});
 await projectDetail.getByRole('button',{name:'Close dialog',exact:true}).click();await lead.getByRole('button',{name:'Refresh workspace',exact:true}).click();await lead.getByRole('tab',{name:'Tenders',exact:true}).click();await lead.getByRole('button',{name:'Scope, teams & bids',exact:true}).click();const bidDetail=lead.getByRole('dialog',{name:tender.title,exact:true});await bidDetail.getByRole('button',{name:'Submit / revise bid',exact:true}).click();const bid=lead.getByRole('dialog',{name:'Submit / revise bid',exact:true});await bid.getByLabel('Accepted team plan',{exact:true}).selectOption(project.id);await bid.getByLabel('Total quote (₹)',{exact:true}).fill('22500');await bid.getByLabel('Proposal, inclusions, exclusions & delivery approach',{exact:true}).fill('We will complete all listed electrical inspection requirements with one accepted technician.');await bid.getByRole('checkbox').check();await bid.getByRole('button',{name:'Save & continue',exact:true}).click();await bid.waitFor({state:'hidden'});
 let owned=(await api('/operations/contractor/workspace',owner)).tenders[0];assert.equal(owned.bids.length,1);assert.equal(owned.bids[0].amount_paise,2250000);
 await api('/e2e-clock',null,'POST',{seconds:3700});await api('/operations/contractor/tenders/'+owned.id+'/commands',owner,'POST',{expected_version:owned.version,action:'award',bid_id:owned.bids[0].id});
 await bidDetail.getByRole('button',{name:'Close dialog',exact:true}).click();await lead.getByRole('button',{name:'Refresh workspace',exact:true}).click();await lead.getByRole('tab',{name:'Projects',exact:true}).click();await lead.getByRole('button',{name:'Open project workspace',exact:true}).click();const awarded=lead.getByRole('dialog',{name:tender.title,exact:true});await awarded.getByRole('button',{name:'Start work',exact:true}).click();const start=lead.getByRole('dialog',{name:'Start project',exact:true});await start.getByRole('checkbox').check();await start.getByRole('button',{name:'Save & continue',exact:true}).click();await start.waitFor({state:'hidden'});
 await awarded.getByRole('button',{name:'Add goal',exact:true}).click();const goal=lead.getByRole('dialog',{name:'Add milestone / goal',exact:true});await goal.getByLabel('Outcome / milestone',{exact:true}).fill('Complete safety inspection');await goal.getByLabel('Acceptance criteria',{exact:true}).fill('Document every inspected circuit and repaired fixture.');await goal.getByLabel('Responsible agent',{exact:true}).selectOption(agent.user.id);await goal.getByLabel('Due date',{exact:true}).fill(local(now+9000000));await goal.getByRole('button',{name:'Save & continue',exact:true}).click();await goal.waitFor({state:'hidden'});
 project=(await api('/operations/contractor/workspace',agent)).projects[0];await api('/operations/contractor/projects/'+project.id+'/commands',agent,'POST',{expected_version:project.version,action:'goal_submit',target_id:project.goals[0].id,note:'Completed inspected circuits and documented the agreed repair evidence.'});
 await awarded.getByRole('button',{name:'Close dialog',exact:true}).click();await lead.getByRole('button',{name:'Refresh workspace',exact:true}).click();await lead.getByRole('button',{name:'Open project workspace',exact:true}).click();const final=lead.getByRole('dialog',{name:tender.title,exact:true});await final.getByRole('button',{name:'Approve',exact:true}).click();const approval=lead.getByRole('dialog',{name:'Approve milestone',exact:true});await approval.getByRole('checkbox').check();await approval.getByRole('button',{name:'Save & continue',exact:true}).click();await approval.waitFor({state:'hidden'});await final.getByRole('button',{name:'Complete',exact:true}).click();const complete=lead.getByRole('dialog',{name:'Complete project',exact:true});await complete.getByRole('checkbox').check();await complete.getByRole('button',{name:'Save & continue',exact:true}).click();await complete.waitFor({state:'hidden'});assert.equal((await api('/operations/contractor/workspace',contractor)).projects[0].status,'completed');
 console.log('PASS: real tender publication, private scope, accepted crew, proposal, award, milestone and completion persistence.');
 await final.getByRole('button',{name:'Close dialog',exact:true}).click();
 // A phone-verified customer can request private work without gaining commercial approval.
 const personal=await newPage(owner);await personal.getByRole('button',{name:'Private work request',exact:true}).click();
 const request=personal.getByRole('dialog',{name:'Post a private work request',exact:true});
 await request.getByLabel('What do you need done?',{exact:true}).fill('Private electrical home project');
 await request.getByLabel('Work and expected outcome',{exact:true}).fill('Inspect circuits and repair safe household electrical fixtures with documented outcomes.');
 await request.getByLabel('Private site address').fill('PRIVATE Customer house site Balasore');await request.getByLabel('Work starts',{exact:true}).fill(local(now+14000000));await request.getByLabel('Work ends',{exact:true}).fill(local(now+18000000));await request.getByLabel('Planned total budget (₹)',{exact:true}).fill('18000');await request.getByRole('checkbox').check();await request.getByRole('button',{name:'Create request & plan hiring',exact:true}).click();await request.waitFor({state:'hidden'});
 const personalProject=personal.getByRole('dialog',{name:'Private electrical home project',exact:true});await personalProject.waitFor();await personalProject.getByRole('button',{name:'Publish roles & review applicants',exact:true}).click();
 let privateProject=(await api('/operations/contractor/workspace',owner)).projects.find(project=>project.title==='Private electrical home project');assert.equal(privateProject.source_kind,'private_request');assert.equal((await api('/operations/contractor/workspace',owner)).can_contract,false);
 await personal.getByRole('button',{name:'Publish hiring',exact:true}).click();const notice=personal.getByRole('dialog',{name:'Publish project hiring',exact:true});
 await notice.getByLabel('City',{exact:true}).fill('Balasore');await notice.getByLabel('Area / neighbourhood',{exact:true}).fill('Central Balasore');await notice.getByLabel('Business sector',{exact:true}).selectOption('Education');assert.equal(await notice.getByLabel('Work category',{exact:true}).inputValue(),'','Industry selection does not silently choose a profession');await notice.getByLabel('Public project description',{exact:true}).fill('Electrical inspection and agreed household fixture repairs with site safety checks.');await notice.getByLabel('Skills (comma separated)',{exact:true}).fill('Electrical inspection');await notice.getByLabel('Minimum experience (years)',{exact:true}).fill('2');await notice.getByLabel('Daily rate (₹)',{exact:true}).fill('1200');await notice.getByLabel('Application deadline (your local time)',{exact:true}).fill(local(now+11000000));await notice.getByLabel('Work, payment & joining terms',{exact:true}).fill('Eight hours with agreed daily compensation, safe equipment and confirmed work dates.');await notice.getByRole('checkbox').check();await notice.getByRole('button',{name:'Save hiring notice',exact:true}).click();assert.equal(await notice.getByLabel('Work category',{exact:true}).evaluate(select=>select.validity.valueMissing),true,'Publishing requires an explicit work category');await notice.getByLabel('Work category',{exact:true}).selectOption('electrician');await layout(personal);await notice.getByRole('button',{name:'Save hiring notice',exact:true}).click();await notice.waitFor({state:'hidden'});
 await api('/repaidians/state',agent);await api('/repaidians/profile',agent,'PATCH',{trade:'electrician',city:'Balasore',skills:['Electrical inspection'],experienceYears:4,workStatus:'available',professionalType:'agent'});
 await personal.getByRole('button',{name:'Ready profiles',exact:true}).click();const ready=personal.getByRole('dialog',{name:'Ready profiles for this project',exact:true});await ready.getByRole('heading',{name:agent.user.name,exact:true}).waitFor();assert(!String(await ready.innerText()).includes('PRIVATE Customer'));await ready.getByRole('button',{name:'Close dialog',exact:true}).click();
 privateProject=(await api('/operations/contractor/workspace',owner)).projects.find(project=>project.id===privateProject.id);assert.equal(privateProject.hiring.sector,'Education');assert.equal(privateProject.hiring.work_trade,'electrician');const electricalJobs=(await api('/repaidians/work/jobs?trade=electrician',agent)).items;assert(electricalJobs.some(job=>job.id===privateProject.id&&job.trade==='electrician'),'Electrical role in Education industry remains discoverable in My jobs');assert(!(await api('/repaidians/work/jobs?trade=spares',agent)).items.some(job=>job.id===privateProject.id),'Industry does not misclassify the role as shop spares');await personal.getByRole('button',{name:'Manage notice',exact:true}).click();const editingNotice=personal.getByRole('dialog',{name:'Manage hiring notice',exact:true});assert.equal(await editingNotice.getByLabel('Business sector',{exact:true}).inputValue(),'Education');assert.equal(await editingNotice.getByLabel('Work category',{exact:true}).inputValue(),'electrician');await personal.keyboard.press('Escape');
 const workApplicant=await newPage(agent);const privateListing=workApplicant.locator('.contract-private-cards article').filter({has:workApplicant.getByRole('heading',{name:'Private electrical home project',exact:true})});await privateListing.waitFor();assert(!String(await privateListing.innerText()).includes('PRIVATE Customer house'));
 // Industry filters and text searches remain independent from the agent's work trade.
 const privateQuery='Private electrical home project';await workApplicant.locator('#contract-sector-options').getByRole('button',{name:'Education',exact:true}).click();await privateListing.waitFor();
 const educationSearch=workApplicant.waitForResponse(response=>{const url=new URL(response.url());return url.pathname==='/api/repaidians/work/jobs'&&url.searchParams.get('sector')==='Education'&&url.searchParams.get('query')===privateQuery;});
 await workApplicant.getByRole('searchbox',{name:'Search contract opportunities',exact:true}).fill(privateQuery);const matchingResponse=await educationSearch;assert.equal(matchingResponse.status(),200);assert((await matchingResponse.json()).items.some(job=>job.id===privateProject.id),'Education industry and project-title query preserve the electrical private role');await privateListing.waitFor();
 const retailSearch=workApplicant.waitForResponse(response=>{const url=new URL(response.url());return url.pathname==='/api/repaidians/work/jobs'&&url.searchParams.get('sector')==='Retail'&&url.searchParams.get('query')===privateQuery;});await workApplicant.locator('#contract-sector-options').getByRole('button',{name:'Retail',exact:true}).click();assert(!(await (await retailSearch).json()).items.some(job=>job.id===privateProject.id),'Different industry excludes an otherwise matching keyword');await privateListing.waitFor({state:'hidden'});await workApplicant.locator('#contract-sector-options').getByRole('button',{name:'Education',exact:true}).click();await privateListing.waitFor();
 await privateListing.getByRole('button',{name:'Work & joining terms',exact:true}).click();const workDetails=workApplicant.getByRole('dialog',{name:'Private electrical home project',exact:true});await workDetails.getByLabel('Why you’re a good fit',{exact:true}).fill('I have four years of electrical inspection experience and am available for these dates.');await workDetails.getByRole('checkbox').check();await workDetails.getByRole('button',{name:'Apply to join · free',exact:true}).click();await workDetails.waitFor({state:'hidden'});const application=(await api('/operations/contractor/hiring/applications?scope=mine',agent)).applications.find(row=>row.project_id===privateProject.id);assert(application,'Actual browser private application persists');await workApplicant.context().close();
 await personal.getByRole('button',{name:'Refresh joining requests',exact:true}).click();await personal.getByRole('button',{name:'Review application',exact:true}).click();const review=personal.getByRole('dialog',{name:agent.user.name+' · application',exact:true});await review.getByText('application viewed',{exact:false}).waitFor();await review.getByText('View applicant profile',{exact:true}).click();await review.getByText('profile viewed',{exact:false}).waitFor();await review.getByRole('button',{name:'Mark reviewed',exact:true}).click();await review.locator('.wn-timeline').getByText('reviewed',{exact:false}).waitFor();await review.getByRole('button',{name:'Close dialog',exact:true}).click();
 await personal.getByRole('button',{name:'Hold',exact:true}).click();const hold=personal.getByRole('dialog',{name:'Place application on hold',exact:true});await hold.getByLabel('Message to candidate',{exact:true}).fill('Confirming the household inspection plan.');await hold.getByRole('button',{name:'Save decision',exact:true}).click();await hold.waitFor({state:'hidden'});await personal.locator('.contract-chip').getByText('On hold',{exact:true}).waitFor();
 await personal.getByRole('button',{name:'Offer',exact:true}).click();const offer=personal.getByRole('dialog',{name:'Send joining terms',exact:true});await offer.getByRole('button',{name:'Send joining offer',exact:true}).click();await offer.waitFor({state:'hidden'});
 const pending=(await api('/operations/contractor/workspace',agent)).projects.find(project=>project.id===privateProject.id);assert.equal(pending.team[0].status,'pending');assert.equal('budget_paise' in pending,false);
 await api('/operations/contractor/projects/'+pending.id+'/commands',agent,'POST',{expected_version:pending.version,action:'accept',target_id:pending.team[0].id});await personal.getByRole('button',{name:'Refresh joining requests',exact:true}).click();await personal.locator('.contract-chip').getByText('Joined',{exact:true}).waitFor();
 const received=(await api('/operations/contractor/hiring/applications?scope=mine',agent)).applications.find(row=>row.id===application.id);for(const action of ['application_viewed','profile_viewed','reviewed','hold','offer','accepted'])assert(received.events.some(event=>event.action===action||event.status===action||(action==='accepted'&&event.status==='hired')),'Actual application event '+action);
 for(const theme of ['light','dark']){await personal.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await layout(personal);await audit(personal);}await personal.setViewportSize({width:320,height:850});await personal.evaluate(()=>document.documentElement.style.fontSize='200%');await layout(personal);await personal.context().close();
 console.log('PASS: customer private request, real ready profile, published notice, application open/profileview/review, hold, offer, acceptance and private budget protection.');
 // Restore a future published tender for mobile discovery checks, with no fake UI data.
 await api('/operations/contractor/tenders',owner,'POST',{request_id:randomUUID(),title:'Second actual maintenance tender',scope:'Inspect and repair agreed workshop requirements',site:'Private test site address',starts_at:now/1000+14000,ends_at:now/1000+18000,budget_paise:3500000,sector:'Electrical',city:'Balasore',opens_at:now/1000+3000,deadline:now/1000+12000,manpower_needed:2,terms:'Contractor must document safety checks and accepted crew for this scope.'});
 // Sign-out/account-switch regression: protected detail cannot survive actor changes,
 // including an old response released after the new actor has been checked.
 const privacy=await newPage(contractor);await privacy.locator('.tender-opportunity').waitFor();
 await privacy.getByRole('button',{name:'View opportunity',exact:true}).click();
 const watch=privacy.getByRole('button',{name:'Watch contract',exact:true});await watch.waitFor();await watch.click();const preferences=privacy.getByRole('dialog',{name:'Opportunity preferences',exact:true});await preferences.getByRole('checkbox',{name:'Daily contract updates',exact:false}).check();await preferences.getByRole('checkbox',{name:'Relevant opportunities',exact:false}).check();await preferences.getByRole('button',{name:'Save preferences',exact:true}).click();await preferences.waitFor({state:'hidden'});await privacy.getByRole('button',{name:'Watching · stop',exact:true}).waitFor();const watchedTender=(await api('/operations/contractor/published')).tenders[0];assert.equal((await api('/repaidians/work/contracts/'+watchedTender.id+'/watch',contractor)).watched,true);await privacy.getByRole('button',{name:'Watching · stop',exact:true}).click();await watch.waitFor();assert.equal((await api('/repaidians/work/contracts/'+watchedTender.id+'/watch',contractor)).watched,false);
 console.log('PASS: explicit personalization/update consent, actual watch persistence, unwatch and daily three-contract limit copy.');
 const protectedText='Inspect and repair agreed workshop requirements';
 await privacy.getByText(protectedText,{exact:true}).waitFor();
 const switchActor=async(page,token)=>page.evaluate(token=>{const oldValue=localStorage.getItem('repaido.token');if(token)localStorage.setItem('repaido.token',token);else localStorage.removeItem('repaido.token');window.dispatchEvent(new StorageEvent('storage',{key:'repaido.token',oldValue,newValue:token||null}));},token);
 await switchActor(privacy,owner.token);await privacy.getByText('Full scope is available to approved contractors',{exact:true}).waitFor();assert.equal(await privacy.getByText(protectedText,{exact:true}).count(),0);
 let release,seen;const held=new Promise(resolve=>release=resolve),started=new Promise(resolve=>seen=resolve);let delay=true;
 const late=async route=>{if(route.request().headers().authorization!=='Bearer '+contractor.token)return route.fallback();const url=new URL(route.request().url()),response=await route.fetch({url:apiOrigin+url.pathname+url.search});if(delay){delay=false;seen();await held;}await route.fulfill({response}).catch(()=>{});};
 await privacy.context().route('**/api/operations/contractor/opportunities',late);
 await switchActor(privacy,contractor.token);await started;await switchActor(privacy,owner.token);release();await privacy.getByText('Full scope is available to approved contractors',{exact:true}).waitFor();assert.equal(await privacy.getByText(protectedText,{exact:true}).count(),0);
 await privacy.context().unroute('**/api/operations/contractor/opportunities',late);await switchActor(privacy,'');await privacy.getByText('Full scope is available to approved contractors',{exact:true}).waitFor();assert.equal(await privacy.getByText(protectedText,{exact:true}).count(),0);await privacy.context().close();
 await switchActor(lead,owner.token);await lead.getByText('Contractor approval required',{exact:true}).waitFor();await lead.getByRole('dialog',{name:tender.title,exact:true}).waitFor();await lead.getByRole('dialog',{name:tender.title,exact:true}).getByRole('button',{name:'Close dialog',exact:true}).click();await lead.getByRole('tab',{name:'Projects',exact:true}).click();await lead.getByRole('heading',{name:'Private electrical home project',exact:true}).waitFor();assert.equal(await lead.locator('.contract-card').count(),1);assert.equal(await lead.locator('.contract-card').getByRole('heading',{name:tender.title,exact:true}).count(),0);await switchActor(lead,contractor.token);await lead.getByRole('dialog',{name:tender.title,exact:true}).waitFor();await lead.getByRole('dialog',{name:tender.title,exact:true}).getByRole('button',{name:'Close dialog',exact:true}).click();await lead.getByRole('tab',{name:'Projects',exact:true}).click();await lead.locator('.contract-card').waitFor();
 // A failed new sector search must never label previous-sector records as matches.
 let failSector=true;const failed=async route=>{const url=new URL(route.request().url());if(failSector&&url.searchParams.get('sector')==='Plumbing')return route.fulfill({status:503,json:{detail:'Search temporarily unavailable'}});return route.fallback();};
 await guest.context().route('**/api/operations/contractor/published?*',failed);
 await guest.getByRole('button',{name:'Plumbing',exact:true}).click();await guest.getByRole('alert').waitFor();assert.equal(await guest.locator('.tender-opportunity').count(),0);failSector=false;await guest.getByRole('button',{name:'Retry',exact:true}).click();await guest.getByRole('heading',{name:'No matching opportunities',exact:true}).waitFor();await guest.locator('.tender-results-heading').getByRole('button',{name:'Clear filters',exact:true}).click();await guest.locator('.tender-opportunity').waitFor();await guest.context().unroute('**/api/operations/contractor/published?*',failed);const selectedBounds=await guest.locator('#contract-sector-options').evaluate(rail=>{const selected=rail.querySelector('[aria-pressed=true]'),bounds=rail.getBoundingClientRect(),button=selected.getBoundingClientRect();return{left:button.left,right:button.right,railLeft:bounds.left,railRight:bounds.right};});assert(selectedBounds.left>=selectedBounds.railLeft-1&&selectedBounds.right<=selectedBounds.railRight+1,'Reset brings the active sector back into view');
 // Shared tab controls have real roving keyboard focus and matching content.
 await lead.getByRole('tab',{name:'Projects',exact:true}).focus();await lead.keyboard.press('ArrowRight');await lead.getByRole('heading',{name:'Find the right fit. Confirm every offer.',exact:true}).waitFor();assert.equal(await lead.getByRole('tab',{name:'Hiring',exact:true}).getAttribute('aria-selected'),'true');await layout(lead);await lead.keyboard.press('Home');await lead.getByRole('heading',{name:'Next deadlines',exact:true}).waitFor();await lead.getByRole('tab',{name:'Projects',exact:true}).click();
 console.log('PASS: actor-bound private detail/workspace, late response rejection, honest failed-filter state and keyboard navigation.');
 for(const width of [320,390,430,524,1280]){await guest.setViewportSize({width,height:850});await guest.getByRole('button',{name:'Refresh opportunities',exact:true}).click();await guest.locator('.tender-opportunity').waitFor();await layout(guest);await lead.setViewportSize({width,height:850});await layout(lead);}
 for(const theme of ['light','dark']){for(const page of [guest,lead]){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await layout(page);await audit(page);}}
 for(const page of [guest,lead]){await page.setViewportSize({width:320,height:850});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await layout(page);await page.evaluate(()=>document.documentElement.style.fontSize='100%');await page.setViewportSize({width:390,height:850});}
 await mkdir(resolve(web,'test-results'),{recursive:true});await guest.screenshot({path:resolve(web,'test-results/contracts-phone.png')});await lead.screenshot({path:resolve(web,'test-results/contract-workspace-phone.png')});assert.deepEqual(errors,[]);
 console.log('PASS: phone320/390/430/524 and desktop1280 layout, compact32px targets, dark/light AAA audit, 200% text.');succeeded=true;
}finally{await browser?.close();server?.kill('SIGTERM');if(succeeded)await rm(work,{recursive:true,force:true});else console.error('Isolated fixture retained at '+work+'\n'+log.slice(-4000));}
