import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
// Run against a local Vite server; all API requests use a fresh isolated database.
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),backend=resolve(web,'../backend');
const origin=process.env.EXPERIENCE_PREVIEW_ORIGIN||'http://127.0.0.1:5187',port=Number(process.env.EXPERIENCE_TEST_PORT||8042),apiOrigin='http://127.0.0.1:'+port;
assert(['127.0.0.1','localhost'].includes(new URL(origin).hostname),'Preview must use a local Vite server');
const python=process.env.EXPERIENCE_TEST_PYTHON||resolve(backend,'.venv/bin/python'),work=await mkdtemp(resolve(tmpdir(),'repaido-experience-')),db=resolve(work,'test.db');
let server,browser,log='';const errors=[],report={variants:[],effects:[],errors};const pause=ms=>new Promise(r=>setTimeout(r,ms));
function fixtures(rows){const code='import json,os,sys\nos.environ["REPAIDO_DB"]=sys.argv[1]\nos.environ["REPAIDO_STORAGE"]="sqlite"\nimport main\nrows=json.loads(sys.argv[2])\nmain.operations_store.run(lambda u:[u.put(kind,key,value) for kind,key,value in rows])';const r=spawnSync(python,['-c',code,db,JSON.stringify(rows)],{cwd:backend,encoding:'utf8'});assert.equal(r.status,0,r.stderr);}
async function api(path,account,method='GET',body){const r=await fetch(apiOrigin+path,{method,headers:{...(account?{Authorization:'Bearer '+account.token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,path+': '+JSON.stringify(data));return data;}
async function pageFor(account,width=476,motion='reduce'){
 const context=await browser.newContext({viewport:{width,height:850},reducedMotion:motion});await context.addInitScript(a=>{if(a)localStorage.setItem('repaido.token',a.token);localStorage.setItem('repaido.customer.tab','"Explore"');},account||null);
 await context.route('**/api/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:apiOrigin+url.pathname+url.search});await route.fulfill({response});});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));return page;
}
async function layout(page,name){const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,name+' document overflow');await page.screenshot({path:work+'/'+name+'.png',fullPage:true});}
async function axe(page,selector){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});const violations=await page.evaluate(async selector=>(await window.axe.run(selector,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),selector);assert.deepEqual(violations,[],JSON.stringify(violations));}
try{
 const code='import main,uvicorn\nfrom fastapi import Header\noriginal=main.current_user\ndef verified(authorization: str=Header(default="")):\n user=original(authorization)\n return {**user,"phone_verified":True,"phone_authenticated":True,"phone":"+919876543210"}\nmain.app.dependency_overrides[original]=verified\nuvicorn.run(main.app,host="127.0.0.1",port='+port+')';
 server=spawn(python,['-c',code],{cwd:backend,env:{...process.env,REPAIDO_DB:db,REPAIDO_STORAGE:'sqlite',REPAIDO_COMMUNITY_BUCKET:'',REPAIDO_KYC_BUCKET:''},stdio:['ignore','pipe','pipe']});for(const s of [server.stdout,server.stderr])s.on('data',d=>log+=d);
 for(let i=0;i<100;i++){try{if((await fetch(apiOrigin+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const customer=await api('/auth/register',null,'POST',{name:'Experience Customer',email:'experience-customer@example.test',password:'isolated-test-password'}),contractor=await api('/auth/register',null,'POST',{name:'Experience Contractor',email:'experience-contractor@example.test',password:'isolated-test-password'}),now=Date.now()/1000,pid='experience-project';
 fixtures([['workers',contractor.user.id,{id:contractor.user.id,name:'Experience Contractor',status:'approved',contractor_verified:true,city:'Balasore',categories:['electrician'],skills:[],tools:[],languages:[],specialties:[],role:'technician',completed_tasks:3,rating_count:3,rating_sum:15}],['rp_members',contractor.user.id,{id:contractor.user.id,createdAt:Date.now()}],['contract_tenders','experience-tender',{id:'experience-tender',owner_id:customer.user.id,status:'awarded',title:'Electrical tender',city:'Balasore',sector:'Electrical',budget_paise:100000,starts_at:now-3600,ends_at:now+86400,opens_at:now-10800,deadline:now-7200,created_at:now-14400,manpower_needed:1,registrations:[],winning_project_id:pid,winning_bid_id:'experience-bid',bids:[{id:'experience-bid',contractor_id:contractor.user.id,contractor_name:'Experience Contractor',team_size:0,project_id:pid,status:'awarded',amount_paise:100000}]}],['contract_projects',pid,{id:pid,owner_id:contractor.user.id,client_id:customer.user.id,title:'Electrical project',scope:'Inspect and repair the recorded circuits',site:'Private fixture site',status:'active',starts_at:now-3600,ends_at:now+86400,awarded_at:now-7200,tender_id:'experience-tender',contract_value_paise:100000,budget_paise:100000,goals:[{id:'goal',title:'Circuit inspection',status:'planned',due_at:now+1800,assignee_id:contractor.user.id,note:''}],team:[],leave:[],attendance:[],events:[],version:1}]]);
 fixtures(Array.from({length:3},(_,i)=>['contract_projects','additional-'+i,{id:'additional-'+i,owner_id:contractor.user.id,owner_name:'Experience Contractor',title:'Additional project '+i,scope:'Recorded test work plan',site:'Fixture site',status:'planning',starts_at:now+86400,ends_at:now+172800,budget_paise:100000,goals:[],team:[],leave:[],attendance:[],events:[],version:1}]));
 const lead=await pageFor(contractor);await lead.goto(origin+'/tests/customer-experience-preview.html?mode=contractor&account='+contractor.user.id);await lead.getByText('Record a project purchase',{exact:true}).click();
 await lead.getByLabel('Materials or purchase description').fill('Electrical cable');await lead.getByLabel('Actual purchase date (India time)').fill(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));await lead.getByLabel('Purchase amount (₹)').fill('250.00');await lead.getByLabel('Vendor (optional)').fill('Fixture vendor');await lead.getByLabel('Actual invoice or receipt reference').fill('INVOICE-1');await lead.getByRole('button',{name:'Save purchase for review',exact:true}).click();await lead.getByText('Purchase recorded for customer review.',{exact:true}).waitFor();
 const current=await api('/operations/contracts/projects/'+pid+'/records',customer);assert.equal(current.purchases.length,1);assert.equal(current.financials.confirmed_paid_paise,0);
 const owner=await pageFor(customer);await owner.goto(origin+'/tests/customer-experience-preview.html?account='+customer.user.id);await owner.getByRole('button',{name:'Review purchase record',exact:true}).click();await owner.getByLabel('Customer review note').fill('Receipt checked in the fixture');await owner.getByRole('button',{name:'Confirm purchase record',exact:true}).click();await owner.getByRole('region',{name:'Contract purchases'}).getByText('customer confirmed',{exact:true}).waitFor();await owner.getByRole('button',{name:'Purchases',exact:true}).click();await owner.locator('.cc-agenda').getByText('Electrical cable',{exact:true}).waitFor();
 assert.equal((await api('/operations/contracts/projects/'+pid+'/records',customer)).financials.confirmed_paid_paise,0);
 for(const width of [320,476,1440])for(const text of [100,200])for(const theme of ['light','dark']){await owner.setViewportSize({width,height:850});await owner.evaluate(({text,theme})=>{document.documentElement.style.fontSize=text+'%';document.documentElement.dataset.theme=theme;},{text,theme});await layout(owner,'calendar-'+width+'-'+text+'-'+theme);report.variants.push({width,text,theme});}
 await owner.setViewportSize({width:476,height:850});await owner.evaluate(()=>{document.documentElement.style.fontSize='100%';document.documentElement.dataset.theme='light';});await axe(owner,'main');
 const cards=await pageFor(null,476,'no-preference');await cards.goto(origin+'/tests/customer-experience-preview.html?mode=bookings');await cards.locator('.customer-booking-card').first().waitFor();const glows=await cards.locator('.customer-booking-card').evaluateAll(nodes=>nodes.map(n=>({tone:n.dataset.tone,animation:getComputedStyle(n,'::after').animationName,accent:getComputedStyle(n).getPropertyValue('--booking-accent'),shadow:getComputedStyle(n).boxShadow})));assert.deepEqual(glows.map(g=>g.tone),['active','onsite','attention','success']);assert(glows.slice(0,3).every(g=>g.animation==='booking-status-light'));assert.equal(glows[3].animation,'none');await layout(cards,'booking-status-lights');await cards.emulateMedia({reducedMotion:'reduce'});assert(await cards.locator('.customer-booking-card').first().evaluate(n=>getComputedStyle(n,'::after').animationName==='none'));
 const home=await pageFor(null,476,'no-preference');await home.goto(origin+'/?tab=explore');await home.locator('.repaido-services-grid-container').waitFor();assert.equal(await home.locator('.repaido-services-grid-container').getAttribute('data-browse-count'),'1');
 await home.locator('.android-bottom-nav').getByRole('button',{name:'Services',exact:true}).click();await home.locator('.android-bottom-nav').getByRole('button',{name:'Explore',exact:true}).click();assert.equal(await home.locator('.repaido-services-grid-container').getAttribute('data-browse-count'),'1');
 await home.reload();await home.locator('.repaido-services-grid-container').waitFor();assert.equal(await home.locator('.repaido-services-grid-container').getAttribute('data-browse-count'),'2');await home.reload();await home.locator('.repaido-services-grid-container').waitFor();assert.equal(await home.locator('.repaido-services-grid-container').getAttribute('data-hydrated'),'true');assert.equal(await home.locator('.repaido-service-motion-card').count(),6);
 await home.getByRole('button',{name:'Pause service cards',exact:true}).click();assert(await home.getByRole('button',{name:'Play service cards',exact:true}).count());
 // Capture short-lived effects when they mount; separate automation round-trips can outlast the animation.
 await home.evaluate(()=>{window.__observedTabEffects=[];const observer=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node instanceof Element&&node.matches('.brand-tab-transition'))window.__observedTabEffects.push({effect:Number(node.getAttribute('data-effect')),text:node.innerText,pointerEvents:getComputedStyle(node).pointerEvents});});observer.observe(document.body,{childList:true,subtree:true});window.__tabEffectObserver=observer;});
 const effects=[];for(let i=0;i<20;i++){await home.locator('.android-bottom-nav').getByRole('button',{name:i%2?'Explore':'Services',exact:true}).click();await home.waitForFunction(n=>window.__observedTabEffects.length>n,i);const observed=await home.evaluate(n=>window.__observedTabEffects[n],i);effects.push(observed.effect);assert.equal(observed.text,'');assert.equal(observed.pointerEvents,'none');await home.locator('.brand-tab-transition').waitFor({state:'hidden'});}await home.evaluate(()=>window.__tabEffectObserver.disconnect());assert.equal(new Set(effects).size,20);report.effects=effects;
 await home.locator('.promo-home-spotlight').scrollIntoViewIfNeeded();await layout(home,'home-premium');const marketHeight=await home.locator('.marketplace-sliding-notifier-container').evaluate(n=>n.getBoundingClientRect().height);assert(marketHeight<150,'Marketplace height '+marketHeight);report.marketHeight=marketHeight;
 await axe(home,'.promo-home-spotlight');
 for(const width of [320,476,1440])for(const text of [100,200])for(const theme of ['light','dark']){await home.setViewportSize({width,height:850});await home.evaluate(({text,theme})=>{document.documentElement.style.fontSize=text+'%';document.documentElement.dataset.theme=theme;},{text,theme});await layout(home,'home-'+width+'-'+text+'-'+theme);}
 await home.setViewportSize({width:320,height:850});await home.locator('.android-bottom-nav').getByRole('button',{name:'Services',exact:true}).click();await home.locator('.catalog-leaders-overview').waitFor();await home.setViewportSize({width:320,height:850});await home.evaluate(()=>document.documentElement.style.fontSize='200%');await layout(home,'leaders-320-200');await home.setViewportSize({width:476,height:850});await home.evaluate(()=>{document.documentElement.style.fontSize='100%';document.documentElement.dataset.theme='light';});report.homeVariants=12;

 await home.locator('.android-bottom-nav').getByRole('button',{name:'Bookings',exact:true}).click();const serviceSwitch=home.getByRole('group',{name:'Booking service type'});assert.equal(await serviceSwitch.getByRole('button').count(),5);await serviceSwitch.getByRole('button',{name:'Rides',exact:true}).click();await home.getByRole('button',{name:'Sign in to manage rides',exact:true}).waitFor();await serviceSwitch.getByRole('button',{name:'Contracts',exact:true}).click();await home.getByRole('heading',{name:'Sign in to manage your contracts'}).waitFor();await layout(home,'contracts-nav-guest');
 await home.emulateMedia({reducedMotion:'reduce'});await home.locator('.android-bottom-nav').getByRole('button',{name:'Explore',exact:true}).click();await pause(150);assert.equal(await home.locator('.brand-tab-transition').count(),0);
 const desk=await pageFor(contractor);await desk.goto(origin+'/tests/contracts-preview.html?mode=workspace');const bottom=desk.getByRole('tablist',{name:'Contractor bottom navigation'});await bottom.waitFor();assert.equal(await bottom.getByRole('tab').count(),5);await desk.getByRole('heading',{name:'Next deadline',exact:true}).waitFor();assert.equal(await desk.getByRole('button',{name:/Search tasks, people & projects/}).count(),0);
 for(const width of [320,520,1440])for(const text of [100,200])for(const theme of ['light','dark']){await desk.setViewportSize({width,height:850});await desk.evaluate(({text,theme})=>{document.documentElement.style.fontSize=text+'%';document.documentElement.dataset.theme=theme;},{text,theme});await layout(desk,'contractor-'+width+'-'+text+'-'+theme);const boxes=await bottom.getByRole('tab').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return{y:r.y,h:r.height,w:r.width};}));assert.equal(new Set(boxes.map(b=>Math.round(b.y))).size,1);assert(boxes.every(b=>b.w>=44&&b.h>=44));}
 await desk.setViewportSize({width:520,height:850});await desk.evaluate(()=>{document.documentElement.style.fontSize='100%';document.documentElement.dataset.theme='light';});assert((await desk.locator('.contractor-overview').boundingBox()).height<620);await axe(desk,'.contract-desk');await bottom.getByRole('tab',{name:'Projects',exact:true}).click();assert.equal(await desk.locator('.contract-card').count(),3);await desk.getByRole('navigation',{name:'Workspace result pages'}).getByRole('button',{name:'Next',exact:true}).click();assert.equal(await desk.locator('.contract-card').count(),1);await desk.getByRole('navigation',{name:'Workspace result pages'}).getByRole('button',{name:'Previous',exact:true}).click();await desk.locator('.contract-card').filter({hasText:'Electrical project'}).getByRole('button',{name:'Open project workspace',exact:true}).click();const project=desk.getByRole('dialog',{name:'Electrical project',exact:true});await project.waitFor();await project.locator('summary').filter({hasText:'Team & reporting lines'}).click();assert.equal(await project.locator('details[open]').count(),1);await project.locator('summary').filter({hasText:'Goals & milestones'}).click();assert.equal(await project.locator('details[open]').count(),1);await desk.keyboard.press('Escape');await bottom.getByRole('tab',{name:'Work & market',exact:true}).click();await desk.getByRole('tablist',{name:'Work and market sections'}).waitFor();await desk.getByRole('button',{name:/Search tasks, people & projects/}).waitFor();await bottom.getByRole('tab',{name:'Profile',exact:true}).click();await desk.getByRole('button',{name:'Edit business details',exact:true}).waitFor();report.contractorVariants=12;
 assert.deepEqual(errors,[]);report.passed=true;console.log(JSON.stringify({passed:true,work,variants:report.variants.length,effects,marketHeight}));
}catch(error){report.passed=false;report.failure=String(error);console.error(error);console.error(log.slice(-2000));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify(report,null,2));await browser?.close();server?.kill('SIGTERM');console.log('Evidence: '+work);}
