// Local-only UI fixture. This entry is never included in production builds.
import {createRoot} from 'react-dom/client';
import {useState} from 'react';
import axe from 'axe-core';
import {Hiring,type Professional} from '../src/components/Hiring';
import {WorkerNavigation} from '../src/components/WorkerNavigation';
import '../src/styles.css';import '../src/design-system.css';import '../src/components/operations.css';
const profiles:Professional[]=[{id:'local-1',name:'Demo professional A',role:'specialist',rank:1,skills:['Home cleaning'],categories:['cleaning'],tools:['Cleaning kit'],bio:'Local fixture for layout only.',languages:['Odia','Hindi'],specialties:['Routine household cleaning'],experience_years:5,completed_tasks:12,rating:4,review_count:1,distribution:{'1':0,'2':0,'3':0,'4':1,'5':0},reviews:[{service:'Home cleaning',rating:4,text:'Local fixture review, not a real customer.',at:1790600000}],home_services:['maid'],work_history:[{service:'Daily household care',category:'cleaning',completed_at:1790600000,rating:4}],category_records:[{category:'home:maid',completed:12,rating:4,review_count:1}]},{id:'local-2',name:'Demo professional B',role:'technician',skills:['Family care'],categories:['care'],tools:[],bio:'Local fixture for layout only.',languages:['Odia'],specialties:['Daily non-medical support'],experience_years:2,completed_tasks:0,rating:null,review_count:0,distribution:{'1':0,'2':0,'3':0,'4':0,'5':0},reviews:[],home_services:['caretaker']}];
const originalFetch=window.fetch.bind(window);
window.fetch=async(input,init)=>{const path=String(input);if(path.endsWith('/hiring/leaderboard'))return new Response(JSON.stringify({professionals:profiles,categories:[{id:'home:maid',name:'Maid & household help',count:1,leader:{id:'local-1',name:'Demo professional A'}},{id:'home:caretaker',name:'Care at home',count:1,leader:null}]}),{status:200});if(path.endsWith('/hiring/policy'))return new Response(JSON.stringify({enabled:false,radius_buffer_bps:1500}),{status:200});return originalFetch(input,init);};
function Preview(){const [worker,setWorker]=useState(true),[tab,setTab]=useState('Home'),[notice,setNotice]=useState(''),[check,setCheck]=useState('');return <><aside style={{padding:12,borderBottom:'1px solid #ccc',fontSize:12}}><strong>LOCAL FIXTURE · no real profiles or bookings</strong><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>setWorker(!worker)}>{worker?'Preview Hire':'Preview worker'}</button><label>Text size<select onChange={e=>document.documentElement.style.fontSize=e.target.value+'%'}><option>100</option><option>200</option></select></label><label><input type="checkbox" onChange={e=>document.documentElement.dataset.theme=e.target.checked?'dark':'light'}/>Dark</label><button onClick={()=>void axe.run(document.querySelector('#qa-surface')!).then(r=>setCheck(JSON.stringify({violations:r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)})))}>Check accessibility</button></div><output>{notice}</output><pre style={{whiteSpace:'pre-wrap'}}>{check}</pre></aside>{worker?<main id="qa-surface" className="operations ops-worker"><h1>Worker workspace</h1><p>{tab} selected</p><p>The idle task-alert and online explanation cards have been removed.</p><WorkerNavigation tab={tab} onChange={setTab}/></main>:<main id="qa-surface" className="repaido-customer-shell"><Hiring city="Balasore" onBooking={id=>setNotice('Booking '+id)} onSignIn={()=>setNotice('Sign-in requested')} onHome={(service,p)=>setNotice('Home request: '+service+(p?' · Preferred professional: '+p.name:''))}/></main>}</>;}
createRoot(document.getElementById('root')!).render(<Preview/>);
