// Local-only reference data. Never imported by production or used for real care records.
import {createRoot} from 'react-dom/client';
import {useState} from 'react';
import axe from 'axe-core';
import {PlanDetail,type HomePlan} from '../src/components/HomePlans';
import {CampaignStudio} from '../src/components/CampaignStudio';
import type {Campaign} from '../src/components/CampaignAdmin';
import '../src/components/promotions.css';import '../src/styles.css';import '../src/design-system.css';import '../src/components/operations.css';
const plan:HomePlan={id:'local-qa-plan',customer_id:'local-only',version:1,state:'active',service_id:'maid',duration:'month1',start_date:'2026-10-01',city:'Balasore',relationship:'parent',minutes:120,worker_name:'Local QA professional',periods:[{index:0,start:'2026-10-01',end:'2026-10-31'}],visits:Array.from({length:31},(_,i)=>({id:String(i+1),date:`2026-10-${String(i+1).padStart(2,'0')}`,time:'09:00',period:0,starts_epoch:1790816400+i*86400,status:i<5?'completed':i===8?'missed':i===14?'off':'scheduled',daily_log:i<5?{hygiene:true,checked:[0,1],note:'Local test service note. No real recipient.',at:1790816400+i*86400}:undefined})),quote:{period_price_paise:310000,gst_bps:0,checklist:['Agreed household tasks','Hygiene & supplies checked'],exclusions:'Local-only test scope.',terms:'Local fixture. No charge, service, provider or booking exists.'},changes:[],issues:[],invoices:[{id:'local',index:0,start:'2026-10-01',end:'2026-10-31',rows:[{date:'2026-10-01',amount_paise:10000,base_paise:10000,gst_paise:0,job_id:'local-test'}],total_paise:10000,status:'accruing',unresolved:true,billing_note:'Local-only fixture: confirmed visits are itemised.'}]};
const initial:Campaign={id:'local-creative',version:0,title:'Repaido Home: Repair your living.',body:'Welcome Maa Durga with a home prepared with care.',service_id:'home:renovation',event_name:'Durga Puja',icon:'gift',tone:'festive',layout:'image-card',placements:['home'],cities:['Balasore'],starts_at:Date.now()/1000,ends_at:Date.now()/1000+30*86400,active:false,audience:'all',min_paid_spend_paise:0,discount_paise:0,budget_paise:0,per_user_limit:1,terms:'This is an unpublished local QA fixture.'};
function Preview(){const [draft,setDraft]=useState(initial),[studio,setStudio]=useState(false),[result,setResult]=useState('');return <main style={{padding:16,maxWidth:1000,margin:'auto'}}><h1 style={{fontSize:'1rem'}}>Local-only Home plan checks</h1><div className="home-actions" style={{marginBlock:16}}><label>Text size<select defaultValue="100" onChange={e=>document.documentElement.style.fontSize=e.target.value+'%'}>{[100,125,200].map(n=><option key={n}>{n}</option>)}</select></label><label><input type="checkbox" onChange={e=>document.documentElement.classList.toggle('reduce-motion',e.target.checked)}/>Reduced motion</label><label><input type="checkbox" onChange={e=>document.documentElement.dataset.theme=e.target.checked?'dark':'light'}/>Night theme</label><button onClick={()=>setStudio(!studio)}>{studio?'Calendar preview':'Studio preview'}</button><button onClick={()=>void axe.run(document.querySelector('#test-surface')!).then(r=>setResult(JSON.stringify({violations:r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)},null,2)))}>Run accessibility check</button></div><div id="test-surface" className="operations">{studio?<><h2>Global Control</h2><CampaignStudio draft={draft} onChange={setDraft} busy={false}/></>:<div className="home-plans"><h2>My Home plan</h2><PlanDetail plan={plan} admin onRefresh={async()=>{}} onJob={()=>{}}/></div>}</div><pre role="status" style={{whiteSpace:'pre-wrap'}}>{result}</pre></main>;}
createRoot(document.getElementById('root')!).render(<Preview/>);
