import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp(resolve(tmpdir(),'repaido-journeys-')),api='http://127.0.0.1:8048',origin='http://127.0.0.1:5187';
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/refinement_api.py',work+'/test.db','8048'],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser;for(const s of [server.stdout,server.stderr])s.on('data',d=>log+=d);
const checks=[],errors=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
async function apiCall(path,uid,body,method){const r=await fetch(api+'/operations/local-business'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+uid,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
async function variants(page,name){for(const width of [320,465,1440])for(const theme of ['light','dark'])for(const scale of [100,200]){await page.setViewportSize({width,height:850});await page.evaluate(({theme,scale})=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=scale+'%';},{theme,scale});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow '+width+' '+scale);await page.screenshot({path:work+'/'+name+'-'+width+'-'+theme+'-'+scale+'.png',fullPage:true});}await page.setViewportSize({width:465,height:850});await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});checks.push(name+' responsive');}
async function pin(page,label,lat,address){await page.getByRole('button',{name:new RegExp(label+'.*Choose on the map')}).click();const dialog=page.locator('dialog[open]').last();await dialog.getByLabel('Latitude',{exact:true}).fill(String(lat));await dialog.getByLabel('Longitude',{exact:true}).fill('86.9135');await dialog.getByLabel('House, street and landmark').fill(address);await dialog.getByLabel('City',{exact:true}).fill('Balasore');await dialog.getByLabel('I have checked that this pin marks my service entrance.').check();await dialog.getByRole('button',{name:'Confirm this location',exact:true}).click();}
async function axe(page){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});const violations=await page.evaluate(async()=>(await window.axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));assert.deepEqual(violations,[]);}
try{
 for(let i=0;i<120;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:465,height:850},reducedMotion:'reduce'});await context.route('**/api/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:api+url.pathname+url.search});await route.fulfill({response});});const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/tests/refinement-preview.html?mode=account');await page.locator('.account-card img').waitFor();assert.equal(await page.locator('.account-card .account-card-sign-out').count(),0);assert.equal(await page.locator('.account-hub-footer .account-card-sign-out').count(),1);await variants(page,'account');await axe(page);checks.push('uploaded photo and bottom sign-out');
 await page.goto(origin+'/tests/refinement-preview.html?mode=desk&uid=worker2');await page.getByRole('navigation',{name:'Cab owner suite navigation'}).getByRole('button',{name:'Bookings',exact:true}).click();await page.getByRole('navigation',{name:'Booking types'}).getByRole('button',{name:'Shared rides',exact:true}).click();await page.getByRole('button',{name:'Publish a departure',exact:true}).click();await pin(page,'Starting point',21.4934,'Fixture public origin');await pin(page,'Destination',21.5934,'Fixture public destination');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Approved vehicle').selectOption({index:1});const local=seconds=>new Date(Date.now()+seconds*1000).toISOString().slice(0,16);await page.getByLabel('Departure',{exact:true}).fill(local(7200));await page.getByLabel('Expected arrival').fill(local(18000));await page.getByLabel('Available passenger seats').fill('2');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Your price per seat (₹)').fill('175');await page.getByLabel('Journey, luggage and cancellation terms').fill('Fixture ride with one bag per seat. Pay the accepted fare directly to the owner.');await page.getByLabel('I am authorized to carry passengers').check();await variants(page,'publish');await page.getByRole('button',{name:'Publish departure',exact:true}).click();await page.getByRole('heading',{name:'Fixture public origin → Fixture public destination'}).waitFor();checks.push('owner publishes route and chosen seat fare');
 await page.goto(origin+'/tests/refinement-preview.html?mode=shared');await pin(page,'Your pickup',21.4934,'Fixture customer pickup');await pin(page,'Your drop-off',21.5934,'Fixture customer dropoff');await page.getByLabel('Depart from').fill(local(3600));await page.getByRole('button',{name:'Search scheduled rides'}).click();await page.getByRole('button',{name:'Review & request to join'}).click();await variants(page,'join');await page.getByLabel('I accept this fare').check();await page.getByRole('button',{name:'Send join request'}).click();await page.getByText('Join request sent.',{exact:false}).waitFor();checks.push('customer search and join request');
 let row=(await apiCall('/shared','worker2')).departures[0],passenger=row.passengers[0];assert.equal(passenger.price_paise,17500);await apiCall('/shared/'+row.id+'/commands','worker2',{action:'accept',passenger_id:passenger.id,expected_version:row.version,command_id:crypto.randomUUID()});
 await page.reload();await page.getByRole('button',{name:'Pickup & drop-off pins'}).waitFor();await page.getByRole('button',{name:'Pickup & drop-off pins'}).click();await page.locator('.journey-leaflet').waitFor();await page.getByRole('link',{name:'Directions to pickup'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Live location & safety'}).click();await page.getByText('Waiting for a fresh location.',{exact:false}).waitFor();await variants(page,'accepted-tracking');checks.push('accepted pickup map and honest missing GPS');
 const notices=await fetch(api+'/operations/notifications',{headers:{Authorization:'Bearer customer'}});assert(notices.ok);assert((await notices.text()).includes('Shared ride accept'));checks.push('acceptance appears in notification inbox');
 await page.goto(origin+'/tests/refinement-preview.html?mode=portal&uid=worker2');await page.getByRole('heading',{name:'Cab owner suite',exact:true}).waitFor();assert.equal(await page.getByRole('combobox',{name:'Work desk'}).count(),0);checks.push('registered cab owner opens its own desk without role switch');
 await page.goto(origin+'/?ride-share#unavailable-test-token');await page.getByRole('heading',{name:'Family ride tracking'}).waitFor();await page.getByText('This journey link has ended or was revoked.').waitFor();checks.push('guest expiry renders without login');assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks,work}));
}catch(e){console.error(e);console.error(log.slice(-1500));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify({checks,errors},null,2));await browser?.close();server.kill('SIGTERM');console.log('Evidence: '+work);}
