import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp(resolve(tmpdir(),'repaido-refinement-')),port=8047,origin='http://127.0.0.1:5187',api='http://127.0.0.1:'+port;
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/refinement_api.py',work+'/test.db',String(port)],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser;for(const s of [server.stdout,server.stderr])s.on('data',d=>log+=d);
const errors=[],checks=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
async function layout(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow');await page.screenshot({path:work+'/'+name+'.png',fullPage:true});}
async function variants(page,name){for(const width of [320,520,1440])for(const theme of ['light','dark'])for(const scale of [100,200]){await page.setViewportSize({width,height:850});await page.evaluate(({theme,scale})=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=scale+'%';},{theme,scale});await layout(page,name+'-'+width+'-'+theme+'-'+scale);}await page.setViewportSize({width:520,height:850});await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});checks.push(name+' responsive');}
async function axe(page,selector='main'){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});const result=await page.evaluate(async selector=>(await window.axe.run(selector,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),selector);assert.deepEqual(result,[],JSON.stringify(result));}
try{
 for(let i=0;i<120;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:520,height:850},reducedMotion:'reduce',hasTouch:true});await context.route('**/api/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:api+url.pathname+url.search});await route.fulfill({response});});
 const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/tests/refinement-preview.html?mode=contracts');await page.getByRole('button',{name:'New requirement',exact:true}).click();await page.getByLabel('What work do you need?').fill('Fixture electrical work');await page.getByLabel('Scope and expected outcome').fill('Inspect and repair the recorded office circuits.');await page.getByLabel('Project sector').fill('Office');await page.getByRole('combobox',{name:'Work category'}).selectOption('electrician');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('City',{exact:true}).fill('Balasore');await page.getByLabel('Area or neighbourhood').fill('Fixture area');await page.getByLabel('Private work site address').fill('Private fixture site 123');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Required skills').fill('Electrical inspection');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Planned total budget (₹)').fill('20000');
 const localTime=seconds=>new Date(Date.now()+seconds*1000).toISOString().slice(0,16);await page.getByLabel('Work starts').fill(localTime(86400*3));await page.getByLabel('Work ends').fill(localTime(86400*5));await page.getByLabel('Proposal deadline').fill(localTime(86400));await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Work, completion and agreement terms').fill('Fixture agreed work and customer completion approval required.');await variants(page,'contract-review');await axe(page);await page.getByLabel('I am authorized to request this work').check();await page.getByRole('button',{name:'Post requirement',exact:true}).click();await page.getByRole('heading',{name:'Fixture electrical work',exact:true}).waitFor();checks.push('contract staged real submission');
 await page.goto(origin+'/tests/refinement-preview.html?mode=desk&uid=worker2');await page.getByRole('button',{name:'Vehicles',exact:true}).click();await page.getByRole('button',{name:'Edit vehicle & tariffs',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Cab / extra rental km (₹)').fill('17.25');await page.getByLabel('Rental daily rate (₹)').fill('2400');await page.getByRole('button',{name:'Continue',exact:true}).click();await variants(page,'vehicle-editor');await axe(page,'dialog');await page.getByRole('button',{name:'Save vehicle & rates',exact:true}).click();await page.getByText('₹17.25/km · ₹2,400.00/day').waitFor();checks.push('owner tariff update persisted');await page.getByRole('button',{name:'Calendar',exact:true}).click();await variants(page,'owner-calendar');
 await page.goto(origin+'/tests/refinement-preview.html?mode=mobility');await page.getByRole('button',{name:'Book cab',exact:true}).click();await page.getByLabel('Pickup date & time').fill(localTime(7200));await page.getByLabel('Expected trip end').fill(localTime(18000));await page.getByRole('button',{name:'Continue',exact:true}).click();await variants(page,'cab-route');await axe(page);checks.push('cab dates and route stages');
 await page.getByRole('button',{name:/Destination.*Choose on the map/i}).click();await page.getByLabel('House, street and landmark').fill('Fixture destination entrance 456');await page.getByLabel('City',{exact:true}).fill('Balasore');await page.getByLabel('I have checked that this pin marks my service entrance.').check();await page.getByRole('button',{name:'Confirm this location',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Calculate full price'}).first().click();await page.getByRole('button',{name:'Continue',exact:true}).click();await variants(page,'cab-quote-review');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Send booking request',exact:true}).click();await page.locator('.business-record').first().waitFor();checks.push('cab request and road-distance quote persisted');
 await page.goto(origin+'/tests/refinement-preview.html?mode=scrap');await page.getByRole('button',{name:'Sell scrap',exact:true}).click();await page.getByLabel('Describe the scrap').fill('Fixture clean steel household scrap');await page.getByRole('button',{name:'Continue',exact:true}).click();await variants(page,'scrap-pickup');await axe(page);checks.push('scrap staged entry');
 await page.goto(origin+'/tests/refinement-preview.html?mode=hiring');await page.getByRole('button',{name:/All categories/}).click();await page.getByRole('button',{name:'View profile',exact:true}).first().click();await page.locator('.hire-full-profile').waitFor();await variants(page,'hire-profile');const cta=page.locator('.hire-profile-fixed-action');assert.equal(await cta.count(),1);{const before=await cta.boundingBox();await page.locator('.hire-profile-scroll').evaluate(n=>n.scrollTop=n.scrollHeight);const after=await cta.boundingBox();assert(Math.abs(before.y-after.y)<2);}await axe(page,'dialog[open]');checks.push('profile records and fixed CTA');
 await page.goto(origin+'/tests/refinement-preview.html?mode=tracking');await page.locator('.rt-map-area').waitFor();await page.locator('.rt-agent-marker').waitFor();const map=page.locator('.rt-map-area');const mapId=await page.locator('.rt-leaflet-container').evaluate(n=>n._leaflet_id);const zoom=()=>page.locator('img.leaflet-tile').evaluateAll(ns=>Math.max(...ns.map(n=>Number(n.src.match(/voyager\/(\d+)\//)?.[1]||0))));const beforeZoom=await zoom();await page.locator('.leaflet-control-zoom-in').click();await pause(500);const afterZoom=await zoom();assert(afterZoom>beforeZoom,'zoom control');await fetch(api+'/test-only/position',{method:'POST'});await pause(16000);assert.equal(await zoom(),afterZoom,'tracking update preserves manual zoom');assert.equal(await page.locator('.rt-leaflet-container').evaluate(n=>n._leaflet_id),mapId,'map instance preserved');await page.locator('.rt-agent-marker').click();await page.locator('dialog[open] .hire-full-profile').waitFor();await page.keyboard.press('Escape');checks.push('actual marker profile and preserved map zoom');const box=await map.boundingBox();assert(Math.abs(box.width-box.height)<2,'square map');await page.getByRole('button',{name:/Full.?screen map/i}).click();assert((await map.boundingBox()).height>=840);const beforePinch=await zoom();const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:300,id:1},{x:330,y:300,id:2}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:170-i*10,y:300,id:1},{x:330+i*10,y:300,id:2}]});await pause(30);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(600);assert(await zoom()>beforePinch,'finger pinch zooms the map');checks.push('two-finger pinch zoom');await page.keyboard.press('Escape');checks.push('square and fullscreen tracking');await variants(page,'tracking');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks,work}));
}catch(e){console.error(e);console.error(log.slice(-3000));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify({checks,errors},null,2));await browser?.close();server.kill('SIGTERM');console.log('Evidence: '+work);}
