import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true,args:['--disable-dev-shm-usage']});
const base='http://127.0.0.1:5187';
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:390,height:850}});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/operations/hiring/leaderboard',route=>route.fulfill({json:{professionals:[{id:'real-sipun',name:'Sipun Mahanta',role:'technician',completed_tasks:0,rating:null,bio:'Registered electrician.'},{id:'real-tushar',name:'Tushar Ranjan Das',role:'specialist',completed_tasks:12,rating:4.5,bio:'Live work profile.'}]}}));
 await mkdir('test-results',{recursive:true});
 const shell=()=>page.getByRole('dialog',{name:'Repaidians community',exact:true});
 const nav=label=>shell().getByRole('navigation',{name:'Repaidians sections'}).getByRole('button',{name:label,exact:true}).click();
 const layout=async()=>{
   const issues=await shell().evaluate(root=>{
    const issues=[];if(root.scrollWidth>root.clientWidth+1)issues.push('dialog overflow');
    for(const e of root.querySelectorAll('.rp-post,.rp-header,.rp-toolbar,.rp-tender,.rp-profile'))if(e.scrollWidth>e.clientWidth+1)issues.push('overflow '+e.className);
    for(const e of root.querySelectorAll('button'))if(e.getClientRects().length&&e.getBoundingClientRect().height<44)issues.push('small target '+e.textContent);
    return issues;
   });assert.deepEqual(issues,[]);
 };
 for(const width of [320,390,430,524]) {
   await page.setViewportSize({width,height:850});await page.goto(base+'/tests/repaidians-preview.html');await shell().waitFor();
   await layout();assert.equal(await shell().locator('.rp-post').count(),4);
   await page.evaluate(()=>document.documentElement.dataset.theme='dark');await layout();
   await page.evaluate(()=>document.documentElement.dataset.theme='light');
 }
 await page.setViewportSize({width:390,height:850});
 await page.screenshot({path:'test-results/repaidians-phone.png'});
 await shell().getByRole('button',{name:'Like post',exact:true}).first().click();
 assert.equal(await shell().getByRole('button',{name:'Unlike post',exact:true}).count(),1);
 await shell().getByRole('button',{name:'Save post',exact:true}).first().click();
 await shell().getByRole('button',{name:'Saved',exact:true}).click();assert.equal(await shell().locator('.rp-post').count(),1);
 await shell().getByRole('button',{name:'Open comments',exact:true}).click();
 const comments=page.getByRole('dialog',{name:'Comments',exact:true});
 await comments.getByLabel('Your comment',{exact:true}).fill('A clear scope makes good work.');
 await comments.getByRole('button',{name:'Post comment',exact:true}).click();await comments.getByText('A clear scope makes good work.',{exact:true}).waitFor();
 await comments.getByRole('button',{name:'Close dialog',exact:true}).click();
 await shell().getByRole('button',{name:'Explore',exact:true}).click();
 await shell().getByRole('button',{name:'Next photo',exact:true}).click();assert.equal(await shell().locator('.rp-slide-count').textContent(),'2/2');
 await shell().getByRole('button',{name:/^Sipun Mahanta/}).click();
 await shell().getByRole('button',{name:'Follow',exact:true}).click();assert.equal(await shell().getByRole('button',{name:'Following',exact:true}).getAttribute('aria-pressed'),'true');
 await shell().getByRole('button',{name:'Message',exact:true}).click();
 let upgrade=page.getByRole('dialog',{name:'Repaidians Pro',exact:true});await upgrade.waitFor();
 assert.equal(await page.getByRole('dialog',{name:'Message Sipun Mahanta',exact:true}).count(),0);
 await upgrade.getByRole('button',{name:'Close dialog',exact:true}).click();
 await shell().getByRole('button',{name:'Back to community',exact:true}).click();
 await shell().getByRole('button',{name:'Following',exact:true}).click();assert.equal(await shell().locator('.rp-post').count(),1);
 await shell().getByRole('button',{name:'Explore',exact:true}).click();
 await shell().getByRole('button',{name:'View Basanti Behera stories',exact:true}).click();
 let story=page.getByRole('dialog',{name:'Story by Basanti Behera',exact:true});await story.waitFor();await story.getByRole('button',{name:'Pause story',exact:true}).click();
 const before=await story.locator('.rp-story-progress i').first().getAttribute('style');await page.waitForTimeout(350);assert.equal(await story.locator('.rp-story-progress i').first().getAttribute('style'),before);
 await story.getByLabel('Reply to story',{exact:true}).fill('How do you plan the scope?');await story.getByRole('button',{name:'Send story reply',exact:true}).click();upgrade=page.getByRole('dialog',{name:'Repaidians Pro',exact:true});await upgrade.waitFor();
 await upgrade.getByText('No money is charged.',{exact:false}).waitFor();await upgrade.getByRole('button',{name:'Simulate ₹199 checkout',exact:true}).click();
 await story.getByRole('button',{name:'Send story reply',exact:true}).click();
 await story.getByRole('button',{name:'Close dialog',exact:true}).click();
 await shell().getByRole('button',{name:'Create',exact:true}).click();
 let studio=page.getByRole('dialog',{name:'Publishing studio',exact:true});await studio.getByLabel('Upload publication media',{exact:true}).setInputFiles('public/images/electrical.jpg');
 await studio.getByLabel('Caption & visual description',{exact:true}).fill('Local portfolio from the browser test.');
 await studio.getByRole('button',{name:'Publish on this device',exact:true}).click();
 await shell().getByText('Local portfolio from the browser test.',{exact:false}).waitFor();
 await page.reload();await shell().waitFor();await shell().getByText('Local portfolio from the browser test.',{exact:false}).waitFor();
 assert.equal(await shell().getByRole('button',{name:'Demo Pro',exact:true}).count(),1);
 await nav('Tenders');await shell().getByRole('button',{name:'Submit interest',exact:false}).first().click();await shell().getByRole('button',{name:'Interest saved',exact:false}).first().waitFor();
 await shell().getByRole('button',{name:'Contact',exact:true}).first().click();await shell().getByText('This sample tender has no contact details.',{exact:false}).waitFor();
 await nav('Reels');await shell().getByText('Labour in action',{exact:true}).waitFor();
 await shell().getByRole('button',{name:'Create something',exact:true}).click();studio=page.getByRole('dialog',{name:'Publishing studio',exact:true});
 await studio.getByLabel('Upload publication media',{exact:true}).setInputFiles('/tmp/repaidians-test.webm');await studio.getByLabel('Caption & visual description',{exact:true}).fill('Test work reel with no audio.');
 await studio.getByRole('button',{name:'Publish on this device',exact:true}).click();await shell().locator('.rp-reel video').waitFor();
 await page.waitForFunction(()=>document.querySelector('.rp-reel video')?.readyState>=2);
 await shell().getByRole('button',{name:'Pause reel',exact:true}).click();assert.equal(await shell().locator('.rp-reel video').evaluate(e=>e.paused),true);
 await page.reload();await shell().waitFor();await nav('Reels');await shell().locator('.rp-reel video').waitFor();await page.waitForFunction(()=>document.querySelector('.rp-reel video')?.readyState>=2);
 await shell().getByRole('button',{name:'Book a service',exact:true}).click();await page.getByLabel('Home search',{exact:true}).waitFor();assert.equal(await page.getByLabel('Home search',{exact:true}).inputValue(),'Electrical');
 await page.getByRole('button',{name:'Open Repaidians community',exact:true}).click();await shell().waitFor();
 await page.addScriptTag({path:require.resolve('axe-core')});
 const audit=async()=>{const result=await page.evaluate(async()=>await window.axe.run(document.querySelector('.rp-shell'),{rules:{'color-contrast':{enabled:true}}}));assert.deepEqual(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),[]);};
 await audit();await page.evaluate(()=>document.documentElement.dataset.theme='dark');await audit();await page.screenshot({path:'test-results/repaidians-dark.png'});
 await page.evaluate(()=>document.documentElement.style.fontSize='200%');await layout();await page.evaluate(()=>document.documentElement.style.fontSize='100%');
 await page.evaluate(()=>{
   localStorage.removeItem('repaidians.v1.subscription.guest');
   const d=new Date(),day=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
   localStorage.setItem('repaidians.v1.usage.guest',JSON.stringify({day,usedMs:900000,chargedUntil:Date.now()}));
 });await page.reload();await page.getByRole('dialog',{name:'Repaidians Pro',exact:true}).waitFor();
 assert.equal(await shell().locator('.rp-post').count(),0);
 await page.getByRole('dialog',{name:'Repaidians Pro',exact:true}).getByRole('button',{name:'Close dialog',exact:true}).click();await shell().getByText('See you after midnight?',{exact:true}).waitFor();
 await page.evaluate(()=>localStorage.setItem('repaidians.v1.usage.guest',JSON.stringify({day:'2000-01-01',usedMs:900000,chargedUntil:0})));await page.reload();await shell().locator('.rp-post').first().waitFor();
 assert.equal(await shell().getByRole('button',{name:/15m left today/}).count(),1);
 await page.route('**/api/**',route=>route.fulfill({status:503,json:{detail:'Offline integration check'}}));
 await page.goto(base+'/?noSplash=1&tab=explore');
 const launcher=page.getByRole('button',{name:'Open Repaidians community',exact:true});await launcher.waitFor();
 const placeBefore=await page.evaluate(()=>localStorage.getItem('repaido.place'));
 await launcher.click();await shell().waitFor();await shell().getByRole('button',{name:'Close Repaidians',exact:true}).click();await launcher.waitFor();
 assert.equal(await page.evaluate(()=>localStorage.getItem('repaido.place')),placeBefore,'closing the community must preserve the customer location');
 assert.deepEqual(errors,[]);
 console.log('Repaidians: quota reset/lock, Pro gates, stories/replies, feed actions, local photo/video persistence, bids, checkout link, themes, 200% text and accessibility passed.');
} finally {await browser.close();}
