import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp('/tmp/repaido-shared-mobile-'),api='http://127.0.0.1:8058',origin='http://127.0.0.1:5187';
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/business_suites_api.py',work+'/test.db','8058'],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser,departureId='',pauseBoard=false;
for(const stream of [server.stdout,server.stderr])stream.on('data',data=>log+=data);
const checks=[],errors=[],commands=[],pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const pickup={lat:21.4934,lng:86.9135},dropoff={lat:21.5434,lng:86.9635};
const passengerName='PARAMESH PRASAD MOHAPATRA',vehicleName='Maruti suzuki ertiga new model';
async function call(path,uid,body){const response=await fetch(api+'/operations/local-business'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+uid,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();assert(response.ok,JSON.stringify(data));return data;}
async function latest(){return (await call('/shared','worker')).departures.find(row=>row.id===departureId);}
async function open(page,role,uid,history=false){await page.goto(origin+'/tests/business-suites-preview.html?mode='+role+'&uid='+uid);await page.getByRole('heading',{name:role==='driver'?'Driver suite':'Cab owner suite',exact:true}).waitFor();const nav=page.getByRole('navigation',{name:/suite navigation/});if(role==='cab_owner'){await nav.getByRole('button',{name:'Bookings',exact:true}).click();await page.getByRole('navigation',{name:'Booking types'}).getByRole('button',{name:'Shared rides',exact:true}).click();}else await nav.getByRole('button',{name:'Shared rides',exact:true}).click();if(history)await page.getByRole('group',{name:'Shared ride history'}).getByRole('button',{name:'History',exact:true}).click();await page.getByRole('heading',{name:'Iti square → Soro college chak, near petrol pump',exact:true}).waitFor();}
async function reachable(page,button){await button.evaluate(el=>el.scrollIntoView({block:'center'}));assert(await button.evaluate(el=>{const r=el.getBoundingClientRect(),nav=document.querySelector('.suite-navigation')?.getBoundingClientRect();return r.top>=0&&(!nav||r.bottom<nav.top)&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===el;}),'operation control is not covered by navigation or another card: '+await button.textContent());}
async function audit(page,name,width=465,scale=100,theme='light'){
 await page.setViewportSize({width,height:850});await page.evaluate(({scale,theme})=>{document.documentElement.style.fontSize=scale+'%';document.documentElement.dataset.theme=theme;},{scale,theme});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' reflow');
 if(!await page.evaluate(()=>Boolean(window.axe)))await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});
 const violations=await page.evaluate(async()=>(await window.axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']},rules:{'color-contrast-enhanced':{enabled:true}}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));
 assert.deepEqual(violations,[],name+' accessibility');
 for(const button of await page.locator('.shared-booking-card button:visible').all())await reachable(page,button);
 await page.locator('.shared-booking-card').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:work+'/'+name+'-'+width+'-'+scale+'-'+theme+'.png',fullPage:true});
}
try{
 for(let i=0;i<120;i++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 const vehicle=(await call('/partner?role=cab_owner','worker')).vehicles[0];
 const row=await call('/shared','worker',{request_id:crypto.randomUUID(),vehicle_id:vehicle.id,origin:pickup,destination:dropoff,origin_address:'Iti square',destination_address:'Soro college chak, near petrol pump',starts_at:Date.now()/1000+900,ends_at:Date.now()/1000+3600,seats:3,price_paise:20000,pickup_mode:'meeting_point',terms:'One bag per passenger. Meet at the agreed pickup pin and pay the accepted fare directly to the owner.'});departureId=row.id;
 const passenger=await call('/shared/'+row.id+'/join','customer',{request_id:crypto.randomUUID(),expected_version:row.version,pickup,dropoff,seats:1,consent:true});
 await call('/shared/'+row.id+'/commands','worker',{action:'accept',passenger_id:passenger.id,expected_version:(await latest()).version,command_id:crypto.randomUUID()});
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:584,height:850},reducedMotion:'reduce'});
 await context.route('**/@vite/client',async route=>{const response=await route.fetch();await route.fulfill({response,body:'class PreviewSocket {addEventListener(){} removeEventListener(){} send(){} close(){}}\n'+(await response.text()).replace(/new WebSocket\(/g,'new PreviewSocket(')});});
 await context.route('**/api/**',async route=>{try{const request=route.request(),url=new URL(request.url());if(url.pathname.endsWith('/commands')){const command=request.postDataJSON();commands.push(command);if(pauseBoard&&command.action==='board')await pause(1000);}const response=await route.fetch({url:api+url.pathname+url.search});if(url.pathname==='/api/operations/local-business/shared'&&request.method()==='GET'&&response.ok()){const data=await response.json();for(const row of data.departures||[])if(row.id===departureId){row.vehicle_name=vehicleName;for(const passenger of row.passengers)if(passenger.customer_id==='customer')passenger.customer_name=passengerName;}await route.fulfill({response,json:data});}else await route.fulfill({response});}catch{await route.abort().catch(()=>{});}});
 const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));
 await open(page,'cab_owner','worker');await page.getByText(passengerName,{exact:true}).waitFor();assert.equal(await page.getByText('Passengers accepted',{exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'Start journey',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Cancel departure',exact:true}).isVisible(),false);
 for(const width of [320,390,465,584,1440])for(const theme of ['light','dark'])for(const scale of [100,200])await audit(page,'accepted-owner',width,scale,theme);
 checks.push('long route, vehicle and passenger names reflow across five widths, both themes and 200% text; visible actions remain unobscured and pass AAA contrast');
 await page.setViewportSize({width:584,height:850});await page.evaluate(()=>{document.documentElement.style.fontSize='100%';document.documentElement.dataset.theme='light';});await page.locator('.shared-booking-card').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:work+'/accepted-owner-phone.png'});
 await page.getByRole('button',{name:'Pickup & drop-off pins',exact:true}).click();await page.getByRole('link',{name:'Directions to pickup',exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Live location & safety',exact:true}).click();await page.locator('.journey-tracking').waitFor();await page.getByRole('button',{name:'Live location & safety',exact:true}).click();checks.push('pickup and live-location controls remain reachable; secondary details stay collapsed');
 await call('/journeys/shared/'+row.id+'/consent','worker',{enabled:true});await call('/journeys/shared/'+row.id+'/position','worker',{...pickup,accuracy:5,captured_at:Date.now()/1000});
 pauseBoard=true;await page.getByRole('button',{name:'Passenger boarded',exact:true}).click();await page.getByRole('button',{name:'Recording boarding…',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Recording boarding…',exact:true}).getAttribute('aria-busy'),'true');await page.getByText('Passenger boarding recorded.',{exact:true}).waitFor();pauseBoard=false;assert.equal((await latest()).passengers[0].state,'boarded');assert.equal(await page.getByRole('button',{name:'Start journey',exact:true}).isEnabled(),true);
 await page.getByRole('button',{name:'Start journey',exact:true}).click();await page.getByText('Journey started.',{exact:true}).waitFor();assert.equal((await latest()).state,'in_progress');assert.equal(await page.getByRole('button',{name:'Finish journey',exact:true}).isDisabled(),true);checks.push('boarding shows progress and confirmed completion; real backend state enables start and requires drop-off before finish');
 await open(page,'driver','shop');assert.equal(await page.getByRole('button',{name:'Cancel departure',exact:true}).count(),0);await audit(page,'active-driver',390,100);await audit(page,'active-driver',320,200,'dark');
 await call('/journeys/shared/'+row.id+'/consent','shop',{enabled:true});await pause(5100);await call('/journeys/shared/'+row.id+'/position','shop',{...dropoff,accuracy:5,captured_at:Date.now()/1000});await page.evaluate(()=>document.documentElement.style.fontSize='100%');await page.getByRole('button',{name:'Record passenger drop-off',exact:true}).click();await page.getByText('Passenger drop-off recorded.',{exact:true}).waitFor();await page.getByRole('button',{name:'Finish journey',exact:true}).click();await page.getByText('Journey completed.',{exact:true}).waitFor();assert.equal((await latest()).state,'completed');checks.push('assigned driver completes drop-off and the journey without owner-only controls');
 await page.goto(origin+'/tests/business-suites-preview.html?mode=shared_bookings&uid=customer');await page.getByRole('group',{name:'Shared ride history'}).getByRole('button',{name:'History',exact:true}).click();await page.getByRole('button',{name:'I paid ₹200.00 to the owner',exact:true}).waitFor();await audit(page,'customer-history',465,100);await audit(page,'customer-history',320,200,'dark');await page.getByRole('button',{name:'I paid ₹200.00 to the owner',exact:true}).click();await page.getByText('Your payment report was sent to the owner.',{exact:true}).waitFor();
 await open(page,'cab_owner','worker',true);await page.getByRole('button',{name:'I received the fare',exact:true}).click();await page.getByText('Fare receipt confirmed.',{exact:true}).waitFor();assert((await latest()).passengers[0].payment_received_at);checks.push('customer payment report and owner receipt remain available in history');
 await audit(page,'owner-paid-history',320,200,'dark');
 const next=await call('/shared','worker',{request_id:crypto.randomUUID(),vehicle_id:vehicle.id,origin:pickup,destination:dropoff,origin_address:'Iti square',destination_address:'Soro college chak, near petrol pump',starts_at:Date.now()/1000+86400,ends_at:Date.now()/1000+90000,seats:2,price_paise:20000,pickup_mode:'meeting_point',terms:'One bag per passenger. Meet at the agreed pickup pin and pay the accepted fare directly to the owner.'});
 await call('/shared/'+next.id+'/join','customer',{request_id:crypto.randomUUID(),expected_version:next.version,pickup,dropoff,seats:1,consent:true});
 await open(page,'cab_owner','worker');await audit(page,'owner-pending-request',320,200,'dark');await page.getByRole('button',{name:'Accept join request',exact:true}).click();await page.getByText('Join request accepted.',{exact:true}).waitFor();assert.equal((await call('/shared','worker')).departures.find(row=>row.id===next.id).passengers[0].state,'accepted');
 await page.getByText('Journey terms & activity',{exact:true}).click();await page.getByRole('button',{name:'Cancel departure',exact:true}).click();await page.getByText('Cancellation recorded.',{exact:true}).waitFor();assert.equal((await call('/shared','worker')).departures.find(row=>row.id===next.id).state,'cancelled');checks.push('pending joins remain actionable on small screens; owner cancellation works from journey details');
 assert.deepEqual(errors,[]);assert(commands.some(command=>command.action==='board'));console.log(JSON.stringify({passed:true,checks,work}));
}catch(error){console.error(error);console.error(log.slice(-1200));process.exitCode=1;}finally{await browser?.close();server.kill('SIGTERM');await writeFile(work+'/report.json',JSON.stringify({checks,errors,commands},null,2));console.log('Evidence: '+work);}
