import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const web=resolve(dirname(fileURLToPath(import.meta.url)),'..'),work=await mkdtemp(resolve(tmpdir(),'repaido-transport-')),api='http://127.0.0.1:8060',origin='http://127.0.0.1:5187';
const server=spawn(resolve(web,'../backend/.venv/bin/python'),[web+'/tests/business_suites_api.py',work+'/test.db','8060'],{cwd:resolve(web,'../backend'),stdio:['ignore','pipe','pipe']});let log='',browser;for(const stream of [server.stdout,server.stderr])stream.on('data',data=>log+=data);
const checks=[],errors=[],writes=[],pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function call(path,uid,body,method){const response=await fetch(api+'/operations/local-business'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+uid,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();assert(response.ok,JSON.stringify(result));return result;}
async function variants(page,selector,name){await page.addScriptTag({path:web+'/node_modules/axe-core/axe.min.js'});for(const width of [320,465,1440])for(const theme of ['light','dark'])for(const scale of [100,200]){await page.setViewportSize({width,height:850});await page.evaluate(({theme,scale})=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=scale+'%';},{theme,scale});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow');const violations=await page.evaluate(async selector=>(await window.axe.run(selector,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag2aaa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),selector);assert.deepEqual(violations,[],name+' '+width+' '+theme+' '+scale);await page.screenshot({path:work+'/'+name+'-'+width+'-'+theme+'-'+scale+'.png',fullPage:true});}await page.setViewportSize({width:465,height:850});await page.evaluate(()=>{document.documentElement.dataset.theme='light';document.documentElement.style.fontSize='100%';});checks.push(name+' responsive and AAA contrast');}
try{
 for(let attempt=0;attempt<120;attempt++){try{if((await fetch(api+'/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(log);await pause(100);}
 browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:465,height:850},reducedMotion:'reduce'});
 await context.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(!['GET','HEAD'].includes(request.method()))writes.push({method:request.method(),path:url.pathname});const response=await route.fetch({url:api+url.pathname+url.search});await route.fulfill({response});});
 await context.route('**/@vite/client',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/new WebSocket\(/g,'new PreviewSocket(');await route.fulfill({response,body:'class PreviewSocket { addEventListener(){} removeEventListener(){} send(){} close(){} }\n'+body});});
 const driver=await context.newPage(),customer=await context.newPage();for(const page of [driver,customer]){page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));}
 await driver.addInitScript(()=>{const Native=window.AudioContext;window.__rings=0;window.AudioContext=class extends Native{createOscillator(){window.__rings++;return super.createOscillator();}};});
 await driver.goto(origin+'/tests/business-suites-preview.html?mode=driver&uid=worker');await driver.getByRole('heading',{name:'Driver suite',exact:true}).waitFor();assert.equal(await driver.getByRole('button',{name:'Enable request bell',exact:true}).count(),0);await driver.getByRole('navigation',{name:'Driver suite navigation'}).getByRole('button',{name:'Account',exact:true}).click();await driver.getByRole('button',{name:'Enable request bell',exact:true}).click();await driver.getByText('Request bell on',{exact:true}).waitFor();
 const vehicles=await call('/partner?role=cab_owner','worker2');const vehicle=vehicles.vehicles.find(row=>row.owner_id==='worker2');assert(vehicle);
 const row=await call('/shared','worker2',{request_id:crypto.randomUUID(),vehicle_id:vehicle.id,origin:{lat:21.4934,lng:86.9135},destination:{lat:21.5934,lng:86.9135},origin_address:'Fixture pickup station',destination_address:'Fixture destination station',starts_at:Date.now()/1000+4*86400,ends_at:Date.now()/1000+4*86400+7200,seats:2,price_paise:17500,pickup_mode:'meeting_point',terms:'One bag per seat. Meet the driver at the agreed pin and pay the accepted fare directly.'});
 const community=await context.newPage();community.setDefaultTimeout(15000);community.on('pageerror',error=>errors.push(error.message));await community.goto(origin+'/tests/business-suites-preview.html?mode=community&uid=customer');await community.locator('.transport-discovery').getByRole('button',{name:'View ride',exact:true}).waitFor();checks.push('the same native departure appears in the Repaidians feed');await community.close();
 await customer.goto(origin+'/tests/business-suites-preview.html?mode=mobility&uid=customer');await customer.locator('.transport-discovery').getByRole('button',{name:'View ride',exact:true}).waitFor();await variants(customer,'.transport-discovery','nearby-rail');checks.push('a published departure appears in customer discovery with owner-set fare');
 await customer.locator('.transport-discovery').getByRole('button',{name:'View ride',exact:true}).click();await customer.getByRole('button',{name:'Check ride & pickup',exact:true}).click();await customer.getByRole('button',{name:'Review & request to join',exact:true}).click();await customer.getByLabel('I accept this fare').check();await customer.getByRole('button',{name:'Send join request',exact:true}).click();await customer.getByText('Join request sent.',{exact:false}).waitFor();checks.push('native route check, explicit fare consent and visible join confirmation');
 await driver.getByText('1 shared-ride join request',{exact:true}).waitFor();await driver.waitForFunction(()=>window.__rings>=4);assert((await driver.evaluate(()=>window.__rings))>=4);await variants(driver,'.suite-request-cue','driver-request');
 await driver.getByRole('navigation',{name:'Driver suite navigation'}).getByRole('button',{name:'Vehicles',exact:true}).click();assert(await driver.getByText('1 shared-ride join request',{exact:true}).isVisible());await driver.getByRole('button',{name:'Review request',exact:true}).click();await driver.getByRole('heading',{name:'Fixture pickup station → Fixture destination station'}).waitFor();assert.equal(await driver.getByRole('button',{name:'Accept join request',exact:true}).count(),0);checks.push('driver banner and audible bell persist across panels and open the exact ride');
 await driver.getByRole('button',{name:'Silence this alert',exact:true}).click();const rings=await driver.evaluate(()=>window.__rings);await pause(2600);assert.equal(await driver.evaluate(()=>window.__rings),rings);assert(await driver.getByText('1 shared-ride join request',{exact:true}).isVisible());checks.push('silencing stops audio without hiding the pending request');
 const current=(await call('/shared','worker2')).departures.find(ride=>ride.id===row.id);await call('/shared/'+row.id+'/commands','worker2',{action:'accept',expected_version:current.version,command_id:crypto.randomUUID(),passenger_id:current.passengers[0].id});await driver.getByText('1 shared-ride join request',{exact:true}).waitFor({state:'hidden'});checks.push('owner decision clears the driver request cue through quiet polling');
 const soon=await call('/shared','worker2',{request_id:crypto.randomUUID(),vehicle_id:vehicle.id,origin:{lat:21.4934,lng:86.9135},destination:{lat:21.5934,lng:86.9135},origin_address:'Near departure pickup station',destination_address:'Near departure destination station',starts_at:Date.now()/1000+600,ends_at:Date.now()/1000+4200,seats:2,price_paise:17500,pickup_mode:'meeting_point',terms:'One bag per seat. Meet at the agreed pickup pin and pay the accepted fare directly.'});
 const joining=await call('/shared/'+soon.id+'/join','customer',{request_id:crypto.randomUUID(),expected_version:soon.version,pickup:soon.origin,dropoff:soon.destination,seats:1,consent:true});
 const pendingSoon=(await call('/shared','worker2')).departures.find(ride=>ride.id===soon.id);await call('/shared/'+soon.id+'/commands','worker2',{action:'accept',expected_version:pendingSoon.version,command_id:crypto.randomUUID(),passenger_id:joining.id});await driver.getByText('1 shared-ride join request',{exact:true}).waitFor({state:'hidden'});
 const beforeChange=await driver.evaluate(()=>window.__rings);const acceptedSoon=(await call('/shared','worker2')).departures.find(ride=>ride.id===soon.id);await call('/shared/'+soon.id+'/commands','worker2',{action:'reschedule',expected_version:acceptedSoon.version,command_id:crypto.randomUUID(),starts_at:soon.starts_at+600,ends_at:soon.ends_at+600,reason:'Waiting for remaining seats to fill'});
 await driver.waitForFunction(previous=>window.__rings>previous,beforeChange);await driver.getByLabel('Shared ride to manage').selectOption(soon.id);await driver.getByText('Waiting for remaining seats to fill',{exact:false}).waitFor();const afterChange=await driver.evaluate(()=>window.__rings);await pause(12000);assert.equal(await driver.evaluate(()=>window.__rings),afterChange,'Time-change notification does not ring again on quiet reads');
 const response=await fetch(api+'/operations/notifications',{headers:{Authorization:'Bearer customer'}});const notices=(await response.json()).notifications;assert(notices.some(n=>n.business_id===soon.id&&n.event_type==='rescheduled'&&n.body.includes('Waiting for remaining seats to fill')&&n.body.includes('No response is needed')));checks.push('real rescheduling reaches the passenger notification bell and driver panel; a new note sounds once, with no repeated polling alarm');
 await customer.keyboard.press('Escape');const count=writes.length;await pause(31000);assert.equal(writes.length,count,'idle reads do not submit changes');assert.equal(await customer.getByText('Your changes are saved.',{exact:true}).count(),0);checks.push('idle refreshes produce no submissions or phantom save messages');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks,work}));
}catch(error){console.error(error);console.error(log.slice(-1500));process.exitCode=1;}finally{await writeFile(work+'/report.json',JSON.stringify({checks,errors,writes},null,2));await browser?.close();server.kill('SIGTERM');console.log('Evidence: '+work);}
