import {apiFetch} from './api';
import {auth} from '../firebase';
import {operation} from './operations';
import type {B2BListing,B2BRfqRequest,B2BQuotation,B2BPolicy,B2BPage,B2BListingDraft,B2BRfqDraft,B2BQuoteDraft} from '../types/b2b';
type Row=Record<string,any>;
const text=(value:unknown)=>typeof value==='string'?value:'';
export const b2bMoney=(rupees:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(rupees);
export function listingFromServer(row:Row):B2BListing{return {
 id:row.id,shopId:row.shop_id,shopName:text(row.shop_name),distributorName:text(row.distributor_name)||text(row.shop_name),
 city:text(row.city),address:text(row.address),title:row.title,category:row.category,partNumber:text(row.part_number),hsnCode:text(row.hsn_code),
 unit:row.unit,moq:row.moq,basePrice:row.base_price_paise/100,mrp:row.mrp_paise==null?undefined:row.mrp_paise/100,
 bulkSlabs:(row.bulk_slabs||[]).map((s:Row)=>({minQty:s.min_qty,maxQty:s.max_qty??undefined,pricePerUnit:s.price_paise/100,discountLabel:text(s.discount_label)})),
 stock:row.stock,leadTimeDays:row.lead_time_days,supplyCapacity:text(row.supply_capacity),description:text(row.description),specifications:row.specifications||{},
 image:text(row.image),status:row.status,verifiedDistributor:row.verified_distributor===true,prime:row.prime,
 createdAt:row.created_at*1000,updatedAt:row.updated_at*1000,version:row.version??1,
};}
export function quoteFromServer(row:Row):B2BQuotation{
 const expiry=typeof row.valid_until==='number'?row.valid_until*1000:typeof row.expires_at==='number'?row.expires_at*1000:Date.parse(row.valid_until||'');
 return {quoteNumber:row.quote_number,rfqId:row.rfq_id,shopId:row.shop_id,shopName:text(row.shop_name),distributorName:text(row.distributor_name),
 distributorGstin:text(row.distributor_gstin),shopAddress:text(row.shop_address),shopPhone:text(row.shop_phone),shopEmail:text(row.shop_email),
 customerName:text(row.customer_name),buyerCompanyName:row.buyer_company_name,buyerGstin:row.buyer_gstin,deliveryAddress:text(row.delivery_address),deliveryCity:text(row.delivery_city),deliveryPincode:text(row.delivery_pincode),
 itemTitle:text(row.item_title),partNumber:text(row.part_number),hsnCode:text(row.hsn_code),unit:row.unit,quantity:row.quantity,offeredRate:row.offered_rate_paise/100,
 taxableAmount:row.taxable_paise/100,gstRate:row.gst_rate??row.gst_bps/10000,gstAmount:row.gst_paise/100,freightCharges:row.freight_charges_paise/100,grandTotal:row.grand_total_paise/100,
 paymentTerms:text(row.payment_terms),deliveryTimeline:text(row.delivery_timeline),warrantyTerms:text(row.warranty_terms),validityDays:row.validity_days,
 validUntil:Number.isFinite(expiry)?new Date(expiry).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Not provided',validUntilMs:expiry,
 authorizedSignatory:text(row.authorized_signatory),signatoryDesignation:text(row.signatory_designation),specialNotes:row.special_notes,createdAt:row.created_at*1000,status:row.status,serverNow:row.server_now?row.server_now*1000:undefined};
}
export function rfqFromServer(row:Row):B2BRfqRequest{return {id:row.id,listingId:row.listing_id,itemTitle:text(row.item_title),category:row.category,hsnCode:text(row.hsn_code),unit:row.unit,
 shopId:row.shop_id,shopName:text(row.shop_name),customerName:text(row.customer_name),customerPhone:text(row.customer_phone),customerEmail:text(row.customer_email),buyerCompanyName:row.buyer_company_name,buyerGstin:row.buyer_gstin,
 deliveryAddress:text(row.delivery_address),deliveryCity:text(row.delivery_city),deliveryPincode:text(row.delivery_pincode),quantityRequested:row.quantity_requested,targetPricePerUnit:row.target_price_paise==null?undefined:row.target_price_paise/100,
 urgency:row.urgency,notes:text(row.notes),status:row.status,createdAt:row.created_at*1000,updatedAt:row.updated_at*1000,version:row.version??1,quotation:row.quotation?quoteFromServer({...row.quotation,status:row.status}):undefined};}
async function publicRead(path:string,signal?:AbortSignal){const response=await apiFetch('/api/operations/b2b'+path,{signal},{background:true});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body.detail?.message||'Wholesale information could not load. Please retry.');return body;}
const privateRead=(path:string,signal?:AbortSignal)=>operation<Row>('/b2b'+path,{signal},{background:true,force:true});
const write=(path:string,method:string,body?:object)=>operation<Row>('/b2b'+path,{method,...(body?{body:JSON.stringify(body)}:{})},{background:true});
const privateScope=()=>auth.currentUser?.uid||localStorage.getItem('repaido.token')||'';
const assertScope=(scope:string)=>{if(scope!==privateScope())throw Error('Your account changed. Reopen this view.');};
export const b2bService={
 async getPolicy(signal?:AbortSignal):Promise<B2BPolicy>{const p=await publicRead('/policy',signal);return {paymentsReady:p.payments_ready===true,escrowAvailable:p.escrow_available===true,acceptanceNote:text(p.acceptance_note),priceNote:text(p.price_note)};},
 async getB2BListings(options:{shopId?:string;cursor?:string;search?:string;category?:string}={},signal?:AbortSignal):Promise<B2BPage<B2BListing>>{const params=new URLSearchParams();if(options.shopId)params.set('shop_id',options.shopId);if(options.cursor)params.set('cursor',options.cursor);if(options.search)params.set('search',options.search);if(options.category&&options.category!=='all')params.set('category',options.category);const data=options.shopId?await privateRead('/listings?'+params,signal):await publicRead('/listings?'+params,signal);return {items:data.listings.map(listingFromServer),nextCursor:data.next_cursor||null};},
 async getCustomerRFQs(cursor='',signal?:AbortSignal):Promise<B2BPage<B2BRfqRequest>>{const data=await privateRead('/rfq'+(cursor?'?cursor='+encodeURIComponent(cursor):''),signal);return {items:data.rfqs.map(rfqFromServer),nextCursor:data.next_cursor||null};},
 async getShopRFQs(shopId:string,cursor='',signal?:AbortSignal):Promise<B2BPage<B2BRfqRequest>>{const data=await privateRead('/rfq?shop_id='+encodeURIComponent(shopId)+(cursor?'&cursor='+encodeURIComponent(cursor):''),signal);return {items:data.rfqs.map(rfqFromServer),nextCursor:data.next_cursor||null};},
 async saveB2BListing(d:B2BListingDraft,id?:string){const body={...(id?{}:{request_id:d.requestId,shop_id:d.shopId}),title:d.title,category:d.category,part_number:d.partNumber,hsn_code:d.hsnCode,unit:d.unit,moq:d.moq,base_price_paise:Math.round(d.basePrice*100),mrp_paise:d.mrp==null?null:Math.round(d.mrp*100),bulk_slabs:d.bulkSlabs.map(s=>({min_qty:s.minQty,max_qty:s.maxQty??null,price_paise:Math.round(s.pricePerUnit*100),discount_label:s.discountLabel})),stock:d.stock,lead_time_days:d.leadTimeDays,supply_capacity:d.supplyCapacity,description:d.description,specifications:d.specifications,image:d.image||null,...(id?{expected_version:d.expectedVersion}:{})};const data=await write('/listings'+(id?'/'+encodeURIComponent(id):''),id?'PUT':'POST',body);return listingFromServer(data.listing);},
 async setListingStatus(listing:B2BListing,status:'active'|'paused'){const data=await write('/listings/'+encodeURIComponent(listing.id)+'/status','POST',{status,expected_version:listing.version});return listingFromServer(data.listing);},
 async deleteB2BListing(listing:B2BListing){return write('/listings/'+encodeURIComponent(listing.id),'DELETE',{expected_version:listing.version});},
 async createRFQ(d:B2BRfqDraft){const data=await write('/rfq','POST',{request_id:d.requestId,listing_id:d.listingId,customer_name:d.customerName,customer_phone:d.customerPhone,customer_email:d.customerEmail,buyer_company_name:d.buyerCompanyName||null,buyer_gstin:d.buyerGstin||null,delivery_address:d.deliveryAddress,delivery_city:d.deliveryCity,delivery_pincode:d.deliveryPincode,quantity_requested:d.quantityRequested,target_price_paise:d.targetPricePerUnit==null?null:Math.round(d.targetPricePerUnit*100),urgency:d.urgency,notes:d.notes});return rfqFromServer(data.rfq);},
 async generateQuotation(rfqId:string,d:B2BQuoteDraft){const data=await write('/quotation','POST',{request_id:d.requestId,rfq_id:rfqId,offered_rate_paise:Math.round(d.offeredRate*100),quantity:d.quantity,gst_bps:Math.round(d.gstRate*10000),freight_charges_paise:Math.round(d.freightCharges*100),payment_terms:d.paymentTerms,delivery_timeline:d.deliveryTimeline,warranty_terms:d.warrantyTerms,validity_days:d.validityDays,authorized_signatory:d.authorizedSignatory,signatory_designation:d.signatoryDesignation,special_notes:d.specialNotes||''});return quoteFromServer(data.quotation);},
 async decideQuotation(rfq:B2BRfqRequest,action:'accept'|'decline'){if(!rfq.quotation)throw Error('No quotation has been issued yet.');const data=await write('/rfq/'+encodeURIComponent(rfq.id)+'/decision','POST',{quote_number:rfq.quotation.quoteNumber,action});return rfqFromServer(data.rfq);},
 async uploadPhoto(file:File,shopId:string){await auth.authStateReady();const scope=privateScope(),token=auth.currentUser?await auth.currentUser.getIdToken():localStorage.getItem('repaido.token');if(!token)throw Error('Sign in to upload a product photo.');assertScope(scope);const response=await apiFetch('/api/operations/b2b/photos?shop_id='+encodeURIComponent(shopId),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':file.type},body:file},{background:true,feedback:true});const data=await response.json().catch(()=>({}));assertScope(scope);if(!response.ok)throw Error(data.detail?.message||'Your product photo was not saved. Please retry.');if(!data.image_url)throw Error('The server did not confirm your product photo.');return data.image_url as string;},
 async downloadQuotation(quoteNumber:string){await auth.authStateReady();const scope=privateScope(),token=auth.currentUser?await auth.currentUser.getIdToken():localStorage.getItem('repaido.token');if(!token)throw Error('Sign in to download this private quotation.');assertScope(scope);const response=await apiFetch('/api/operations/b2b/quotation/'+encodeURIComponent(quoteNumber)+'/pdf',{headers:{Authorization:'Bearer '+token}},{background:true});assertScope(scope);if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.detail?.message||'The saved quotation PDF could not load. Please retry.');}const blob=await response.blob();assertScope(scope);if(!response.headers.get('content-type')?.includes('application/pdf'))throw Error('The saved quotation document was not confirmed.');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=quoteNumber+'.pdf';document.body.append(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);},
};
