import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {operation,type Job} from '../services/operations';
type Position={lat:number;lng:number;accuracy:number;received_at:number};
export function AgentTravelMap({job,onArrival}:{job:Job;onArrival:()=>Promise<void>}){
 const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),pin=useRef<L.CircleMarker|null>(null),accuracy=useRef<L.Circle|null>(null),latest=useRef(onArrival),centred=useRef(false);
 const [status,setStatus]=useState('Loading live position…'),[position,setPosition]=useState<Position|null>(null),[tileError,setTileError]=useState(false);
 latest.current=onArrival;
 useEffect(()=>{if(!host.current||!job.location)return;const target:L.LatLngTuple=[job.location.lat,job.location.lng];const m=L.map(host.current,{scrollWheelZoom:false}).setView(target,16);map.current=m;
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>setTileError(true)).addTo(m);
 L.circle(target,{radius:100,color:'#08733b',fillOpacity:.1,weight:2}).addTo(m).bindTooltip('100 m arrival area');L.circleMarker(target,{radius:9,color:'#fff',fillColor:'#08733b',fillOpacity:1,weight:3}).addTo(m).bindTooltip('Work location',{permanent:true,direction:'top'});
 const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(host.current);return()=>{resize.disconnect();m.remove();map.current=null;pin.current=null;accuracy.current=null;centred.current=false;};},[job.id,job.location?.lat,job.location?.lng]);
 useEffect(()=>{let gone=false,inflight=false;const load=async()=>{if(inflight||document.hidden)return;inflight=true;try{const d=await operation<{phase:string;status:string;position:Position|null}>(`/jobs/${job.id}/tracking`,{}, {background:true});if(gone)return;setPosition(d.position);setStatus(d.status==='live'?'Live GPS · updates every 15 seconds':d.status==='stale'?'GPS is outdated. Refresh location sharing.':'Share GPS to show your current position.');if(d.phase==='arrived'&&job.state==='en_route')await latest.current();}catch(e){if(!gone){setPosition(null);setStatus((e as Error).message);}}finally{inflight=false;}};void load();const timer=setInterval(load,15000);return()=>{gone=true;clearInterval(timer);};},[job.id,job.state]);
 useEffect(()=>{const m=map.current;if(!m)return;if(!position){pin.current?.remove();accuracy.current?.remove();pin.current=null;accuracy.current=null;return;}const point:L.LatLngTuple=[position.lat,position.lng];if(!pin.current){pin.current=L.circleMarker(point,{radius:8,color:'#fff',fillColor:'#123879',fillOpacity:1,weight:3}).addTo(m).bindTooltip('You');accuracy.current=L.circle(point,{radius:position.accuracy,color:'#123879',weight:1,fillOpacity:.1}).addTo(m);}else{pin.current.setLatLng(point);accuracy.current?.setLatLng(point).setRadius(position.accuracy);}if(!centred.current&&job.location){m.fitBounds(L.latLngBounds([point,[job.location.lat,job.location.lng]]),{padding:[30,35],maxZoom:17});centred.current=true;}},[position,job.location]);
 return <div className="agent-travel-map" onTouchStart={e=>e.stopPropagation()} onTouchEnd={e=>e.stopPropagation()}><div ref={host} className="agent-travel-map-canvas" role="region" aria-label="Live travel map: your position and the work location"/><div className="agent-map-caption"><span role="status">{tileError?'Map tiles unavailable. Use directions below.':status}</span><button type="button" onClick={()=>{if(job.location)map.current?.fitBounds(L.latLngBounds(position?[[position.lat,position.lng],[job.location.lat,job.location.lng]]:[[job.location.lat,job.location.lng]]),{padding:[30,35],maxZoom:17});}}>Re-centre</button></div><small>Blue: you · Green: work site · Boundary: 100 m</small></div>;
}
