import {TaskMarket} from './TaskMarket';
import {AgentTravelMap} from './AgentTravelMap';
import {HomeVisitChecks,HomeBrief} from './HomePlans';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BadgeCheck,Camera,Check,ClipboardCheck,FileText,MapPin,Package,RefreshCw,Route,ShieldCheck,Wrench} from 'lucide-react';
import {Modal} from './ui';
import {type Job,operation,money} from '../services/operations';
import {taskNextAction,taskProgress,taskStage,taskStages} from '../services/taskStages.mjs';
import {VisitEvidence} from './VisitEvidence';
import {TaskProcurement} from './Procurement';
import {RentalManager} from './Rentals';
import {BookingRecovery,SupportCenter} from './Lifecycle';
import {TaskReport} from './WorkerRecords';
import './agent-workspace.css';

type Props={job:Job;busy:boolean;error:string;onClose:()=>void;onRefresh:()=>Promise<void>;onRun:(action:string,payload?:object)=>Promise<Job|undefined>;onShare:()=>Promise<void>;onStop:()=>Promise<void>};
const messages:Record<string,string>={offered:'Review the scope, visit time and terms before accepting.',accepted:'Visit accepted. Acknowledge the reminder when it becomes due.',follow_up_scheduled:'Your next visit is saved. The same task continues at this appointment.',en_route:'Share a fresh location. Arrival is recorded when you reach the service area.',arrived:'You are almost there — arrival area confirmed. Verify the customer’s six-digit in-app code and take the before photo.',in_progress:'Work is running. Request approval before adding any parts or rentals.',collecting_parts:'Work time is paused while you collect parts. Confirm receipt at the shop.',completion_pending:'Submitted. The customer must review and confirm the work.',completed:'Customer confirmed completion. Payment and payout are tracked separately.',cancelled:'This task is cancelled. Review its history and financial status.',disputed:'This task is under review. Use support to provide your explanation.',stop_requested:'Work is paused for support review.',follow_up_required:'Arrange the next visit with the customer.'};
const stageIcons=[ClipboardCheck,Route,MapPin,Wrench,BadgeCheck];
function CheckStatus({done,completeLabel='Saved'}:{done:boolean;completeLabel?:string}) {
  return <strong className="agent-status-label" data-tone={done?'success':'warning'}>{done&&<Check size={14} aria-hidden="true"/>}{done?completeLabel:'Required'}</strong>;
}
function RecordStatus({value}:{value:string}) {
  const tone=['verified','paid','settled','released'].includes(value)?'success':['failed','rejected','cancelled','disputed'].includes(value)?'danger':'warning';
  const label=({pay_after_service:'Pay after service',held:'On hold',verified:'Payment verified',paid:'Paid',settled:'Settled',released:'Released',failed:'Failed',pending:'Pending',unpaid:'Payment due'} as Record<string,string>)[value]||value.replaceAll('_',' ');
  return <span className="agent-status-label" data-tone={tone}>{label}</span>;
}
export function AgentTaskWorkspace({job,busy,error,onClose,onRefresh,onRun,onShare,onStop}:Props){
  const current=taskStage(job),next=taskNextAction(job),progress=taskProgress(job);
  const [stage,setStage]=useState(current),[tool,setTool]=useState<string|null>(null),[localError,setError]=useState(''),[saving,setSaving]=useState(false),[otp,setOtp]=useState('');
  const draftKey=`repaido.task.${job.id}.${job.visit_id}`;
  const [note,setNote]=useState(()=>sessionStorage.getItem(draftKey)||''),[reason,setReason]=useState(''),[date,setDate]=useState(''),[purpose,setPurpose]=useState('repair');
  const touch=useRef<{x:number;y:number}|null>(null),tabs=useRef<(HTMLButtonElement|null)[]>([]);
  useEffect(()=>{setStage(current);},[current,job.visit_id]);
  useEffect(()=>{tabs.current[stage]?.scrollIntoView({block:'nearest',inline:'nearest'});},[stage]);
  useEffect(()=>{sessionStorage.setItem(draftKey,note);},[note,draftKey]);
  const can=(a:string)=>job.allowed_actions.includes(a);
  const perform=async(fn:()=>Promise<unknown>,close=false)=>{setSaving(true);setError('');try{const result=await fn();if(close&&result!==undefined)setTool(null);}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
  const action=async(a:string,p:object={})=>{const result=await onRun(a,p);if(result){setTool(null);if(a==='depart')await onShare();if(a==='submit_completion'||a==='schedule_follow_up')sessionStorage.removeItem(draftKey);}return result;};
  const move=(n:number,focus=false)=>{const value=Math.max(0,Math.min(4,n));setStage(value);if(focus)tabs.current[value]?.focus();};
  const locked=busy||saving;
  const StageIcon=stageIcons[stage],stageDone=stage<progress.completed;
  return <Modal title={job.service_name} frameless className="agent-task-dialog" onClose={onClose}>
    <div className="agent-task-shell">
      <header className="agent-task-head"><button aria-label="Close task" onClick={onClose}><ArrowLeft size={19}/></button><div><small>Task {job.id.slice(0,8)} · {job.state.replaceAll('_',' ')}</small><h2>{job.service_name}</h2></div><button disabled={locked} aria-label="Refresh task" onClick={()=>void onRefresh()}><RefreshCw size={18}/></button></header>
      <div className="agent-stage-navigation">
        <div className="agent-stage-tabs" role="tablist" aria-label="Task stages">{taskStages.map((s:string,i:number)=><button key={s} ref={el=>{tabs.current[i]=el;}} role="tab" id={`stage-${i}`} aria-selected={stage===i} aria-controls="agent-stage-panel" aria-label={`${s}, ${i<progress.completed?'completed':i===current?progress.status:'not reached'}`} data-complete={i<progress.completed} tabIndex={stage===i?0:-1} onClick={()=>move(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();move(e.key==='Home'?0:e.key==='End'?4:stage+(e.key==='ArrowRight'?1:-1),true);}}}><span className="agent-stage-number" aria-hidden="true">{i<progress.completed?<Check size={14}/>:i+1}</span><span className="agent-stage-name">{s}</span></button>)}</div>
        <div className="agent-task-progress" data-tone={progress.tone}>
          <div className="agent-progress-caption"><span>This visit · {progress.completed} of 5 stages done</span><strong>{progress.percent}%</strong></div>
          <div className="agent-progress-track" role="progressbar" aria-label="Visit stage completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percent} aria-valuetext={`${progress.percent}%, ${progress.completed} of 5 stages completed. ${progress.status}. Based on stages, not time or payment.`}><span style={{width:`${progress.percent}%`}}/></div>
          <span className="sr-only" role="status">{progress.status}. {progress.percent}% of visit stages completed.</span>
        </div>
      </div>
      {(error||localError)&&<div className="agent-inline-error" role="alert">{localError||error}<button onClick={()=>void onRefresh()}>Refresh task</button></div>}
      <section key={stage} id="agent-stage-panel" role="tabpanel" aria-labelledby={`stage-${stage}`} tabIndex={0} className={`agent-stage-panel${stage===1?" agent-travel-stage":""}`} onTouchStart={e=>{if((e.target as HTMLElement).closest('input,textarea,select,button,a'))return;touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY};}} onTouchEnd={e=>{const start=touch.current;touch.current=null;if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)move(stage+(dx<0?1:-1));}}>
        <div className="agent-stage-caption"><span>Stage {stage+1} of 5</span>{stage===current?<strong className="agent-status-label" data-tone={progress.tone}>{progress.status}</strong>:<button onClick={()=>move(current)}>Current stage <ArrowRight size={14} aria-hidden="true"/></button>}</div>
        <div className="agent-stage-heading" data-tone={stageDone?'success':stage===current?progress.tone:'brand'}><span className="agent-stage-symbol" data-stage={stage} data-active={stage===current} aria-hidden="true"><StageIcon size={24} strokeWidth={2}/></span><h3>{taskStages[stage]}</h3>{stageDone&&<span className="agent-stage-done"><Check size={14} aria-hidden="true"/>Completed</span>}</div><p>{stage===current?(job.home_log_required&&job.state==='arrived'?'Verify the customer code, then record arrival and hygiene checks.':job.home_log_required&&job.state==='in_progress'?'Complete the agreed daily tasks and record the service report.':messages[job.state])||'Refresh the task for the next available action.':stageDone?'You can revisit the records for this stage.':'This stage opens as the task progresses.'}</p>
        {job.coupon&&<p className="agent-step-note">{job.coupon.code}: {money(job.vendor_discount_paise||0)} discount funded from professional earnings. Taxes, parts and travel are excluded. Review this before accepting.</p>}{stage!==1&&<div className="agent-task-facts"><span><strong>Visit</strong>{new Date(job.starts_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span><span><strong>Customer bill</strong>{money(job.total_paise)}</span></div>}
        {stage===0&&<><div className="agent-step-note"><ClockText job={job}/>{job.follow_up_reason&&<p>{job.follow_up_purpose}: {job.follow_up_reason}</p>}</div><button onClick={()=>setTool('terms')}><ShieldCheck size={16}/>Scope & visit terms</button>{can('decline')&&<button className="agent-danger" disabled={locked} onClick={()=>setTool('decline')}>Decline request</button>}</>}
        {stage===1&&<>{job.location&&<AgentTravelMap job={job} onArrival={onRefresh}/>}<p className="agent-address"><MapPin size={17}/>{job.address||`${job.city} · Exact location opens after acknowledgement.`}</p>{job.location&&<a className="agent-primary-link" href={`https://www.google.com/maps/dir/?api=1&destination=${job.location.lat},${job.location.lng}`} target="_blank" rel="noreferrer">Open directions <ArrowRight size={16}/></a>}{can('position')&&<div className="agent-tool-grid"><button disabled={locked} onClick={()=>void onShare()}>Refresh / share GPS</button><button disabled={locked} onClick={()=>void onStop()}>Stop sharing</button></div>}<p className="agent-muted">{job.distance_metres===null?'No fresh task location yet.':`${job.distance_metres} m straight-line distance to site.`} If GPS fails, ask the customer to confirm your arrival in their booking.</p></>}
        {stage===2&&<>{job.home_log_required&&<button onClick={()=>setTool('daily')}>Arrival & hygiene checks</button>}<div className="agent-check-row"><ShieldCheck size={18}/><span>Customer OTP</span><CheckStatus done={job.arrival_verified_visit===job.visit_id||(job.procurement_version||1)<2} completeLabel="Verified"/></div><div className="agent-check-row"><Camera size={18}/><span>{job.home_log_required?'Arrival checks':'Before photo'}</span><CheckStatus done={!!(job.home_log_required?job.home_arrival_log:job.evidence_summary?.has_before)}/></div><div className="agent-tool-grid"><button disabled={job.state!=='arrived'} onClick={()=>setTool('otp')}>Verify arrival</button><button onClick={()=>setTool(job.home_log_required?'daily':'photos')}>{job.home_log_required?'Visit checks':'Work camera'}</button></div>{job.notes&&<p>Customer instructions: {job.notes}</p>}</>}
        {stage===3&&<>{job.home_plan_id&&<button onClick={()=>setTool('brief')}>Customer brief & PDF</button>}{job.home_log_required&&<button className="ops-primary" onClick={()=>setTool('daily')}>Daily tasks & hygiene report</button>}<div className="agent-tool-grid">{[{key:'photos',name:'Work photos',Icon:Camera},{key:'parts',name:'Parts & pickups',Icon:Package},{key:'rentals',name:'Rental equipment',Icon:Wrench},{key:'followup',name:'Next visit',Icon:RefreshCw}].map(({key,name,Icon})=><button key={key} disabled={key==='followup'&&!can('schedule_follow_up')} onClick={()=>setTool(job.home_log_required&&key==='photos'?'daily':key)}><Icon size={20}/>{job.home_log_required&&key==='photos'?'Daily checks':name}</button>)}</div>{job.proposal&&<div className="agent-step-note">Parts: {job.proposal.status.replaceAll('_',' ')} · {money(job.proposal.amount_paise)}<p>Customer approval and payment are required before the shop receives the order.</p></div>}</>}
        {stage===4&&<><div className="agent-check-row"><Camera size={18}/><span>{job.home_log_required?'Daily report':'After photo'}</span><CheckStatus done={!!(job.home_log_required?job.home_daily_log:job.evidence_summary?.has_after)}/></div><div className="agent-task-facts"><span><strong>Payment</strong><RecordStatus value={job.payment_status}/></span><span><strong>Payout</strong><RecordStatus value={job.payout_status}/></span></div>{job.review&&<p>{job.review.rating}/5 · {job.review.text}</p>}<button onClick={()=>setTool('report')}><FileText size={17}/>Report, SLA & penalties</button></>}
      </section>
      <footer className="agent-stage-footer"><div className="agent-stage-controls"><button aria-label="Previous stage" disabled={stage===0} onClick={()=>move(stage-1)}><ArrowLeft size={17}/></button><button onClick={()=>setTool('support')}>Help</button><button onClick={()=>setTool('report')}>Records</button><button aria-label="Next stage" disabled={stage===4} onClick={()=>move(stage+1)}><ArrowRight size={17}/></button></div>{next&&<button className="ops-primary" disabled={locked} onClick={()=>next.tool?setTool(next.tool):void perform(()=>action(next.action!))}>{locked?'Saving…':next.label}<ArrowRight size={16}/></button>}<span className="agent-live-status" role="status">{next?'Actions use the live task status.':progress.status}</span></footer>
    </div>
    {tool&&<Modal title={({daily:'Daily service checks',photos:'Work camera',parts:'Parts & pickups',rentals:'Rental equipment',followup:'Schedule another visit',complete:'Complete work',otp:'Verify arrival',decline:'Decline this request',report:'Task records',support:'Task support',terms:'Scope & terms'} as Record<string,string>)[tool]} className="agent-tool-sheet" onClose={()=>setTool(null)}>
      {(error||localError)&&<p role="alert" className="ops-error">{localError||error}</p>}
      {tool==='brief'&&job.home_plan_id&&<HomeBrief plan={{id:job.home_plan_id,brief_rows:job.home_brief_rows,instructions:job.notes}}/>}
      {tool==='daily'&&<HomeVisitChecks job={job} onRefresh={onRefresh}/>}
      {tool==='photos'&&<VisitEvidence job={job} worker onRefresh={onRefresh}/>}
      {tool==='otp'&&<form onSubmit={e=>{e.preventDefault();void perform(async()=>{await operation(`/jobs/${job.id}/verify-arrival`,{method:'POST',body:JSON.stringify({code:otp})});setOtp('');await onRefresh();setTool(null);});}}><label>Customer’s 6-digit code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} autoComplete="off" required/></label><p>Ask the customer for the code shown in their booking.</p><button className="ops-primary" disabled={locked||otp.length!==6}>Verify code</button></form>}
      {tool==='parts'&&<><details className="task-market-orders"><summary>Existing quotes, pickup & verification</summary><TaskProcurement job={job} worker onRefresh={onRefresh} onCollect={()=>action('collect_parts',{return_policy:'pickup-return-v1'})}/></details><TaskMarket canRent={job.state==='in_progress'} jobId={job.id} canRequest={can('propose_parts')} busy={locked} onSubmit={items=>action('propose_parts',{items})}/><div className="agent-tool-grid">{can('install_parts')&&<button disabled={locked} onClick={()=>void action('install_parts')}>Confirm installation</button>}{can('parts_unavailable')&&<button disabled={locked} onClick={()=>void action('parts_unavailable')}>Report unavailable parts</button>}</div></>}
      {tool==='rentals'&&<><RentalManager jobId={job.id}/><TaskMarket canRent={job.state==='in_progress'} jobId={job.id} initialMode="rent" canRequest={can('propose_parts')} busy={locked} onSubmit={items=>action('propose_parts',{items})}/></>}
      {tool==='followup'&&<form onSubmit={e=>{e.preventDefault();void perform(()=>action('schedule_follow_up',{starts_at:new Date(date).toISOString(),reason,purpose}));}}><label>Visit purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)}>{['repair','inspection','update','maintenance','other'].map(p=><option key={p}>{p}</option>)}</select></label><label>Agreed date & time<input type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Why another visit is needed<textarea required minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>This remains pending. A reminder is due 24 hours before the next visit. Confirm the time with the customer first.</p><button className="ops-primary" disabled={locked||!date||reason.trim().length<10}>Save next visit</button></form>}
      {tool==='complete'&&<form onSubmit={e=>{e.preventDefault();void perform(()=>action('submit_completion',{notes:note,forgotten_info:reason}));}}><label>Work done & checks completed<textarea required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>{!job.home_log_required&&!job.evidence_summary?.has_before&&<label>Missing before-photo explanation (legacy task)<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<p>Return rental equipment and close all parts orders first. The customer confirms completion before payment.</p><button className="ops-primary" disabled={locked||!note.trim()||(!job.home_log_required&&(!job.evidence_summary?.has_after||(!job.evidence_summary?.has_before&&reason.trim().length<5)))}>Submit for customer review</button></form>}
      {tool==='decline'&&<><p>This releases the request for reassignment. It does not cancel the customer’s booking.</p><button className="agent-danger" disabled={locked} onClick={()=>void action('decline')}>Confirm decline</button></>}
      {tool==='report'&&<TaskReport jobId={job.id}/>}
      {tool==='support'&&<><BookingRecovery job={job} worker onRefresh={onRefresh}/><SupportCenter jobId={job.id}/></>}
      {tool==='terms'&&<><p>{job.service_terms?.text||'No additional service terms published.'}</p><p>Visit {new Date(job.starts_at).toLocaleString()}. Parts need customer approval. Payout depends on verified payment and the earnings policy accepted for this task.</p><TaskReport jobId={job.id}/></>}
    </Modal>}
  </Modal>;
}
function ClockText({job}:{job:Job}){const [now,setNow]=useState(Date.now()/1000);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(id);},[]);return <p>{job.state==='offered'?`Respond within ${Math.max(0,Math.ceil(((job.offer_expires_at||now)-now)/60))} minutes.`:job.reminder_ack_at?'Visit acknowledged.':`Reminder: ${new Date(job.reminder_at*1000).toLocaleString()}`}</p>;}
