import {useEffect,useState} from 'react';
import {auth} from '../firebase';
import {apiFetch} from '../services/api';
import type {Campaign} from './CampaignAdmin';
export function CampaignStudio({draft:d,onChange,busy}:{draft:Campaign;onChange:(v:Campaign)=>void;busy:boolean}){
 const [image,setImage]=useState(''),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
 useEffect(()=>{let alive=true,url='';setImage('');if(d.image_id)void (async()=>{try{const token=await auth.currentUser?.getIdToken();const r=await apiFetch('/api/operations/admin/campaign-media/'+d.image_id,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Saved artwork preview could not load. Retry or upload a replacement.');url=URL.createObjectURL(await r.blob());if(alive)setImage(url);}catch(e){if(alive)setError((e as Error).message);}})();return()=>{alive=false;if(url)URL.revokeObjectURL(url);};},[d.image_id]);
 const template=(event:string)=>onChange({...d,title:event==='Durga Puja'?'Repaido Home: Repair your living.':'A new year. A fresh start at home.',body:event==='Durga Puja'?'Welcome Maa Durga with a home prepared with care. Explore your home project.':'Plan your home refresh, daily help or renovation with a written scope.',event_name:event,service_id:'home:renovation',tone:event==='Durga Puja'?'festive':'blue',layout:'image-card',discount_paise:0,starts_at:Date.now()/1000,ends_at:Date.now()/1000+30*86400,active:false,audience:'all',terms:'Request a written scope, schedule and estimate before confirming work. Materials, permits and extra work are included only when explicitly agreed. Subject to professional availability.'});
 const upload=async(file:File)=>{setUploading(true);setError('');try{const token=await auth.currentUser?.getIdToken();const r=await apiFetch('/api/operations/admin/campaign-media',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':file.type},body:file});const result=await r.json();if(!r.ok)throw Error(result.detail?.message||'Upload failed. Try a JPG or PNG under 5 MB.');onChange({...d,image_id:result.id,image_alt:d.image_alt||''});}catch(e){setError((e as Error).message);}finally{setUploading(false);}};
 return <section className="campaign-studio"><h3>Event design studio</h3><p>Choose a reusable layout, upload campaign artwork and set a date range below. Templates stay in draft until published. Targeting uses opted-in service interests and purchases; care notes, age and religion are never targeting inputs.</p><div className="campaign-admin-flags"><button type="button" disabled={busy||uploading} onClick={()=>template('Durga Puja')}>Durga Puja · 30-day draft</button><button type="button" disabled={busy||uploading} onClick={()=>template('New Year')}>New Year · 30-day draft</button></div><label>Event / collection label<input maxLength={80} value={d.event_name||''} onChange={e=>onChange({...d,event_name:e.target.value})}/></label><label>Layout<select value={d.layout||'compact'} onChange={e=>onChange({...d,layout:e.target.value as Campaign['layout']})}><option value="compact">Compact strip</option><option value="image-card">Artwork card</option><option value="editorial">Editorial panel</option></select></label><label>Campaign artwork · JPG / PNG, up to 5 MB<input type="file" accept="image/jpeg,image/png" disabled={busy||uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>{d.image_id&&<><label>Describe this artwork<input required minLength={5} maxLength={150} value={d.image_alt||''} onChange={e=>onChange({...d,image_alt:e.target.value})}/></label><button type="button" onClick={()=>onChange({...d,image_id:'',image_alt:''})}>Remove artwork from this draft</button></>}{uploading&&<p role="status">Uploading artwork…</p>}{error&&<p role="alert">{error}</p>}<div className={`campaign-studio-preview promo-${d.tone} preview-${d.layout||'compact'}`} role="region" aria-label="Campaign design preview">{image&&<img src={image} alt={d.image_alt||'Draft artwork'}/>}<div><small>{d.event_name||'Event name'}</small><strong>{d.title||'Your headline'}</strong><p>{d.body||'A clear description of your service offer.'}</p></div></div><p>Images are public only while a linked campaign is active. Choose artwork you have permission to publish. Headlines remain real, accessible text.</p></section>;
}
