import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BriefcaseBusiness,MapPin,ShieldCheck} from 'lucide-react';
import type {ContractFreshLocation,CustomContractQuery,CustomContractsPage} from '../types/customContracts';
import type {CustomContractHubProps} from './CustomContracts';
import {CustomContractDetail} from './CustomContracts';
import {customContractQueries,expressContractInterest,messageNearbyContractor,freshContractLocation,pendingContractOpportunities} from '../services/customContractsService';
import {ContractError,ContractQueryCard,ContractRefresh,contractDate,useCustomContractAction,useCustomContractResource} from './customContractUI';
import {WorkHub} from './repaidians/WorkHub';
import {Modal} from './ui';
import './custom-contracts.css';

export function MatchedContractTenders(props:Omit<CustomContractHubProps,'mode'>){
  const [selected,setSelected]=useState('');
  return <section className="cc-hub" aria-label="Matched customer contracts"><MatchedContracts {...props} mode="contractor" onOpen={setSelected}/>{selected&&<Modal title="Customer contract requirement" className="contract-dialog" onClose={()=>setSelected('')}><CustomContractDetail key={props.accountKey+selected} {...props} id={selected} mode="contractor" onBack={()=>setSelected('')}/></Modal>}</section>;
}

export function ContractOpportunities(props:CustomContractHubProps&{mode:'contractor'|'agent'}){
  const [tab,setTab]=useState<'contracts'|'jobs'|'applications'>('contracts'),[selected,setSelected]=useState(props.focusContractId||'');
  useEffect(()=>{if(props.focusContractId){setSelected(props.focusContractId);setTab('contracts');}},[props.focusContractId,props.mode]);
  if(!props.authenticated)return <section className="cc-hub"><div className="cc-empty"><ShieldCheck size={26} aria-hidden="true"/><h2>Sign in for your contract opportunities</h2><p>Use your approved professional profile to find work and manage private proposals.</p>{props.onSignIn&&<button className="cc-primary" onClick={props.onSignIn}>Sign in<ArrowRight size={16} aria-hidden="true"/></button>}</div></section>;
  return <section className="cc-hub" aria-label="Professional contract opportunities"><nav className="cc-tabs" aria-label="Work opportunity sections"><button aria-pressed={tab==='contracts'} onClick={()=>setTab('contracts')}>{props.mode==='contractor'?'Matched contracts':'Nearby upcoming contracts'}</button><button aria-pressed={tab==='jobs'} onClick={()=>setTab('jobs')}>Open jobs</button><button aria-pressed={tab==='applications'} onClick={()=>setTab('applications')}>Apply Status</button></nav>{tab!=='contracts'?<WorkHub accountKey={props.accountKey} view={tab} onOpenProject={props.onOpenProject}/>:selected?<CustomContractDetail key={props.accountKey+selected} {...props} id={selected} mode={props.mode} onBack={()=>setSelected('')}/>:props.mode==='agent'?<NearbyContracts key={props.accountKey} {...props}/>:<MatchedContracts {...props} onOpen={setSelected}/>}</section>;
}
function MatchedContracts({accountKey,onOpen,onOpenCommunityContract}:CustomContractHubProps&{onOpen:(id:string)=>void}){
  const resource=useCustomContractResource<CustomContractsPage>(accountKey+':custom:matched',(force,signal)=>customContractQueries('matched','',force,signal)),action=useCustomContractAction(),[extra,setExtra]=useState<CustomContractsPage|null>(null);
  useEffect(()=>setExtra(null),[resource.data]);
  const items=[...new Map([...(resource.data?.items||[]),...(extra?.items||[])].map(row=>[row.id,row])).values()],cursor=extra?extra.nextCursor:resource.data?.nextCursor;
  return <><header className="cc-heading"><div><span className="cc-eyebrow">Private proposals. Clear agreements.</span><h2>Matched contract requirements</h2><p>Work requirements matched to your registered trades, location and experience. The customer chooses the award.</p></div><ContractRefresh busy={resource.busy} onRefresh={()=>void resource.refresh()}/></header><ContractError error={resource.error} onRetry={()=>void resource.refresh()}/>{resource.busy&&!resource.data&&<p role="status" className="cc-note">Finding your contract matches…</p>}<div className="cc-grid">{items.map(query=><ContractQueryCard key={query.id} query={query} onOpen={()=>onOpen(query.id)} onOpenCommunityContract={onOpenCommunityContract}/>)}</div>{!items.length&&!resource.busy&&!resource.error&&<div className="cc-empty"><BriefcaseBusiness size={26} aria-hidden="true"/><h3>No matching requests yet</h3><p>Keep your professional trades, skills and city current. Matching requirements will appear as customers publish them.</p></div>}{cursor&&<button className="cc-more" disabled={action.busy} onClick={()=>void action.run(async()=>{const page=await customContractQueries('matched',cursor);setExtra(prior=>({items:[...(prior?.items||[]),...page.items],members:page.members,nextCursor:page.nextCursor}));})}>More matches</button>}<ContractError error={action.error}/></>;
}
function NearbyContracts({accountKey,onOpenProject}:CustomContractHubProps){
  const action=useCustomContractAction(),[location,setLocation]=useState<ContractFreshLocation|null>(null),[page,setPage]=useState<CustomContractsPage|null>(null),[selected,setSelected]=useState<CustomContractQuery|null>(null),alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  const find=()=>void action.run(async()=>{const current=await freshContractLocation(),result=await pendingContractOpportunities(current);if(alive.current){setLocation(current);setPage(result);setSelected(null);}});
  if(selected)return <><button onClick={()=>setSelected(null)}><ArrowLeft size={16} aria-hidden="true"/>Nearby upcoming contracts</button><ContractQueryCard query={selected} onOpen={()=>setSelected(null)}/>{selected.phase==='jobs_open'&&selected.opening_project_id&&onOpenProject&&<button className="cc-primary" onClick={()=>onOpenProject(selected.opening_project_id!)}>View live hiring & project<ArrowRight size={16} aria-hidden="true"/></button>}{selected.permissions.can_message_nearby&&<NearbyContractMessage query={selected}/>}<PendingInterest key={selected.id} query={selected} onSaved={async()=>{const result=await pendingContractOpportunities(location);if(alive.current){setPage(result);setSelected(result.items.find(item=>item.id===selected.id)||null);}}}/><p className="cc-note">{selected.phase==='jobs_open'?'This awarded contract has a live hiring notice. Apply through Open jobs and review any actual joining offer in Apply Status.':'This is customer-requested work awaiting a contractor award. Open jobs and accepted joining offers are tracked separately.'}</p>{onOpenProject&&<p className="cc-note">An accepted project will appear in your work workspace after a real joining offer is accepted.</p>}</>;
  return <><header className="cc-heading"><div><span className="cc-eyebrow">Plan ahead, near you</span><h2>Nearby upcoming contracts</h2><p>Share fresh location for this search to find eligible requirements within 10 km. Expressing availability does not join a team or apply to a hiring notice.</p></div></header><button className="cc-primary" disabled={action.busy} onClick={find}><MapPin size={16} aria-hidden="true"/>{action.busy?'Checking nearby requirements…':page?'Refresh using my current location':'Find nearby using my current location'}</button><button disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await pendingContractOpportunities(null);if(alive.current){setLocation(null);setPage(result);setSelected(null);}})}>Search with my active membership & registered city</button><p className="cc-note">Location is requested only when you choose this search. Your precise coordinates are not saved with an availability receipt.</p><ContractError error={action.error}/>{page&&<><div className="cc-grid">{page.items.map(query=><div key={query.id}><p className="cc-note">{typeof query.distance_km==='number'?query.distance_km+' km away · ':''}{query.phase==='jobs_open'?'Hiring open · awarded project':'Awaiting contractor award'}</p><ContractQueryCard query={query} onOpen={()=>setSelected(query)}/>{query.my_interest&&<p className="cc-success">Your availability is recorded · awaiting award.</p>}</div>)}</div>{!page.items.length&&<div className="cc-empty"><h3>No eligible upcoming requirements nearby</h3><p>Try again when new work is published. Open jobs remain available in their own section.</p></div>}{page.nextCursor&&<button className="cc-more" disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await pendingContractOpportunities(location,page.nextCursor!);if(alive.current)setPage(previous=>({items:[...(previous?.items||[]),...result.items],members:result.members,nextCursor:result.nextCursor}));})}>More nearby requirements</button>}</>}</>;
}
function PendingInterest({query,onSaved}:{query:CustomContractQuery;onSaved:()=>Promise<void>}){
  const action=useCustomContractAction(),roles=query.workforce_requirements||[];
  if(query.phase==='jobs_open')return <section className="cc-section"><h3>Hiring is now open</h3><p>Review the live notice in Open jobs and submit a real application for a current vacancy. Any earlier availability receipt remains separate from an accepted joining offer.</p></section>;
  if(query.my_interest)return <section className="cc-section"><h3>Availability recorded · awaiting award</h3><p>{query.my_interest.note}</p><p className="cc-note">Requested work type: {query.my_interest.worker_type.replaceAll('_',' ')}. This receipt is not a hiring offer or accepted placement.</p></section>;
  if(!query.permissions.can_interest||!roles.length)return <p className="cc-note">This requirement is not accepting availability for a specified worker type.</p>;
  return <section className="cc-section"><h3>Express your availability</h3><p className="cc-note">Work is planned for {contractDate(query.starts_at)} – {contractDate(query.ends_at)}. A contractor must receive the award and publish genuine hiring before a joining offer can be made.</p><form className="cc-form" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{const current=query.interest_access==='membership'?null:await freshContractLocation();await expressContractInterest(query.id,String(fields.get('note')),String(fields.get('worker_type')),current);await onSaved();},'Your availability was recorded. This requirement is awaiting a contractor award.');}}><label>Requested worker type<select aria-label="Requested worker type" name="worker_type" required disabled={action.busy}><option value="">Choose the work you can do</option>{roles.map(role=><option key={role.worker_type} value={role.worker_type}>{role.worker_type.replaceAll('_',' ')} · {role.count} requested</option>)}</select></label><label>Your relevant experience and availability<textarea name="note" minLength={20} maxLength={2000} required rows={4} disabled={action.busy}/></label><label className="cc-check"><input type="checkbox" required disabled={action.busy}/><span>{query.interest_access==='membership'?'I am available for the published dates and requested work type.':'I am available for these dates and consent to checking my current location for this requirement.'}</span></label><ContractError error={action.error}/>{action.message&&<p role="status" className="cc-success">{action.message}</p>}<button className="cc-primary" disabled={action.busy}>{action.busy?'Checking location & recording…':'Check location & express availability'}</button></form></section>;
}

function NearbyContractMessage({query}:{query:CustomContractQuery}){
  const action=useCustomContractAction(),[open,setOpen]=useState(false),[sent,setSent]=useState(false);
  const recipients=query.message_recipients||[],winner=query.message_recipient_id;
  if(!winner&&!recipients.length)return null;
  return <section className="cc-section"><h3>Ask the contractor about this work</h3><p className="cc-note">During your first 60 days, you can message an actual bidding contractor or the awarded contractor with open hiring after a fresh location check within 10 km. This does not apply for a job or accept an offer.</p>{!open?<button className="cc-primary" onClick={()=>setOpen(true)}>Message contractor</button>:<form className="cc-form" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{const current=await freshContractLocation();await messageNearbyContractor(query.id,winner||String(fields.get('recipient')),String(fields.get('text')),current);setSent(true);setOpen(false);},'Message sent to the contractor’s normal Repaidians conversation.');}}>{!winner&&<label>Actual bidding contractor<select aria-label="Actual bidding contractor" required name="recipient" disabled={action.busy}><option value="">Choose a contractor</option>{recipients.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label>}<label>Your question about the work<textarea name="text" required minLength={1} maxLength={2000} rows={3} disabled={action.busy}/></label><label className="cc-check"><input type="checkbox" required disabled={action.busy}/><span>I consent to checking my current location for this contractor conversation.</span></label><div className="cc-actions"><button type="button" disabled={action.busy} onClick={()=>setOpen(false)}>Cancel</button><button className="cc-primary" disabled={action.busy}>{action.busy?'Checking location & sending…':'Check location & send'}</button></div></form>}<ContractError error={action.error}/>{sent&&<p className="cc-success" role="status">{action.message||'Message sent. Replies appear in your Repaidians messages.'}</p>}</section>;
}
