import {useMemo,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,ReceiptText} from 'lucide-react';
import type {ContractRecords} from '../types/contractRecords';
import {contractCalendarEvents,contractDayKey,contractMonthDays,shiftContractMonth} from '../services/contractCalendar.mjs';
import {contractDate,contractMoney} from './customContractUI';
import './contract-calendar.css';
const dateLabel=(day:string)=>new Intl.DateTimeFormat('en-IN',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric'}).format(new Date(day+'T12:00:00Z'));
export default function ContractCalendar({record}:{record:ContractRecords}){
 const events=useMemo(()=>contractCalendarEvents(record),[record]),today=contractDayKey(Date.now()/1000);
 const [selected,setSelected]=useState(today),[month,setMonth]=useState(today.slice(0,7)),[filter,setFilter]=useState('all');
 const days=contractMonthDays(month),counts=new Map<string,number>();for(const entry of events)counts.set(entry.day,(counts.get(entry.day)||0)+1);
 const rows=events.filter(e=>e.day===selected&&(filter==='all'||e.kind===filter));
 const move=(delta:number)=>{const next=shiftContractMonth(month,delta);setMonth(next);setSelected(next+'-01');};
 return <section className="cc-detail cc-project-calendar" aria-label="Contract calendar"><header className="cc-between"><div><h4><CalendarDays size={16} aria-hidden="true"/>Your project, day by day</h4><p className="cc-note">Work, team check-ins, purchases and payments · India time</p></div><button onClick={()=>{setMonth(today.slice(0,7));setSelected(today);}}>Today</button></header><div className="cc-month"><button aria-label="Previous contract month" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><strong>{new Intl.DateTimeFormat('en-IN',{timeZone:'UTC',month:'long',year:'numeric'}).format(new Date(month+'-01T12:00:00Z'))}</strong><button aria-label="Next contract month" onClick={()=>move(1)}><ChevronRight size={18}/></button></div><div className="cc-month-grid">{['M','T','W','T','F','S','S'].map((label,i)=><span className="cc-weekday" key={i} aria-hidden="true">{label}</span>)}{days.map((day,i)=>day?<button key={day} aria-label={dateLabel(day)+(counts.has(day)?', '+counts.get(day)+' recorded entries':', no recorded entries')} aria-pressed={day===selected} aria-current={day===today?'date':undefined} onClick={()=>setSelected(day)}><span>{Number(day.slice(-2))}</span><span className="cc-day-dot" data-events={counts.has(day)} aria-hidden="true"/></button>:<span key={'blank'+i}/>)}</div><div className="cc-agenda"><h4>{dateLabel(selected)}</h4><div className="cc-day-filters" role="group" aria-label="Calendar entry type">{[['all','All'],['work','Work & team'],['purchase','Purchases'],['payment','Payments']].map(([key,label])=><button key={key} aria-pressed={key===filter} onClick={()=>setFilter(key)}>{label}</button>)}</div>{rows.length?<ol>{rows.map(entry=><li key={entry.id} data-kind={entry.kind}><span className="cc-event-icon" aria-hidden="true">{entry.kind==='work'?<CalendarDays size={16}/>:<ReceiptText size={16}/>}</span><div><strong>{entry.title}</strong><small>{contractDate(entry.at,true)}</small>{entry.detail&&<p>{entry.detail}</p>}{entry.amount!==null&&<b>{contractMoney(entry.amount)}</b>}</div></li>)}</ol>:<p className="cc-note">No {filter==='all'?'entries':filter==='work'?'work or team records':filter==='purchase'?'purchases':'payments'} recorded for this day.</p>}</div></section>;
}
