import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Building2,Users,BriefcaseBusiness,Gavel,Target,CalendarDays,Clock,CheckCircle2,ChevronRight,Plus,RefreshCw,MapPin,ShieldCheck,FileText,ArrowUpRight,Boxes,Handshake,Layers} from 'lucide-react';
import {operation} from '../services/operations';
import {Modal} from './ui';
import RepaidoBrand from './RepaidoBrand';
import './contract-work.css';
import {ContractorHiring} from './ContractorHiring';
import {BusinessSectorField} from './BusinessSectorField';
import {B2BMarketplace} from './B2BMarketplace';

type Row=Record<string,any>;
type Workspace={user_id:string;can_contract:boolean;profile:Row|null;projects:Row[];tenders:Row[]};
type Field={name:string;label:string;type?:string;min?:number|string;max?:number|string;options?:{value:string;label:string}[];value?:string|number;required?:boolean};
type Form={title:string;description?:string;fields:Field[];submit:(data:Row,request:string)=>Promise<unknown>;confirm?:string};
const money=(v:number|null|undefined)=>v==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2,minimumFractionDigits:0}).format(v/100);
const date=(v:number)=>new Date(v*1000).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
const local=(v:number)=>{const d=new Date(v*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const epoch=(v:string)=>new Date(v).getTime()/1000;
const accepted=(p:Row)=>p.team.filter((m:Row)=>m.status==='accepted');
const title=(s:string)=>s.replaceAll('_',' ');
const options=(rows:Row[],label='name')=>rows.map(r=>({value:r.id||r.worker_id,label:r[label]}));

function WorkForm({form,onClose,onSaved}:{form:Form;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRef(crypto.randomUUID());const last=useRef('');
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const encoded=JSON.stringify(data);if(last.current&&last.current!==encoded)key.current=crypto.randomUUID();last.current=encoded;setBusy(true);setError('');try{await form.submit(data,key.current);await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Modal title={form.title} onClose={()=>{if(!busy)onClose();}} className="contract-dialog"><form className="contract-form" onSubmit={submit}>{form.description&&<p>{form.description}</p>}{form.fields.map(f=><label key={f.name}>{f.label}{f.type==='sector'?<BusinessSectorField name={f.name} value={String(f.value||'')} required={f.required!==false}/>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value} required={f.required!==false} minLength={typeof f.min==='number'?f.min:undefined} maxLength={typeof f.max==='number'?f.max:6000} rows={3}/>:f.options?<select name={f.name} defaultValue={f.value??''} required={f.required!==false}><option value="">Choose…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input name={f.name} type={f.type||'text'} defaultValue={f.value} min={f.min} max={f.max} step={f.type==='number'?'0.01':undefined} required={f.required!==false} maxLength={f.type==='text'||!f.type?300:undefined}/>}</label>)}{form.confirm&&<label className="contract-consent"><input type="checkbox" required/>{form.confirm}</label>}{error&&<p className="ops-error" role="alert">{error}</p>}<button className="contract-primary" disabled={busy}>{busy?'Saving…':'Save & continue'}</button></form></Modal>;
}

export function ContractorPortal({onBackToCustomer,onPartnerProfile,accountControls,agent=false,onOpenB2BMarket}:{accountControls?:ReactNode;onBackToCustomer?:()=>void;onPartnerProfile?:()=>void;agent?:boolean;onOpenB2BMarket?:()=>void}){
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState(agent?'Projects':'Overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('deadline');
 const [projectId,setProjectId]=useState<string|null>(null),[tenderId,setTenderId]=useState<string|null>(null),[form,setForm]=useState<Form|null>(null),[agents,setAgents]=useState<Row[]>([]);
 const load=async(background=false)=>{const next=await operation<Workspace>('/contractor/workspace',{}, {background});setData(next);};
 useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>{if(!document.hidden)void load(true).catch(e=>setError(e.message));},45000);return()=>clearInterval(timer);},[]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const send=(path:string,body:Row)=>operation('/contractor'+path,{method:'POST',body:JSON.stringify(body)});
 const pc=(p:Row,action:string,extra:Row={})=>send(`/projects/${p.id}/commands`,{expected_version:p.version,action,...extra});
 const tc=(t:Row,action:string,extra:Row={})=>send(`/tenders/${t.id}/commands`,{expected_version:t.version,action,...extra});
 const uid=data?.user_id||'';const projects=data?.projects||[];const tenders=data?.tenders||[];const p=projects.find(p=>p.id===projectId);const t=tenders.find(t=>t.id===tenderId);
 const projectFields:Field[]=[{name:'title',label:'Project title'},{name:'scope',label:'Scope & deliverables',type:'textarea',min:10,max:4000},{name:'site',label:'Site address'},{name:'starts_at',label:'Work starts',type:'datetime-local'},{name:'ends_at',label:'Work ends',type:'datetime-local'},{name:'budget',label:'Planned budget (₹)',type:'number',min:0,max:500000000}];
 const createProject=(tender?:Row)=>setForm({title:tender?'Prepare tender team':'Create project',description:'Accepted agents reserve the full date range. Use precise shift dates to avoid blocking unrelated work.',fields:tender?[{name:'scope',label:'Your delivery plan',type:'textarea',min:10,max:4000,value:tender.scope}]:projectFields,submit:(v,request_id)=>send('/projects',tender?{request_id,title:tender.title,scope:v.scope,site:tender.site,starts_at:tender.starts_at,ends_at:tender.ends_at,budget_paise:tender.budget_paise,tender_id:tender.id}:{request_id,title:v.title,scope:v.scope,site:v.site,starts_at:epoch(v.starts_at),ends_at:epoch(v.ends_at),budget_paise:Math.round(Number(v.budget)*100)})});
 const createTender=()=>setForm({title:'Publish a tender',description:'Set the scope, work dates and bidding window. Registered contractors can prepare teams before bidding opens. Publishing does not collect fees or create escrow.',fields:[...projectFields,{name:'city',label:'City'},{name:'sector',label:'Business sector',type:'sector'},{name:'opens_at',label:'Bidding opens',type:'datetime-local'},{name:'deadline',label:'Bidding closes',type:'datetime-local'},{name:'manpower_needed',label:'Required agents',type:'number',min:1,max:500},{name:'terms',label:'Tender terms, eligibility & evaluation criteria',type:'textarea',min:20,max:6000}],confirm:'I am authorised to publish this tender and accept responsibility for its scope and terms.',submit:(v,request_id)=>send('/tenders',{request_id,title:v.title,scope:v.scope,site:v.site,starts_at:epoch(v.starts_at),ends_at:epoch(v.ends_at),budget_paise:Math.round(Number(v.budget)*100),city:v.city,sector:v.sector,opens_at:epoch(v.opens_at),deadline:epoch(v.deadline),manpower_needed:Number(v.manpower_needed),terms:v.terms})});
 const decision=(label:string,description:string,submit:()=>Promise<unknown>)=>setForm({title:label,description,fields:[],confirm:'I confirm this action.',submit});
 const invite=async(project:Row)=>{setBusy(true);setError('');try{const {agents:rows}=await operation<{agents:Row[]}>('/contractor/agents');setAgents(rows);setForm({title:'Invite a Repaido agent',description:`${date(project.starts_at)} — ${date(project.ends_at)}. The agent sees the role, reporting line, rate and terms before accepting.`,fields:[{name:'worker_id',label:'Registered agent',options:rows.filter(w=>!project.team.some((m:Row)=>m.worker_id===w.id&&['accepted','pending'].includes(m.status))).map(w=>({value:w.id,label:`${w.name} · ${w.city} · ${(w.skills||[]).join(', ')}`}))},{name:'role',label:'Project role',options:[{value:'member',label:'Team member'},{value:'supervisor',label:'Supervisor'}]},{name:'reports_to',label:'Reports to (blank = contractor)',required:false,options:accepted(project).filter((m:Row)=>m.role==='supervisor').map((m:Row)=>({value:m.worker_id,label:m.name}))},{name:'daily_rate',label:'Agreed daily rate (₹)',type:'number',min:0,max:100000},{name:'terms',label:'Duties, hours, compensation & joining terms',type:'textarea',min:20,max:2000}],confirm:'This is an invitation, not an automatic assignment or payment.',submit:v=>send(`/projects/${project.id}/invitations`,{expected_version:project.version,worker_id:v.worker_id,role:v.role,reports_to:v.reports_to||null,daily_rate_paise:Math.round(Number(v.daily_rate)*100),terms:v.terms})});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const goal=(project:Row)=>setForm({title:'Add milestone / goal',fields:[{name:'title',label:'Outcome / milestone'},{name:'note',label:'Acceptance criteria',type:'textarea',max:2000},{name:'assignee_id',label:'Responsible agent',required:false,options:accepted(project).map((m:Row)=>({value:m.worker_id,label:m.name}))},{name:'due_at',label:'Due date',type:'datetime-local',min:local(project.starts_at),max:local(project.ends_at)}],submit:v=>pc(project,'goal_add',{title:v.title,note:v.note,assignee_id:v.assignee_id||null,due_at:epoch(v.due_at)})});
 const bid=(tender:Row)=>setForm({title:'Submit / revise bid',description:'A revision replaces your earlier pending bid. Required agents must have accepted the team plan. No tender fee is collected.',fields:[{name:'project_id',label:'Accepted team plan',options:projects.filter(p=>p.owner_id===uid&&p.tender_id===tender.id&&p.status==='planning').map(p=>({value:p.id,label:`${p.title} · ${accepted(p).length}/${tender.manpower_needed} accepted`}))},{name:'amount',label:'Total quote (₹)',type:'number',min:1,max:500000000},{name:'proposal',label:'Proposal, inclusions, exclusions & delivery approach',type:'textarea',min:20,max:6000}],confirm:'I have read and accept the tender terms shown in its details.',submit:(v,request_id)=>send(`/tenders/${tender.id}/bid`,{request_id,expected_version:tender.version,project_id:v.project_id,amount_paise:Math.round(Number(v.amount)*100),proposal:v.proposal,accepted_terms:true})});
 const name=(project:Row,id:string)=>id===project.owner_id?project.owner_name:project.team.find((m:Row)=>m.worker_id===id)?.name||'Unassigned';
 const own=p?.owner_id===uid;const me=p?.team.find((m:Row)=>m.worker_id===uid&&m.status==='accepted');const manage=own||me?.role==='supervisor';const closed=p&&['completed','cancelled'].includes(p.status);
 const filtered=tenders.filter(t=>(filter==='all'||(filter==='mine'?t.owner_id===uid:filter==='registered'?t.registered:filter==='upcoming'?t.status==='open'&&t.opens_at>Date.now()/1000:t.status===filter))&&`${t.title} ${t.city} ${t.sector}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='budget'?a.budget_paise-b.budget_paise:sort==='newest'?b.created_at-a.created_at:a.deadline-b.deadline);
 return <section className="contract-desk" aria-label={agent?'Project teams':'Contractor workspace'}>
  <header className="contract-heading"><div><span className="contract-kicker"><Building2 size={16}/> REPAIDO WORKSPACE</span><h1>{agent?'Your project teams':'Contracts, teams & tenders'}</h1><p>{agent?'Review invitations, record attendance and deliver your goals.':'Plan the work. Build the team. Track every decision.'}</p></div><button aria-label="Refresh workspace" disabled={busy} onClick={()=>void run(load)}><RefreshCw size={19}/></button></header>
  {error&&<p className="ops-error" role="alert">{error}<button onClick={()=>void run(load)}>Retry</button></p>}
  {!data?<p role="status">Loading your workspace…</p>:<>
  {!agent&&!data.can_contract&&<div className="contract-note"><ShieldCheck size={20}/><div><strong>Contractor approval required</strong><p>You can browse opportunities and publish your own tender. Project creation and bidding unlock after contractor review.</p>{onPartnerProfile&&<button onClick={onPartnerProfile}>Complete partner profile <ArrowUpRight size={16}/></button>}</div></div>}
  {!agent&&<nav className="contract-tabs" aria-label="Contractor sections">{['Overview','Tenders','Projects','B2B Raw Materials','Hiring','Team & HR','Business profile'].map(label=><button key={label} aria-pressed={tab===label} onClick={()=>{setTab(label);setFilter('all');}}>{label}</button>)}</nav>}
  {(tab==='Overview')&&<><div className="contract-metrics">{[[BriefcaseBusiness,projects.filter(p=>p.owner_id===uid&&!['completed','cancelled'].includes(p.status)).length,'Open projects'],[Users,projects.reduce((n,p)=>n+accepted(p).length,0),'Team placements'],[Gavel,tenders.filter(t=>t.bids.some((b:Row)=>b.contractor_id===uid&&b.status==='submitted')).length,'Pending bids'],[Target,projects.reduce((n,p)=>n+p.goals.filter((g:Row)=>g.status!=='approved').length,0),'Open goals']].map(([Icon,count,label]:any)=><div key={label}><Icon size={20}/><strong>{count}</strong><span>{label}</span></div>)}</div><div className="contract-actions"><button onClick={()=>setTab('Tenders')}><Gavel size={18}/> Explore tenders</button><button disabled={!data.can_contract} onClick={()=>createProject()}><Plus size={18}/> New project</button><button onClick={createTender}><Plus size={18}/> Publish tender</button></div><button className="contract-hiring-entry b2b-contractor-entry" onClick={()=>setTab('B2B Raw Materials')}><Boxes size={18}/><span><strong>Procure B2B Raw Materials &amp; Spares</strong><small>Wholesale cables, copper, conduits, power tools &amp; refurbished gear for tenders</small></span><ChevronRight size={17}/></button><button className="contract-hiring-entry" onClick={()=>setTab('Hiring')}><Users size={18}/><span><strong>Hire for your projects</strong><small>Publish roles · review requests · send offers</small></span><ChevronRight size={17}/></button><h2>Next deadlines</h2>{projects.flatMap(p=>p.goals.filter((g:Row)=>g.status!=='approved').map((g:Row)=>({...g,project:p}))).sort((a,b)=>a.due_at-b.due_at).slice(0,5).map(g=><button className="contract-deadline" key={g.id} onClick={()=>setProjectId(g.project.id)}><Target size={18}/><span><strong>{g.title}</strong><small>{g.project.title} · {date(g.due_at)}</small></span><ChevronRight size={18}/></button>)}{!projects.some(p=>p.goals.length>0)&&<p className="contract-empty">Your project milestones and due dates will appear here.</p>}</>}
  {tab==='Tenders'&&<><div className="contract-toolbar"><input aria-label="Search tenders" placeholder="Search title, city or trade" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Tender status" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','upcoming','open','registered','mine','awarded','closed'].map(v=><option key={v} value={v}>{title(v)}</option>)}</select><select aria-label="Sort tenders" value={sort} onChange={e=>setSort(e.target.value)}><option value="deadline">Deadline first</option><option value="budget">Budget: low first</option><option value="newest">Newest</option></select><button onClick={createTender}><Plus size={17}/> Publish</button></div><div className="contract-grid">{filtered.map(t=><article className="contract-card" key={t.id}><span className="contract-chip">{t.status==='open'?(Date.now()/1000<t.opens_at?'Upcoming':Date.now()/1000>=t.deadline?'Awaiting decision':'Bidding open'):title(t.status)}</span><h2>{t.title}</h2><p><MapPin size={15}/>{t.city} · {t.sector}</p><strong>{money(t.budget_paise)} budget</strong><div className="contract-facts"><span><Users size={15}/>{t.manpower_needed} agents</span><span><Gavel size={15}/>{t.bids_count} bids</span></div><small>Closes {date(t.deadline)}</small><button onClick={()=>setTenderId(t.id)}>Scope, teams & bids <ChevronRight size={17}/></button></article>)}</div>{!filtered.length&&<p className="contract-empty">No tenders match these filters. New published opportunities will appear here.</p>}</>}
  {(tab==='Projects'||tab==='Team & HR')&&<><div className="contract-actions">{!agent&&<button disabled={!data.can_contract} onClick={()=>createProject()}><Plus size={17}/> Create project</button>}<select aria-label="Project status" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','planning','active','paused','completed','cancelled'].map(v=><option key={v}>{v}</option>)}</select></div><div className="contract-grid">{projects.filter(p=>filter==='all'||p.status===filter).map(p=>{const pending=p.team.some((m:Row)=>m.worker_id===uid&&m.status==='pending');const done=p.goals.filter((g:Row)=>g.status==='approved').length;return <article key={p.id} className="contract-card"><span className="contract-chip">{pending?'Invitation pending':title(p.status)}</span><h2>{p.title}</h2><p>{p.owner_name}</p><p><CalendarDays size={15}/>{date(p.starts_at)} — {date(p.ends_at)}</p><div className="contract-facts"><span><Users size={15}/>{accepted(p).length} accepted</span><span><Target size={15}/>{done}/{p.goals.length} goals</span></div><progress aria-label="Approved goals" value={done} max={p.goals.length||1}/><button onClick={()=>setProjectId(p.id)}>{pending?'Review joining terms':'Open project workspace'} <ChevronRight size={17}/></button></article>;})}</div>{!projects.length&&<p className="contract-empty">{agent?'Invitations will appear here when a contractor invites your registered profile.':'Create a project or prepare a team for a tender to start.'}</p>}</>}
  {tab==='B2B Raw Materials'&&<div className="contractor-b2b-workbench">
    <div className="contractor-b2b-header-card">
      <div className="contractor-b2b-header-text">
        <span className="contract-chip"><Boxes size={14}/> CONTRACTOR PROCUREMENT WORKBENCH</span>
        <h2>Wholesale Raw Materials, Equipment &amp; Tender Supply</h2>
        <p>Fulfill your contracts without hassle: Purchase bulk raw materials directly from verified distributors for your tenders, or take supply responsibility for active contracts.</p>
      </div>
      <div className="contractor-b2b-actions">
        <button type="button" className="contract-primary" onClick={()=>alert('Raw Material Supply Responsibility Desk: Registered contractors can take full supply responsibility for raw materials across municipal, commercial & infrastructure tenders.')}><Handshake size={16}/> Take Supply Tender Responsibility</button>
      </div>
    </div>
    <div className="contractor-market-switcher" role="tablist" aria-label="Procurement channels">
      <span className="contractor-market-pill active"><Boxes size={14}/> B2B Wholesale Market (Bulk Lots &amp; RFQs)</span>
      {onBackToCustomer&&<button type="button" className="contractor-market-pill" onClick={onBackToCustomer} title="Browse customer-centric markets for Refurbished, Old/Used, and Retail Spares"><Layers size={14}/> Refurbished, Used &amp; New Markets <ArrowUpRight size={13}/></button>}
    </div>
    <B2BMarketplace contractorMode customerUser={{name:data.profile?.name||'Contractor Enterprise',phone:'',email:''}} onSwitchToTenders={()=>setTab('Tenders')}/>
  </div>}
  {tab==='Hiring'&&data&&(data.can_contract?<ContractorHiring projects={projects} uid={uid} onRefresh={load} onProject={setProjectId} onCreate={()=>createProject()}/>:<p className="contract-empty">Contractor approval is required to publish project roles and manage applicants. Complete your partner profile to continue.</p>)}
  {tab==='Business profile'&&accountControls}
  {tab==='Business profile'&&<article className="contract-card"><RepaidoBrand size="sm"/><h2>{data.profile?.name||'Your business profile'}</h2><p>{data.profile?.city||'Add your service city'}</p>{data.profile?.sector&&<span className="contract-chip">{data.profile.sector}</span>}<p>{data.profile?.scope||'Describe the work your business can deliver.'}</p><span className="contract-chip">{data.can_contract?'Contractor approved':'Contractor approval pending'}</span><button onClick={()=>setForm({title:'Business details',fields:[{name:'name',label:'Business name',value:data.profile?.name},{name:'city',label:'City',value:data.profile?.city},{name:'sector',label:'Business sector',type:'sector',value:data.profile?.sector},{name:'scope',label:'Capabilities & service scope',type:'textarea',min:10,max:2000,value:data.profile?.scope}],submit:v=>operation('/contractor/profile',{method:'PUT',body:JSON.stringify(v)})})}>Edit business details</button>{onPartnerProfile&&<button onClick={onPartnerProfile}>Partner agreements & verification</button>}</article>}
  </>}
  {p&&<Modal title={p.title} className="contract-dialog" onClose={()=>setProjectId(null)}><div className="contract-detail">
   <div className="contract-facts"><span className="contract-chip">{title(p.status)}</span><span><Users size={16}/>{accepted(p).length} team</span><span><Target size={16}/>{p.goals.filter((g:Row)=>g.status==='approved').length}/{p.goals.length} approved</span></div>
   <details open><summary><FileText size={17}/> Contract & work plan</summary><p>{p.scope}</p><dl><dt>Site</dt><dd>{p.site}</dd><dt>Starts</dt><dd>{date(p.starts_at)}</dd><dt>Ends</dt><dd>{date(p.ends_at)}</dd><dt>Contractor</dt><dd>{p.owner_name}</dd>{own&&<><dt>{p.contract_value_paise?'Awarded value':'Planned budget'}</dt><dd>{money(p.contract_value_paise??p.budget_paise)}</dd><dt>Daily team cost</dt><dd>{money(accepted(p).reduce((n:number,m:Row)=>n+m.daily_rate_paise,0))} · agreed rates</dd></>}</dl>{p.tender_id&&!p.awarded_at&&<p className="contract-note">Tender preparation only. An accepted team does not mean the contract has been awarded.</p>}</details>
   {p.team.filter((m:Row)=>m.worker_id===uid&&m.status==='pending').map((m:Row)=><article className="contract-invitation" key={m.id}><h3>Welcome to the project team</h3><dl><dt>Role</dt><dd>{m.role}</dd><dt>Reports to</dt><dd>{m.reports_to?name(p,m.reports_to):p.owner_name}</dd><dt>Daily rate</dt><dd>{money(m.daily_rate_paise)}</dd></dl><p>{m.terms}</p><p>Acceptance reserves these work dates and records your agreement to the joining terms.</p><div className="contract-actions"><button disabled={busy||closed} onClick={()=>decision('Accept team invitation',`${p.title} · ${date(p.starts_at)} — ${date(p.ends_at)} · ${money(m.daily_rate_paise)}/day. ${m.terms}`,()=>pc(p,'accept',{target_id:m.id}))}>Accept & join</button><button disabled={busy||closed} onClick={()=>void run(()=>pc(p,'decline',{target_id:m.id}))}>Decline</button></div></article>)}
   <details open><summary><Users size={17}/> Team & reporting lines <span>{p.team.length}</span></summary>{own&&!closed&&<button disabled={busy} onClick={()=>void invite(p)}><Plus size={16}/> Invite agent</button>}{p.team.length===0&&<p>No invitations yet.</p>}{p.team.map((m:Row)=><div className="contract-member" key={m.id}><span className="contract-avatar"><Users size={19}/></span><div><strong>{m.name}</strong><small>{m.role} · {m.status}</small><small>Reports to {m.reports_to?name(p,m.reports_to):p.owner_name}</small>{m.daily_rate_paise!=null&&<small>{money(m.daily_rate_paise)}/day</small>}{m.terms&&<details><summary>Joining terms</summary><p>{m.terms}</p></details>}</div>{own&&!closed&&['accepted','pending'].includes(m.status)&&<button onClick={()=>decision('Remove team member',`Remove ${m.name} from this project? Reports will return to the contractor.`,()=>pc(p,'remove',{target_id:m.worker_id}))}>Remove</button>}</div>)}</details>
   {(own||me)&&<><details open><summary><Target size={17}/> Goals & milestones</summary>{manage&&!closed&&<button onClick={()=>goal(p)}><Plus size={16}/> Add goal</button>}{p.goals.length===0&&<p>No goals yet. Add clear outcomes and an owner.</p>}{p.goals.map((g:Row)=><article className="contract-goal" key={g.id}><strong>{g.title}</strong><span className="contract-chip">{title(g.status)}</span><small>{name(p,g.assignee_id)} · {date(g.due_at)}</small><p>{g.note}</p>{g.evidence&&<details><summary>Submitted evidence</summary><p>{g.evidence}</p></details>}<div className="contract-actions">{!closed&&(manage||g.assignee_id===uid)&&['planned','reopened'].includes(g.status)&&<button onClick={()=>setForm({title:'Submit goal for review',fields:[{name:'note',label:'Work completed & evidence reference',type:'textarea',min:10,max:2000}],submit:v=>pc(p,'goal_submit',{target_id:g.id,note:v.note})})}>Submit progress</button>}{!closed&&own&&g.status==='submitted'&&<button onClick={()=>decision('Approve milestone',g.title,()=>pc(p,'goal_approve',{target_id:g.id}))}>Approve</button>}{!closed&&own&&['submitted','approved'].includes(g.status)&&<button onClick={()=>setForm({title:'Request changes',fields:[{name:'note',label:'Changes required',type:'textarea',min:5,max:2000}],submit:v=>pc(p,'goal_reopen',{target_id:g.id,note:v.note})})}>Reopen</button>}</div></article>)}</details>
   <details><summary><Clock size={17}/> Attendance & time records</summary><p>Self-reported check-ins use server time. They are not GPS verification or payroll approval.</p>{me&&!closed&&<div className="contract-actions"><button disabled={busy} onClick={()=>void run(()=>pc(p,'check_in'))}>Check in</button><button disabled={busy} onClick={()=>void run(()=>pc(p,'check_out'))}>Check out</button></div>}<div className="contract-table"><table><caption>Recorded project attendance</caption><thead><tr><th>Agent</th><th>In</th><th>Out</th><th>Hours</th></tr></thead><tbody>{p.attendance.map((a:Row)=><tr key={a.id}><td>{name(p,a.worker_id)}</td><td>{date(a.in_at)}</td><td>{a.out_at?date(a.out_at):'Open'}</td><td>{a.out_at?((a.out_at-a.in_at)/3600).toFixed(2):'—'}</td></tr>)}</tbody></table></div></details>
   <details><summary><CalendarDays size={17}/> Leave & availability</summary>{me&&!closed&&<button onClick={()=>setForm({title:'Request project leave',fields:[{name:'starts_at',label:'From',type:'datetime-local',min:local(p.starts_at),max:local(p.ends_at)},{name:'ends_at',label:'Until',type:'datetime-local',min:local(p.starts_at),max:local(p.ends_at)},{name:'note',label:'Reason',type:'textarea',min:5,max:2000}],submit:v=>pc(p,'leave_request',{starts_at:epoch(v.starts_at),ends_at:epoch(v.ends_at),note:v.note})})}>Request leave</button>}{!p.leave.length&&<p>No leave requests.</p>}{p.leave.map((l:Row)=><article className="contract-goal" key={l.id}><strong>{name(p,l.worker_id)} · {l.status}</strong><small>{date(l.starts_at)} — {date(l.ends_at)}</small><p>{l.note}</p>{own&&!closed&&l.status==='pending'&&<div className="contract-actions"><button disabled={busy} onClick={()=>void run(()=>pc(p,'leave_approve',{target_id:l.id}))}>Approve leave</button><button disabled={busy} onClick={()=>void run(()=>pc(p,'leave_decline',{target_id:l.id}))}>Decline</button></div>}</article>)}</details>
   <details><summary><FileText size={17}/> Activity & decision history</summary><ol className="contract-timeline">{p.events.slice().reverse().map((e:Row)=><li key={e.id}><strong>{title(e.action)}</strong><small>{date(e.at)} · {name(p,e.actor)}</small>{e.note&&<p>{e.note}</p>}</li>)}</ol>{!p.events.length&&<p>No changes recorded yet.</p>}</details>
   {!closed&&<div className="contract-actions">{own&&<>{p.status==='planning'&&<button onClick={()=>decision('Start project','Work dates and any tender award will be checked.',()=>pc(p,'start'))}>Start work</button>}{p.status==='active'&&<><button onClick={()=>decision('Pause project','Open attendance sessions will close at the pause time.',()=>pc(p,'pause'))}>Pause</button><button onClick={()=>decision('Complete project','All goals must be approved. This closes the operational project; it does not settle payments.',()=>pc(p,'complete'))}>Complete</button></>}{p.status==='paused'&&<button disabled={busy} onClick={()=>void run(()=>pc(p,'resume'))}>Resume</button>}<button className="contract-danger" onClick={()=>decision('Cancel project','This releases the team reservation and preserves the project history.',()=>pc(p,'cancel'))}>Cancel project</button></>}{me&&<button className="contract-danger" onClick={()=>decision('Leave project team','Your contractor will retain the work and attendance history.',()=>pc(p,'leave_team'))}>Leave team</button>}</div>}</>}
   {error&&<p className="ops-error" role="alert">{error}</p>}
  </div></Modal>}
  {t&&<Modal title={t.title} className="contract-dialog" onClose={()=>setTenderId(null)}><div className="contract-detail"><span className="contract-chip">{title(t.status)}</span><details open><summary><FileText size={17}/> Scope & tender terms</summary><p>{t.scope}</p><p>{t.terms}</p><dl><dt>Owner</dt><dd>{t.owner_name}</dd><dt>Budget</dt><dd>{money(t.budget_paise)}</dd><dt>Site</dt><dd>{t.site}</dd><dt>Bidding opens</dt><dd>{date(t.opens_at)}</dd><dt>Bidding closes</dt><dd>{date(t.deadline)}</dd><dt>Work dates</dt><dd>{date(t.starts_at)} — {date(t.ends_at)}</dd><dt>Required crew</dt><dd>{t.manpower_needed} accepted agents</dd></dl></details><div className="contract-actions">{t.owner_id!==uid&&data?.can_contract&&t.status==='open'&&<><button disabled={busy} onClick={()=>void run(()=>tc(t,t.registered?'unregister':'register'))}>{t.registered?'Withdraw registration':'Register interest'}</button><button onClick={()=>createProject(t)}>Prepare team</button><button disabled={Date.now()/1000<t.opens_at||Date.now()/1000>=t.deadline} onClick={()=>bid(t)}>Submit / revise bid</button><button onClick={()=>{setTenderId(null);setTab('B2B Raw Materials');}}><Boxes size={15}/> Source raw materials for tender</button></>}{t.owner_id===uid&&t.status==='open'&&<button onClick={()=>decision('Close tender','Close bidding without awarding a contract.',()=>tc(t,'close'))}>Close tender</button>}</div><details open><summary><Gavel size={17}/>{t.owner_id===uid?'Compare bids & decide':'Your bids'}</summary><p>Compare the quoted scope, amount and accepted crew. No automated suitability score or payment is implied.</p><div className="contract-table"><table><caption>{t.owner_id===uid?'Submitted proposals':'Your proposal history'}</caption><thead><tr><th>Contractor</th><th>Quote</th><th>Crew</th><th>Status</th><th>Decision</th></tr></thead><tbody>{t.bids.map((b:Row)=><tr key={b.id}><td>{b.contractor_name}<details><summary>Proposal</summary><p>{b.proposal}</p></details></td><td>{money(b.amount_paise)}</td><td>{b.team_size}</td><td>{b.status}</td><td>{b.status==='submitted'&&t.status==='open'&&(t.owner_id===uid?<button disabled={Date.now()/1000<t.deadline} onClick={()=>decision('Award contract',`Award ${t.title} to ${b.contractor_name} for ${money(b.amount_paise)}? Team capacity is checked again.`,()=>tc(t,'award',{bid_id:b.id}))}>Award</button>:<button disabled={busy} onClick={()=>void run(()=>tc(t,'withdraw',{bid_id:b.id}))}>Withdraw</button>)}</td></tr>)}</tbody></table></div>{!t.bids.length&&<p>No bids available to your account.</p>}</details>{error&&<p className="ops-error" role="alert">{error}</p>}</div></Modal>}
  {form&&<WorkForm form={form} onClose={()=>setForm(null)} onSaved={load}/>}
 </section>;
}
export function AgentProjectDesk(){const [open,setOpen]=useState(new URLSearchParams(location.search).get('tab')==='projects'),[count,setCount]=useState(0);useEffect(()=>{let live=true;const refresh=()=>operation<Workspace>('/contractor/workspace',{}, {background:true}).then(d=>{if(live)setCount(d.projects.reduce((n,p)=>n+p.team.filter((m:Row)=>m.worker_id===d.user_id&&m.status==='pending').length,0));}).catch(()=>{});void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},60000);return()=>{live=false;clearInterval(timer);};},[open]);return <section className="agent-project-entry"><button onClick={()=>setOpen(true)}><Users size={22}/><span><strong>Project teams & invitations</strong><small>{count?`${count} pending invitation${count===1?'':'s'}`:'Your crews, goals, attendance & leave'}</small></span><ChevronRight size={20}/></button>{open&&<Modal title="Project teams" className="contract-dialog" onClose={()=>setOpen(false)}><ContractorPortal agent/></Modal>}</section>;}
export default ContractorPortal;
