import {useEffect,useRef,useState} from 'react';
import {Bell,BellOff,Settings2,Sparkles,ChevronRight,CalendarDays} from 'lucide-react';
import {auth} from '../firebase';
import {contractDiscovery,workPreferences,updateWorkPreferences,watchContract,workCachedRead,subscribeWorkReads} from '../services/repaidiansWorkService';
import type {WorkPreferences} from '../types/repaidiansWork';
import {Modal} from './ui';
import {InlineNotice} from './BusinessUI';
const identity=()=>auth.currentUser?.uid||localStorage.getItem('repaido.token')||'guest';
type ContractSummary={id:string;title:string;city:string;sector:string;deadline:number;watched:boolean;match?:{reasons:string[]}};
type Page={items:ContractSummary[];personalized:boolean;preferences:WorkPreferences};
function PreferencesForm({preferences,onClose,onSaved}:{preferences:WorkPreferences;onClose:()=>void;onSaved:(preferences:WorkPreferences)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Modal title="Opportunity preferences" className="contract-dialog contract-preferences" onClose={()=>{if(!busy)onClose();}}><form className="contract-form" onSubmit={event=>{event.preventDefault();if(busy)return;const values=new FormData(event.currentTarget);setBusy(true);setError('');void updateWorkPreferences({personalizedDiscovery:values.has('personalizedDiscovery'),contractUpdates:values.has('contractUpdates')}).then(result=>{onSaved(result.preferences);onClose();}).catch(error=>setError(error.message)).finally(()=>setBusy(false));}}><label className="contract-consent"><input type="checkbox" name="personalizedDiscovery" defaultChecked={preferences.personalizedDiscovery}/><span><strong>Relevant opportunities</strong><small>Use my Repaidians trade searches and interactions to suggest relevant contracts. I can turn this off any time.</small></span></label><label className="contract-consent"><input type="checkbox" name="contractUpdates" defaultChecked={preferences.contractUpdates}/><span><strong>Daily contract updates</strong><small>Notify me about watched contracts and relevant actual milestones or deadlines. At most three distinct contracts a day.</small></span></label>{error&&<InlineNotice tone="error">{error}</InlineNotice>}<p className="contract-fineprint">Updates appear in notifications. Device push also needs notification permission and a registered device.</p><button className="contract-primary" disabled={busy}>{busy?'Saving…':'Save preferences'}</button></form></Modal>;
}
export function ContractRecommendations({sector,query,onOpen}:{sector:string;query:string;onOpen:(id:string)=>void}){
 const account=identity(),[data,setData]=useState<Page|null>(null),[error,setError]=useState(''),[settings,setSettings]=useState(false),[revision,setRevision]=useState(0);
 const generation=useRef(0);
 useEffect(()=>subscribeWorkReads(()=>setRevision(value=>value+1)),[]);
 useEffect(()=>{const seq=++generation.current,controller=new AbortController();setError('');void contractDiscovery<Page>(account,{query:query||sector,limit:3},false,controller.signal).then(result=>{if(seq===generation.current&&account===identity())setData(result);}).catch(error=>{if(!controller.signal.aborted&&seq===generation.current)setError(error.message);});return()=>{generation.current++;controller.abort();};},[account,sector,query,revision]);
 if(!data)return error?<details className="contract-recommendations-error"><summary>Opportunity preferences unavailable</summary><p>{error}</p><button onClick={()=>setRevision(value=>value+1)}>Retry</button></details>:null;
 if(!data.personalized)return <div className="contract-recommendations-options"><button onClick={()=>setSettings(true)}><Settings2 size={15}/>Opportunity settings</button><small>Suggestions & daily updates</small>{settings&&<PreferencesForm preferences={data.preferences} onClose={()=>setSettings(false)} onSaved={()=>setRevision(value=>value+1)}/>}</div>;
 return <section className="contract-recommendations" aria-label="Your opportunity suggestions"><div className="tender-section-heading"><h2><Sparkles size={15}/>{data.personalized?'For your work interests':'Opportunity preferences'}</h2><button onClick={()=>setSettings(true)} aria-label="Manage opportunity preferences"><Settings2 size={16}/></button></div>{data.personalized&&data.items.length>0&&<div className="contract-recommendation-list">{data.items.map(item=><button className="contract-recommendation" key={item.id} onClick={()=>onOpen(item.id)}><span><strong>{item.title}</strong><small>{item.city} · {item.sector}</small>{(item.match?.reasons?.length||0)>0&&<small>{item.match?.reasons.slice(0,2).join(' · ')}</small>}</span><ChevronRight size={16}/></button>)}</div>}{!data.personalized&&<p>Choose whether your searches shape your suggestions and daily updates.</p>}{data.personalized&&!data.items.length&&<p>No relevant published contracts are available for this search yet.</p>}{settings&&<PreferencesForm preferences={data.preferences} onClose={()=>setSettings(false)} onSaved={()=>setRevision(value=>value+1)}/>}</section>;
}
export function ContractWatch({tenderId}:{tenderId:string}){
 const account=identity(),[preferences,setPreferences]=useState<WorkPreferences|null>(null),[watched,setWatched]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[revision,setRevision]=useState(0);
 const generation=useRef(0),gate=useRef(false);
 useEffect(()=>subscribeWorkReads(()=>setRevision(value=>value+1)),[]);
 useEffect(()=>{const seq=++generation.current,controller=new AbortController();setError('');void Promise.all([workPreferences(account,false,controller.signal),workCachedRead<{watched:boolean}>(account,'/work/contracts/'+encodeURIComponent(tenderId)+'/watch',false,controller.signal)]).then(([prefs,watch])=>{if(seq===generation.current&&account===identity()){setPreferences(prefs.preferences);setWatched(watch.watched);}}).catch(error=>{if(!controller.signal.aborted&&seq===generation.current)setError(error.message);});return()=>{generation.current++;controller.abort();};},[account,tenderId,revision]);
 const toggle=async()=>{if(gate.current||!preferences)return;if(!preferences.contractUpdates&&!watched){setSettings(true);return;}gate.current=true;setBusy(true);setError('');try{await watchContract(tenderId,!watched);if(account===identity())setWatched(previous=>!previous);}catch(error){if(account===identity())setError((error as Error).message);}finally{gate.current=false;setBusy(false);}};
 return <div className="contract-watch"><div><CalendarDays size={16}/><span><strong>Stay with this contract</strong><small>Important dates and actual project updates. Up to three contracts a day.</small></span></div><button disabled={busy||!preferences} aria-pressed={watched} onClick={()=>void toggle()}>{watched?<BellOff size={16}/>:<Bell size={16}/>} {busy?'Saving…':watched?'Watching · stop':'Watch contract'}</button>{error&&<InlineNotice tone="error" action={<button onClick={()=>setRevision(value=>value+1)}>Retry</button>}>{error}</InlineNotice>}{settings&&preferences&&<PreferencesForm preferences={preferences} onClose={()=>setSettings(false)} onSaved={preferences=>{setPreferences(preferences);setRevision(value=>value+1);if(preferences.contractUpdates){gate.current=true;setBusy(true);void watchContract(tenderId,true).then(()=>{if(account===identity())setWatched(true);}).catch(error=>setError(error.message)).finally(()=>{gate.current=false;setBusy(false);});}}}/>}</div>;
}
