import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CalendarDays,Download,FileCheck2,ImagePlus,LockKeyhole,Users} from 'lucide-react';
import type {ContractBankInstructions,ContractEvidence,ContractPayment,ContractProgress,ContractPurchase,ContractRecords} from '../types/contractRecords';
import {approveContractPayment,checkContractPayment,contractBankInstructions,contractRecords,createContractPaymentOrder,reportContractProgress,reportContractTransfer,requestContractPayment,reviewContractProgress,shareContractProgress,recordContractPurchase,reviewContractPurchase} from '../services/contractRecordsService';
import {downloadContractReport,privateContractBlob,rupeesToPaise,uploadContractEvidence} from '../services/customContractsService';
import {ContractError,ContractRefresh,contractDate,contractMoney,contractStatus,useCustomContractAction,useCustomContractResource} from './customContractUI';
import ContractCalendar from './ContractCalendar';
import './custom-contracts.css';
import './contract-refinement.css';
import {loadCheckout} from './PaymentPanel';

export function ContractRecordsPanel({projectId,accountKey,mode}:{projectId:string;accountKey:string;mode:'customer'|'contractor'|'agent'}){
  const [reportKind,setReportKind]=useState('summary');
  const resource=useCustomContractResource<ContractRecords>(accountKey+':records:'+projectId,(force,signal)=>contractRecords(projectId,force,signal),mode!=='agent','/contracts/projects/'+encodeURIComponent(projectId)+'/records'),action=useCustomContractAction(),record=resource.data;
  if(mode==='agent')return <p className="cc-note">Customer contract payment and progress records are private to the customer and awarded contractor. Your accepted placement stays in Apply Status.</p>;
  const refresh=()=>resource.refresh();
  return <section className="cc-section" aria-label="Awarded contract records">
    <header className="cc-between"><div><span className="cc-eyebrow">Every commitment, recorded</span><h3>Project progress & payments</h3></div><ContractRefresh busy={resource.busy} label="Refresh project records" onRefresh={()=>void refresh()}/></header>
    <ContractError error={resource.error} onRetry={()=>void refresh()}/>{resource.busy&&!record&&<p role="status" className="cc-note">Opening private project records…</p>}
    {record&&<>
      <div className="cc-facts"><span><CalendarDays size={16} aria-hidden="true"/>{contractDate(record.project.starts_at)} – {contractDate(record.project.ends_at)}</span><span>{contractStatus(record.project.status)}</span></div>
      <dl className="cc-financials">{[['Agreed contract price',record.financials.agreed_deal_paise],['Confirmed net payments',record.financials.confirmed_paid_paise],['Awaiting payment or verification',record.financials.pending_reserved_paise],['Balance after confirmed payments',record.financials.balance_paise],['Collected by the platform gateway',record.financials.gateway_collected_paise],['Verified received by contractor',record.financials.contractor_received_paise]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{contractMoney(Number(value))}</dd></div>)}</dl>
      <p className="cc-note">Pending requests and reported transfers are excluded from confirmed payments. Gateway collection and contractor receipt are recorded separately.</p>
      <section className="cc-detail"><h4><Users size={16} aria-hidden="true"/>Accepted project team</h4>{record.team?.length?<ul>{record.team.map(member=><li key={member.worker_id}><strong>{member.name||'Accepted team member'}</strong> · {(member.worker_type||member.role).replaceAll('_',' ')}</li>)}</ul>:<p className="cc-note">No accepted team members are recorded yet.</p>}</section>
      <ContractCalendar record={record}/>
      <ContractPurchases record={record} accountKey={accountKey} onSaved={refresh}/>
      <ContractProgressHistory entries={record.progress}/>{record.actions.can_progress&&<ProgressForm record={record} onSaved={refresh}/>}
      <div className="cc-list">{record.progress.map(entry=><ProgressRecord key={entry.id} record={record} entry={entry} accountKey={accountKey} onChanged={refresh}/>)}</div>
      {record.actions.can_manage_public_progress&&<PublicProgressControl record={record} onChanged={refresh}/>}
      <section className="cc-detail"><h4>Payment requests & confirmations</h4>{record.payments.length?<div className="cc-list">{record.payments.map(payment=><PaymentRecord key={payment.id} record={record} payment={payment} accountKey={accountKey} onChanged={refresh}/>)}</div>:<p className="cc-note">No payment requests are recorded.</p>}</section>
      {record.actions.can_request&&<PaymentRequestForm record={record} onSaved={refresh}/>}
      <details className="cc-section"><summary>Available payment methods</summary>{(['gateway','neft','rtgs'] as const).map(method=><p className="cc-note" key={method}><strong>{method==='gateway'?'Online gateway':method.toUpperCase()}</strong> · {record.payment_methods[method].available?'Connected':'Unavailable'} · {record.payment_methods[method].reason}</p>)}</details>
      {record.actions.can_read_report&&<div className="cc-report-picker"><label>Report<select aria-label="Contract report type" value={reportKind} onChange={e=>setReportKind(e.target.value)}>{[['summary','Executive summary'],['progress','Progress & milestones'],['payments','Payment reconciliation'],['purchases','Purchase register'],['team','Team & attendance'],['timeline','Activity audit trail'],['full','Complete audit record']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button disabled={action.busy} onClick={()=>void action.run(()=>downloadContractReport(record.report_url+'?kind='+reportKind,'Repaido-contract-'+reportKind+'.pdf'))}><Download size={16} aria-hidden="true"/>{action.busy?'Preparing private PDF…':'Download private PDF'}</button></div>}
      <ContractError error={action.error}/><p className="cc-note"><LockKeyhole size={13} aria-hidden="true"/>Private records are available to the customer and awarded contractor.</p>
    </>}
  </section>;
}
function ContractProgressHistory({entries}:{entries:ContractProgress[]}){
  const rows=[...entries].sort((a,b)=>a.created_at-b.created_at),first=rows[0]?.created_at||0,last=rows.at(-1)?.created_at||first,range=Math.max(last-first,1);
  return <section className="cc-detail" aria-label="Recorded progress history"><h4>Recorded progress over time</h4><p className="cc-note">Percentages are contractor-reported. Customer-confirmed reports and approved milestones remain separate records.</p>{rows.length?<><svg className="cc-progress-chart" viewBox="0 0 560 170" role="img" aria-label={rows.length+' contractor progress reports, with the latest at '+rows.at(-1)!.percent+' percent'}><line x1="35" y1="140" x2="535" y2="140" stroke="currentColor" opacity=".3"/><line x1="35" y1="20" x2="35" y2="140" stroke="currentColor" opacity=".3"/><text x="0" y="25" fill="currentColor" fontSize="12">100%</text><text x="8" y="144" fill="currentColor" fontSize="12">0%</text><polyline fill="none" stroke="currentColor" strokeWidth="2.5" points={rows.map(row=>(35+(row.created_at-first)/range*500)+','+(140-row.percent*1.2)).join(' ')}/>{rows.map(row=><circle key={row.id} cx={35+(row.created_at-first)/range*500} cy={140-row.percent*1.2} r="4" fill="currentColor"><title>{contractDate(row.created_at,true)} · {row.percent}% · {contractStatus(row.status)}</title></circle>)}</svg><div className="cc-between"><small>{contractDate(first)}</small><small>{contractDate(last)}</small></div></>:<p className="cc-note">The progress graph appears after an actual contractor report is saved.</p>}</section>;
}
function ProgressRecord({record,entry,accountKey,onChanged}:{record:ContractRecords;entry:ContractProgress;accountKey:string;onChanged:()=>Promise<void>}){
  const action=useCustomContractAction(),[reviewing,setReviewing]=useState(false),[note,setNote]=useState('');
  return <article className="cc-payment-card"><div className="cc-between"><strong>{entry.percent}% reported progress</strong><span className="cc-status" data-status={entry.status}>{contractStatus(entry.status)}</span></div><p className="cc-detail-description">{entry.note}</p><p className="cc-note">Contractor report · {contractDate(entry.created_at,true)}{entry.reviewed_at?' · Customer reviewed '+contractDate(entry.reviewed_at,true):''}</p>{entry.review_note&&<p>Customer response: {entry.review_note}</p>}<EvidencePhotos evidence={entry.evidence} accountKey={accountKey}/>{entry.actions.can_review&&!reviewing&&<button onClick={()=>setReviewing(true)}>Review reported progress<FileCheck2 size={16} aria-hidden="true"/></button>}{reviewing&&entry.actions.can_review&&<form className="cc-form" onSubmit={event=>event.preventDefault()}><label>Review note<textarea maxLength={1000} rows={3} disabled={action.busy} value={note} onChange={event=>setNote(event.target.value)}/></label><div className="cc-actions"><button disabled={action.busy} onClick={()=>setReviewing(false)}>Cancel review</button>{[false,true].map(approved=><button key={String(approved)} className={approved?'cc-primary':''} disabled={action.busy} onClick={()=>void action.run(async()=>{await reviewContractProgress(record.project.id,entry.id,record.version,approved,note);setReviewing(false);await onChanged();})}>{approved?'Confirm this progress report':'Request changes'}</button>)}</div></form>}<ContractError error={action.error}/></article>;
}
function EvidencePhotos({evidence,accountKey}:{evidence:ContractEvidence[];accountKey:string}){
  const action=useCustomContractAction(),[preview,setPreview]=useState<{id:string;url:string;kind?:'image'|'video'}|null>(null),urls=useRef(new Set<string>()),alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;for(const url of urls.current)URL.revokeObjectURL(url);urls.current.clear();};},[accountKey]);
  const close=()=>{if(preview){URL.revokeObjectURL(preview.url);urls.current.delete(preview.url);}setPreview(null);};
  return evidence.length?<div className="cc-detail"><div className="cc-actions">{evidence.map((photo,index)=><button key={photo.id} disabled={action.busy} onClick={()=>void action.run(async()=>{const blob=await privateContractBlob(photo.url,photo.kind==='video'?'video':'image');if(!alive.current)return;close();const url=URL.createObjectURL(blob);urls.current.add(url);setPreview({id:photo.id,url,kind:photo.kind});})}><ImagePlus size={15} aria-hidden="true"/>View private {photo.kind==='video'?'video':'photo'} {index+1}</button>)}</div>{preview&&<div className="cc-photo-preview">{preview.kind==='video'?<video src={preview.url} controls aria-label="Saved private contract video evidence"/>:<img src={preview.url} alt="Saved private contract evidence"/>}<button onClick={close}>Close photo</button></div>}<ContractError error={action.error}/></div>:null;
}
function FilePicker({files,onChange,disabled,required=false,video=false}:{files:File[];onChange:(files:File[])=>void;disabled:boolean;required?:boolean;video?:boolean}){return <label>Evidence photos {required?'(required)':'(optional)'}<input type="file" accept={video?'image/jpeg,image/png,image/webp,video/mp4,video/webm':'image/jpeg,image/png,image/webp'} multiple required={required} disabled={disabled} onChange={event=>onChange(Array.from(event.target.files||[]))}/><small>{video?'Up to five images or MP4/WebM videos, up to 8 MB each.':'Up to five JPEG, PNG or WebP photos, up to 8 MB each.'}</small>{files.length>0&&<small>{files.map(file=>file.name).join(', ')}</small>}</label>;}
async function uploadFiles(projectId:string,files:File[],purpose:'progress'|'payment'|'purchase',sharePublic=false){if(files.length>5)throw new Error('Attach up to five evidence photos.');const ids:string[]=[];for(const file of files)ids.push((await uploadContractEvidence(projectId,file,purpose,sharePublic)).id);return ids;}
function ProgressForm({record,onSaved}:{record:ContractRecords;onSaved:()=>Promise<void>}){
  const action=useCustomContractAction(),[files,setFiles]=useState<File[]>([]),[publicConsent,setPublicConsent]=useState(false),formRef=useRef<HTMLFormElement>(null);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{const ids=await uploadFiles(record.project.id,files,'progress',publicConsent);await reportContractProgress(record.project.id,record.version,Number(fields.get('percent')),String(fields.get('note')),ids,publicConsent,String(fields.get('milestone_id')||'')||undefined);setFiles([]);setPublicConsent(false);formRef.current?.reset();await onSaved();},'Your progress report was saved for customer review.');};
  return <details className="cc-section"><summary>Report work progress</summary><form className="cc-form" ref={formRef} onSubmit={submit}><label>Contractor-reported completion (%)<input type="number" name="percent" required min={0} max={100} step={1} disabled={action.busy}/></label><label>Work completed and next steps<textarea name="note" minLength={10} maxLength={2000} required rows={4} disabled={action.busy}/></label><MilestoneSelect record={record} disabled={action.busy}/><FilePicker video files={files} onChange={setFiles} disabled={action.busy}/><label className="cc-check"><input type="checkbox" checked={publicConsent} disabled={action.busy} onChange={event=>setPublicConsent(event.target.checked)}/><span>I consent to sharing this note and these photos if the customer enables public project progress. I have permission from any people shown.</span></label><p className="cc-note">Reporting 100% does not complete the project. Milestone and completion decisions use their separate approval process.</p><ContractError error={action.error}/>{action.message&&<p className="cc-success" role="status">{action.message}</p>}<button className="cc-primary" disabled={action.busy}>{action.busy?'Saving report & photos…':'Save progress for review'}</button></form></details>;
}
function MilestoneSelect({record,disabled}:{record:ContractRecords;disabled:boolean}){return record.milestones.length?<label>Related milestone (optional)<select aria-label="Related milestone (optional)" name="milestone_id" disabled={disabled}><option value="">Overall contract</option>{record.milestones.map(goal=><option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label>:null;}
function PublicProgressControl({record,onChanged}:{record:ContractRecords;onChanged:()=>Promise<void>}){
  const action=useCustomContractAction(),[confirm,setConfirm]=useState(false);
  return <section className="cc-detail"><h4>Public project progress</h4><p className="cc-note">{record.public_progress.enabled?'You have enabled a public project summary.':'Your project progress is private.'} The summary can show project dates, milestone decisions and reported percentages. Notes and photos appear only with their uploader’s consent. Payment records and private site details stay private.</p>{confirm?<div className="cc-bid-confirm"><p>Enable this project’s public progress summary?</p><div className="cc-actions"><button disabled={action.busy} onClick={()=>setConfirm(false)}>Keep private</button><button className="cc-primary" disabled={action.busy} onClick={()=>void action.run(async()=>{await shareContractProgress(record.project.id,record.version,true);setConfirm(false);await onChanged();})}>Enable public progress</button></div></div>:<button disabled={action.busy} onClick={()=>record.public_progress.enabled?void action.run(async()=>{await shareContractProgress(record.project.id,record.version,false);await onChanged();}):setConfirm(true)}>{record.public_progress.enabled?'Make project progress private':'Review public sharing'}</button>}<ContractError error={action.error}/></section>;
}
function PaymentRequestForm({record,onSaved}:{record:ContractRecords;onSaved:()=>Promise<void>}){
  const action=useCustomContractAction(),form=useRef<HTMLFormElement>(null),methods=(['gateway','neft','rtgs'] as const).filter(method=>record.payment_methods[method].available);
  if(!methods.length)return <p className="cc-note">Payment requests will be available when a supported payment method is connected. No payment can be collected here yet.</p>;
  return <details className="cc-section"><summary>Create a payment request</summary><p className="cc-note">Available within the agreed price: {contractMoney(record.financials.available_to_request_paise)}. The customer must approve each request before payment.</p><form className="cc-form" ref={form} onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{const amount=rupeesToPaise(String(fields.get('amount')));if(amount<=0||amount>record.financials.available_to_request_paise)throw new Error('Request an amount within the available agreed balance.');await requestContractPayment(record.project.id,record.version,amount,String(fields.get('method')) as ContractPayment['method'],String(fields.get('note')),String(fields.get('milestone_id')||'')||undefined);form.current?.reset();await onSaved();},'Payment request saved. It is awaiting customer approval.');}}><label>Requested amount (₹)<input type="text" name="amount" inputMode="decimal" required pattern="[0-9]+(\.[0-9]{1,2})?" disabled={action.busy}/></label><label>Payment method<select aria-label="Payment method" name="method" required disabled={action.busy}>{methods.map(method=><option key={method} value={method}>{method==='gateway'?'Online gateway':method.toUpperCase()}</option>)}</select></label><label>Reason or payment terms<textarea name="note" maxLength={1000} rows={3} disabled={action.busy}/></label><MilestoneSelect record={record} disabled={action.busy}/><ContractError error={action.error}/>{action.message&&<p className="cc-success" role="status">{action.message}</p>}<button className="cc-primary" disabled={action.busy||record.financials.available_to_request_paise<=0}>{action.busy?'Saving request…':'Request customer approval'}</button></form></details>;
}
function PaymentRecord({record,payment,accountKey,onChanged}:{record:ContractRecords;payment:ContractPayment;accountKey:string;onChanged:()=>Promise<void>}){
  const action=useCustomContractAction(),[approving,setApproving]=useState(false),[reporting,setReporting]=useState(false),[bank,setBank]=useState<ContractBankInstructions|null>(null),[note,setNote]=useState(''),alive=useRef(true),widget=useRef<{close?:()=>void}|null>(null);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;widget.current?.close?.();};},[accountKey]);
  const pay=()=>void action.run(async()=>{const order=await createContractPaymentOrder(record.project.id,payment.id);await loadCheckout();if(!alive.current)return;const checkout=new window.Razorpay!({key:order.key_id,order_id:order.order_id,amount:order.amount_paise,currency:order.currency,name:'Repaido',description:record.project.title,handler:async(result:{razorpay_payment_id:string})=>{if(!alive.current)return;await action.run(async()=>{await checkContractPayment(record.project.id,payment.id,result.razorpay_payment_id);await onChanged();},'Payment checked with the provider. The current saved status is shown above.');},modal:{ondismiss:()=>{if(alive.current)action.setMessage('Checkout closed. Refresh the payment status before retrying if money was debited.');}}});checkout.on('payment.failed',()=>{if(alive.current)action.setError('The provider did not confirm this payment. Refresh its status before retrying.');});widget.current=checkout;checkout.open();await onChanged();});
  return <article className="cc-payment-card"><div className="cc-between"><strong>{contractMoney(payment.amount_paise)}</strong><span className="cc-status" data-status={payment.status}>{contractStatus(payment.status)}</span></div><p>{payment.method==='gateway'?'Platform gateway':payment.method.toUpperCase()} · Requested {contractDate(payment.created_at,true)}</p>{payment.note&&<p className="cc-detail-description">{payment.note}</p>}{payment.confirmed_at&&<p className="cc-note">Confirmed {contractDate(payment.confirmed_at,true)} · {payment.method==='gateway'?'Collected by the platform; contractor payout is separate.':'Verified payment reference recorded.'}</p>}{payment.reference&&<p className="cc-note">Transfer reference: {payment.reference}</p>}{payment.status==='reported_pending'&&<p className="cc-note">Your transfer report is awaiting independent verification. It has not been counted as paid.</p>}{payment.amount_refunded?<p className="cc-note">Provider-confirmed refund: {contractMoney(payment.amount_refunded)}</p>:null}<EvidencePhotos evidence={payment.evidence||[]} accountKey={accountKey}/><div className="cc-actions">{payment.actions.can_approve&&!approving&&<button className="cc-primary" disabled={action.busy} onClick={()=>setApproving(true)}>Review payment request</button>}{payment.actions.can_pay&&<button className="cc-primary" disabled={action.busy} onClick={pay}>Pay approved {contractMoney(payment.amount_paise)} securely</button>}{payment.actions.can_report&&!reporting&&<button disabled={action.busy} onClick={()=>setReporting(true)}>Report bank transfer</button>}{payment.report_id&&<button disabled={action.busy} onClick={()=>void action.run(()=>downloadContractReport('/contracts/reports/'+encodeURIComponent(payment.report_id!)+'.pdf','Repaido-contract-payment-report.pdf'))}><Download size={15} aria-hidden="true"/>Payment report</button>}</div>
    {approving&&payment.actions.can_approve&&<form className="cc-form" onSubmit={event=>event.preventDefault()}><p>Approve a {payment.method==='gateway'?'gateway':payment.method.toUpperCase()} payment request for <strong>{contractMoney(payment.amount_paise)}</strong>? Approval does not confirm payment.</p><label>Approval or decline note<textarea maxLength={1000} rows={2} disabled={action.busy} value={note} onChange={event=>setNote(event.target.value)}/></label><div className="cc-actions"><button disabled={action.busy} onClick={()=>setApproving(false)}>Keep reviewing</button>{[false,true].map(approved=><button key={String(approved)} className={approved?'cc-primary':''} disabled={action.busy} onClick={()=>void action.run(async()=>{await approveContractPayment(record.project.id,payment.id,record.version,approved,note);setApproving(false);await onChanged();})}>{approved?'Approve this request':'Decline request'}</button>)}</div></form>}
    {payment.actions.can_check&&<form className="cc-form" onSubmit={event=>{event.preventDefault();const id=String(new FormData(event.currentTarget).get('provider_id')).trim();void action.run(async()=>{await checkContractPayment(record.project.id,payment.id,id);await onChanged();},'The provider payment was checked. Only confirmed capture changes the saved amount.');}}><label>Provider payment ID from your receipt<input name="provider_id" pattern="pay_[A-Za-z0-9]+" required defaultValue={payment.payment_id||''} disabled={action.busy}/></label><button disabled={action.busy}>Check payment with provider</button></form>}
    {reporting&&payment.actions.can_report&&<><button disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await contractBankInstructions(record.project.id);if(alive.current)setBank(result);})}>Show verified contractor bank instructions</button>{bank&&<section className="cc-bank"><h4>Provider-verified contractor bank</h4><dl>{[['Account holder',bank.account_holder],['Account number',bank.account_number],['IFSC',bank.ifsc],['Bank',bank.bank_name]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="cc-note">{bank.guidance}</p></section>}<TransferReportForm record={record} payment={payment} onSaved={async()=>{setReporting(false);setBank(null);await onChanged();}}/><button disabled={action.busy} onClick={()=>{setReporting(false);setBank(null);}}>Close transfer report</button></>}
    <ContractError error={action.error}/>{action.message&&<p className="cc-success" role="status">{action.message}</p>}
  </article>;
}
function TransferReportForm({record,payment,onSaved}:{record:ContractRecords;payment:ContractPayment;onSaved:()=>Promise<void>}){
  const action=useCustomContractAction(),[files,setFiles]=useState<File[]>([]);
  return <form className="cc-form" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{if(!files.length)throw new Error('Attach at least one bank transfer evidence photo.');const ids=await uploadFiles(record.project.id,files,'payment');await reportContractTransfer(record.project.id,payment.id,record.version,String(fields.get('reference')).trim(),ids,String(fields.get('note')));await onSaved();});}}><label>Bank transfer / UTR reference<input name="reference" minLength={6} maxLength={100} required disabled={action.busy}/></label><label>Transfer note<textarea name="note" maxLength={1000} rows={3} disabled={action.busy}/></label><FilePicker required files={files} onChange={setFiles} disabled={action.busy}/><label className="cc-check"><input type="checkbox" required disabled={action.busy}/><span>I made this transfer to the displayed verified contractor account and am submitting its actual bank reference and evidence.</span></label><p className="cc-note">This saves a transfer report for independent verification. It does not mark the contract paid.</p><ContractError error={action.error}/><button className="cc-primary" disabled={action.busy}>{action.busy?'Uploading & reporting…':'Submit transfer for verification'}</button></form>;
}
function ContractPurchases({record,accountKey,onSaved}:{record:ContractRecords;accountKey:string;onSaved:()=>Promise<void>}){
 const purchases=record.purchases||[],confirmed=purchases.filter(p=>p.status==='customer_confirmed').reduce((sum,p)=>sum+p.amount_paise,0),reported=purchases.filter(p=>p.status==='reported').reduce((sum,p)=>sum+p.amount_paise,0);
 return <section className="cc-detail" aria-label="Contract purchases"><h4>Project purchases</h4><p className="cc-note">Record materials and other project purchases with their actual receipt reference. Customer review confirms the recorded purchase; payment requests remain separate and within the agreed price.</p><div className="cc-purchase-summary"><span><small>Customer-confirmed purchases</small><strong>{contractMoney(confirmed)}</strong></span><span><small>Awaiting customer review</small><strong>{contractMoney(reported)}</strong></span></div>{purchases.length?<div className="cc-list">{purchases.map(p=><PurchaseRecord key={p.id} purchase={p} record={record} accountKey={accountKey} onChanged={onSaved}/>)}</div>:<p className="cc-note">No project purchases have been recorded.</p>}{record.actions.can_record_purchase&&<PurchaseForm record={record} onSaved={onSaved}/>}</section>;
}
function PurchaseRecord({purchase:p,record,accountKey,onChanged}:{purchase:ContractPurchase;record:ContractRecords;accountKey:string;onChanged:()=>Promise<void>}){
 const action=useCustomContractAction(),[reviewing,setReviewing]=useState(false),[note,setNote]=useState('');
 return <article className="cc-payment-card"><div className="cc-between"><strong>{p.title}</strong><span className="cc-status">{contractStatus(p.status)}</span></div><strong>{contractMoney(p.amount_paise)}</strong><p className="cc-note">Purchased {contractDate(p.purchased_at)} · Contractor-reported{p.vendor?' · '+p.vendor:''}</p><p className="cc-note">Receipt reference: {p.receipt_reference}</p>{p.note&&<p className="cc-detail-description">{p.note}</p>}{p.reviewed_at&&<p className="cc-note">Customer reviewed {contractDate(p.reviewed_at,true)}{p.review_note?' · '+p.review_note:''}</p>}<EvidencePhotos evidence={p.evidence} accountKey={accountKey}/>{p.actions.can_review&&!reviewing&&<button onClick={()=>setReviewing(true)}>Review purchase record</button>}{reviewing&&p.actions.can_review&&<div className="cc-form"><label>Customer review note<textarea maxLength={1000} value={note} disabled={action.busy} onChange={e=>setNote(e.target.value)}/></label><p className="cc-note">This records your review of the purchase and does not approve an extra charge.</p><div className="cc-actions"><button disabled={action.busy} onClick={()=>setReviewing(false)}>Cancel review</button>{[false,true].map(approved=><button key={String(approved)} disabled={action.busy} className={approved?'cc-primary':''} onClick={()=>void action.run(async()=>{await reviewContractPurchase(record.project.id,p.id,record.version,approved,note);setReviewing(false);await onChanged();})}>{approved?'Confirm purchase record':'Request correction'}</button>)}</div></div>}<ContractError error={action.error}/></article>;
}
function PurchaseForm({record,onSaved}:{record:ContractRecords;onSaved:()=>Promise<void>}){
 const action=useCustomContractAction(),[files,setFiles]=useState<File[]>([]),form=useRef<HTMLFormElement>(null);
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const fields=new FormData(event.currentTarget);void action.run(async()=>{const purchasedAt=Date.parse(String(fields.get('date'))+'T00:00:00+05:30')/1000;if(!Number.isFinite(purchasedAt)||purchasedAt>Date.now()/1000)throw new Error('Choose the actual purchase date in India time.');const ids=await uploadFiles(record.project.id,files,'purchase');await recordContractPurchase(record.project.id,record.version,{title:String(fields.get('title')).trim(),vendor:String(fields.get('vendor')).trim(),amount_paise:rupeesToPaise(String(fields.get('amount'))),purchased_at:purchasedAt,receipt_reference:String(fields.get('receipt')).trim(),note:String(fields.get('note')).trim(),evidence_ids:ids});setFiles([]);form.current?.reset();await onSaved();},'Purchase recorded for customer review.');};
 return <details className="cc-section"><summary>Record a project purchase</summary><form className="cc-form" ref={form} onSubmit={submit}><label>Materials or purchase description<input name="title" required minLength={3} maxLength={150} disabled={action.busy}/></label><div className="cc-form-grid"><label>Actual purchase date (India time)<input type="date" name="date" required min="2000-01-01" disabled={action.busy}/></label><label>Purchase amount (₹)<input name="amount" inputMode="decimal" required pattern="[0-9]+(\.[0-9]{1,2})?" disabled={action.busy}/></label></div><label>Vendor (optional)<input name="vendor" maxLength={150} disabled={action.busy}/></label><label>Actual invoice or receipt reference<input name="receipt" required minLength={3} maxLength={150} disabled={action.busy}/></label><label>Purchase note<textarea name="note" maxLength={1000} disabled={action.busy}/></label><FilePicker files={files} onChange={setFiles} disabled={action.busy}/><ContractError error={action.error}/>{action.message&&<p role="status" className="cc-success">{action.message}</p>}<button className="cc-primary" disabled={action.busy}>{action.busy?'Saving purchase…':'Save purchase for review'}</button></form></details>;
}
