import {useEffect,useState} from 'react';
import {onIdTokenChanged} from 'firebase/auth';
import {Gift,Ticket,ArrowRight} from 'lucide-react';
import {auth} from '../firebase';
import {operation,money} from '../services/operations';
import {Modal} from './ui';
import './coupons.css';
export type Coupon={id:string;code:string;family:string;scope:string;bps:number;title:string;terms:string;expires_at:number};
const days=(c:Coupon)=>Math.max(0,Math.ceil((c.expires_at-Date.now()/1000)/86400));
export function CouponField({scope,base=0,value,onChange,disabled=false}:{scope:string;base?:number;value:Coupon|null;onChange:(c:Coupon|null)=>void;disabled?:boolean}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Coupon[]>([]),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let previous=auth.currentUser?.uid;return onIdTokenChanged(auth,u=>{if(previous!==u?.uid){setRows([]);setCode('');setOpen(false);onChange(null);}previous=u?.uid;});},[]);
 const load=()=>{const uid=auth.currentUser?.uid;if(!auth.currentUser){setError('Sign in to check your coupons.');return;}setBusy(true);void operation<{coupons:Coupon[]}>('/coupons/wallet',{}, {background:true}).then(d=>{if(uid!==auth.currentUser?.uid)return;setRows(d.coupons.filter(c=>c.scope===(['hire','home'].includes(scope)?'service':scope)));setError('');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));};
 const apply=async(text:string)=>{const uid=auth.currentUser?.uid;setBusy(true);setError('');try{const c=await operation<Coupon>('/coupons/check',{method:'POST',body:JSON.stringify({code:text,scope})},{background:true});if(uid===auth.currentUser?.uid){onChange(c);setOpen(false);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="coupon-field"><button type="button" disabled={disabled} onClick={()=>{setOpen(v=>!v);if(!open)load();}} aria-expanded={open}><Ticket size={16}/><span>{value?`${value.code} · ${value.bps/100}% off${base?' · −'+money(Math.floor(base*value.bps/10000)):''}`:'Offers & promo codes'}</span><ArrowRight size={14}/></button>{disabled&&<small>Remove the other promotion to use a coupon.</small>}{value&&<><small>{scope==='home'?'Applies to completed service in the first quoted billing period.':'Eligible base only; final savings confirmed at checkout.'} Expires {new Date(value.expires_at*1000).toLocaleDateString('en-IN')}.</small><button type="button" onClick={()=>onChange(null)}>Remove coupon</button></>}{open&&<div className="coupon-options"><div className="coupon-input"><input aria-label="Promo code" maxLength={30} value={code} placeholder="Enter code" onChange={e=>setCode(e.target.value.toUpperCase())}/><button type="button" disabled={busy||!code.trim()} onClick={()=>void apply(code)}>Apply</button></div>{busy&&<small role="status">Checking eligible offers…</small>}{!busy&&!rows.length&&!error&&<small>No eligible coupons for this checkout.</small>}{rows.map(c=><button type="button" key={c.code} disabled={busy} onClick={()=>void apply(c.code)}><span><strong>{c.title}</strong><small>{c.code} · {days(c)} days left</small></span><ArrowRight size={14}/></button>)}<details><summary>Coupon terms</summary><p>One use per account. No stacking. Vendor-funded discount on the eligible base; taxes, travel, delivery, parts and deposits excluded. Rental savings apply at the coupon percentage to actual usage before tax; extra fees are excluded. Home-plan savings apply to the first quoted billing period. Reserved coupons cannot be transferred to another order.</p></details>{error&&<p role="alert">{error}</p>}</div>}</section>;
}
export function CouponWelcome({onExplore}:{onExplore:(scope:string)=>void}){
 const [data,setData]=useState<Coupon[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true,timer:ReturnType<typeof setTimeout>|undefined,account='';const tryShow=async()=>{if(!account||document.hidden||document.querySelector('dialog[open]'))return;const uid=account;try{const d=await operation<{show:boolean;coupons:Coupon[]}>('/coupons/launch',{method:'POST'},{background:true});if(alive&&uid===auth.currentUser?.uid&&d.show)setData(d.coupons);}catch{/* Never block app entry on promotional network failure. */}};const off=onIdTokenChanged(auth,u=>{account=u?.uid||'';setData([]);clearTimeout(timer);timer=setTimeout(()=>void tryShow(),8500);});const focus=()=>{clearTimeout(timer);timer=setTimeout(()=>void tryShow(),1200);};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{alive=false;off();clearTimeout(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);};},[]);
 if(!data.length)return null;const choice=data.some(c=>c.family==='return_choice');
 return <Modal title={choice?'A little thank-you, your choice':'Your first Repaido perks'} className="coupon-welcome" onClose={()=>setData([])}><div className="coupon-gift"><Gift size={30}/><span>REPAIDO REWARDS</span></div><p>{choice?'Choose one 10% thank-you coupon. Your choice is saved to your account.':'Choose an eligible offer at checkout. Your service and rental welcome offers are separate.'}</p><div className="coupon-welcome-cards">{data.map(c=><button key={c.code} disabled={busy} onClick={()=>{if(c.family==='return_choice'){setBusy(true);void operation('/coupons/choose',{method:'POST',body:JSON.stringify({code:c.code})},{background:true}).then(()=>{setData([]);onExplore(c.scope);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}else{setData([]);onExplore(c.scope);}}}><strong>{c.bps/100}% <small>OFF</small></strong><span>{c.title}</span><b>{c.code}</b><small>{days(c)} days left · ends {new Date(c.expires_at*1000).toLocaleDateString('en-IN')}</small><ArrowRight size={16}/></button>)}</div><details><summary>What’s included</summary><p>{data[0].terms}</p><p>No automatic charge. Welcome service offers include day hiring and the first quoted Home-plan period. Rental savings exclude deposits and delivery. Refurbished savings apply only to qualifying items with a declared tax breakdown.</p></details>{error&&<p role="alert">{error}</p>}<button type="button" onClick={()=>setData([])}>Maybe later</button></Modal>;
}
