import {notifyFeedback} from '../services/actionFeedback';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,CalendarDays,Eye,MapPin,MessageCircle,RefreshCw,Users} from 'lucide-react';
import type {ContractPublicMember,CustomContractQuery} from '../types/customContracts';
import {CustomContractError,subscribeCustomContracts} from '../services/customContractsService';
import {RepaidianBadge} from './RepaidianBadge';
import {apiAssetUrl} from '../services/api';

export const contractMoney=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value/100);
export function contractDate(value:number,time=false){return Number.isFinite(value)&&value>0?new Date(value>1e12?value:value*1000).toLocaleString('en-IN',time?{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}:{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'}):'Not shared';}
export function contractLocalDate(value:number){const date=new Date(value*1000);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export const contractStatus=(value:string)=>({open:'Awaiting contract award',awarded:'Contract awarded',closed:'Query closed',planning:'Award accepted · planning',active:'Work in progress',paused:'Work paused',completed:'Completed',cancelled:'Cancelled',submitted:'Proposal submitted',requested:'Payment requested',approved:'Approved for payment',reported_pending:'Transfer reported · verification pending',confirmed:'Payment confirmed',rejected:'Declined',expired:'Expired'}[value]||value.replaceAll('_',' '));

export function useCustomContractResource<T>(key:string,load:(force:boolean,signal:AbortSignal)=>Promise<T>,enabled=true){
  const [state,setState]=useState<{key:string;data:T|null;busy:boolean;error:string}>({key,data:null,busy:enabled,error:''}),[revision,setRevision]=useState(0);
  const loader=useRef(load),controller=useRef<AbortController|null>(null),generation=useRef(0),mounted=useRef(true);loader.current=load;
  const refresh=useCallback(async(force=true)=>{if(!enabled)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;const epoch=++generation.current;setState(prior=>({key,data:prior.key===key?prior.data:null,busy:true,error:''}));try{const data=await loader.current(force,abort.signal);if(mounted.current&&epoch===generation.current&&!abort.signal.aborted)setState({key,data,busy:false,error:''});}catch(error){if(mounted.current&&epoch===generation.current&&!abort.signal.aborted)setState(prior=>({...prior,data:error instanceof CustomContractError&&[401,403,404].includes(error.status)?null:prior.data,busy:false,error:(error as Error).message}));}},[key,enabled]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;controller.current?.abort();};},[]);
  useEffect(()=>subscribeCustomContracts(()=>setRevision(value=>value+1)),[]);
  useEffect(()=>{void refresh(false);return()=>{generation.current++;controller.current?.abort();};},[refresh,revision]);
  useEffect(()=>{if(!enabled)return;const tick=()=>{if(!document.hidden)void refresh(true);};const timer=setInterval(tick,30000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[refresh,enabled]);
  return {...(state.key===key?state:{key,data:null,busy:enabled,error:''}),refresh};
}
export function useCustomContractAction(){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),gate=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const run=async(task:()=>Promise<void>,success='')=>{if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');try{await task();if(mounted.current&&success)setMessage(success);}catch(error){if(mounted.current)setError((error as Error).message);notifyFeedback({tone:'error',title:'Action needs attention',message:(error as Error).message},'contract-action');}finally{gate.current=false;if(mounted.current)setBusy(false);}};return {busy,error,message,run,setError,setMessage};}
export function ContractError({error,onRetry}:{error:string;onRetry?:()=>void}){return error?<div className="cc-error" role="alert"><p>{error}</p>{onRetry&&<button onClick={onRetry}>Retry</button>}</div>:null;}
export function ContractPerson({member,fallbackName,onOpenMember}:{member?:ContractPublicMember;fallbackName?:string;onOpenMember?:(id:string)=>void}){const name=member?.name||fallbackName||'Contract member',portrait=member?.portrait_url||member?.avatarUrl,initials=name.trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase();return <div className="cc-person"><span className="cc-person-avatar">{portrait?<img src={apiAssetUrl(portrait)} alt="" loading="lazy"/>:<span aria-hidden="true">{initials}</span>}<RepaidianBadge badge={member?.repaidianBadge} variant="avatar"/></span><span>{member&&onOpenMember?<button onClick={()=>onOpenMember(member.id)}>{name}</button>:<strong>{name}</strong>}{member?.city&&<small>{member.city}</small>}</span></div>;}
export function ContractQueryCard({query,onOpen,onOpenCommunityContract}:{query:CustomContractQuery;onOpen:()=>void;onOpenCommunityContract?:(id:string)=>void}){return <article className="cc-card"><div className="cc-between"><span className="cc-status" data-status={query.status}>{contractStatus(query.status)}</span><small>{query.sector}</small></div><h3>{query.title}</h3><div className="cc-facts"><span><MapPin size={15} aria-hidden="true"/>{query.area}, {query.city}</span><span><CalendarDays size={15} aria-hidden="true"/>Starts {contractDate(query.starts_at)}</span></div><p>{query.scope}</p><div className="cc-money"><strong>{contractMoney(query.budget_paise)}</strong><small>Planned budget</small></div><ul className="cc-skills" aria-label="Required skills">{query.skills.map(skill=><li key={skill}>{skill}</li>)}</ul>{query.match&&<div className="cc-match"><strong>{query.match.eligible?'Matches your registered work':'Review the requirements'}</strong><ul>{query.match.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}<div className="cc-facts"><span><Eye size={14} aria-hidden="true"/>{query.stats.views} views</span><span><Users size={14} aria-hidden="true"/>{query.stats.bids} proposal{query.stats.bids===1?'':'s'}</span><span><MessageCircle size={14} aria-hidden="true"/>{query.stats.comments} comment{query.stats.comments===1?'':'s'}</span></div><div className="cc-actions"><button className="cc-primary" onClick={onOpen}>{query.permissions.can_award?'Review proposals':'Open contract'}<ArrowRight size={16} aria-hidden="true"/></button>{onOpenCommunityContract&&<button onClick={()=>onOpenCommunityContract(query.id)}>Community post</button>}</div></article>;}
export function ContractRefresh({busy,onRefresh,label='Refresh contracts'}:{busy:boolean;onRefresh:()=>void;label?:string}){return <button className="cc-icon" aria-label={label} disabled={busy} onClick={onRefresh}><RefreshCw size={18} aria-hidden="true"/></button>;}
