import type {ProfessionalOffer} from './ProfessionalOffers';
import {CouponField,type Coupon} from './Coupons';
import {RotatingNote} from './RotatingNote';
import type {DiscoveryEvent} from './ServiceHydration';
import {useEffect,useRef,useState} from 'react';
import {onIdTokenChanged} from 'firebase/auth';
import {CalendarDays,ChevronLeft,ChevronRight,HeartHandshake,House,Paintbrush,RefreshCw,ShieldCheck,ArrowRight} from 'lucide-react';
import {auth} from '../firebase';
import {nativeAvailable,nativeCall} from '../services/native';
import {loadCheckout} from './PaymentPanel';
import {apiFetch} from '../services/api';
import {operation,money,type Job} from '../services/operations';
import {Modal} from './ui';
import {LocationPickerModal} from './LocationPickerModal';
import './home-plans.css';
type BriefField={id:string;label:string;required:boolean;options?:string[]};
export type HomeService={id:string;name:string;category:string;description:string;recurring:boolean;requirements:BriefField[];requirements_version:string};
type DailyLog={hygiene:boolean;checked:number[];note:string;at:number};
export type HomeVisit={id:string;date:string;time:string;starts_epoch:number;status:string;period:number;job_id?:string;worker_name?:string;acknowledged_at?:number;started_at?:number;completed_at?:number;daily_log?:DailyLog;review?:{rating:number;text:string}};
type Invoice={id:string;index:number;start:string;end:string;total_paise:number;status:string;unresolved:boolean;payment_id?:string;rows:{date:string;amount_paise:number;base_paise:number;gst_paise:number;discount_paise?:number;job_id:string}[];billing_note:string};
export type HomePlan={coupon?:{code:string;bps:number};id:string;customer_id:string;version:number;state:string;service_id:string;duration:string;start_date:string;city:string;address?:string;recipient_name?:string;relationship:string;instructions?:string;brief_rows?:{label:string;value:string}[];minutes:number;worker_id?:string;worker_name?:string;preferred_worker_name?:string;customer_accepted_at?:number;worker_accepted_at?:number;periods:{index:number;start:string;end:string}[];visits:HomeVisit[];quote?:{professional_offer?:ProfessionalOffer;period_price_paise:number;gst_bps:number;checklist:string[];exclusions:string;terms:string};changes:{id:string;visit_id:string;new_date?:string;new_time:string;reason:string;proposer:string;status:string}[];issues:{id:string;reason:string;status:string;response?:string}[];invoices:Invoice[]};
export type HomeAvailability={version:number;worker_id?:string;name?:string;services:string[];weekdays:number[];start_time:string;end_time:string;off_dates:string[];experience:string;approved_services?:string[];review_reason?:string};
export const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export const homePost=<T,>(path:string,body:unknown)=>operation<T>(path,{method:'POST',body:JSON.stringify(body)});
const label=(s:string)=>s.replaceAll('_',' ');
export async function homeCatalog(){const r=await apiFetch('/api/operations/home/catalog');if(!r.ok)throw Error('Home services could not load. Please retry.');return r.json() as Promise<{services:HomeService[];cities:string[];durations:{id:string;label:string}[];assurance:string}>;}
export function HomeEntry({onOpen}:{onOpen:()=>void}){return <div className="home-entry-premium"><button className="home-entry" onClick={onOpen}><img src="/images/puja-ready-home.jpg" alt=""/><span className="home-entry-copy"><strong><House size={14} aria-hidden="true"/>Repaido Home</strong><RotatingNote lines={["Daily help & family care","Puja-ready cleaning & repairs","Interiors, decor & renovation"]}/><span className="home-entry-icons" aria-hidden="true"><HeartHandshake size={12}/><Paintbrush size={12}/><ShieldCheck size={12}/></span></span><ArrowRight size={18} aria-hidden="true"/></button></div>;}
export function HomeHub({city,onClose,onSignIn,onPlans,initialService,onEvent,preferredWorker}:{city:string;onClose:()=>void;onSignIn:()=>void;onPlans:()=>void;initialService?:string;preferredWorker?:{id:string;name:string};onEvent?:(event:DiscoveryEvent)=>void}){
 const [data,setData]=useState<Awaited<ReturnType<typeof homeCatalog>>>(),[chosen,setChosen]=useState<HomeService>(),[error,setError]=useState('');
 const load=()=>void homeCatalog().then(d=>{setData(d);if(initialService)setChosen(d.services.find(s=>s.id===initialService));}).catch(e=>setError(e.message));
 useEffect(load,[]);
 useEffect(()=>{if(chosen)onEvent?.({kind:'service_view',service_id:'home:'+chosen.id});},[chosen?.id]);
 return <Modal title="Repaido Home" onClose={onClose} className="home-hub-dialog"><section className="home-plans">{!chosen&&<header className="home-brand"><span className="home-eyebrow">REPAIDO HOME</span><h2>Repair your living.</h2><p>This Durga Puja, welcome Maa to a home filled with care.</p><small>Plan your repairs, refresh your rooms, and celebrate together.</small></header>}{error&&<p role="alert">{error}<button onClick={load}>Retry</button></p>}{chosen&&data?<HomeRequest key={chosen.id} service={chosen} preferredWorker={preferredWorker} city={city} data={data} onBack={()=>setChosen(undefined)} onSignIn={onSignIn} onDone={onPlans}/>:<><div className="home-offerings">{data?.services.map(s=><button key={s.id} onClick={()=>setChosen(s)}><img src={s.id==='maid'?'/images/cleaning.jpg':s.id==='caretaker'?'/images/family-home-care.jpg':['floor-plan','civil-engineer','contractor'].includes(s.id)?'/images/home-project-planning.jpg':'/images/puja-ready-home.jpg'} alt="" loading="lazy"/><strong>{s.name}</strong><span>{s.recurring?'7 days · 1, 3 or 6 months':'Scope & estimate first'}</span></button>)}</div>{!data&&!error&&<p role="status">Loading home services…</p>}<div className="home-assurance"><ShieldCheck size={20}/><p>{data?.assurance}</p></div><button className="ops-primary" onClick={onPlans}>My plans & calendar</button></>}</section></Modal>;
}
function HomeRequest({service,city,data,onBack,onSignIn,onDone,preferredWorker}:{service:HomeService;preferredWorker?:{id:string;name:string};city:string;data:Awaited<ReturnType<typeof homeCatalog>>;onBack:()=>void;onSignIn:()=>void;onDone:()=>void}){
 const [stage,setStage]=useState(0),[duration,setDuration]=useState(service.recurring?'trial7':'project'),[date,setDate]=useState(''),[clock,setClock]=useState('09:00'),[minutes,setMinutes]=useState(120),[weekdays,setWeekdays]=useState([0,1,2,3,4,5]),[off,setOff]=useState(''),[address,setAddress]=useState(''),[location,setLocation]=useState<{lat:number;lng:number}>(),[map,setMap]=useState(false),[serviceCity,setCity]=useState(city),[name,setName]=useState(''),[relation,setRelation]=useState('self'),[phone,setPhone]=useState(''),[instructions,setInstructions]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [requirements,setRequirements]=useState<Record<string,string>>({});
 const [coupon,setCoupon]=useState<Coupon|null>(null);
 const briefComplete=service.requirements.every(f=>requirements[f.id]?.trim().length>=2);
 const request=useRef<{payload:string;key:string}|undefined>(undefined);
 const send=async()=>{if(!auth.currentUser){onSignIn();return;}setBusy(true);setError('');try{const body={coupon_code:coupon?.code||null,service_id:service.id,preferred_worker_id:preferredWorker?.id,duration,start_date:date,time:clock,minutes,weekdays,off_dates:off.split(',').map(s=>s.trim()).filter(Boolean),city:serviceCity,address,location,phone,recipient_name:name,relationship:relation,consent,instructions,requirements,requirements_version:service.requirements_version};const payload=JSON.stringify(body);if(request.current?.payload!==payload)request.current={payload,key:crypto.randomUUID()};await homePost('/home/plans',{...body,request_id:request.current.key});onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><button onClick={onBack}>‹ All Home services</button><h3>{service.name}</h3><p>{service.description}</p>{preferredWorker&&<p className="home-status">Preferred professional: {preferredWorker.name}. The team checks the full schedule before confirming.</p>}<StageTabs labels={['Your needs','Home','Review']} current={stage} onChange={n=>{if(n<stage)setStage(n);}}/><form onSubmit={e=>{e.preventDefault();if(stage<2)setStage(stage+1);else void send();}}>
 {stage===0&&<div className="home-form-grid"><fieldset className="home-wide home-brief-fields"><legend>{service.name} · Your requirements</legend>{service.requirements.map(f=><label key={f.id}>{f.label}{f.options?<select required value={requirements[f.id]||''} onChange={e=>setRequirements({...requirements,[f.id]:e.target.value})}><option value="" disabled>Choose an option</option>{f.options.map(v=><option key={v}>{v}</option>)}</select>:<textarea required minLength={2} maxLength={1000} value={requirements[f.id]||''} onChange={e=>setRequirements({...requirements,[f.id]:e.target.value})}/>}</label>)}</fieldset>{service.recurring&&<label>Plan length<select value={duration} onChange={e=>setDuration(e.target.value)}>{data.durations.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label>}<label>First visit<input type="date" required value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label>Visit time · India<input type="time" required value={clock} onInput={e=>setClock(e.currentTarget.value)} onChange={e=>setClock(e.target.value)}/></label><label>Minutes per visit<input type="number" min={30} max={480} step={30} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>{service.recurring&&<><fieldset className="home-wide"><legend>Visit days</legend><Weekdays value={weekdays} onChange={setWeekdays}/></fieldset><label className="home-wide">Planned days off (optional)<input placeholder="YYYY-MM-DD, YYYY-MM-DD" value={off} onChange={e=>setOff(e.target.value)}/></label></>}<p className="home-wide">The team confirms worker availability and a written quote. Nothing is charged now. All visit times use Asia/Kolkata.</p></div>}
 {stage===1&&<div className="home-form-grid"><label>Who is this for?<select value={relation} onChange={e=>setRelation(e.target.value)}>{['self','parent','family','authorised representative'].map(v=><option key={v}>{v}</option>)}</select></label><label>Person receiving the service<input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Service city<select value={serviceCity} onChange={e=>setCity(e.target.value)}>{data.cities.map(c=><option key={c}>{c}</option>)}</select></label><label>On-site contact number<input required type="tel" pattern="\+?[0-9]{10,15}" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="home-wide">House, street & landmark<textarea required minLength={10} maxLength={500} value={address} onChange={e=>setAddress(e.target.value)}/></label><button type="button" onClick={()=>setMap(true)}>{location?'Edit service entrance pin':'Set service entrance pin'}</button><p>{location?'Location confirmed.':'Choose the recipient’s home, even if you live in another city.'}</p><label className="home-wide">Work needed & access instructions<textarea required minLength={10} maxLength={1000} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Describe household tasks or the home project. Do not add diagnoses, medicines, ID numbers or passwords."/></label></div>}
 {stage===2&&<><CouponField scope="home" value={coupon} onChange={setCoupon}/><details className="home-brief" open><summary>Your service requirements</summary><dl>{service.requirements.map(f=><div key={f.id}><dt>{f.label}</dt><dd>{requirements[f.id]}</dd></div>)}</dl></details><dl className="home-facts"><div><dt>Plan</dt><dd>{data.durations.find(d=>d.id===duration)?.label||'Project consultation'}</dd></div><div><dt>Visits</dt><dd>{date} · {clock} IST · {minutes} min</dd></div><div><dt>For</dt><dd>{name} · {serviceCity}</dd></div><div><dt>Payment</dt><dd>Written quote first. Monthly collection after visit approval.</dd></div></dl><label className="home-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I am booking for myself or with the recipient’s permission. I will share only necessary service instructions.</label><p>Day changes need agreement. No automatic renewal. Non-medical care is not a substitute for nursing or emergency assistance. Do not upload photos of the recipient.</p></>}
 {error&&<p className="ops-error" role="alert">{error}</p>}<footer className="home-actions">{stage>0&&<button type="button" onClick={()=>setStage(stage-1)}>Back</button>}<button className="ops-primary" disabled={busy||stage===2&&(!briefComplete||!location||!consent||!date||!weekdays.length||name.length<2||instructions.length<10||address.length<10)}>{busy?'Sending…':stage===2?'Request plan & quote':'Continue'}<ArrowRight size={16}/></button></footer></form>{map&&<LocationPickerModal isOpen onClose={()=>setMap(false)} initialLat={location?.lat} initialLng={location?.lng} onConfirmLocation={p=>{setLocation(p);if(p.address)setAddress(p.address);const match=data.cities.find(c=>c.toLowerCase()===p.city.toLowerCase());if(match)setCity(match);setMap(false);}}/>}</>;
}
export function StageTabs({labels,current,onChange}:{labels:string[];current:number;onChange:(n:number)=>void}){return <nav className="home-stages" aria-label="Plan sections">{labels.map((s,i)=><button key={s} aria-current={i===current?'step':undefined} onClick={()=>onChange(i)}><span>{i+1}</span>{s}</button>)}</nav>;}
export function Weekdays({value,onChange}:{value:number[];onChange:(days:number[])=>void}){return <div className="home-days">{dayNames.map((d,i)=><button type="button" key={d} aria-pressed={value.includes(i)} onClick={()=>onChange(value.includes(i)?value.filter(x=>x!==i):[...value,i].sort())}>{d}</button>)}</div>;}
export function HomePlans({worker=false,onSignIn,onJob}:{worker?:boolean;onSignIn?:()=>void;onJob:(id:string)=>void}){
 const [plans,setPlans]=useState<HomePlan[]>([]),[selected,setSelected]=useState(new URLSearchParams(location.search).get('home-plan')||''),[services,setServices]=useState<HomeService[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[uid,setUid]=useState(auth.currentUser?.uid);
 const load=async(background=false)=>{if(!background)setBusy(true);setError('');try{setPlans((await operation<{plans:HomePlan[]}>('/home/plans',{}, {background})).plans.filter(p=>worker?p.worker_id===auth.currentUser?.uid:p.customer_id===auth.currentUser?.uid));setLoaded(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>onIdTokenChanged(auth,u=>setUid(u?.uid)),[]);
 useEffect(()=>{void homeCatalog().then(d=>setServices(d.services)).catch(e=>setError(e.message));if(uid)void load();const timer=setInterval(()=>{if(uid&&!document.hidden)void load(true);},30000);return()=>clearInterval(timer);},[uid]);
 const plan=plans.find(p=>p.id===selected);
 return <section className="home-plans"><header className="home-section-head"><div><span className="home-eyebrow">REPAIDO HOME</span><h2>{worker?'My calendar':'Home plans & attendance'}</h2></div><button disabled={busy||!uid} aria-label="Refresh home calendar" onClick={()=>void load()}><RefreshCw size={18}/></button></header>{!uid?<button className="ops-primary" onClick={onSignIn}>Sign in to see your plans</button>:<>{error&&<p role="alert" className="ops-error">{error}<button onClick={()=>void load()}>Retry</button></p>}{worker&&<details className="home-availability"><summary>My service hours & days off</summary><WorkerHomeAvailability services={services}/></details>}<div className="home-plan-rail">{plans.map(p=><button key={p.id} aria-pressed={p.id===selected} onClick={()=>setSelected(p.id)}><strong>{services.find(s=>s.id===p.service_id)?.name||p.service_id}</strong><span>{p.city} · {label(p.state)}</span><small>{p.start_date} · {p.worker_name||'Team review'}</small></button>)}</div>{!loaded&&!error&&<p role="status">Loading calendar…</p>}{loaded&&!plans.length&&<p className="home-empty">{worker?'Accepted home plans appear here. Set your service hours and submit your skills for team review.':'No home plans yet. Explore Repaido Home to request daily help, family care or a home project.'}</p>}{plan?<PlanDetail key={plan.id} plan={plan} onRefresh={load} onJob={onJob} worker={worker}/>:!!plans.length&&<p>Select a plan to view its calendar.</p>}</>}</section>;
}
export function PlanDetail({plan:p,onRefresh,onJob,worker=false,admin=false}:{plan:HomePlan;onRefresh:()=>Promise<void>;onJob:(id:string)=>void;worker?:boolean;admin?:boolean}){
 const [stage,setStage]=useState(0),[month,setMonth]=useState(p.start_date.slice(0,7)),[visit,setVisit]=useState(p.visits[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[altDate,setAltDate]=useState(''),[altTime,setAltTime]=useState('09:00'),[issue,setIssue]=useState(''),[ack,setAck]=useState(false);
 const selected=p.visits.find(v=>v.id===visit);const [year,m]=month.split('-').map(Number),offset=(new Date(year,m-1,1).getDay()+6)%7,count=new Date(year,m,0).getDate();
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const decide=(action:string)=>run(()=>homePost('/home/plans/'+p.id+'/decision',{expected_version:p.version,action,reason}));
 const shift=(n:number)=>{const d=new Date(year,m-1+n,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};
 return <div className="home-plan-detail"><HomeBrief plan={p} admin={admin}/><div className="home-status"><strong>{label(p.state)}</strong><span>{p.worker_name||'Awaiting matching'} · {p.city}</span></div><StageTabs labels={['Calendar','Daily work','Billing','Help']} current={stage} onChange={setStage}/>{error&&<p className="ops-error" role="alert">{error}</p>}
 {p.state==='offered'&&p.quote&&!admin&&<section className="home-quote"><h3>Review your plan</h3>{p.quote.professional_offer&&<div className="home-status"><strong>{p.quote.professional_offer.bps/100}% professional offer · save {money(p.quote.professional_offer.discount_paise||0)}</strong><p>First-period service fee after saving: {money(p.quote.professional_offer.discounted_base_paise||0)}. Tax remains calculated on the original fee. Savings apply to completed, approved visits only.</p><details><summary>Offer terms</summary><p>{p.quote.professional_offer.terms}</p></details></div>}{p.coupon&&<p className="home-status">{p.coupon.code} · {p.coupon.bps/100}% vendor-funded discount on service fees for the first billing period only; GST unchanged. Savings apply only to completed, approved visits.</p>}<strong>{money(p.quote.period_price_paise)} / {p.duration==='trial7'?'7-day plan':p.duration==='project'?'project visit':'month'} + {p.quote.gst_bps/100}% GST</strong><p>{p.visits.length} planned visits · {p.minutes} minutes each. {worker?'Accept only if you can cover every visit. Your accepted earnings policy applies.':'The plan starts only when you and the professional accept.'}</p><ul>{p.quote.checklist.map(t=><li key={t}>{t}</li>)}</ul><details><summary>Scope, exclusions & cancellation</summary><p>{p.quote.exclusions}</p><p>{p.quote.terms}</p><p>Unserved visits are not collected. Future visits can be paused or cancelled before work starts; started visits must be resolved. No automatic renewal.</p></details><p>Customer: {p.customer_accepted_at?'Accepted':'Pending'} · Professional: {p.worker_accepted_at?'Accepted':'Pending'}</p><label className="home-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I agree to the scope, schedule and quote.</label><button className="ops-primary" disabled={busy||!ack||!!(worker?p.worker_accepted_at:p.customer_accepted_at)} onClick={()=>void decide('accept')}>Accept plan</button><details><summary>Request a revised quote</summary><label>What needs to change?<textarea minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.length<5} onClick={()=>void decide('decline')}>Return for revision</button></details></section>}
 {stage===0&&<><div className="home-month"><button aria-label="Previous month" onClick={()=>shift(-1)}><ChevronLeft size={17}/></button><h3>{new Date(year,m-1).toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</h3><button aria-label="Next month" onClick={()=>shift(1)}><ChevronRight size={17}/></button></div><div className="home-calendar-scroll"><div className="home-calendar" role="group" aria-label="Attendance calendar">{dayNames.map(d=><span className="home-weekday" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,v=p.visits.find(v=>v.date===date);return <button key={date} className={v?`day-${['completed','in_progress','missed','cancelled','off','paused'].includes(v.status)?v.status:'scheduled'}`:''} aria-label={`${date}: ${v?label(v.status)+', '+v.time:'No visit'}`} aria-pressed={!!v&&v.id===visit} disabled={!v} onClick={()=>{setVisit(v!.id);setStage(1);}}><strong>{i+1}</strong><small>{v?(v.status==='completed'?'Done':v.status==='scheduled'?v.time:label(v.status)):'Off'}</small></button>;})}</div></div><p className="home-muted">Tap a day for attendance, daily tasks and the visit record. All times are India time. “Off” means no planned visit.</p></>}
 {stage===1&&<><label>Visit<select value={visit} onChange={e=>setVisit(e.target.value)}>{p.visits.map(v=><option key={v.id} value={v.id}>{v.date} · {v.time} · {label(v.status)}</option>)}</select></label>{selected&&<><dl className="home-facts"><div><dt>Attendance</dt><dd>{label(selected.status)}</dd></div><div><dt>Acknowledged</dt><dd>{selected.acknowledged_at?new Date(selected.acknowledged_at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not yet'}</dd></div><div><dt>Started</dt><dd>{selected.started_at?new Date(selected.started_at*1000).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'}):'Not yet'}</dd></div><div><dt>Completed</dt><dd>{selected.completed_at?'Customer confirmed':'Awaiting completion'}</dd></div></dl>{selected.daily_log?<><h3>Daily service report</h3><p>Hygiene checks recorded · {new Date(selected.daily_log.at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</p><ul>{p.quote?.checklist.map((t,i)=><li key={i}>{selected.daily_log!.checked.includes(i)?'✓ ':''}{t}</li>)}</ul><p>{selected.daily_log.note}</p></>:<p>The professional’s daily report appears after the visit.</p>}{selected.review&&<p>Verified visit review: {selected.review.rating}/5 · {selected.review.text}</p>}{selected.job_id&&!admin&&<button className="ops-primary" onClick={()=>onJob(selected.job_id!)}>Open visit · tracking, approval & review</button>}{!selected.job_id&&<p>Accepted visits open in Tasks 24 hours before the scheduled time.</p>}{!admin&&['active','paused'].includes(p.state)&&<details><summary>Request a day off / alternative day</summary><form onSubmit={e=>{e.preventDefault();void run(()=>homePost(`/home/plans/${p.id}/changes`,{expected_version:p.version,visit_id:selected.id,new_date:altDate||null,new_time:altTime,reason}));}}><label>Alternative date (leave empty for a day off)<input type="date" value={altDate} onInput={e=>setAltDate(e.currentTarget.value)} onChange={e=>setAltDate(e.target.value)}/></label>{altDate&&<label>Time · India<input type="time" required value={altTime} onInput={e=>setAltTime(e.currentTarget.value)} onChange={e=>setAltTime(e.target.value)}/></label>}<label>Reason<textarea required minLength={5} maxLength={600} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>The other party must agree. Alternatives stay within the same billing period and preserve the agreed visit price.</p><button disabled={busy}>Send change request</button></form></details>}</>}{p.changes.map(c=><div className="home-change" key={c.id}><strong>{c.new_date?`Move visit to ${c.new_date} · ${c.new_time}`:'Requested day off'}</strong><p>{c.reason} · {c.status}</p>{!admin&&c.status==='pending'&&c.proposer!==auth.currentUser?.uid&&<div className="home-actions">{[true,false].map(accept=><button key={String(accept)} disabled={busy} onClick={()=>void run(()=>homePost(`/home/plans/${p.id}/changes/${c.id}`,{expected_version:p.version,accept}))}>{accept?'Agree':'Decline change'}</button>)}</div>}</div>)}</>}
 {stage===2&&<>{p.invoices.map(i=><article className="home-invoice" key={i.id}><h3>{i.start} — {i.end}</h3><div className="home-status"><strong>{money(i.total_paise)}</strong><span>{label(i.status)}</span></div><p>{i.billing_note}</p>{i.unresolved&&<p>Some visits still need completion approval or team review.</p>}<details><summary>{i.rows.length} completed visit lines</summary>{i.rows.map(r=><div className="home-invoice-line" key={r.job_id}><span>{r.date}<small>Service {money(r.base_paise)} · GST {money(r.gst_paise)}{!!r.discount_paise&&<> · Saving {money(r.discount_paise)}</>}</small></span><strong>{money(r.amount_paise)}</strong></div>)}</details>{i.payment_id&&<p>Verified payment reference: {i.payment_id}</p>}{!worker&&!admin&&['ready','created','creating'].includes(i.status)&&i.total_paise>0&&<HomeInvoicePay planId={p.id} invoice={i} onRefresh={onRefresh}/>}</article>)}{!p.quote&&<p>Your billing schedule appears with the team’s quote.</p>}</>}
 {stage===3&&<><h3>Plan support</h3><p>Report missed visits, hygiene concerns, conduct or changes in the agreed work. For immediate danger, use local emergency services; this app does not monitor emergencies.</p>{!admin&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await homePost(`/home/plans/${p.id}/issues`,{reason:issue});setIssue('');});}}><label>Your concern<textarea required minLength={10} maxLength={2000} value={issue} onChange={e=>setIssue(e.target.value)}/></label><button disabled={busy}>Send to Repaido team</button></form>}{p.issues.map(i=><article className="home-change" key={i.id}><strong>{i.status}</strong><p>{i.reason}</p>{i.response&&<p>Team response: {i.response}</p>}</article>)}{!worker&&!admin&&!['cancelled','completed'].includes(p.state)&&<details><summary>Pause or end this plan</summary><p>No charge for unserved visits. Started work must be resolved. Paused dates are not silently moved or charged. Resume covers remaining future dates only.</p><label>Reason<textarea value={reason} minLength={5} onChange={e=>setReason(e.target.value)}/></label><div className="home-actions">{p.state==='active'&&<button disabled={busy||reason.length<5} onClick={()=>void decide('pause')}>Pause future visits</button>}{p.state==='paused'&&<button disabled={busy} onClick={()=>void decide('resume')}>Resume future visits</button>}<button disabled={busy||reason.length<5} onClick={()=>void decide('cancel')}>Cancel remaining visits</button></div></details>}</>}
 </div>;
}
function HomeInvoicePay({planId,invoice,onRefresh}:{planId:string;invoice:Invoice;onRefresh:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const pay=async()=>{setBusy(true);setError('');try{const order=await homePost<{key_id:string;order_id:string;amount:number;currency:string}>(`/home/plans/${planId}/invoices/${invoice.index}/order`,{});await loadCheckout();const widget=new window.Razorpay!({key:order.key_id,order_id:order.order_id,amount:order.amount,currency:order.currency,name:'Repaido',description:'Home plan monthly invoice',handler:async(result:{razorpay_payment_id:string})=>{try{await homePost(`/home/plans/${planId}/invoices/${invoice.index}/check`,{payment_id:result.razorpay_payment_id});await onRefresh();}catch(e){setError((e as Error).message);}},modal:{ondismiss:()=>setError('Checkout closed. Refresh billing to check payment before retrying.')}});widget.on('payment.failed',()=>setError('Payment not confirmed. Retry uses the same order; check billing first.'));widget.open();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};return <>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="ops-primary" onClick={()=>void pay()}>{busy?'Checking…':'Pay monthly invoice'}</button><button disabled={busy} onClick={()=>void onRefresh()}>Refresh payment status</button></>;}
export function WorkerHomeAvailability({services}:{services:HomeService[]}){
 const [a,setA]=useState<HomeAvailability>({version:0,services:[],weekdays:[0,1,2,3,4,5],start_time:'08:00',end_time:'18:00',off_dates:[],experience:''}),[off,setOff]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void operation<{availability:HomeAvailability|null}>('/home/worker-availability').then(d=>{if(d.availability){setA(d.availability);setOff(d.availability.off_dates.join(', '));}}).catch(e=>setError(e.message));},[]);
 return <form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');const {version,services,weekdays,start_time,end_time,experience}=a;void operation<HomeAvailability>('/home/worker-availability',{method:'PUT',body:JSON.stringify({version,services,weekdays,start_time,end_time,experience,off_dates:off.split(',').map(v=>v.trim()).filter(Boolean)})}).then(d=>{setA(d);setStatus('Schedule saved. New skills need team review before assignment.');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><fieldset><legend>Services you can provide</legend>{services.map(s=><label className="home-check" key={s.id}><input type="checkbox" checked={a.services.includes(s.id)} onChange={e=>setA({...a,services:e.target.checked?[...a.services,s.id]:a.services.filter(v=>v!==s.id)})}/>{s.name}</label>)}</fieldset><Weekdays value={a.weekdays} onChange={weekdays=>setA({...a,weekdays})}/><div className="home-form-grid"><label>From · India<input type="time" required value={a.start_time} onInput={e=>setA({...a,start_time:e.currentTarget.value})} onChange={e=>setA({...a,start_time:e.target.value})}/></label><label>Until · India<input type="time" required value={a.end_time} onInput={e=>setA({...a,end_time:e.currentTarget.value})} onChange={e=>setA({...a,end_time:e.target.value})}/></label></div><label>Days off (YYYY-MM-DD, separated by commas)<input value={off} onChange={e=>setOff(e.target.value)}/></label><label>Experience, training & qualifications<textarea required minLength={10} maxLength={1000} value={a.experience} onChange={e=>setA({...a,experience:e.target.value})}/></label><p>Approved services: {a.approved_services?.map(id=>services.find(s=>s.id===id)?.name||id).join(', ')||'Awaiting team review'}. Existing commitments require an agreed day change.</p>{a.review_reason&&<p>{a.review_reason}</p>}{error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}<button className="ops-primary" disabled={busy||!a.services.length||!a.weekdays.length}>{busy?'Saving…':'Save schedule for review'}</button></form>;
}
export function HomeVisitChecks({job,onRefresh}:{job:Job;onRefresh:()=>Promise<void>}){
 const saved=job.state==='arrived'?job.home_arrival_log:job.home_daily_log;const [checked,setChecked]=useState(saved?.checked||[]),[hygiene,setHygiene]=useState(saved?.hygiene||false),[note,setNote]=useState(saved?.note||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <form className="home-plans" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void homePost(`/home/jobs/${job.id}/log`,{expected_version:job.version,hygiene,checked,note}).then(onRefresh).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><p>{job.state==='arrived'?'Confirm arrival and the agreed hygiene precautions.':'Record today’s agreed work before submitting completion.'} Keep notes about service delivery; do not add diagnoses or take photos of the recipient.</p><label className="home-check"><input type="checkbox" required checked={hygiene} onChange={e=>setHygiene(e.target.checked)}/>Agreed hygiene precautions completed</label>{job.state!=='arrived'&&job.home_checklist?.map((t,i)=><label className="home-check" key={i}><input type="checkbox" checked={checked.includes(i)} onChange={e=>setChecked(e.target.checked?[...checked,i]:checked.filter(n=>n!==i))}/>{t}</label>)}<label>Service note<textarea required minLength={5} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Saved at {new Date(saved.at*1000).toLocaleTimeString()}</p>}<button className="ops-primary" disabled={busy||!hygiene||!['arrived','in_progress'].includes(job.state)}>Save visit checks</button></form>;
}

export function HomeBrief({plan,admin=false}:{plan:Pick<HomePlan,'id'|'brief_rows'|'instructions'>;admin?:boolean}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const download=async()=>{setBusy(true);setError('');try{const token=await auth.currentUser?.getIdToken();const response=await apiFetch(`/api/operations/${admin?'admin/':''}home/plans/${plan.id}/brief.pdf`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw Error('Could not download your work brief. Please retry.');const blob=await response.blob();if(nativeAvailable()){const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));await nativeCall('saveReport',{data:btoa(binary),filename:'Repaido-work-brief.pdf'});return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Repaido-work-brief.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <details className="home-brief"><summary>Customer requirements & team brief</summary><dl>{plan.brief_rows?.map(r=><div key={r.label}><dt>{r.label}</dt><dd>{r.value}</dd></div>)}<div><dt>Work instructions</dt><dd>{plan.instructions||'Not supplied'}</dd></div></dl><button disabled={busy} onClick={()=>void download()}>{busy?'Preparing…':'Download work brief PDF'}</button>{error&&<p role="alert">{error}</p>}</details>;
}
