import {useEffect,useState} from 'react';
import {operation,money} from '../services/operations';
import {PlanDetail,homeCatalog,homePost,type HomePlan,type HomeAvailability,type HomeService} from './HomePlans';
export function HomePlanAdmin(){
 const [data,setData]=useState<{plans:HomePlan[];availability:HomeAvailability[];candidates:Record<string,{id:string;name:string;rating:number|null;review_count:number}[]>;issues:{id:string;plan_id:string;reason:string;status:string}[]}>(),[services,setServices]=useState<HomeService[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);setError('');try{setData(await operation('/admin/home'));setServices((await homeCatalog()).services);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const p=data?.plans.find(p=>p.id===selected);
 return <section className="home-plans"><div className="home-section-head"><div><span className="home-eyebrow">OPERATIONS · REPAIDO HOME</span><h2>Plans, care & home projects</h2></div><button disabled={busy} onClick={()=>void load()}>Refresh</button></div><p>Review role qualifications and recipient consent, agree scope and price, then invite an available professional. Monthly plans need both parties’ acceptance. No clinical care or absolute safety guarantee is advertised.</p>{error&&<p className="ops-error" role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading plans…</p>}<div className="home-admin-layout"><aside><h3>Plan requests</h3>{data?.plans.map(p=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>setSelected(p.id)}><strong>{services.find(s=>s.id===p.service_id)?.name}</strong><span>{p.recipient_name} · {p.city}</span><small>{p.start_date} · {p.state.replaceAll('_',' ')}</small></button>)}{data&&!data.plans.length&&<p>No plan requests yet.</p>}<h3>Home-service skill reviews</h3>{data?.availability.map(a=><details key={a.worker_id}><summary>{a.name} · {a.approved_services?.length||0} approved</summary><HomeSkillReview availability={a} services={services} onRefresh={load}/></details>)}</aside><main>{p?<><h3>{p.recipient_name} · {p.city}</h3><p>{p.address}</p><p>{p.instructions}</p>{p.preferred_worker_name&&<p>Customer preference: <strong>{p.preferred_worker_name}</strong>. Both parties must accept the quoted professional.</p>}{['requested','offered'].includes(p.state)&&!p.customer_accepted_at&&!p.worker_accepted_at&&<HomeQuote key={p.id+':'+p.version} plan={p} candidates={data?.candidates[p.id]||[]} onRefresh={load}/>}<PlanDetail plan={p} admin onRefresh={load} onJob={()=>{}}/>{data?.issues.filter(i=>i.plan_id===p.id&&i.status==='open').map(i=><IssueReply key={i.id} issue={i} onRefresh={load}/>)}</>:<div className="home-empty">Choose a plan to see its full calendar, attendance, quote and concerns.</div>}</main></div></section>;
}
function HomeSkillReview({availability:a,services,onRefresh}:{availability:HomeAvailability;services:HomeService[];onRefresh:()=>Promise<void>}){const [approved,setApproved]=useState(a.approved_services||[]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={e=>{e.preventDefault();setBusy(true);void homePost(`/admin/home/workers/${a.worker_id}/review`,{expected_version:a.version,approved_services:approved,reason}).then(onRefresh).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><p>{a.experience}</p><p>{a.start_time}–{a.end_time} IST · Days off: {a.off_dates.join(', ')||'None listed'}</p>{a.services.map(id=><label className="home-check" key={id}><input type="checkbox" checked={approved.includes(id)} onChange={e=>setApproved(e.target.checked?[...approved,id]:approved.filter(v=>v!==id))}/>{services.find(s=>s.id===id)?.name||id}</label>)}<label>Qualification, safeguarding / hygiene review evidence<textarea required minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Use relevant training and qualification evidence. Do not approve nursing or medical work through this non-medical service.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy}>Save skill review</button></form>;}
function HomeQuote({plan:p,candidates,onRefresh}:{plan:HomePlan;candidates:{id:string;name:string;rating:number|null;review_count:number}[];onRefresh:()=>Promise<void>}){
 const [worker,setWorker]=useState(p.worker_id||''),[price,setPrice]=useState(p.quote?String(p.quote.period_price_paise/100):''),[gst,setGst]=useState(p.quote?String(p.quote.gst_bps/100):''),[tasks,setTasks]=useState(p.quote?.checklist.join('\n')||''),[excluded,setExcluded]=useState(p.quote?.exclusions||''),[terms,setTerms]=useState(p.quote?.terms||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="home-quote" open><summary>Prepare scope & quote</summary><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void homePost(`/admin/home/plans/${p.id}/quote`,{expected_version:p.version,worker_id:worker,period_price_paise:Math.round(Number(price)*100),gst_bps:Math.round(Number(gst)*100),checklist:tasks.split('\n').map(s=>s.trim()).filter(Boolean),exclusions:excluded,terms}).then(onRefresh).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Eligible professional<select required value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Choose a reviewed professional</option>{candidates.map(w=><option key={w.id} value={w.id}>{w.name} · {w.rating?`${w.rating.toFixed(1)} (${w.review_count} reviews)`:'No reviews yet'}</option>)}</select></label>{!candidates.length&&<p role="status">No reviewed professional covers all days, hours, city and service radius. Review skills / availability or agree a different schedule with the customer.</p>}<div className="home-form-grid"><label>₹ per {p.duration==='trial7'?'7-day plan':p.duration==='project'?'project visit':'monthly period'} before GST<input required min="1" type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Applicable GST % (enter approved rate)<input required type="number" min="0" max="30" step="0.01" value={gst} onChange={e=>setGst(e.target.value)}/></label></div><label>Agreed visit tasks (one per line, maximum 12)<textarea required value={tasks} onChange={e=>setTasks(e.target.value)}/></label><label>Exclusions & materials<textarea required minLength={10} maxLength={1500} value={excluded} onChange={e=>setExcluded(e.target.value)}/></label><label>Scope, safety, responsibilities & terms<textarea required minLength={20} maxLength={3000} value={terms} onChange={e=>setTerms(e.target.value)}/></label><p>{p.visits.length} visits. Each period’s {price?money(Number(price)*100):'quoted fee'} is allocated across its scheduled visits. Unserved visits are not collected. Parts/extra work require customer approval. No automatic renewal.</p>{error&&<p role="alert">{error}</p>}<button className="ops-primary" disabled={busy||!candidates.length}>Send quote to both parties</button></form></details>;
}
function IssueReply({issue:i,onRefresh}:{issue:{id:string;reason:string};onRefresh:()=>Promise<void>}){const [response,setResponse]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="home-concern" onSubmit={e=>{e.preventDefault();setBusy(true);void homePost('/admin/home/issues/'+i.id+'/resolve',{response}).then(onRefresh).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><h3>Open concern</h3><p>{i.reason}</p><label>Resolution & follow-up<textarea required minLength={10} maxLength={2000} value={response} onChange={e=>setResponse(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>Send resolution</button></form>;}
