import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {MapPin,Navigation,Share2,ShieldCheck,Maximize,Minimize} from 'lucide-react';
import {auth} from '../firebase';
import {business,businessPublic} from '../services/localBusiness';
import {currentPosition} from '../services/operations';
import {nativeAvailable,nativeCall} from '../services/native';
import {ContractError,useCustomContractAction} from './customContractUI';
import './journey-tracking.css';

type Point={lat:number;lng:number};
export function JourneyMap({position,origin,destination,route=[]}:{position?:Point|null;origin?:Point;destination?:Point;route?:Point[]}){
 const element=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),marker=useRef<L.CircleMarker|null>(null),[full,setFull]=useState(false);
 useEffect(()=>{if(!element.current)return;const m=L.map(element.current,{zoomControl:true,scrollWheelZoom:true});map.current=m;L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{attribution:'© OpenStreetMap © CARTO',maxZoom:19}).addTo(m);const points=[origin,destination,...route].filter(Boolean) as Point[];for(const [pin,label] of [[origin,'Pickup / origin'],[destination,'Drop-off / destination']] as const){if(pin)L.circleMarker([pin.lat,pin.lng],{radius:8,color:'#142858',fillColor:'#e9c877',fillOpacity:1}).addTo(m).bindTooltip(label);}
 if(route.length)L.polyline(route.map(p=>[p.lat,p.lng]),{color:'#406dbe',weight:4}).addTo(m);if(points.length>1)m.fitBounds(L.latLngBounds(points.map(p=>[p.lat,p.lng])),{padding:[24,24],maxZoom:15});else m.setView([origin?.lat||20.3,origin?.lng||85.8],13);const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(element.current);return()=>{observer.disconnect();m.remove();map.current=null;marker.current=null;};},[origin?.lat,origin?.lng,destination?.lat,destination?.lng,JSON.stringify(route)]);
 useEffect(()=>{if(!map.current)return;if(position){if(marker.current)marker.current.setLatLng([position.lat,position.lng]);else marker.current=L.circleMarker([position.lat,position.lng],{radius:11,color:'#fff',weight:3,fillColor:'#175ee5',fillOpacity:1}).addTo(map.current).bindTooltip('Latest vehicle position');}else if(marker.current){marker.current.remove();marker.current=null;}},[position?.lat,position?.lng,origin?.lat,origin?.lng,destination?.lat,destination?.lng,JSON.stringify(route)]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setFull(false);};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 return <div className={`journey-map${full?' is-fullscreen':''}`}><div ref={element} className="journey-leaflet" aria-label="Journey map"/><div className="journey-map-tools"><button aria-label={full?'Exit fullscreen map':'Fullscreen journey map'} onClick={()=>setFull(!full)}>{full?<Minimize size={18}/>:<Maximize size={18}/>}</button>{position&&<button aria-label="Centre on vehicle" onClick={()=>map.current?.setView([position.lat,position.lng],16)}><Navigation size={18}/></button>}</div></div>;
}
export function JourneyTracking({kind,id,canSend=false,rental=false,passengerId,canShare=false,guestToken}:{kind:'rides'|'shared';id:string;canSend?:boolean;rental?:boolean;passengerId?:string;canShare?:boolean;guestToken?:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[sharing,setSharing]=useState(false),[background,setBackground]=useState(false),[link,setLink]=useState(''),[clock,setClock]=useState(Date.now());const receipt=useRef(0),action=useCustomContractAction(),uid=auth.currentUser?.uid;
 const path=`/journeys/${kind}/${id}`;
 useEffect(()=>{let cancelled=false;setData(null);setLink('');const refresh=async()=>{try{const value=guestToken?await businessPublic('/guest-tracking/'+encodeURIComponent(guestToken)):await business(path+'/tracking');if(!cancelled){receipt.current=Date.now();setData(value);setError('');}}catch(e){if(!cancelled){setError((e as Error).message);setData(null);}}};void refresh();const t=setInterval(()=>{setClock(Date.now());if(!document.hidden)void refresh();},10000);return()=>{cancelled=true;clearInterval(t);};},[path,guestToken,uid]);
 useEffect(()=>{if(!sharing||background)return;let stopped=false,running=false;const send=async()=>{if(stopped||running||document.hidden)return;running=true;try{const position=await currentPosition(true);if(!stopped&&auth.currentUser?.uid===uid){await business(path+'/position',position);setError('');}}catch(e){if(!stopped)setError((e as Error).message);}finally{running=false;}};void send();const timer=setInterval(()=>void send(),12000);return()=>{stopped=true;clearInterval(timer);};},[sharing,background,path,uid]);
 useEffect(()=>{if(data&&['completed','cancelled','completion_pending','balance_due','expired','disputed'].includes(data.state)){setSharing(false);setLink('');if(background)void nativeCall('stopTracking').catch(()=>{});setBackground(false);}},[data?.state]);
 const toggle=()=>action.run(async()=>{if(sharing){await business(path+'/consent',{enabled:false});if(background)await nativeCall('stopTracking');setSharing(false);setBackground(false);return;}await business(path+'/consent',{enabled:true});if(!rental&&nativeAvailable()){const session=await business(path+'/tracking-session',{enabled:true});try{await nativeCall('startTracking',{token:session.token});setBackground(true);}catch(e){await business(path+'/consent',{enabled:false});throw e;}}setSharing(true);});
 const live=data?.position&&data.server_time-data.position.received_at+Math.max(0,clock-receipt.current)/1000<=75?data.position:null;
 return <section className="journey-tracking" aria-label="Journey live location"><header><ShieldCheck size={18}/><strong>{data?.vehicle_name||'Journey tracking'}</strong><span>{data?.state?.replaceAll('_',' ')}</span></header><ContractError error={error}/><ContractError error={action.error}/>{data&&<><JourneyMap position={live} origin={data.origin} destination={data.destination} route={data.route}/><p className="business-note" role="status">{live?`Location updated ${Math.max(0,Math.round(data.server_time-live.received_at+(clock-receipt.current)/1000))}s ago${live.source==='vehicle_tracker'?' · Vehicle tracker':live.source==='renter_phone'?' · Renter’s phone':live.source?' · Driver’s phone':''}.`:data.location_status==='ended'?'This journey has ended.':'Waiting for a fresh location. No current position is available.'}{live?.outside_route&&' The latest position is outside the planned route.'}</p></>}{!guestToken&&canSend&&<><button disabled={action.busy} onClick={()=>void toggle()}><Navigation size={16}/>{sharing?'Stop sharing my location':'Enable journey location'}</button><p className="business-note">{sharing&&background?'Android is sharing location through its foreground tracking service.':rental?'Share your phone location with the vehicle owner during this rental. An installed vehicle tracker requires your consent too.':'Allow precise GPS. Keep this page open while driving; the Agent Android app supports background sharing.'}</p></>}{!guestToken&&rental&&!canSend&&<p className="business-note">An installed tracker shows the vehicle’s position. A renter-phone reading is labelled separately.</p>}{!guestToken&&canShare&&data?.state==='in_progress'&&<div className="journey-share"><button disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await business(path+'/share',{passenger_id:passengerId||null});setLink(window.location.origin+'/?ride-share#'+result.token);})}><Share2 size={16}/>Create family tracking link</button>{link&&<><label>Private journey link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button onClick={()=>void action.run(async()=>{if(navigator.share)await navigator.share({title:'My Repaido journey',url:link});else {await navigator.clipboard.writeText(link);}})}>Share link</button><button onClick={()=>void action.run(async()=>{await business(path+'/share',{},'DELETE');setLink('');})}>Revoke link</button><p className="business-note">Anyone with this link can view your active ride. It expires at drop-off or journey end, and after 24 hours.</p></>}</div>}</section>;
}
export function GuestJourney(){const token=window.location.hash.slice(1);useEffect(()=>{const meta=document.createElement('meta');meta.name='referrer';meta.content='no-referrer';document.head.append(meta);return()=>meta.remove();},[]);return <main className="guest-journey local-business-hub"><header className="business-compact-heading"><div><small>REPAIDO · JOURNEY SAFETY</small><h1>Family ride tracking</h1></div><MapPin size={24}/></header>{token?<JourneyTracking kind="rides" id="guest" guestToken={token}/>:<p>This journey link is incomplete.</p>}<p className="business-note">No sign-in needed. The link closes when the passenger’s ride ends. GPS depends on the sender’s device and connection.</p></main>;}
