import {auth} from '../firebase';
import {nativeAvailable,enableNativePush,stopNativeSession} from '../services/native';
import {useEffect,useRef,useState} from 'react';
import {operation,money,type Job} from '../services/operations';

function persistentId(scope:string,payload:string){
 const key='repaido.lifecycle.intent.'+JSON.stringify([scope,payload]);
 const existing=sessionStorage.getItem(key);if(existing)return existing;
 const id=crypto.randomUUID();sessionStorage.setItem(key,id);return id;
}
function supportDraft(key:string){try{return sessionStorage.getItem(key)||'';}catch{return '';}}
type Case={assigned_to?:string;id:string;job_id?:string;category:string;state:string;version:number;resolution?:string};
type Thread={case:Case;messages:{id:string;actor_role:string;message:string;created_at:number}[]};
export const post=(path:string,body:object)=>operation(path,{method:'POST',body:JSON.stringify(body)});
export function SupportCenter({jobId,admin=false,onSignIn}:{jobId?:string;admin?:boolean;onSignIn?:()=>void}){
 const draftKey='repaido.support-draft.'+(jobId||'general')+(admin?'.admin':'');
 const [cases,setCases]=useState<Case[]>([]),[thread,setThread]=useState<Thread|null>(null),[text,setText]=useState(()=>supportDraft(draftKey)),[category,setCategory]=useState(jobId?'booking':'general'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const [stateFilter,setStateFilter]=useState('all');
 const prefix=admin?'/admin/support':'/support';
 const request=useRef<{text:string;key:string}>({text:'',key:crypto.randomUUID()});
 const key=(value:string)=>{if(request.current.text!==value)request.current={text:value,key:persistentId(prefix,value)};return request.current.key;};
 const load=async()=>{const d=await operation<{cases:Case[]}>(prefix);setCases(d.cases.filter(c=>!jobId||c.job_id===jobId));setLoaded(true);};
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void run(load);},[jobId,admin]);
 useEffect(()=>{sessionStorage.setItem(draftKey,text);},[draftKey,text]);
 const open=async(id:string)=>{setThread(await operation<Thread>(`${prefix}/${id}`));setText('');};
 return <section className="operations ops-card"><h3>{admin?'Support inbox':'Help with your service'}</h3><p>Keep messages about your booking here. Do not include identity documents, bank details or passwords. For an immediate emergency, contact local emergency services.</p>{error&&<p role="alert" className="ops-error">{error}{onSignIn&&error.toLowerCase().includes('sign')&&<button onClick={onSignIn}>Sign in</button>}</p>}<button disabled={busy} onClick={()=>void run(async()=>{await load();if(thread)await open(thread.case.id);})}>Refresh messages</button>
 {admin&&<label>Case status<select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="all">All cases</option><option value="open">Open · needs attention</option><option value="escalated">Escalated · urgent review</option><option value="resolved">Resolved</option></select></label>}{loaded&&!cases.length&&<p>No support cases yet.</p>}<div className="support-case-grid">{cases.filter(c=>stateFilter==='all'||c.state===stateFilter).map(c=><button className={`support-case ${c.state==='resolved'?'status-green':c.state==='escalated'?'status-red':'status-orange'}`} key={c.id} disabled={busy} onClick={()=>void run(()=>open(c.id))}>{c.category} · {c.state} · {c.id.slice(0,8)}</button>)}</div>
 {thread?<><div className="ops-notice"><h4>{thread.case.category} · {thread.case.state}</h4>{admin&&<div className="ops-actions"><span>{!thread.case.assigned_to?'Unassigned':thread.case.assigned_to===auth.currentUser?.uid?'Assigned to you':'Assigned to a teammate'}</span><button disabled={busy||!!thread.case.assigned_to&&thread.case.assigned_to!==auth.currentUser?.uid} onClick={()=>void run(async()=>{await post(`/admin/support/${thread.case.id}/claim`,{expected_version:thread.case.version,release:thread.case.assigned_to===auth.currentUser?.uid});await open(thread.case.id);await load();})}>{thread.case.assigned_to===auth.currentUser?.uid?'Release to team':'Assign to me'}</button></div>}{thread.case.job_id&&<p>Booking: {thread.case.job_id}</p>}{thread.messages.map(m=><article key={m.id}><strong>{m.actor_role==='support'?'Repaido support':'You'}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.message}</p><small>{new Date(m.created_at*1000).toLocaleString()}</small></article>)}{thread.case.resolution&&<p>Latest decision: {thread.case.resolution}</p>}</div><label>{thread.case.state==='resolved'?'Reason to reopen':'Message or resolution reason'}<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={3000}/></label>
 {thread.case.state!=='resolved'&&<button disabled={busy||!text.trim()} onClick={()=>void run(async()=>{await post(`${prefix}/${thread.case.id}/messages`,{message:text,request_id:key(thread.case.id+text)});await open(thread.case.id);await load();})}>Send reply</button>}
 <button disabled={busy||text.trim().length<10} onClick={()=>void run(async()=>{await post(`${prefix}/${thread.case.id}/actions`,{action:thread.case.state==='resolved'?'reopen':admin?'resolve':'escalate',reason:text,expected_version:thread.case.version});await open(thread.case.id);await load();})}>{thread.case.state==='resolved'?'Reopen case':admin?'Record resolution':'Request escalation'}</button><button onClick={()=>{setThread(null);setText('');}}>Back to cases</button></>:!admin&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{const c=await post('/support',{job_id:jobId||null,category,message:text,request_id:key(category+text)}) as Case;await load();await open(c.id);});}}><label>What do you need help with?<select value={category} onChange={e=>setCategory(e.target.value)}>{(jobId?['booking','warranty','payment','penalty','safety']:['general','safety']).map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>Tell us what happened<textarea required minLength={5} maxLength={3000} value={text} onChange={e=>setText(e.target.value)}/></label><button className="ops-primary" disabled={busy||text.trim().length<5}>{busy?'Saving…':'Send to Repaido support'}</button></form>}
 </section>;
}

type Resolution={id:string;status:string;proposal:{action:string;reason:string;final_paise?:number;final_base_paise?:number;starts_at?:string}};
export function BookingRecovery({job,worker,onRefresh}:{job:Job;worker:boolean;onRefresh:()=>Promise<void>}){
 const [proposals,setProposals]=useState<Resolution[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<{document_type:string;final_total_paise:number;payment_status:string;tax_note:string}|null>(null);
 const load=async()=>setProposals((await operation<{resolutions:Resolution[]}>(`/jobs/${job.id}/resolutions`)).resolutions);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await onRefresh();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[job.id,job.version]);
 return <><section className="ops-card"><h3>Booking help & records</h3>{error&&<p role="alert" className="ops-error">{error}</p>}
 {proposals.filter(p=>p.status==='pending').map(p=><article className="ops-notice" key={p.id}><h4>Proposed {p.proposal.action.replaceAll('_',' ')}</h4><p>{p.proposal.reason}</p>{p.proposal.starts_at&&<p>{new Date(p.proposal.starts_at).toLocaleString()}</p>}{p.proposal.final_paise!==undefined&&<p>Final total {money(p.proposal.final_paise)} · service {money(p.proposal.final_base_paise||0)} · approved parts {money(p.proposal.final_paise-(p.proposal.final_base_paise||0))}</p>}{!worker&&<><p>Accept only if this resolves your issue. Your approval is recorded with this booking.</p>{[true,false].map(accept=><button key={String(accept)} disabled={busy} onClick={()=>void run(()=>post(`/resolutions/${p.id}/decision`,{accept,expected_version:job.version}))}>{accept?'Accept resolution':'Decline resolution'}</button>)}</>}</article>)}
 {(['en_route','arrived','in_progress','collecting_parts','follow_up_required'].includes(job.state))&&<><label>Reason / arrival confirmation<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label>{!worker&&job.state==='en_route'?<button disabled={busy||reason.trim().length<5} onClick={()=>void run(()=>post(`/jobs/${job.id}/confirm-arrival`,{reason}))}>I confirm the professional is here</button>:job.state!=='en_route'&&<button disabled={busy||reason.trim().length<5} onClick={()=>void run(()=>post(`/jobs/${job.id}/stop-request`,{reason}))}>Stop work and request support review</button>}</>}
 <button disabled={busy} onClick={()=>void run(async()=>setReceipt(await operation(`/jobs/${job.id}/receipt`)))}>View service statement / receipt</button>{receipt&&<div className="ops-notice"><h4>{receipt.document_type.replaceAll('_',' ')}</h4><p>{money(receipt.final_total_paise)} · {receipt.payment_status}</p><p>{receipt.tax_note}</p></div>}
 {job.review&&<details><summary>Review replies & reporting</summary><p>{job.review.rating}/5 · {job.review.text}</p><label>Reply or report reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label>{worker&&<button disabled={busy||reason.length<5} onClick={()=>void run(()=>post(`/jobs/${job.id}/review/reply`,{text:reason}))}>Publish worker reply</button>}<button disabled={busy||reason.length<5} onClick={()=>void run(()=>post(`/jobs/${job.id}/review/report`,{reason}))}>Report for moderation</button></details>}
 </section><SupportCenter jobId={job.id}/></>;
}

export function AdminRecovery({job,onRefresh}:{job:Job;onRefresh:()=>Promise<void>}){
 const [action,setAction]=useState('resume'),[reason,setReason]=useState(''),[date,setDate]=useState(''),[amount,setAmount]=useState(''),[base,setBase]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const request=useRef<{body:string;key:string}>({body:'',key:crypto.randomUUID()});
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <details><summary>Resolve booking / review penalties</summary>{error&&<p role="alert" className="ops-error">{error}</p>}<label>Evidence and reason<textarea value={reason} minLength={20} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>
 {['disputed','stop_requested','follow_up_required','completion_pending'].includes(job.state)&&<><label>Proposed resolution<select value={action} onChange={e=>setAction(e.target.value)}>{['resume','follow_up','reassign','partial_close'].map(a=><option key={a}>{a}</option>)}</select></label>{['follow_up','reassign'].includes(action)&&<label>Requested next visit<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label>}{action==='partial_close'&&<><label>Final total (₹)<input type="number" min="0" step=".01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Final service charge (₹), excluding parts<input type="number" min="0" step=".01" value={base} onChange={e=>setBase(e.target.value)}/></label></>}<p>The customer must approve this proposal. Existing payment or payout attempts require finance reconciliation first.</p><button disabled={busy||reason.trim().length<20} onClick={()=>void run(async()=>{const body={action,reason,expected_version:job.version,starts_at:date?new Date(date).toISOString():null,final_paise:action==='partial_close'?Math.round(Number(amount)*100):null,final_base_paise:action==='partial_close'?Math.round(Number(base)*100):null};const serial=JSON.stringify(body);if(request.current.body!==serial)request.current={body:serial,key:persistentId('recovery:'+job.id,serial)};await post(`/admin/jobs/${job.id}/resolution`,{...body,request_id:request.current.key});})}>Send proposal for customer approval</button></>}
 {job.penalties.map((p,i)=><div key={i}><p>{p.code} · {p.status}</p>{['waive','uphold'].map(decision=><button key={decision} disabled={busy||reason.trim().length<20} onClick={()=>void run(()=>post(`/admin/jobs/${job.id}/penalty-review`,{code:p.code,visit_id:p.visit_id,decision,reason}))}>{decision==='waive'?'Waive assessment':'Uphold assessment'}</button>)}</div>)}
 </details>;
}

export function RefundReview(){
 const [paymentRecord,setPaymentRecord]=useState('');
 const [rows,setRows]=useState<{id:string;job_id:string;status:string;amount_paise:number}[]>([]),[job,setJob]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const request=useRef<{body:string;key:string}>({body:'',key:crypto.randomUUID()});
 const load=async()=>setRows((await operation<{refunds:typeof rows}>('/admin/refunds')).refunds);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="ops-card"><h3>Refund review</h3><p>Refunds require a verified captured payment. An uncertain response stays pending; reconciliation never submits another refund. Existing payouts require separate recovery before a refund can be sent.</p>{error&&<p role="alert" className="ops-error">{error}</p>}<button disabled={busy} onClick={()=>void run(load)}>Load refund records</button><label>Booking ID<input value={job} onChange={e=>setJob(e.target.value)}/></label><label>Parts payment record ID (leave blank for final invoice)<input value={paymentRecord} onChange={e=>setPaymentRecord(e.target.value)}/></label><label>Amount to refund (₹)<input type="number" min=".01" step=".01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Approval reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!job||Number(amount)<=0||reason.trim().length<20} onClick={()=>void run(async()=>{const body={amount_paise:Math.round(Number(amount)*100),reason,payment_record_id:paymentRecord.trim()||null};const serial=job+JSON.stringify(body);if(request.current.body!==serial)request.current={body:serial,key:persistentId('refund:'+job,serial)};await post(`/admin/jobs/${encodeURIComponent(job)}/refund`,{...body,request_id:request.current.key});})}>Authorize refund of {money(Math.max(0,Number(amount)*100))}</button>{rows.map(r=><article key={r.id}><p>{r.job_id} · {money(r.amount_paise)} · {r.status}</p><button disabled={busy} onClick={()=>void run(()=>post(`/admin/refunds/${r.id}/reconcile`,{}))}>Check provider outcome</button></article>)}</section>;
}

export function NotificationInbox({onOpen}:{onOpen:(job?:string)=>void}){
 const [rows,setRows]=useState<{id:string;title:string;body:string;job_id?:string;destination?:string;campaign_id?:string;plan_id?:string;read_at?:number}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const load=async()=>{setBusy(true);setError('');try{
   const backendNotifs = (await operation<{notifications:typeof rows}>('/notifications').catch(()=>({notifications:[]}))).notifications || [];
   const b2bNotifsStr = typeof localStorage !== 'undefined' ? localStorage.getItem('repaido_b2b_notifications_v1') : null;
   const b2bNotifs = b2bNotifsStr ? JSON.parse(b2bNotifsStr) : [];
   setRows([...b2bNotifs, ...backendNotifs]);
   setLoaded(true);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 return <section className="operations">{nativeAvailable()&&<><button disabled={busy} onClick={async()=>{setBusy(true);try{await enableNativePush();setError('Notifications enabled on this device.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Enable background booking notifications</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await stopNativeSession();setError('Device notifications disabled.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Disable device notifications</button></>}<button disabled={busy} onClick={()=>void load()}>Refresh updates</button>{error&&<p role="alert">{error}</p>}{loaded&&!rows.length&&<p>No updates yet. Your booking updates will appear here.</p>}{rows.map(n=><article className="ops-card" key={n.id}><h3>{n.title}{!n.read_at?' · New':''}</h3><p>{n.body}</p><button disabled={busy} onClick={async()=>{setBusy(true);try{if(!n.id.startsWith('notif-b2b'))await post(`/notifications/${n.id}/read`,{});if(n.destination==='b2b_quotation')window.location.assign('/?tab=ShopSpares&marketSub=b2b');else if(n.destination==='home_plan')window.location.assign((location.pathname.startsWith('/worker')?'/worker':'/')+'?home-plan='+encodeURIComponent(n.plan_id||''));else if(n.destination==='promotion')window.location.assign('/?campaign='+encodeURIComponent(n.campaign_id||''));else if(n.destination==='wallet')window.location.assign('/worker?tab=wallet');else if(n.destination==='exchange'||n.destination==='second_hand')window.location.assign('/?market='+n.destination);else if(n.destination==='hire')window.location.assign(location.pathname.startsWith('/worker')?'/worker?tab=hire':'/?hiring=1');else if(n.destination==='contractor')window.location.assign('/worker?mode=technician&tab=projects');else if(n.destination==='onboarding')window.location.assign('/worker');else onOpen(n.job_id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Open {n.destination==='b2b_quotation'?'quotation & PDF':n.destination==='contractor'?'project teams':n.destination==='promotion'?'offer':n.destination==='wallet'?'wallet':n.destination==='onboarding'?'application':n.destination==='exchange'?'exchange listings':n.destination==='second_hand'?'used-item listings':'booking'}</button></article>)}</section>;
}

export function EvidenceReview(){
 const [corrections,setCorrections]=useState<{worker_id:string;status:string}[]>([]),[reports,setReports]=useState<{id:string;job_id:string;reason:string;state:string}[]>([]),[worker,setWorker]=useState(''),[source,setSource]=useState(''),[kind,setKind]=useState('assignment'),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setCorrections((await operation<{corrections:typeof corrections}>('/admin/rewards')).corrections);setReports((await operation<{reports:typeof reports}>('/admin/review-reports')).reports);};
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="ops-card"><h3>Evidence & review moderation</h3><p>Correct proven measurement errors only. Reviews and ratings stay unchanged. Record the evidence before resolving a worker’s review request.</p>{error&&<p role="alert" className="ops-error">{error}</p>}<button disabled={busy} onClick={()=>void run(load)}>Load review queues</button><label>Reason and evidence reference<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={20} maxLength={1000}/></label>{corrections.map(c=><article key={c.worker_id}><p>{c.worker_id} · {c.status}</p>{['resolved_no_change','hold_for_evidence'].map(decision=><button key={decision} disabled={busy||reason.length<20} onClick={()=>void run(()=>post(`/admin/rewards/${c.worker_id}/review`,{decision,reason}))}>{decision==='resolved_no_change'?'Close evidence review':'Keep on hold for evidence'}</button>)}</article>)}<details><summary>Correct a source metric</summary><label>Worker ID<input value={worker} onChange={e=>setWorker(e.target.value)}/></label><label>Metric type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="assignment">Assignment response</option><option value="acknowledgement">Visit reminder acknowledgement</option></select></label><label>Assignment metric ID / booking ID<input value={source} onChange={e=>setSource(e.target.value)}/></label>{[true,false].map(exclude=><button key={String(exclude)} disabled={busy||!worker||!source||reason.length<20} onClick={()=>void run(()=>post(`/admin/reward-metrics/${encodeURIComponent(worker)}/correction`,{source_kind:kind,source_id:source,exclude,reason}))}>{exclude?'Exclude proven invalid measurement':'Restore valid measurement'}</button>)}</details>{reports.map(r=><article key={r.id}><p>Booking {r.job_id} · {r.state}</p><p>{r.reason}</p><button disabled={busy||reason.length<20||r.state!=='pending'} onClick={()=>void run(()=>post(`/admin/review-reports/${r.id}/resolve`,{reason}))}>Record moderation decision</button></article>)}</section>;
}
