import {CouponField,type Coupon} from './Coupons';
import {PromotionRail,type Promotion} from './Promotions';
import {auth} from '../firebase';
import {onIdTokenChanged} from 'firebase/auth';
import {ServiceTerms,type TermsRecord} from './ServiceTerms';
import { apiFetch } from '../services/api';
import {useEffect,useRef,useState} from 'react';
import {Modal} from './ui';
import {LocationPickerModal} from './LocationPickerModal';
import {currentPosition,money,operation,type Job} from '../services/operations';
import type {Service} from '../types';
import './operations.css';
import ServiceImage from './ServiceImage';

export default function LiveBooking({service,city,onClose,onSignIn,onBooked,promotionId,onRemovePromotion,onPromotion}:{service:Service;city:string;onClose:()=>void;onSignIn:()=>void;onBooked:()=>void;promotionId?:string;onRemovePromotion?:()=>void;onPromotion?:(c:Promotion)=>void}) {
  const [serviceTerms,setServiceTerms]=useState<TermsRecord|null>(null);
  const draftKey = `repaido.booking-draft.${service.id}`;
  const [saved] = useState(()=>{try{return JSON.parse(sessionStorage.getItem(draftKey)||'{}');}catch{return {};}});
  const [savedAddresses,setSavedAddresses]=useState<{id:string;label:string;address:string;city:string;location:{lat:number;lng:number}}[]>([]);
  const [bookingCity,setBookingCity]=useState(saved.city||city);
  const [catalog,setCatalog]=useState<{id:string;name:string;category:string;price_paise:number;included:string[];excluded:string[]}[]>([]);
  const [serviceId,setServiceId]=useState(''),[pin,setPin]=useState<{lat:number;lng:number}|null>(saved.pin||null),[map,setMap]=useState(false);
  const [address,setAddress]=useState(saved.address||''),[phone,setPhone]=useState(saved.phone||''),[date,setDate]=useState(saved.date||''),[notes,setNotes]=useState(saved.notes||'');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[receipt,setReceipt]=useState<Job|null>(null),[loaded,setLoaded]=useState(false);
  const request=useRef<{payload:string;key:string}|null>(null);
  useEffect(()=>{if(!receipt)sessionStorage.setItem(draftKey,JSON.stringify({address,phone,date,notes,pin,city:bookingCity}));else sessionStorage.removeItem(draftKey);},[address,phone,date,notes,pin,receipt,draftKey,bookingCity]);
  const load=async()=>{try{const r=await apiFetch('/api/catalog',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Service catalogue unavailable. Retry in a moment.');const data=await r.json();setCatalog(data.services);const match=data.services.find((s:Service)=>s.id===service.id)||data.services.find((s:Service)=>s.category===service.category);setServiceId(match?.id||'');setLoaded(true);setError('');}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void load();},[service.id]);
  const [coupon,setCoupon]=useState<Coupon|null>(null);
  useEffect(()=>{if(promotionId)setCoupon(null);},[promotionId]);
  const [offer,setOffer]=useState<{discount_paise:number;price_paise:number;terms:string;title:string}|null>(null),[offerError,setOfferError]=useState(''),[session,setSession]=useState(''),[quoteRetry,setQuoteRetry]=useState(0);
  useEffect(()=>onIdTokenChanged(auth,u=>setSession(u?.uid||'')),[]);
  useEffect(()=>{let alive=true;setOffer(null);setOfferError('');if(promotionId&&serviceId)void operation<typeof offer>('/campaigns/quote',{method:'POST',body:JSON.stringify({campaign_id:promotionId,service_id:serviceId,city:bookingCity})}).then(r=>{if(alive)setOffer(r);}).catch(e=>{if(alive)setOfferError(e.message);});return()=>{alive=false;};},[promotionId,serviceId,bookingCity,session,quoteRetry]);
  const selected=catalog.find(s=>s.id===serviceId);
  return <Modal className="reference-booking-sheet" title={receipt?'Booking request received':'Plan your visit'} onClose={onClose}><div className="operations">
    {receipt?<><span className="ops-badge">{receipt.state==='offered'?'Waiting for professional acceptance':'Searching within 6 km'}</span><h3>{receipt.service_name}</h3><p>{new Date(receipt.starts_at).toLocaleString('en-IN')}</p><p>{receipt.address}</p><p>Service price: <strong>{money(receipt.total_paise)}</strong>. Pay after service. Your visit is confirmed when a professional accepts.</p><button className="ops-primary" onClick={onBooked}>View booking updates</button></>:<form onSubmit={async e=>{e.preventDefault();if(!pin||!selected||!serviceTerms||(promotionId&&!offer)){setError('Choose an available service and confirm your location.');return;}setBusy(true);setError('');try{const payload=JSON.stringify({coupon_code:coupon?.code||null,promotion_id:promotionId||null,service_id:serviceId,service_terms_version:serviceTerms!.version,city:bookingCity,address,phone:phone.replace(/[^+\d]/g,''),location:pin,starts_at:new Date(date).toISOString(),notes});if(request.current?.payload!==payload){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(payload)))).map(n=>n.toString(16).padStart(2,'0')).join('');const storageKey='repaido.booking-retry.'+hash;const key=sessionStorage.getItem(storageKey)||crypto.randomUUID();sessionStorage.setItem(storageKey,key);request.current={payload,key};}const result=await operation<Job>('/bookings',{method:'POST',body:JSON.stringify({...JSON.parse(payload),idempotency_key:request.current.key})});setReceipt(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
      {!loaded&&<p role="status">Loading services…</p>}
      <div className="reference-selected-service"><ServiceImage service={service} className="reference-summary-photo" decorative/><div><span>Selected service</span><h3>{selected?.name||service.name}</h3><p>Pay after service · review extra charges first</p></div></div><h3 className="reference-step-title"><span>1</span>Choose your service</h3><label>Service<select value={serviceId} onChange={e=>{setServiceId(e.target.value);onRemovePromotion?.();}} required><option value="">Choose a service</option>{catalog.filter(s=>s.category===service.category).map(s=><option key={s.id} value={s.id}>{s.name} · {money(s.price_paise)}</option>)}</select></label>
      {loaded&&!catalog.some(s=>s.category===service.category)&&<p>This category has no available services. Choose another category.</p>}
      {selected&&<div className="ops-notice"><h3>{money(selected.price_paise)} · service charge</h3><p>Included: {selected.included.join(', ')}.</p><p>Not included: {selected.excluded.join(', ')}. Parts and additional work need your approval. No payment is taken now.</p></div>}
      <CouponField scope="service" base={selected?.price_paise||0} value={coupon} onChange={setCoupon} disabled={!!promotionId}/>
      {promotionId&&<section className="ops-notice"><h3>{offer?.title||(offerError?'Offer needs attention':'Checking offer…')}</h3>{offer&&<><p>{money(offer.discount_paise)} discount · service price {money(offer.price_paise)}</p><p>{offer.terms}</p></>}{offerError&&<p role="alert">{offerError}<button type="button" onClick={()=>auth.currentUser?setQuoteRetry(n=>n+1):onSignIn()}>{auth.currentUser?'Retry offer':'Sign in to check offer'}</button></p>}<button type="button" onClick={onRemovePromotion}>Remove offer</button></section>}
      <h3 className="reference-step-title"><span>2</span>Choose a visit time</h3><label>Appointment date and time<input type="datetime-local" value={date} required onChange={e=>setDate(e.target.value)}/></label><p className="ops-help">Choose a time at least 1 hour from now and within 30 days. Your visit is confirmed when a professional accepts.</p>
      <h3 className="reference-step-title"><span>3</span>Confirm your address</h3><details><summary>Saved service addresses</summary><button type="button" onClick={()=>void operation<{addresses:typeof savedAddresses}>('/addresses').then(d=>setSavedAddresses(d.addresses)).catch(e=>setError(e.message))}>Load saved addresses</button>{savedAddresses.map(a=><div key={a.id}><button type="button" onClick={()=>{setAddress(a.address);setPin(a.location);setBookingCity(a.city);}}>{a.label} · {a.address}</button><button type="button" onClick={()=>void operation(`/addresses/${encodeURIComponent(a.id)}`,{method:'DELETE'}).then(()=>setSavedAddresses(rows=>rows.filter(x=>x.id!==a.id))).catch(e=>setError(e.message))}>Delete saved address</button></div>)}<button type="button" disabled={!pin||address.trim().length<10} onClick={()=>void operation('/addresses/'+crypto.randomUUID(),{method:'PUT',body:JSON.stringify({label:'Home',address,city:bookingCity,location:pin,confirmed:true})}).then(()=>{setError('');setMessage('Address saved. Select Load saved addresses to view it.');}).catch(e=>setError(e.message))}>Save this address</button></details><label>House number, street and landmark<textarea autoComplete="street-address" value={address} required minLength={10} maxLength={500} onChange={e=>setAddress(e.target.value)}/></label><p>Service city: {bookingCity}</p>
      <div className="ops-actions"><button type="button" onClick={()=>setMap(true)}>Set location on map</button><button type="button" onClick={()=>void currentPosition().then(p=>{setPin({lat:p.lat,lng:p.lng});setError('');}).catch(e=>setError(e.message))}>Use current location</button></div>
      <details><summary>Enter pin coordinates manually</summary><div className="ops-grid"><label>Latitude<input type="number" step="any" min={-90} max={90} value={pin?.lat??''} onChange={e=>setPin(p=>({lat:Number(e.target.value),lng:p?.lng??0}))}/></label><label>Longitude<input type="number" step="any" min={-180} max={180} value={pin?.lng??''} onChange={e=>setPin(p=>({lat:p?.lat??0,lng:Number(e.target.value)}))}/></label></div></details>
      {pin&&<p role="status">Selected pin: {pin.lat.toFixed(5)}, {pin.lng.toFixed(5)}. Check this is your service entrance.</p>}
      <label>Contact number<input type="tel" inputMode="tel" autoComplete="tel" required value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Access instructions (optional)<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000}/></label>
      <ServiceTerms serviceId={serviceId||service.id} onLoaded={setServiceTerms}/><h3 className="reference-step-title"><span>4</span>Review your request</h3><div className="reference-invoice"><div><span>Service charge</span><strong>{selected?money(selected.price_paise):'—'}</strong></div>{coupon&&<div><span>{coupon.code}</span><strong>−{money(Math.floor((selected?.price_paise||0)*coupon.bps/10000))}</strong></div>}{offer&&<div><span>Repaido offer</span><strong>−{money(offer.discount_paise)}</strong></div>}{offer&&<div><span>Service after discount</span><strong>{money(offer.price_paise)}</strong></div>}<div><span>Parts & extra work</span><span>Only with your approval</span></div><div><strong>Due now</strong><strong>₹0</strong></div></div><label className="ops-check"><input type="checkbox" required/>I confirm the location and included work. I understand there is no cancellation fee before work starts; extra work requires approval.</label>
      {message&&<p role="status">{message}</p>}{error&&<div className="ops-error" role="alert">{error}<button type="button" onClick={()=>void load()}>Retry catalogue</button>{error.toLowerCase().includes('sign')&&<button type="button" onClick={onSignIn}>Sign in to continue</button>}</div>}
      <button className="ops-primary" disabled={busy||!selected||!pin||!serviceTerms||!!promotionId&&!offer}>{busy?'Sending request…':`Request visit${selected?' · '+money(offer?.price_paise??(selected.price_paise-Math.floor(selected.price_paise*(coupon?.bps||0)/10000))):''}`}</button>
      {onPromotion&&<details><summary>Other services & offers (optional)</summary><p>Viewing another offer keeps this address and time saved. Nothing is added automatically.</p><PromotionRail city={bookingCity} placement="checkout" serviceId={serviceId} onOpen={onPromotion}/></details>}
    </form>}
    {map&&<LocationPickerModal isOpen onClose={()=>setMap(false)} initialLat={pin?.lat} initialLng={pin?.lng} onConfirmLocation={p=>{setPin({lat:p.lat,lng:p.lng});setMap(false);}}/>}
  </div></Modal>;
}
