import {useState} from 'react';
import {apiFetch} from '../services/api';
import {currentPosition} from '../services/operations';
import {LocationPickerModal} from './LocationPickerModal';
type Ranking={agents:{id:string;name:string;role:string;rating:number|null;review_count:number;completed_tasks:number;zone:string;distance_km:number;skills:string[]}[];services:{id:string;name:string;rating:number;review_count:number}[];method:string};
export function LocalLeaderboard(){
 const [data,setData]=useState<Ranking|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[map,setMap]=useState(false),[zone,setZone]=useState('all'),[kind,setKind]=useState('agents');
 const load=async(location:{lat:number;lng:number})=>{setBusy(true);setError('');try{const r=await apiFetch('/api/operations/discovery/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Rankings are unavailable. Please retry.');setData(await r.json());setZone('all');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="operations ops-card"><h2>Local leaderboards</h2><p>Verified reviews within 20 km. Browse approximate 8 km hexagonal zones. Booking availability still depends on the professional’s service radius.</p><div className="ops-actions"><button disabled={busy} onClick={async()=>{try{setBusy(true);await load(await currentPosition(true));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Use my location</button><button disabled={busy} onClick={()=>setMap(true)}>Choose area on map</button></div>{busy&&<p role="status">Loading nearby rankings…</p>}{error&&<p role="alert">{error}</p>}{data&&<><div className="ops-grid"><label>Rank by<select value={kind} onChange={e=>setKind(e.target.value)}><option value="agents">Professionals</option><option value="services">Services</option></select></label>{kind==='agents'&&<label>Hexagonal zone<select value={zone} onChange={e=>setZone(e.target.value)}><option value="all">All nearby zones</option>{[...new Set(data.agents.map(a=>a.zone))].map(z=><option key={z} value={z}>Zone {z}</option>)}</select></label>}</div><div className="leaderboard-grid">{kind==='agents'?data.agents.filter(a=>zone==='all'||a.zone===zone).map((a,i)=><article className="ops-card" key={a.id}><span className="ops-badge">#{i+1} · {a.role}</span><h3>{a.name}</h3><p>{a.rating===null?'New · no reviews yet':`★ ${a.rating.toFixed(1)} · ${a.review_count} verified reviews`}</p><p>{a.completed_tasks} completed tasks · about {a.distance_km} km away</p><p>{a.skills.join(', ')}</p></article>):data.services.map((s,i)=><article className="ops-card" key={s.id}><span>#{i+1}</span><h3>{s.name}</h3><p>★ {s.rating.toFixed(1)} · {s.review_count} verified reviews</p></article>)}</div>{!(kind==='agents'?data.agents:data.services).length&&<p>No eligible rankings in this area yet. Ratings appear after completed-booking reviews.</p>}<details><summary>How rankings work</summary><p>{data.method}</p></details></>}<LocationPickerModal isOpen={map} title="Choose leaderboard area" onClose={()=>setMap(false)} onConfirmLocation={p=>void load(p)}/></section>;
}
