import {useEffect,useState} from 'react';
import {Search,MapPin,ArrowUpRight,Star} from 'lucide-react';
import {apiFetch} from '../services/api';
import {Modal} from './ui';
import {ProfessionalAvatar,ProfessionalDetails,type Professional} from './Hiring';
import {RepaidianBadge} from './RepaidianBadge';
import './repaidian-professional.css';
export function NearbyDiscovery({city,pin,radius,onClose,initialCategory=''}:{city:string;pin:{lat:number;lng:number};radius:number;onClose:()=>void;initialCategory?:string}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(initialCategory),[role,setRole]=useState('all'),[sort,setSort]=useState('recommended'),[available,setAvailable]=useState(false),[rating,setRating]=useState('0');
 const [rows,setRows]=useState<Professional[]>([]),[categories,setCategories]=useState<{id:string;name:string;count:number}[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Professional|null>(null),[retry,setRetry]=useState(0),[total,setTotal]=useState(0);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');setRows([]);const timer=setTimeout(()=>{void apiFetch('/api/operations/hiring/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({city,location:pin,radius_km:radius,strict_nearby:true,query,category,role,sort,available_only:available,min_rating:Number(rating)}),signal:AbortSignal.any([c.signal,AbortSignal.timeout(15000)])},{background:true}).then(async r=>{if(!r.ok)throw Error('Nearby profiles could not load. Please retry.');return r.json();}).then(d=>{if(!c.signal.aborted){setRows(d.professionals);setCategories(d.categories);setTotal(d.total);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});},250);return()=>{clearTimeout(timer);c.abort();};},[city,pin,radius,query,category,role,sort,available,rating,retry]);
 return <Modal title="Discover nearby professionals" className="nearby-discovery" onClose={onClose}><div className="nearby-intro"><span>REPAIDO · LOCAL NETWORK</span><p><MapPin size={13}/>Service bases within {radius} km of your selected location</p></div><label className="nearby-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search nearby professionals" placeholder="Name, skills, repair or work…"/></label><div className="nearby-filters"><label>Expertise<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All services</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Professional<select value={role} onChange={e=>setRole(e.target.value)}><option value="all">Everyone</option><option value="technician">Technicians</option><option value="specialist">Specialists</option><option value="contractor">Verified contractors</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Best match</option><option value="rating">Highest rated</option><option value="completed">Completed work</option><option value="experience">Experience</option></select></label><label>Reviews<select value={rating} onChange={e=>setRating(e.target.value)}><option value="0">Any rating</option><option value="4">4+ stars</option><option value="4.5">4.5+ stars</option></select></label></div><label className="nearby-availability"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/>Available now</label>
 {busy&&<p role="status">Finding matching professionals nearby…</p>}{error&&<p role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}{!busy&&!error&&<p className="nearby-count">{total} matching profiles · {rows.length<total?'Showing the top 40. Refine your search.':'Service availability is confirmed on request.'}</p>}
 <div className="nearby-results">{rows.map(p=><article key={p.id} className="nearby-person"><div className="nearby-person-header"><ProfessionalAvatar p={p}/><div><div className="repaidian-professional-name"><h3>{p.name}</h3><RepaidianBadge badge={p.repaidianBadge}/></div><p>{p.contractor_verified?'Verified contractor':p.role} · {p.distance_km} km</p></div></div><p>{p.specialties?.slice(0,3).join(' · ')||p.skills.slice(0,3).join(' · ')}</p><div className="nearby-stats"><span><Star size={12}/>{p.rating==null?'New':p.rating.toFixed(1)} · {p.review_count} reviews</span><span>{p.completed_tasks} completed</span><span>{p.experience_years} years</span></div><button onClick={()=>setSelected(p)}>Full profile, services & rates<ArrowUpRight size={14}/></button></article>)}</div>
 {!busy&&!error&&!rows.length&&<p>No matching profiles inside this radius. Try another skill or remove a filter.</p>}
 {selected&&<Modal title={selected.name} className="hire-profile-modal nearby-profile" onClose={()=>setSelected(null)}><ProfessionalDetails p={selected}/><button onClick={()=>{setQuery('');setCategory(selected.categories[0]||'');setRole('all');setSelected(null);}}>More similar profiles nearby</button></Modal>}
 </Modal>;
}
