import {useEffect,useRef,useState} from 'react';
import {auth} from '../firebase';
import {apiFetch} from '../services/api';
import {operation} from '../services/operations';
export function OnboardingSelfie({consent,onSaved}:{consent:boolean;onSaved:()=>Promise<void>}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),pending=useRef<{id:string;blob:Blob}|null>(null);
 const [open,setOpen]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setOpen(false);setReady(false);};
 useEffect(()=>{if(!open)return;let active=true;void navigator.mediaDevices?.getUserMedia({video:{facingMode:'user'},audio:false}).then(async s=>{if(!active){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play();setReady(true);}}).catch(()=>setError('Camera unavailable. Allow camera access and retry, or use the manual identity-review route with support.'));return()=>{active=false;stream.current?.getTracks().forEach(t=>t.stop());};},[open]);
 const upload=async()=>{if(!pending.current)return;const token=await auth.currentUser?.getIdToken();const r=await apiFetch(`/api/operations/worker/selfies/${pending.current.id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'image/jpeg','X-Verification-Consent':'private-review-v1'},body:pending.current.blob,signal:AbortSignal.timeout(60000)});const d=await r.json();if(!r.ok)throw Error(d.detail?.message||'Upload failed. Retry this selfie.');pending.current=null;setMessage('Selfie uploaded privately for the Repaido team.');await onSaved();};
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const capture=async()=>{const v=video.current;if(!v?.videoWidth)throw Error('Wait for the camera.');const session=await operation<{id:string}>('/worker/selfie-session',{method:'POST'});const c=document.createElement('canvas');c.width=800;c.height=Math.round(v.videoHeight*800/v.videoWidth)+72;const ctx=c.getContext('2d')!;ctx.drawImage(v,0,0,c.width,c.height-72);ctx.fillStyle='#102345';ctx.fillRect(0,c.height-72,800,72);ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText('Repaido · Identity selfie · '+new Date().toISOString(),16,c.height-42,770);ctx.fillText('Capture '+session.id,16,c.height-14,770);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Capture failed.')),'image/jpeg',.85));pending.current={id:session.id,blob};stop();await upload();};
 return <div className="ops-notice"><h3>Timestamped verification selfie</h3><p>Used only by Repaido to compare you with your identity document. No automated face recognition. Private retention: 30 days. Camera time is device-reported; upload time is recorded by the server.</p>{open?<><video ref={video} autoPlay playsInline muted aria-label="Selfie camera preview" style={{width:'100%',maxHeight:280}}/><button type="button" disabled={!ready||busy||!consent} onClick={()=>void run(capture)}>Take selfie and upload</button><button type="button" onClick={stop}>Cancel camera</button></>:<button type="button" disabled={!consent||busy} onClick={()=>{if(!navigator.mediaDevices?.getUserMedia){setError('This browser does not support the camera. Contact support for manual review.');return;}setError('');setOpen(true);}}>Open selfie camera</button>}{pending.current&&<button type="button" disabled={busy||!consent} onClick={()=>void run(upload)}>Retry selfie upload</button>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>;
}
