import {useEffect,useState} from 'react';
import {operation} from '../services/operations';
import {apiFetch} from '../services/api';
import {auth} from '../firebase';
type Row={id:string;name:string;city:string;status:string;requested_role:string;skills:string[];tools:string[];categories:string[];experience_years:number;identity_status:string;bank_status:string;document_kinds:string[];ready:boolean;dob:string;home_address:string;phone:string;radius_km:number;terms_version:string};
type Doc={id:string;kind:string;status:string;content_type:string;created_at:number;expires_at:number};
function DocumentPreview({doc}:{doc:Doc}){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let disposed=false,objectUrl='';setError('');setUrl('');void(async()=>{try{const token=await auth.currentUser?.getIdToken();const r=await apiFetch(`/api/operations/admin/documents/${doc.id}`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Preview unavailable. Refresh or ask for a new upload.');objectUrl=URL.createObjectURL(new Blob([await r.blob()],{type:doc.content_type}));if(!disposed)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}catch(e){if(!disposed)setError((e as Error).message);}})();return()=>{disposed=true;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[doc.id,retry]);
 const image=['image/jpeg','image/png'].includes(doc.content_type);
 return <figure className="onboarding-document"><figcaption><strong>{doc.kind.replaceAll('_',' ')}</strong><span>{new Date(doc.created_at*1000).toLocaleDateString()}</span></figcaption>{url?(image?<a href={url} target="_blank" rel="noreferrer" aria-label={`Enlarge ${doc.kind} photo`}><img src={url} alt={`${doc.kind} submitted by applicant`}/></a>:<a href={url} download={`${doc.kind}.pdf`}>Download document</a>):error?<div role="alert"><p>{error}</p><button onClick={()=>setRetry(x=>x+1)}>Retry preview</button></div>:<p role="status">Loading private document…</p>}</figure>;
}
function Application({worker,onSaved}:{worker:Row;onSaved:()=>Promise<void>}){
 const [docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false),[note,setNote]=useState(''),[role,setRole]=useState(worker.requested_role||'technician'),[success,setSuccess]=useState('');
 const load=async()=>{setLoading(true);setError('');setChecked(false);try{const data=await operation<{documents:Doc[]}>(`/admin/verification/${worker.id}`);setDocs(data.documents.filter(d=>d.status==='pending_review'&&d.expires_at>Date.now()/1000));}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[worker.id]);
 const missing=['identity','pan','address','tools'].filter(k=>!docs.some(d=>d.kind===k));
 const decide=async(decision:string)=>{setBusy(true);setError('');setSuccess('');try{await operation(`/admin/workers/${worker.id}/review`,{method:'POST',body:JSON.stringify({decision,role,reason:note.trim()||'Identity, date of birth, PAN, address, tools and identity match reviewed by the Repaido team.',identity_reviewed:checked,document_ids:docs.map(d=>d.id)})});setSuccess(decision==='approved'?'Agent approved. Joining is complete.':'Application rejected with your reason.');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <article className="review-detail onboarding-application"><div className="ops-heading"><div><h2>{worker.name}</h2><p>{worker.requested_role} application · {worker.status.replaceAll('_',' ')}</p></div><button disabled={loading||busy} onClick={()=>void load()}>Refresh documents</button></div><div className="onboarding-facts">{[['Contact',worker.phone],['Date of birth',worker.dob],['Home address',worker.home_address],['Service area',`${worker.city} · ${worker.radius_km} km`],['Experience',`${worker.experience_years} years`],['Services',worker.categories?.join(', ')],['Skills',worker.skills?.join(', ')],['Tools',worker.tools?.join(', ')],['Accepted terms',worker.terms_version]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value||'Not provided'}</strong></div>)}</div><h3>Documents & identity photo</h3><p className="ops-help">Private, audited access. Select a photo to enlarge it. Review the identity match using the selfie or your accessible manual review process.</p>{loading?<p role="status">Loading documents…</p>:<><div className="onboarding-documents">{docs.map(d=><DocumentPreview key={d.id} doc={d}/>)}</div>{missing.length>0&&worker.identity_status!=='approved'&&<p className="ops-error">Still needed: {missing.join(', ')}. Ask the applicant to upload these before approval.</p>}{!docs.length&&<p>No current documents uploaded.</p>}</>}
 <div className="onboarding-decision"><div><label>Joining role<select value={role} onChange={e=>setRole(e.target.value)}><option value="technician">Technician</option><option value="specialist">Specialist</option></select></label><label>Decision note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Required when rejecting (at least 10 characters)"/></label></div><div><label className="ops-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I reviewed identity, date of birth, PAN, address, tools and the identity match.</label><p className="ops-help">Joining approval does not require a payment-provider reference. Bank verification is a separate step before payouts.</p><div className="ops-actions"><button className="status-green" disabled={busy||loading||!checked||(missing.length>0&&worker.identity_status!=='approved')||worker.status==='approved'} onClick={()=>void decide('approved')}>{busy?'Saving…':'Approve agent'}</button><button className="status-red" disabled={busy||note.trim().length<10} onClick={()=>void decide('rejected')}>Reject with reason</button></div></div></div>{error&&<p role="alert" className="ops-error">{error}</p>}{success&&<p role="status" className="status-green">{success}</p>}</article>;
}
export function OnboardingOverview(){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState(''),[filter,setFilter]=useState('pending'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const data=await operation<{workers:Row[]}>('/admin/onboarding-overview');setRows(data.workers);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const worker=rows.find(w=>w.id===selected);const shown=rows.filter(w=>(filter==='all'||filter==='ready'&&w.ready&&w.status!=='approved'||filter==='pending'&&w.status==='pending_verification')&&`${w.name} ${w.city} ${w.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="onboarding-overview"><div className="ops-heading"><div><h2>Agent onboarding</h2><p>One application. All details and documents. One decision.</p></div><button disabled={busy} onClick={()=>void load()}>Refresh applications</button></div><div className="ops-grid"><label>Find an applicant<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, city or skill"/></label><label>Applications<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Awaiting review</option><option value="ready">Evidence ready</option><option value="all">All applications</option></select></label></div>{error&&<p role="alert" className="ops-error">{error}</p>}<div className="onboarding-applicants" aria-label="Applications">{shown.map(w=><button className="review-row" key={w.id} aria-pressed={selected===w.id} onClick={()=>setSelected(w.id)}><strong>{w.name}</strong><span>{w.city} · {w.experience_years} years</span><span className={`status-chip ${w.ready?'status-green':'status-orange'}`}>{w.status==='approved'?'Approved':w.ready?'Evidence ready':'Documents pending'}</span></button>)}{!busy&&!shown.length&&<p>No matching applications.</p>}</div>{worker?<Application key={worker.id} worker={worker} onSaved={load}/>:<p className="ops-empty">Choose an applicant above to review all information.</p>}</section>;
}
