import {useEffect,useRef,useState} from 'react';
import {onIdTokenChanged} from 'firebase/auth';
import {auth} from '../firebase';
import {operation} from '../services/operations';
import {ArrowRight,ChevronLeft,ChevronRight} from 'lucide-react';
import type {AnimationItem} from 'lottie-web';
import './opportunity-carousel.css';
export type Opportunity={id:string;tag:string;title:string;body:string;cta:string;image:string;alt:string;legacy?:boolean;terms?:string};
export const opportunities:Opportunity[]=[
 {id:'sell',tag:'A FRESH START',title:'Less clutter. More possibility.',body:'Sell your pre-loved items.',cta:'Sell an item',image:'sell',alt:'Carefully kept furniture ready for a new home',terms:'New sellers receive unlimited listings during their first 90 days, starting at their first eligible listing. Up to 10 listings per day. Existing sellers excluded; standard fees apply afterwards. No sale is guaranteed.'},
 {id:'refurbished',tag:'RETHINK NEW',title:'Good tech. A fresh chapter.',body:'Compare condition, value & warranty.',cta:'Explore refurbished',image:'refurbished',alt:'Refurbished phone, laptop and watch in a premium product scene',terms:'Illustrative image. Actual products, condition, warranty and prices are shown in the live shop catalogue.'},
 {id:'rentals',tag:'RENT SMART',title:'Big plans. Smaller commitments.',body:'Tools & equipment, for the time you need.',cta:'Find equipment',image:'rentals',alt:'A toolbox, drill and pressure washer in a modern home',terms:'Illustrative equipment. Compare live stock, rates, deposits and return terms. Billing stops at verified physical return.'},
 {id:'exchange',tag:'PASS IT FORWARD',title:'Your next find could be a swap.',body:'Meet useful things. Give yours a new home.',cta:'Explore exchanges',image:'exchange',alt:'Two people exchanging useful electronics',terms:'Inspect condition and ownership. Listing terms and eligibility are shown before publishing; matching is not guaranteed.'},
 {id:'contracts',tag:'BUILD WHAT’S NEXT',title:'Your next project starts here.',body:'Discover sectors, scopes & opportunities.',cta:'Explore contracts',image:'contracts',alt:'Indian project professionals reviewing building plans',terms:'Illustrative professionals. Tenders require approved contractor access. Review each scope, deadline and eligibility; no award is guaranteed.'},
];
// Chosen once per mount: the weekday changes the shell, never an individual slide.
export function bannerShape(date=new Date()){const day=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short'}).format(date);return ({Mon:'panorama',Tue:'soft',Wed:'editorial',Thu:'panorama',Fri:'studio',Sat:'soft',Sun:'editorial'} as Record<string,string>)[day];}
function MotionAccent({playing}:{playing:boolean}){const ref=useRef<HTMLSpanElement>(null),animation=useRef<AnimationItem|undefined>(undefined),playingRef=useRef(playing);playingRef.current=playing;useEffect(()=>{let alive=true;void import('lottie-web').then(({default:lottie})=>{if(!alive||!ref.current)return;animation.current=lottie.loadAnimation({container:ref.current,renderer:'svg',loop:true,autoplay:false,path:'/animations/opportunity-orbit.json'});if(playingRef.current)animation.current.play();});return()=>{alive=false;animation.current?.destroy();};},[]);useEffect(()=>{playing?animation.current?.play():animation.current?.pause();},[playing]);return <span ref={ref} className="opportunity-motion" aria-hidden="true"/>;}
export default function OpportunityCarousel({slides=opportunities,variant='market',onOpen}:{slides?:Opportunity[];variant?:'home'|'market';onOpen:(slide:Opportunity)=>void}){
 const [ranking,setRanking]=useState<string[]>([]);
 const ordered=[...slides.filter(s=>s.legacy),...slides.filter(s=>!s.legacy).sort((a,b)=>{const ai=ranking.indexOf(a.id),bi=ranking.indexOf(b.id);return (ai<0?99:ai)-(bi<0?99:bi);})];
 useEffect(()=>{let generation=0;const read=()=>{const g=++generation;setRanking([]);if(auth.currentUser)void operation<{ids:string[]}>('/opportunities/order',{}, {background:true}).then(d=>{if(g===generation)setRanking(d.ids);}).catch(()=>{});};const off=onIdTokenChanged(auth,read);window.addEventListener('repaido:interests',read);return()=>{generation++;off();window.removeEventListener('repaido:interests',read);};},[]);
 const [index,setIndex]=useState(0),[shape]=useState(bannerShape),[engaged,setEngaged]=useState(false),[visible,setVisible]=useState(false),[reduced,setReduced]=useState(false),[hidden,setHidden]=useState(document.hidden);const ref=useRef<HTMLElement>(null),touch=useRef<{x:number;y:number}|null>(null);const slide=ordered[index%ordered.length];
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)'),read=()=>setReduced(q.matches||document.documentElement.classList.contains('reduce-motion')),visibility=()=>setHidden(document.hidden);read();q.addEventListener('change',read);document.addEventListener('visibilitychange',visibility);const mo=new MutationObserver(read);mo.observe(document.documentElement,{attributes:true,attributeFilter:['class']});const io=new IntersectionObserver(e=>setVisible(!!e[0]?.isIntersecting),{threshold:.3});if(ref.current)io.observe(ref.current);return()=>{q.removeEventListener('change',read);document.removeEventListener('visibilitychange',visibility);mo.disconnect();io.disconnect();};},[]);
 const playing=visible&&!hidden&&!reduced&&!engaged;
 useEffect(()=>{if(!playing||slides.length<2)return;const timer=setInterval(()=>setIndex(i=>(i+1)%slides.length),6500);return()=>clearInterval(timer);},[playing,slides.length]);
 const move=(n:number)=>setIndex(i=>(i+n+slides.length)%slides.length);
 return <section ref={ref} className={`opportunity-carousel opportunity-${variant} opportunity-shape-${shape} ${playing?'is-playing':''} ${slide.legacy?'is-legacy':''}`} aria-label={variant==='home'?'Repaido highlights':'Marketplace opportunities'} aria-roledescription="carousel" onPointerEnter={()=>setEngaged(true)} onPointerLeave={()=>setEngaged(false)} onFocusCapture={()=>setEngaged(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setEngaged(false);}} onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY};setEngaged(true);}} onTouchEnd={e=>{const p=touch.current;touch.current=null;if(p){const dx=e.changedTouches[0].clientX-p.x,dy=e.changedTouches[0].clientY-p.y;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)*1.5)move(dx<0?1:-1);}setEngaged(false);}}>
 <button className="opportunity-slide" key={slide.id} onClick={()=>{if(!slide.legacy&&auth.currentUser)void operation('/opportunities/open',{method:'POST',body:JSON.stringify({category:slide.id})},{background:true}).catch(()=>{});onOpen(slide);}} aria-label={slide.legacy?'Book a home service — browse services':slide.cta}>
 <img className="opportunity-photo" src={slide.legacy?slide.image:`/images/banners/${slide.image}.jpg`} alt={slide.alt} width={1536} height={1024} decoding="async"/>
 {!slide.legacy&&<><span className="opportunity-scrim"/><span className="opportunity-copy"><small>{slide.tag}</small><strong>{slide.title}</strong><span>{slide.body}</span><b>{slide.cta}<ArrowRight size={13}/></b></span></>}
 </button>{!slide.legacy&&<MotionAccent playing={playing}/>}
 <div className="opportunity-controls"><button aria-label="Previous banner" onClick={()=>move(-1)}><ChevronLeft size={13}/></button><span aria-label={`Slide ${index+1} of ${slides.length}`}>{index+1}/{slides.length}</span><button aria-label="Next banner" onClick={()=>move(1)}><ChevronRight size={13}/></button></div>
 </section>;
}
