import {useEffect,useState} from 'react';
import {operation} from '../services/operations';
import {apiFetch} from '../services/api';
type Policy={version:string;min_tasks:number;min_reviews:number;min_rating:number;min_on_time_percent:number;sections:{id:string;title:string;text:string}[]};
type Application={id:string;name:string;business_name:string;team_size:number;experience:string;qualifications:string;scope:string;status:string;version:number;reason?:string};
export function PartnerAgreement({onChange}:{onChange:(version:string,sections:string[])=>void}){
 const [policy,setPolicy]=useState<Policy>(),[checked,setChecked]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{void apiFetch('/api/operations/partner-policy').then(async r=>{if(!r.ok)throw Error('Partner rules could not load. Please refresh.');setPolicy(await r.json());}).catch(e=>setError(e.message));},[]);
 return <section className="home-brief"><h3>Launch partner agreement</h3>{error&&<p role="alert">{error}</p>}{!policy&&!error&&<p>Loading current rules…</p>}{policy&&<><CriteriaText policy={policy}/>{policy.sections.map(s=><details key={s.id}><summary>{checked.includes(s.id)?'✓ ':''}{s.title}</summary><p>{s.text}</p><label className="ops-check"><input required type="checkbox" checked={checked.includes(s.id)} onChange={e=>{const next=e.target.checked?[...checked,s.id]:checked.filter(x=>x!==s.id);setChecked(next);onChange(policy.version,next);}}/>I have read and agree to this section.</label></details>)}<small>Policy {policy.version}. Each section must be acknowledged.</small></>}</section>;
}
function CriteriaText({policy:p}:{policy:Policy}){return <p>Annual listing criteria: {p.min_tasks} customer-confirmed, verified-paid tasks; {p.min_reviews} genuine reviews averaging at least {p.min_rating}/5; at least {p.min_on_time_percent}% of recorded work starts within 10 minutes of the agreed time. Every counted task needs a start timestamp. Approved account and no unresolved work disputes. Assessment covers work after agreement through 29 December 2026.</p>;}
export function PartnerProgram(){
 const [data,setData]=useState<{policy:Policy;progress:{status:string;policy?:Policy;metrics?:Record<string,number|null>;award?:{reference_value:number}};application?:Application}>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[agreement,setAgreement]=useState({version:'',sections:[] as string[]});
 const load=()=>operation<typeof data>('/worker/partner-program').then(setData);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="home-plans"><h3>Grow with Repaido · 3 months free</h3><p>Free launch listing until 29 December 2026. Earn a further year of listing through consistent, verified work. No automatic membership charge.</p>{error&&<p role="alert">{error}</p>}{data&&<>{data.progress.status==='agreement_required'?<form onSubmit={e=>{e.preventDefault();void run(()=>operation('/worker/partner-program/agree',{method:'POST',body:JSON.stringify(agreement)}));}}><PartnerAgreement onChange={(version,sections)=>setAgreement({version,sections})}/><button disabled={busy||agreement.sections.length!==4}>Join the free listing programme</button></form>:<details className="home-brief" open><summary>Your annual listing progress · {data.progress.status.replaceAll('_',' ')}</summary><CriteriaText policy={data.progress.policy||data.policy}/><dl>{Object.entries(data.progress.metrics||{}).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{value??'Not yet measured'}</dd></div>)}</dl>{data.progress.award&&<p>One-year listing awarded. Reference value ₹{data.progress.award.reference_value.toLocaleString('en-IN')}. Valid through 29 December 2027.</p>}</details>}<details className="home-brief"><summary>Become a Repaido verified contractor {data.application?'· '+data.application.status:''}</summary><p>Your identity, qualifications and project experience need company review. Include evidence references, not ID numbers or private customer details.</p>{data.application?.reason&&<p>Review: {data.application.reason}</p>}{data.application?.status==='approved'?<p>✓ Repaido verified contractor</p>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>operation('/worker/contractor-application',{method:'POST',body:JSON.stringify({expected_version:data.application?.version||0,business_name:f.get('business_name'),team_size:Number(f.get('team_size')),experience:f.get('experience'),qualifications:f.get('qualifications'),scope:f.get('scope')})}));}}><label>Business or professional name<input name="business_name" required minLength={2} maxLength={120} defaultValue={data.application?.business_name}/></label><label>Team size<input name="team_size" type="number" required min={1} max={500} defaultValue={data.application?.team_size||1}/></label>{(['experience','qualifications','scope'] as const).map(key=><label key={key}>{key==='experience'?'Past projects & experience':key==='qualifications'?'Qualifications & evidence references':'Trades, service scope & team responsibilities'}<textarea name={key} required minLength={key==='experience'?30:20} maxLength={2000} defaultValue={data.application?.[key]}/></label>)}<button disabled={busy||data.progress.status==='agreement_required'}>{busy?'Saving…':'Submit contractor application'}</button></form>}</details></>}</section>;
}
export function PartnerAdmin(){
 const [data,setData]=useState<{policy:Policy;applications:Application[];awards:{worker_id:string;reference_value:number}[]}>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>operation<typeof data>('/admin/partner-program').then(setData);useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const run=async(path:string,body:object,method='POST')=>{setBusy(true);setError('');try{await operation(path,{method,body:JSON.stringify(body)});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="home-plans"><h2>Partner programme & contractor verification</h2>{error&&<p role="alert">{error}</p>}{data&&<><details className="home-brief"><summary>Future agreements · performance criteria</summary><p>Publishing creates a new version. Existing participants keep their agreed thresholds.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('/admin/partner-policy',{expected_version:data.policy.version,min_tasks:Number(f.get('min_tasks')),min_reviews:Number(f.get('min_reviews')),min_rating:Number(f.get('min_rating')),min_on_time_percent:Number(f.get('min_on_time_percent'))},'PUT');}}>{(['min_tasks','min_reviews','min_rating','min_on_time_percent'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input name={k} type="number" required min={1} max={k==='min_rating'?5:100} step={k==='min_rating'?0.1:1} defaultValue={data.policy[k]}/></label>)}<button disabled={busy}>Publish for new agreements</button></form></details><div className="portal-card-grid">{data.applications.map(a=><details className="home-brief" key={a.id+':'+a.version}><summary>{a.name} · {a.status}</summary><dl>{(['business_name','team_size','experience','qualifications','scope'] as const).map(k=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{a[k]}</dd></div>)}</dl><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(`/admin/contractors/${a.id}/review`,{expected_version:a.version,decision:f.get('decision'),reason:f.get('reason'),evidence_reference:f.get('evidence')});}}><label>Decision<select name="decision"><option value="approved">Approve contractor</option><option value="rejected">Return for corrections</option></select></label><label>Review reason<textarea name="reason" required minLength={20} maxLength={2000}/></label><label>Private verification evidence reference<input name="evidence" required minLength={10} maxLength={500}/></label><button disabled={busy}>Save reviewed decision</button></form></details>)}</div>{!data.applications.length&&<p>No contractor applications yet.</p>}<details className="home-brief"><summary>Annual listing awards · {data.awards.length}</summary>{data.awards.map(a=><p key={a.worker_id}>{a.worker_id} · reference value ₹{a.reference_value}</p>)}</details></>}</section>;
}
