import {useState} from 'react';
import {operation,type Job} from '../services/operations';

let checkout:Promise<void>|null=null;
export function loadCheckout(){if(window.Razorpay)return Promise.resolve();return checkout||=new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve();s.onerror=()=>{checkout=null;s.remove();reject(new Error('Payment screen could not load. Check your connection and retry.'));};document.head.appendChild(s);});}
export function PaymentPanel({job,onRefresh,parts=false}:{job:Job;onRefresh:()=>Promise<void>;parts?:boolean}){
 const path=parts?`/jobs/${job.id}/parts/${job.proposal!.id}`:`/jobs/${job.id}`;
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const pay=async()=>{setBusy(true);setError('');try{const order=await operation<{key_id:string;order_id:string;amount:number;currency:string}>(`${path}/payment-order`,{method:'POST'});await loadCheckout();const widget=new window.Razorpay!({key:order.key_id,order_id:order.order_id,amount:order.amount,currency:order.currency,name:'Repaido',description:job.service_name,handler:async(result:{razorpay_payment_id:string})=>{try{await operation(`${path}/payment-check`,{method:'POST',body:JSON.stringify({payment_id:result.razorpay_payment_id})});await onRefresh();setMessage('Payment checked with the gateway. See the current booking status above.');}catch(e){setError((e as Error).message);}},modal:{ondismiss:()=>setMessage('Checkout closed. If money was debited, check status before trying again.')}});widget.on('payment.failed',()=>setError('Payment was not confirmed. Check status before retrying; the same invoice will be reused.'));widget.open();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(job.home_plan_id&&!parts)return <section className="ops-card"><h3>Monthly invoice</h3><p>This visit is included in your Home plan. Review attendance and pay completed visits together after the billing period ends.</p><a className="ops-primary" href={'/?home-plan='+encodeURIComponent(job.home_plan_id)}>Open plan & billing</a></section>;
 return <section className="ops-card"><h3>{parts?'Pay for approved parts':'Payment & receipt'}</h3>{error&&<p className="ops-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!parts&&job.payment_status==='verified'?<p>Payment confirmed by the gateway. Your booking invoice is marked paid.</p>:<><p>{parts?'The shop receives this order only after the gateway confirms payment. This amount is deducted from your final bill. If stock changes before confirmation, support arranges a refund.':'Pay the remaining balance after any confirmed parts advances. Pending payments never release earnings.'}</p><button className="ops-primary" disabled={busy} onClick={()=>void pay()}>{busy?'Checking payment…':parts?'Pay approved parts securely':'Pay remaining balance securely'}</button></>}<button disabled={busy} onClick={()=>void onRefresh()}>Refresh payment status</button></section>;
}
