import {Modal} from './ui';
import { apiFetch } from '../services/api';
import {useState,useEffect} from 'react';
import {auth} from '../firebase';
import {operation,money} from '../services/operations';

export function PrivateReview({workerId}:{workerId:string}){
 const [data,setData]=useState<{verification:Record<string,string>|null;documents:{id:string;kind:string;status:string;content_type:string;created_at:number}[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[evidence,setEvidence]=useState('verification-case:'+workerId),[validation,setValidation]=useState(''),[checks,setChecks]=useState<string[]>([]);
 const [preview,setPreview]=useState<string|null>(null);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const run=async(task:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const load=async()=>setData(await operation(`/admin/verification/${workerId}`));
 const download=async(id:string,type:string)=>{const token=await auth.currentUser?.getIdToken();const r=await apiFetch(`/api/operations/admin/documents/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Document could not be downloaded. It may have expired.');const blob=await r.blob();const url=URL.createObjectURL(new Blob([blob],{type}));if(['image/jpeg','image/png'].includes(type)){setPreview(url);return;}const a=document.createElement('a');a.href=url;a.download=`verification-${id}.bin`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <details><summary>Private identity and bank review</summary><p>Access and decisions are audited. Download only on a company-managed device. Do not forward documents. Files expire after 30 days.</p>{error&&<p role="alert" className="ops-error">{error}</p>}<button disabled={busy} onClick={()=>void run(load)}>Open verification case</button>{data&&<><p>Identity: {data.verification?.identity_status||'not submitted'} · Bank: {data.verification?.bank_status||'not verified'}</p>{data.documents.map(d=><button key={d.id} disabled={busy} onClick={()=>void run(()=>download(d.id,d.content_type))}>View {d.kind} · {new Date(d.created_at*1000).toLocaleDateString()}</button>)}<label>Review reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Private case reference<input value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><fieldset><legend>Confirm your review</legend><p>Check identity, date of birth, address, PAN, tools, and the one-to-one identity match using the documents and private selfie/manual review.</p><label className="ops-check"><input type="checkbox" checked={checks.length===6} onChange={e=>setChecks(e.target.checked?['identity','date_of_birth','address','pan','tools','one_to_one_identity_match']:[])}/>I have personally completed all six checks above.</label></fieldset><div className="ops-actions">{['approved','rejected'].map(decision=><button key={decision} disabled={busy||reason.length<10||evidence.length<8||(decision==='approved'&&checks.length!==6)} onClick={()=>void run(async()=>{await operation(`/admin/verification/${workerId}/identity`,{method:'POST',body:JSON.stringify({decision,reason,evidence_reference:evidence,checks,document_ids:data.documents.filter(d=>d.status==='pending_review').map(d=>d.id)})});await load();})}>{decision==='approved'?'Approve identity checks':'Reject with explanation'}</button>)}</div><p>In the approved RazorpayX account, create a contact with reference <strong>{workerId}</strong>, securely collect its bank account, and complete account validation. The server checks the returned account status, name and worker reference.</p><label>Razorpay validation ID<input value={validation} placeholder="fav_…" onChange={e=>setValidation(e.target.value)}/></label><button disabled={busy||!validation.startsWith('fav_')||reason.length<10} onClick={()=>void run(async()=>{await operation(`/admin/verification/${workerId}/bank`,{method:'POST',body:JSON.stringify({validation_id:validation,reason})});await load();})}>Check bank result with provider</button></>}{preview&&<Modal title="Private verification photo" onClose={()=>setPreview(null)}><img src={preview} alt="Private onboarding evidence" style={{maxWidth:"100%",maxHeight:"70vh",objectFit:"contain"}}/></Modal>}</details>;
}

export function FinanceReview(){
 const [data,setData]=useState<{payments:{id:string;job_id:string;kind?:string;status:string;amount_paise:number;recovery?:string}[];settlements:{id:string;gross_paise:number;deduction_paise:number;net_paise:number;status:string}[];payouts:{id:string;amount_paise:number;status:string}[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[job,setJob]=useState(''),[reason,setReason]=useState('');
 const load=async()=>setData(await operation('/admin/finance',{}, {background:true}));
 const run=async(task:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await task();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void run(async()=>{});},[]);
 return <section className="ops-card"><h2>Settlement review</h2><p>Only captured payments for completed, undisputed jobs can settle. Accepted policy snapshots determine deductions. Payouts require a separately activated payout account.</p>{error&&<p role="alert" className="ops-error">{error}</p>}<button disabled={busy} onClick={()=>void run(async()=>{})}>{busy?'Loading finance records…':'Refresh finance records'}</button>{busy&&!data&&<p role="status">Loading finance records…</p>}{data&&<p role="status">{data.payments.length} collection records · {data.settlements.length} settlements · {data.payouts.length} payouts</p>}<details><summary>Collections and parts advances</summary>{data&&!data.payments.length&&<p>No collection records yet.</p>}{data?.payments.map(p=><article key={p.id}><p>{p.kind==='parts'?'Parts advance':'Final invoice'} · {money(p.amount_paise)} · {p.status} {p.recovery||''}</p><p>Booking: {p.job_id}</p><p>Payment record: {p.id}</p>{p.recovery==='refund_review'&&<p>Use this booking and payment record in Refund review. Verify the amount before authorizing.</p>}</article>)}</details><label>Booking ID<input value={job} onChange={e=>setJob(e.target.value)}/></label><button disabled={busy||!job} onClick={()=>void run(()=>operation(`/admin/settlements/${encodeURIComponent(job)}/calculate`,{method:'POST'}))}>Calculate and review earnings</button><label>Payout approval reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{data?.settlements.map(s=><div className="ops-card" key={s.id}><h3>{s.id}</h3><p>{s.status} · regular {money(s.gross_paise)} · deduction {money(s.deduction_paise)} · payable {money(s.net_paise)}</p><button disabled={busy||reason.length<10||s.status==='paid'} onClick={()=>void run(()=>operation(`/admin/settlements/${s.id}/release`,{method:'POST',body:JSON.stringify({expected_net_paise:s.net_paise,reason})}))}>Authorize payout of {money(s.net_paise)}</button></div>)}{data?.payouts.filter(p=>['failed','rejected','cancelled'].includes(p.status)).map(p=><div key={p.id}><p>Provider-confirmed {p.status} · {p.id}</p><button disabled={busy||reason.length<10} onClick={()=>void run(()=>operation(`/admin/payouts/${p.id}/retry-failed`,{method:'POST',body:JSON.stringify({expected_net_paise:p.amount_paise,reason})}))}>Recheck and retry failed payout</button></div>)}</section>;
}
