import {useEffect,useState} from 'react';
import {operation} from '../services/operations';

export type ProfessionalOffer={id:string;worker_id:string;worker_name:string;service_id:string;bps:number;starts_at:number;ends_at:number;active:boolean;terms:string;eligible_base_paise?:number;discount_paise?:number;discounted_base_paise?:number};
export const offerDate=(timestamp:number)=>new Date(timestamp*1000).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'});
export function PublishedOffers({offers}:{offers:ProfessionalOffer[]}){
 return <section className="professional-offers" aria-label="Professional offers">{offers.map(o=><div key={o.id} className="professional-offer"><strong>{o.bps/100}% off · {o.service_id.replace('day:','Day hire · ').replaceAll('-',' ')}</strong><p>Offered by {o.worker_name} · valid until {offerDate(o.ends_at)}</p><details><summary>Offer terms</summary><p>{o.terms}</p></details></div>)}</section>;
}
export function WorkerOfferEditor(){
 const [data,setData]=useState<{services:{id:string;name:string}[];offers:ProfessionalOffer[];terms:string}>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setData(await operation('/worker/home-offers'));
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setMessage('');try{await action();await load();setMessage(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="worker-offer-editor"><p>Publish a saving for your approved hiring categories and Home services for up to two months. You fund the discount from your earnings. Existing issued quotes keep their agreed offer.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!data&&!error&&<p role="status">Loading your services…</p>}{data&&<>{data.services.length?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>operation('/worker/home-offers',{method:'POST',body:JSON.stringify({service_id:f.get('service'),percent:Number(f.get('percent')),ends_at:new Date(String(f.get('expiry'))+'T23:59:59+05:30').getTime()/1000})}),'Your offer is published.');}}><label>Approved hiring service<select name="service" required>{data.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Saving (%)<input name="percent" type="number" min={1} max={50} step={1} required inputMode="numeric"/></label><label>Last valid date · India time<input name="expiry" type="date" required/></label><p>{data.terms}</p><label className="hire-check"><input type="checkbox" required/>I agree to fund this offer from my earnings.</label><button className="ops-primary" disabled={busy}>{busy?'Saving…':'Publish offer'}</button></form>:<p>Have your service skills reviewed before publishing an offer.</p>}<h3>Your offers</h3>{!data.offers.length&&<p>No offers published yet.</p>}{data.offers.map(o=><article key={o.id} className="agent-record-box"><strong>{data.services.find(s=>s.id===o.service_id)?.name||o.service_id} · {o.bps/100}%</strong><p>{!o.active?'Withdrawn':o.ends_at<=Date.now()/1000?'Expired':o.starts_at>Date.now()/1000?'Scheduled':'Published'} · until {offerDate(o.ends_at)}</p>{o.active&&o.ends_at>Date.now()/1000&&<button disabled={busy} onClick={()=>void run(()=>operation('/worker/home-offers/'+o.id,{method:'DELETE'}),'Offer withdrawn. Previously issued quotes keep their terms.')}>Withdraw offer</button>}</article>)}</>}</section>;
}
