import {useEffect,useRef,useState} from 'react';
import {onIdTokenChanged} from 'firebase/auth';
import {ArrowRight,Car,ChevronLeft,ChevronRight,Gift,Headphones,IndianRupee,Leaf,Pause,Play,Repeat2,ShieldCheck,Sparkles,Wrench,X,Zap} from 'lucide-react';
import {auth} from '../firebase';
import {apiFetch,apiAssetUrl} from '../services/api';
import {operation,money} from '../services/operations';
import {enableNativePush,nativeAvailable,nativeCall} from '../services/native';
import {Modal} from './ui';
import {seededServices} from '../data';
import type {Service} from '../types';
import './promotions.css';
export type Placement='home'|'explore'|'checkout'|'launch'|'push';
export type Promotion={home_service?:string;event_name?:string;image_url?:string;image_alt?:string;layout?:string;launch_only?:boolean;id:string;version:number;title:string;body:string;icon:string;tone:string;terms:string;ends_at:number;discount_paise:number;price_paise:number;offer_price_paise:number;per_user_limit:number;reason:string;service?:{id:string;name:string;category:Service['category'];description:string;price_paise:number;duration_minutes:number;included:string[];excluded:string[]}};
const icons:Record<string,typeof Gift>={gift:Gift,sparkles:Sparkles,wrench:Wrench,shield:ShieldCheck,rupee:IndianRupee,headset:Headphones,repeat:Repeat2,leaf:Leaf,car:Car,zap:Zap};
const defaults:Promotion[]=[['sparkles','A little care. A better home.','Find the right service for your next home project.'],['shield','Your home. Your call.','Review the scope, price and any extras before approving.'],['wrench','From plans to progress.','Follow your visits, home plans and contracts in Bookings.'],['headset','Care beyond the visit.','Keep booking records and support together, whenever you need them.']].map(([icon,title,body],i)=>({id:'usp-'+i,version:1,title,body,icon,tone:i%2?'blue':'mint',terms:body,ends_at:0,discount_paise:0,price_paise:0,offer_price_paise:0,per_user_limit:0,reason:''}));
export function promotionService(c:Promotion):Service{const s=c.service!;const art=seededServices.find(a=>a.id===s.id)||seededServices.find(a=>a.category===s.category);return {...s,price:s.price_paise,duration:s.duration_minutes,image:art?.image||'',imageTile:art?.imageTile,imageAlt:s.name};}
function useCampaigns(city:string,placement:Placement,serviceId=''){
 const feedKey=useRef('');const [uid,setUid]=useState<string>();const [cards,setCards]=useState<Promotion[]>([]),[seconds,setSeconds]=useState(4),[busy,setBusy]=useState(true),[error,setError]=useState(''),[epoch,setEpoch]=useState(0);
 useEffect(()=>onIdTokenChanged(auth,u=>setUid(u?.uid)),[]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setEpoch(x=>x+1);};const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);window.addEventListener('repaido:interests',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('repaido:interests',refresh);};},[]);
 useEffect(()=>{let alive=true;const key=JSON.stringify([uid,city,placement,serviceId]);if(feedKey.current!==key){setCards([]);feedKey.current=key;}setBusy(true);setError('');const body=JSON.stringify({city,placement,service_id:serviceId});const fetchCards=async()=>{try{let data:{cards:Promotion[];rotation_seconds:number};if(uid)data=await operation('/campaigns/feed/personal',{method:'POST',body},{background:true});else{const r=await apiFetch('/api/operations/campaigns/feed',{method:'POST',headers:{'Content-Type':'application/json'},body,signal:AbortSignal.timeout(10000)},{background:true});if(!r.ok)throw Error('Offers could not load.');data=await r.json();}if(alive){setCards(data.cards);setSeconds(data.rotation_seconds);}}catch{if(alive)setError('Offers could not load. Regular services are still available.');}finally{if(alive)setBusy(false);}};void fetchCards();return()=>{alive=false;};},[uid,city,placement,serviceId,epoch]);
 return {cards,seconds,busy,error,uid,retry:()=>setEpoch(n=>n+1)};
}
async function interaction(card:Promotion,kind:'open'|'impression'|'dismiss'){if(!auth.currentUser||card.id.startsWith('usp-'))return;await operation(`/campaigns/${encodeURIComponent(card.id)}/events`,{method:'POST',body:JSON.stringify({kind,event_id:crypto.randomUUID()})},{background:true});}
export function PromotionRail({city,placement='home',serviceId='',onOpen,onSignIn,onCards,onExplore}:{city:string;placement?:Placement;serviceId?:string;onOpen:(c:Promotion)=>void;onSignIn?:()=>void;onCards?:(cards:Promotion[])=>void;onExplore?:()=>void}){
 const feed=useCampaigns(city,placement,serviceId),[index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hovered,setHovered]=useState(false),[reduced,setReduced]=useState(false),[visible,setVisible]=useState(false),[detail,setDetail]=useState<Promotion|null>(null),[dismissed,setDismissed]=useState(false),[status,setStatus]=useState('');const rail=useRef<HTMLElement>(null),touch=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{onCards?.(feed.cards);},[feed.cards,onCards]);
 const [launchHidden,setLaunchHidden]=useState(false);
 const cards=placement==='home'?[...feed.cards.filter(c=>!c.launch_only||!launchHidden),...defaults]:feed.cards;const current=index%Math.max(1,cards.length),card=cards[current];
 const launchKey=`repaido.launch.${feed.uid||'guest'}.${new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})}`;
 useEffect(()=>{setLaunchHidden(!!sessionStorage.getItem(launchKey));},[launchKey]);
 useEffect(()=>{if(card?.launch_only&&visible)sessionStorage.setItem(launchKey,'shown');},[card?.id,visible,launchKey]);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const read=()=>setReduced(q.matches||document.documentElement.classList.contains('reduce-motion'));read();q.addEventListener('change',read);const mo=new MutationObserver(read);mo.observe(document.documentElement,{attributes:true,attributeFilter:['class']});return()=>{q.removeEventListener('change',read);mo.disconnect();};},[]);
 useEffect(()=>{if(!rail.current)return;const observer=new IntersectionObserver(e=>setVisible(e[0]?.isIntersecting||false),{threshold:.6});observer.observe(rail.current);return()=>observer.disconnect();},[!!card]);
 useEffect(()=>{if(paused||hovered||reduced||!visible||cards.length<2)return;const id=setInterval(()=>{if(document.visibilityState==='visible')setIndex(i=>i+1);},feed.seconds*1000);return()=>clearInterval(id);},[paused,hovered,reduced,visible,cards.length,feed.seconds]);
 useEffect(()=>{if(card&&visible)void interaction(card,'impression').catch(()=>{});},[card?.id,visible,feed.uid]);
 const move=(n:number)=>{setPaused(true);setIndex((current+n+cards.length)%cards.length);setStatus(`Item ${(current+n+cards.length)%cards.length+1} of ${cards.length}`);};
 if(dismissed||(placement==='launch'&&sessionStorage.getItem(launchKey)))return null;
 if(!card){if(placement!=='home')return null;return <p className="promo-state" role="status">{feed.busy?'Loading service ideas…':feed.error}<button onClick={feed.retry}>Retry</button></p>;}
 const Icon=icons[card.icon]||Gift;
 return <><section ref={rail} className={`promo-rail ${placement==='home'?'promo-home-spotlight':''} promo-${card.tone} promo-layout-${card.layout||'compact'}`} aria-roledescription="carousel" aria-label={{home:'Home benefits and offers',explore:'Explore service offers',checkout:'Optional checkout offers',launch:'Today’s welcome offers',push:'Notification offers'}[placement]} onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)} onFocusCapture={e=>{if(!(e.target as Element).closest('[data-carousel-playback]'))setPaused(true);}} onTouchStart={e=>{if(!(e.target as Element).closest('[data-carousel-playback]'))setPaused(true);touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY};}} onTouchEnd={e=>{const p=touch.current;touch.current=null;if(p){const dx=e.changedTouches[0].clientX-p.x,dy=e.changedTouches[0].clientY-p.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.5)move(dx<0?1:-1);}}}>
  <span className="promo-lightfield" aria-hidden="true"/><button type="button" className="promo-slide" key={card.id} onClick={()=>{setPaused(true);setDetail(card);void interaction(card,'open').catch(()=>{});}}><span className="promo-icon">{card.image_url?<img src={apiAssetUrl(card.image_url)} alt={card.image_alt||''}/>:<Icon size={23} strokeWidth={1.8}/>}</span><span className="promo-copy">{placement==='home'&&<small className="promo-eyebrow">Repaido · {city}</small>}{card.event_name&&<small>{card.event_name}</small>}<strong>{card.title}</strong><span className={card.discount_paise?'promo-price':undefined}>{card.discount_paise?`${money(card.offer_price_paise)} · Save ${money(card.discount_paise)}`:card.body}</span></span><ArrowRight size={17}/></button>
  <div className="promo-controls">{placement==='home'&&<button type="button" data-carousel-playback aria-label={paused?'Play home spotlight':'Pause home spotlight'} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button>}<button type="button" aria-label="Previous offer or benefit" onClick={()=>move(-1)} disabled={cards.length<2}><ChevronLeft size={15}/></button><span aria-hidden="true">{current+1}/{cards.length}</span><button type="button" aria-label="Next offer or benefit" onClick={()=>move(1)} disabled={cards.length<2}><ChevronRight size={15}/></button>{placement==='launch'&&<button type="button" aria-label="Dismiss today’s welcome offer" onClick={()=>{sessionStorage.setItem(launchKey,'dismissed');setDismissed(true);}}><X size={16}/></button>}</div><span className="sr-only" role="status">{status}</span>
 </section>{detail&&<Modal title={detail.title} className="promo-detail" onClose={()=>setDetail(null)}><p>{detail.body}</p>{detail.image_url&&<img className="promo-detail-image" src={apiAssetUrl(detail.image_url)} alt={detail.image_alt||''}/>} {!detail.service&&onExplore&&<button type="button" className="ops-primary" onClick={()=>{setDetail(null);onExplore();}}>Explore services<ArrowRight size={16}/></button>}{detail.service&&<><h3>{detail.service.name}</h3><p>{detail.discount_paise>0&&<><s>{money(detail.price_paise)}</s> · </>}<strong>{detail.home_service?'Scope & quote before booking':money(detail.offer_price_paise)}</strong></p><details open><summary>Offer terms & conditions</summary><p>{detail.terms}</p></details><p>Available until {new Date(detail.ends_at*1000).toLocaleString('en-IN')}. {detail.home_service?'Plan and professional availability require confirmation.':`Limit ${detail.per_user_limit} per customer, subject to remaining offer budget and service availability.`}</p><details><summary>Why this suggestion?</summary><p>{detail.reason}. Optional personalisation and offer notifications can be changed in your profile.</p></details><button type="button" className="ops-primary" onClick={()=>{setDetail(null);onOpen(detail);}}>{detail.home_service?'Explore Home service':'View service & offer'}</button>{!feed.uid&&onSignIn&&<button type="button" onClick={onSignIn}>Sign in to check eligibility</button>}{feed.uid&&<button type="button" onClick={()=>void interaction(detail,'dismiss').then(()=>{setDetail(null);feed.retry();}).catch(()=>setStatus('Could not hide this offer. Please retry.'))}>Hide this offer</button>}</>}</Modal>}</>;
}
type Prefs={consent_version:1;personalised:boolean;push:boolean;launch:boolean;daily_cap:number;city:string};
export function PromotionPreferences({city,onSignIn}:{city:string;onSignIn:()=>void}){
 const [p,setP]=useState<Prefs|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{let generation=0;const unsubscribe=onIdTokenChanged(auth,account=>{const request=++generation;setP(null);setError('');setLoading(!!account);if(account)void operation<Prefs>('/campaigns/preferences').then(data=>{if(request===generation)setP(data);}).catch(e=>{if(request===generation)setError(e.message);}).finally(()=>{if(request===generation)setLoading(false);});});return()=>{generation++;unsubscribe();};},[retry]);
 const save=async(next:Prefs)=>{setBusy(true);setError('');try{if(next.push&&nativeAvailable()){if(await nativeCall('appKind')!=='customer')throw Error('Offer notifications require the updated Repaido customer app.');await enableNativePush('customer');}const data=await operation<Prefs>('/campaigns/preferences',{method:'PUT',body:JSON.stringify({consent_version:1,personalised:next.personalised,push:next.push,launch:next.launch,daily_cap:next.daily_cap,city})});setP(data);if(nativeAvailable())await nativeCall('setOffersEnabled',{enabled:data.push}).catch(()=>{});setMessage('Offer preferences saved.');window.dispatchEvent(new Event('repaido:interests'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="promo-preferences"><h3>Offers & suggestions</h3><p>Optional suggestions can use saved category interests and completed, paid bookings, including spending, and marketplace banners you open. Prices are not increased based on your profile. Turn this off at any time.</p>{p?<><label><input type="checkbox" checked={p.personalised} disabled={busy} onChange={e=>void save({...p,personalised:e.target.checked})}/>Personalise offers</label><label><input type="checkbox" checked={p.launch} disabled={busy} onChange={e=>void save({...p,launch:e.target.checked})}/>Show welcome-only offers when I open the app</label><label><input type="checkbox" checked={p.push} disabled={busy} onChange={e=>void save({...p,push:e.target.checked})}/>Send offer notifications, 8 AM–11 PM India time</label><label>Daily maximum<select value={p.daily_cap} disabled={busy} onChange={e=>void save({...p,daily_cap:Number(e.target.value)})}>{[0,1,2,3].map(v=><option key={v} value={v}>{v===0?'Off':v}</option>)}</select></label><p>Only relevant, available offers are sent. Booking notifications are separate. Background offers require the updated Android customer app with device notifications enabled.</p></>:loading?<p role="status">Loading your preferences…</p>:!auth.currentUser?<button type="button" onClick={onSignIn}>Sign in to manage offers</button>:null}{error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}{message&&<p role="status">{message}</p>}</section>;
}
