import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,CheckCircle2,Clock3,RefreshCw} from 'lucide-react';
import {apiAssetUrl,apiFetch} from '../services/api';
import './public-contract-progress.css';

type PublicMilestone={id:string;title:string;status:string;due_at:number|null;submitted_at?:number|null;reviewed_at?:number|null};
type PublicEvidence={id:string;url:string;kind?:'image'|'video';mime?:'image/jpeg'|'image/png'|'video/mp4'|'video/webm';source:'uploader_consented_photo'|'uploader_consented_media'};
type PublicProgressEntry={id:string;percent:number;status:string;created_at:number;reviewed_at?:number;source:string;milestone_id?:string;note:string|null;evidence:PublicEvidence[]};
interface PublicContract {
  project:{id:string;title:string;status:string;starts_at:number;ends_at:number;awarded_at:number};
  contractor:{id:string;name:string};milestones:PublicMilestone[];progress:PublicProgressEntry[];
  calendar:{kind:'work_starts'|'work_deadline'|'milestone';at:number|null;id?:string;title?:string;status?:string}[];
  progress_series:{at:number;percent:number;status:string;source:string}[];
  verified_milestone_progress:{approved:number;total:number};visibility_source:'customer_owner_consent';source:string;server_time:number;
}
type PublicHistoryPage={projects:PublicContract[];has_more:boolean;next_cursor:string|null;source:string};
type ReadState<T>={path:string;data:T|null;busy:boolean;error:string;private:boolean};
const dateTime=(value:number|null)=>typeof value==='number'&&Number.isFinite(value)&&value>0&&Number.isFinite(new Date(value*1000).getTime())?new Date(value*1000).toISOString():undefined;
const date=(value:number|null)=>dateTime(value)?new Date(value!*1000).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'Date not shared';
const status=(value:string)=>({planning:'Planning',planned:'Planned',active:'Work in progress',paused:'Paused',completed:'Completed',cancelled:'Cancelled',pending:'Awaiting review',submitted:'Awaiting customer review',reported:'Contractor reported',customer_confirmed:'Customer confirmed',changes_requested:'Changes requested',approved:'Customer approved',rejected:'Changes requested'}[value]||value.replaceAll('_',' '));
const publicPhoto=(url:string)=>/^\/api\/operations\/contracts\/public\/attachments\/[A-Za-z0-9_-]+$/.test(url)?apiAssetUrl(url):null;
function PublicEvidenceMedia({evidence,title,at}:{evidence:PublicEvidence;title:string;at:number}){const url=publicPhoto(evidence.url),label='Shared work '+(evidence.kind==='video'?'video':'photo')+' for '+title+' on '+date(at);if(!url)return null;if(evidence.kind==='video'&&!['video/mp4','video/webm'].includes(evidence.mime||''))return null;if(evidence.kind!=='video'&&evidence.mime&&!['image/jpeg','image/png'].includes(evidence.mime))return null;return <figure>{evidence.kind==='video'?<video src={url} controls playsInline preload="metadata" aria-label={label}/>:<img src={url} alt={label} loading="lazy" decoding="async"/>}<figcaption>Shared with uploader consent</figcaption></figure>;}

async function publicRead<T>(path:string,signal?:AbortSignal):Promise<T>{
  const response=await apiFetch(path,{signal,headers:{Accept:'application/json'},credentials:'omit',cache:'no-store'},{background:true});
  if(!response.ok){const error=new Error(response.status===404?'This contract has no public progress shared.':'Public contract details could not load. Retry.');Object.assign(error,{status:response.status});throw error;}
  return response.json() as Promise<T>;
}
function usePublicContract<T>(path:string){
  const [state,setState]=useState<ReadState<T>>({path,data:null,busy:true,error:'',private:false}),request=useRef(0),controller=useRef<AbortController|null>(null),alive=useRef(true);
  const load=useCallback(async()=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const generation=++request.current;setState({path,data:null,busy:true,error:'',private:false});try{const data=await publicRead<T>(path,AbortSignal.any([abort.signal,AbortSignal.timeout(15000)]));if(alive.current&&generation===request.current&&!abort.signal.aborted)setState({path,data,busy:false,error:'',private:false});}catch(error){if(alive.current&&generation===request.current&&!abort.signal.aborted)setState({path,data:null,busy:false,error:(error as Error).message,private:(error as Error&{status?:number}).status===404});}},[path]);
  useEffect(()=>{alive.current=true;void load();const refresh=()=>{if(!document.hidden)void load();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive.current=false;request.current++;controller.current?.abort();window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[load]);
  return {...(state.path===path?state:{path,data:null,busy:true,error:'',private:false}),reload:load};
}
function ReadMessage({busy,error,private:privateProgress,onRetry}:{busy:boolean;error:string;private:boolean;onRetry:()=>void}){return busy?<p className="public-contract-note" role="status">Loading shared contract progress…</p>:error?<div className="public-contract-read-message" role={privateProgress?'status':'alert'}><p>{error}</p><button type="button" onClick={onRetry}><RefreshCw size={16} aria-hidden="true"/>Refresh public progress</button></div>:null;}
function PublicContractSummary({contract}:{contract:PublicContract}){const {project,verified_milestone_progress:milestones}=contract;return <><div className="public-contract-summary"><span className="public-contract-state">{status(project.status)}</span><h3>{project.title}</h3><p>{contract.contractor.name}</p><span className="public-contract-dates"><CalendarDays size={16} aria-hidden="true"/>{date(project.starts_at)} – {date(project.ends_at)}</span></div><p className="public-contract-review-count"><CheckCircle2 size={16} aria-hidden="true"/>{milestones.approved} of {milestones.total} milestones approved by the customer</p></>;}
function PublicContractTimeline({contract}:{contract:PublicContract}){
  const entries=[...contract.progress].sort((a,b)=>b.created_at-a.created_at),series=[...contract.progress_series].sort((a,b)=>a.at-b.at);
  return <div className="public-contract-detail"><PublicContractSummary contract={contract}/><p className="public-contract-note">The customer chose to share this progress. Percentages are progress reports; milestone approvals record the customer’s review.</p>
    {series.length>0&&<section className="public-contract-section" aria-label="Reported progress over time"><h4>Reported progress</h4><ol className="public-contract-series">{series.map((point,index)=><li key={point.at+':'+index}><time dateTime={dateTime(point.at)}>{date(point.at)}</time><span className="public-contract-progress-bar" aria-hidden="true"><span style={{width:Math.max(0,Math.min(100,point.percent))+'%'}}/></span><strong>{point.percent}%</strong><span>{status(point.status)}</span></li>)}</ol></section>}
    <section className="public-contract-section" aria-label="Shared contract calendar"><h4>Calendar</h4>{contract.calendar.length?<ol className="public-contract-calendar">{[...contract.calendar].sort((a,b)=>(a.at||0)-(b.at||0)).map((event,index)=><li key={event.kind+':'+(event.id||index)}><CalendarDays size={16} aria-hidden="true"/><div><time dateTime={dateTime(event.at)}>{date(event.at)}</time><strong>{event.kind==='work_starts'?'Work starts':event.kind==='work_deadline'?'Work deadline':event.title||'Milestone due'}</strong>{event.status&&<span>{status(event.status)}</span>}</div></li>)}</ol>:<p className="public-contract-note">No calendar entries shared.</p>}</section>
    <section className="public-contract-section" aria-label="Shared contract milestones"><h4>Milestones</h4>{contract.milestones.length?<ul className="public-contract-milestones">{contract.milestones.map(item=><li key={item.id}>{item.status==='approved'?<CheckCircle2 size={18} aria-hidden="true"/>:<Clock3 size={18} aria-hidden="true"/>}<div><strong>{item.title}</strong><span>{status(item.status)} · Due {date(item.due_at)}</span></div></li>)}</ul>:<p className="public-contract-note">No milestones shared yet.</p>}</section>
    <section className="public-contract-section" aria-label="Shared work updates"><h4>Work updates</h4>{entries.length?<ol className="public-contract-updates">{entries.map(entry=><li key={entry.id}><div className="public-contract-update-heading"><strong>{entry.percent}% reported</strong><span>{status(entry.status)}</span></div><time dateTime={dateTime(entry.created_at)}>{date(entry.created_at)}</time>{entry.note&&<p>{entry.note}</p>}{entry.evidence.length>0&&<div className="public-contract-photos">{entry.evidence.map(evidence=><PublicEvidenceMedia key={evidence.id} evidence={evidence} title={contract.project.title} at={entry.created_at}/>)}</div>}</li>)}</ol>:<p className="public-contract-note">No work updates shared yet.</p>}</section>
  </div>;
}

export function PublicContractProgress({projectId}:{projectId:string}){const resource=usePublicContract<PublicContract>('/api/operations/contracts/public/projects/'+encodeURIComponent(projectId)+'/progress');return <section className="public-contract-progress" aria-label="Public contract progress"><ReadMessage {...resource} onRetry={()=>void resource.reload()}/>{resource.data&&<><div className="public-contract-refresh"><button type="button" onClick={()=>void resource.reload()} disabled={resource.busy}><RefreshCw size={16} aria-hidden="true"/>Refresh progress</button></div><PublicContractTimeline contract={resource.data}/></>}</section>;}
export function PublicContractHistory({contractorId}:{contractorId:string}){
  const resource=usePublicContract<PublicHistoryPage>('/api/operations/contracts/public/contractors/'+encodeURIComponent(contractorId)+'/projects?limit=12'),[extra,setExtra]=useState<PublicHistoryPage|null>(null),[selected,setSelected]=useState(''),[moreBusy,setMoreBusy]=useState(false),[moreError,setMoreError]=useState(''),alive=useRef(true),generation=useRef(0);
  useEffect(()=>{alive.current=true;setExtra(null);setSelected('');setMoreBusy(false);setMoreError('');return()=>{alive.current=false;generation.current++;};},[contractorId]);
  useEffect(()=>{setExtra(null);setMoreBusy(false);setMoreError('');generation.current++;},[resource.data]);
  const projects=[...new Map([...(resource.data?.projects||[]),...(extra?.projects||[])].map(contract=>[contract.project.id,contract])).values()],cursor=extra?extra.next_cursor:resource.data?.next_cursor;
  const more=async()=>{if(!cursor||moreBusy)return;const request=++generation.current;setMoreBusy(true);setMoreError('');try{const page=await publicRead<PublicHistoryPage>('/api/operations/contracts/public/contractors/'+encodeURIComponent(contractorId)+'/projects?'+new URLSearchParams({limit:'12',cursor}),AbortSignal.timeout(15000));if(alive.current&&request===generation.current)setExtra(old=>({projects:[...(old?.projects||[]),...page.projects],has_more:page.has_more,next_cursor:page.next_cursor,source:page.source}));}catch(error){if(alive.current&&request===generation.current)setMoreError((error as Error).message);}finally{if(alive.current&&request===generation.current)setMoreBusy(false);}};
  return <section className="public-contract-history" aria-label="Public contract history"><header className="public-contract-history-heading"><div><span>SHARED PROJECT HISTORY</span><h2>Contract work & progress</h2></div><button type="button" aria-label="Refresh public contract history" disabled={resource.busy} onClick={()=>void resource.reload()}><RefreshCw size={18} aria-hidden="true"/></button></header>{selected?<><button type="button" className="public-contract-back" onClick={()=>setSelected('')}><ArrowLeft size={16} aria-hidden="true"/>All shared projects</button><PublicContractProgress key={selected} projectId={selected}/></>:<><ReadMessage {...resource} onRetry={()=>void resource.reload()}/>{resource.data&&<><p className="public-contract-note">Only projects with customer-approved public sharing appear here.</p><div className="public-contract-history-grid">{projects.map(contract=><article key={contract.project.id}><PublicContractSummary contract={contract}/><button type="button" onClick={()=>setSelected(contract.project.id)}>View shared progress<ArrowRight size={16} aria-hidden="true"/></button></article>)}</div>{!projects.length&&<p className="public-contract-note">No contract progress has been shared publicly yet.</p>}{moreError&&<p className="public-contract-read-message" role="alert">{moreError}</p>}{cursor&&<button type="button" className="public-contract-more" disabled={moreBusy} onClick={()=>void more()}>{moreBusy?'Loading…':'More shared projects'}</button>}</>}</>}</section>;
}
