import type {HomeService} from './HomePlans';
import {ServiceTerms} from './ServiceTerms';
import type {DiscoveryEvent} from './ServiceHydration';
import {useEffect, useState, useRef} from 'react';
import {searchCompletions} from '../services/searchCompletions.mjs';
import './search-discovery.css';
import {Search, MapPin, SlidersHorizontal, ArrowRight, ShieldCheck, Scale, X} from 'lucide-react';
import {Modal} from './ui';
import ServiceImage from './ServiceImage';
import {apiFetch} from '../services/api';
import {operation, money} from '../services/operations';
import {seededServices} from '../data';
import type {Service, CategoryId} from '../types';

type Professional = {id:string;name:string;role:string;skills:string[];categories:string[];tools:string[];experience_years:number;completed_tasks:number;rating:number|null;rating_count:number;distance_km:number};
type Package = {id:string;name:string;category:CategoryId;description:string;price_paise:number;duration_minutes:number;included:string[];excluded:string[]};
type Results = {suggestion_catalog?:{label:string;category:string;kind:string}[];services:Package[];home_services?:HomeService[];professionals:Professional[];categories:{id:string;name:string}[];covered:boolean;offers_status:string;ranking:string};
type Preferences = {enabled:boolean;categories:Record<string,number>};
function asService(p:Package):Service {
  const art=seededServices.find(s=>s.id===p.id)||seededServices.find(s=>s.category===p.category);
  return {...p,price:p.price_paise,duration:p.duration_minutes,image:art?.image||'',imageTile:art?.imageTile,imageAlt:p.name};
}

type Filters={category:string;sort:string;role:string;price:string;minPrice:string;duration:string;rating:string;experience:string;radius:string};
const defaultFilters:Filters={category:'',sort:'relevance',role:'',price:'',minPrice:'',duration:'',rating:'0',experience:'0',radius:'8'};
export default function SearchDiscovery({query,onQuery,place,onClose,onLocation,onBook,signedIn,onSignIn,onEvent,onPreferencesChange,onHomeService}:{onHomeService:(id:string)=>void;onEvent:(event:DiscoveryEvent)=>void;onPreferencesChange:(enabled:boolean)=>void;query:string;onQuery:(q:string)=>void;place:{city:string;lat?:number;lng?:number;confirmed:boolean};onClose:()=>void;onLocation:()=>void;onBook:(s:Service)=>void;signedIn:boolean;onSignIn:()=>void}) {
  const [searchEdited,setSearchEdited]=useState(false);
  const [filters,setFilters]=useState<Filters>(defaultFilters),[draft,setDraft]=useState<Filters>(defaultFilters),[filterOpen,setFilterOpen]=useState(false),[filterGroup,setFilterGroup]=useState('Services'),[filterError,setFilterError]=useState('');
  const {category,sort,role,price,minPrice,duration,rating,experience,radius}=filters;
  const setCategory=(category:string)=>setFilters(f=>({...f,category}));
  const [suggestOpen,setSuggestOpen]=useState(false),[suggestIndex,setSuggestIndex]=useState(-1);
  const input=useRef<HTMLInputElement>(null);
  const [results,setResults]=useState<Results|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [compare,setCompare]=useState<Package[]>([]),[detail,setDetail]=useState<Package|null>(null),[comparing,setComparing]=useState(false);
  const [prefs,setPrefs]=useState<Preferences>({enabled:false,categories:{}}),[prefBusy,setPrefBusy]=useState(false),[prefError,setPrefError]=useState('');
  useEffect(()=>setFilterError(''),[draft]);
  const hasLocation=place.confirmed&&Number.isFinite(place.lat)&&Number.isFinite(place.lng);
  useEffect(()=>{if(signedIn)void operation<Preferences>('/discovery/preferences',{}, {background:true}).then(setPrefs).catch(()=>setPrefError('Personalisation settings could not load. Try again.'));},[signedIn]);
  useEffect(()=>{
    const controller=new AbortController();let active=true;
    setBusy(true);setError('');
    const timer=setTimeout(async()=>{
      const timeout=setTimeout(()=>controller.abort(),12000);
      try {
        const r=await apiFetch('/api/operations/discovery/search',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({query,category,city:place.city,location:hasLocation?{lat:place.lat,lng:place.lng}:null,radius_km:Number(radius),sort,role,min_price_paise:Math.round(Number(minPrice||0)*100),max_price_paise:price?Math.round(Number(price)*100):null,max_duration_minutes:duration?Number(duration):null,min_rating:Number(rating),min_experience:Number(experience)})},{background:true});
        if(!r.ok)throw Error('Search is unavailable right now. Please retry.');
        const data:Results=await r.json();if(active)setResults(data);
      }catch(e){if(active){setResults(null);setError((e as Error).name==='AbortError'?'Search took too long. Check your connection and retry.':(e as Error).message);}}
      finally{clearTimeout(timeout);if(active)setBusy(false);}
    },250);
    return()=>{active=false;clearTimeout(timer);controller.abort();};
  },[query,category,sort,role,price,minPrice,duration,rating,experience,radius,place.city,place.lat,place.lng,hasLocation,retry]);
  useEffect(()=>{if(!searchEdited||!prefs.enabled||busy||!query.trim()||!results?.services.length)return;const timer=setTimeout(()=>onEvent({kind:'search',query}),1200);return()=>clearTimeout(timer);},[searchEdited,prefs.enabled,busy,query,results,onEvent]);
  const suggestions=searchCompletions(query,results?.suggestion_catalog||[],prefs.enabled?prefs.categories:{});
  const showSuggestions=suggestOpen&&suggestions.length>0;
  const activeCount=Object.keys(defaultFilters).filter(k=>filters[k as keyof Filters]!==defaultFilters[k as keyof Filters]).length;
  const chooseSuggestion=(label:string)=>{setSearchEdited(true);onQuery(label);setSuggestOpen(false);setSuggestIndex(-1);setDetail(null);setComparing(false);input.current?.focus();};
  const openFilters=()=>{setDraft(filters);setFilterError('');setFilterOpen(true);setSuggestOpen(false);};
  const packages=[...(results?.services||[])];
  const open=(p:Package)=>{setDetail(p);setComparing(false);if(prefs.enabled&&signedIn)onEvent({kind:'service_view',service_id:p.id});};
  const toggleCompare=(p:Package)=>setCompare(rows=>rows.some(s=>s.id===p.id)?rows.filter(s=>s.id!==p.id):rows.length<3?[...rows,p]:rows);
  const info=(p:Package)=><><p>{p.description}</p><dl><div><dt>Service charge</dt><dd>{money(p.price_paise)}</dd></div><div><dt>Estimated duration</dt><dd>{p.duration_minutes} min</dd></div></dl><h4>Included</h4><ul>{p.included.map(x=><li key={x}>{x}</li>)}</ul><h4>Not included</h4><ul>{p.excluded.map(x=><li key={x}>{x}</li>)}</ul><p className="discovery-note">Parts and extra work need your approval. Review the final bill before paying. A professional must accept your requested appointment.</p><button className="discovery-primary" onClick={()=>onBook(asService(p))}>Choose this service <ArrowRight size={16}/></button></>;
  return <Modal className="search-discovery discovery-frameless" frameless title="Find the right help" onClose={onClose}>
    <div className="discovery-content">
    <div className="discovery-search-dock" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setSuggestOpen(false);}}>
      <div className="discovery-search-row"><div className="discovery-search customer-search-field"><Search size={18} aria-hidden="true"/><input ref={input} data-autofocus type="search" role="combobox" autoComplete="off" autoCorrect="off" spellCheck={false} aria-autocomplete="list" aria-expanded={showSuggestions} aria-controls={showSuggestions?'discovery-suggestions':undefined} aria-activedescendant={showSuggestions&&suggestions[suggestIndex]?`discovery-suggestion-${suggestIndex}`:undefined} value={query} maxLength={120} onFocus={()=>setSuggestOpen(true)} onChange={e=>{setSearchEdited(true);onQuery(e.target.value);setSuggestOpen(true);setSuggestIndex(-1);setDetail(null);setComparing(false);}} onKeyDown={e=>{if(e.key==='Escape'&&showSuggestions){e.preventDefault();e.stopPropagation();setSuggestOpen(false);}else if(showSuggestions&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setSuggestIndex(i=>(i+(e.key==='ArrowDown'?1:-1)+suggestions.length)%suggestions.length);}else if(e.key==='Enter'){e.preventDefault();if(showSuggestions&&suggestions[suggestIndex])chooseSuggestion(suggestions[suggestIndex].label);else setSuggestOpen(false);}}} placeholder="Search for repair or home services" aria-label="Search services, skills and professionals"/><button className="discovery-input-close" aria-label="Close search" onClick={onClose}><X size={18}/></button></div><button className="discovery-location-icon" aria-label={hasLocation?`Change search location: ${place.city}`:'Set location for nearby professionals'} title={hasLocation?place.city:'Set location'} onClick={onLocation}><MapPin size={19}/></button><button className="discovery-filter-icon" aria-label={`Filters and sort${activeCount?`, ${activeCount} active`:''}`} aria-haspopup="dialog" onClick={openFilters}><SlidersHorizontal size={19}/>{!!activeCount&&<span>{activeCount}</span>}</button></div>
      {showSuggestions&&<div className="discovery-suggestions" role="listbox" aria-label="Search suggestions" id="discovery-suggestions">{suggestions.map((s,i)=><button role="option" id={`discovery-suggestion-${i}`} aria-selected={suggestIndex===i} key={s.label} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseSuggestion(s.label)}><Search size={14}/><span>{s.label}<small>{s.kind}</small></span><ArrowRight size={14}/></button>)}</div>}
    </div>
    {(query||activeCount>0)&&<div className="discovery-active-filters">{query&&<button onClick={()=>{onQuery('');input.current?.focus();}}>Clear query<X size={12}/></button>}{activeCount>0&&<button onClick={openFilters}>{activeCount} active filters<SlidersHorizontal size={12}/></button>}{activeCount>0&&<button onClick={()=>setFilters(defaultFilters)}>Reset filters</button>}</div>}
    <nav className="discovery-categories" aria-label="Search service category"><button aria-pressed={!category} onClick={()=>{setCategory('');setDetail(null);}}>All services</button>{results?.categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setDetail(null);onEvent({kind:'category_view',category:c.id});}}>{c.name}</button>)}</nav>
    {filterOpen&&<Modal title="Filters & sort" className="discovery-filter-sheet" onClose={()=>setFilterOpen(false)}><div className="discovery-filter-layout"><nav aria-label="Filter groups">{['Services','Budget & time','Professionals','Preferences'].map(g=><button key={g} aria-pressed={filterGroup===g} onClick={()=>setFilterGroup(g)}>{g==='Professionals'?'Experts':g}</button>)}</nav><div className="discovery-filter-fields">
      {filterGroup==='Services'&&<><label>Category<select value={draft.category} onChange={e=>setDraft(f=>({...f,category:e.target.value}))}><option value="">All services</option>{results?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Sort results<select value={draft.sort} onChange={e=>setDraft(f=>({...f,sort:e.target.value}))}><option value="relevance">Best match</option><option value="price">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="duration">Shortest service first</option><option value="distance" disabled={!hasLocation}>Nearest professional</option><option value="rating">Highest rated professional</option><option value="experience">Most experienced professional</option></select></label></>}
      {filterGroup==='Budget & time'&&<><label>Minimum price · ₹<input type="number" min="0" max="1000000" step="1" inputMode="numeric" value={draft.minPrice} placeholder="0" onChange={e=>setDraft(f=>({...f,minPrice:e.target.value}))}/></label><label>Maximum price · ₹<input type="number" min="0" max="1000000" step="1" inputMode="numeric" value={draft.price} placeholder="Any budget" onChange={e=>setDraft(f=>({...f,price:e.target.value}))}/></label><div className="discovery-budget-chips">{['500','1000','2000'].map(v=><button key={v} aria-pressed={draft.price===v} onClick={()=>setDraft(f=>({...f,price:v,minPrice:''}))}>Under ₹{v}</button>)}</div><label>Service duration<select value={draft.duration} onChange={e=>setDraft(f=>({...f,duration:e.target.value}))}><option value="">Any duration</option><option value="60">Up to 1 hour</option><option value="120">Up to 2 hours</option><option value="240">Up to 4 hours</option></select></label><p>Price and duration apply to fixed catalogue packages. Quote-based home plans are hidden when these limits are set.</p></>}
      {filterGroup==='Professionals'&&<><label>Professional level<select value={draft.role} onChange={e=>setDraft(f=>({...f,role:e.target.value}))}><option value="">All levels</option><option value="technician">Technician</option><option value="specialist">Specialist</option></select></label><label>Minimum rating<select value={draft.rating} onChange={e=>setDraft(f=>({...f,rating:e.target.value}))}><option value="0">Any rating</option><option value="4">4+ stars</option><option value="4.5">4.5+ stars</option></select></label><label>Experience<select value={draft.experience} onChange={e=>setDraft(f=>({...f,experience:e.target.value}))}><option value="0">Any experience</option><option value="2">2+ years</option><option value="5">5+ years</option><option value="10">10+ years</option></select></label><label>Search radius<select value={draft.radius} onChange={e=>setDraft(f=>({...f,radius:e.target.value}))}><option value="3">Within 3 km</option><option value="5">Within 5 km</option><option value="8">Within 8 km</option></select></label><p>Only approved professionals online recently are shown. Travel limits and current 6 km booking coverage apply. Ratings and experience filter professionals, not service packages.</p>{!hasLocation&&<button onClick={()=>{setFilterOpen(false);onLocation();}}>Set your search location</button>}</>}
      {filterGroup==='Preferences'&&<div className="discovery-preferences"><label className="discovery-optin"><input type="checkbox" checked={prefs.enabled} disabled={prefBusy||!signedIn} onChange={async e=>{const enabled=e.target.checked;setPrefBusy(true);setPrefError('');try{setPrefs(await operation<Preferences>('/discovery/preferences',{method:'PUT',body:JSON.stringify({enabled,consent_version:2})}));onPreferencesChange(enabled);}catch(e){setPrefError((e as Error).message);}finally{setPrefBusy(false);}}}/> Personalise suggestions from searches and service visits</label><p className="discovery-note">Optional. Saves category interests from catalogue searches and service/category visits, not raw search text or location history. Turning it off clears them. Does not subscribe you to messages.</p>{!signedIn&&<button onClick={onSignIn}>Sign in to save preferences</button>}{prefError&&<p role="alert">{prefError}</p>}</div>}
    </div></div>{filterError&&<p role="alert" className="discovery-filter-error">{filterError}</p>}<div className="discovery-filter-footer"><button onClick={()=>{setDraft(defaultFilters);setFilterError('');}}>Reset all</button><button className="discovery-primary" onClick={()=>{const min=Number(draft.minPrice||0),max=Number(draft.price||0);if(min<0||max<0||min>1000000||max>1000000||!Number.isFinite(min)||!Number.isFinite(max)||(draft.price&&min>max)){setFilterError('Enter valid prices; minimum must not exceed maximum.');return;}setFilters(draft);setDetail(null);setComparing(false);setFilterOpen(false);}}>Apply filters<ArrowRight size={16}/></button></div></Modal>}
    {detail?<section className="discovery-detail"><button onClick={()=>setDetail(null)}>← Back to results</button><h3>{detail.name}</h3>{info(detail)}<ServiceTerms serviceId={detail.id}/></section>:comparing?<section className="discovery-detail"><button onClick={()=>setComparing(false)}>← Back to results</button><h3>Compare your choices</h3><div className="discovery-compare-grid">{compare.map(p=><article key={p.id}><h4>{p.name}</h4>{info(p)}<ServiceTerms serviceId={p.id}/></article>)}</div></section>:<>
      <div className="discovery-heading"><h3>{query?'Matching services':prefs.enabled?'Services for you':'Explore services'}</h3><span role="status" aria-live="polite">{busy?'Searching…':`${packages.length+(results?.home_services?.length||0)} services`}</span></div>
      {error&&<div className="discovery-error" role="alert"><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Retry search</button></div>}
      <div className="discovery-results" aria-busy={busy}>{!busy&&packages.map(p=><article className="discovery-card" data-selected={compare.some(s=>s.id===p.id)} key={p.id}><button className="discovery-card-open" onClick={()=>open(p)}><ServiceImage className="discovery-thumbnail" decorative service={asService(p)}/><span><strong>{p.name}</strong><span>{p.duration_minutes} min · {money(p.price_paise)}</span></span><ArrowRight size={16}/></button><div className="discovery-card-bottom"><span>View scope & exclusions</span><label><input type="checkbox" checked={compare.some(s=>s.id===p.id)} disabled={compare.length>=3&&!compare.some(s=>s.id===p.id)} onChange={()=>toggleCompare(p)}/> Compare</label></div></article>)}</div>
      {!busy&&!!results?.home_services?.length&&<section><h3>Repaido Home · plans & projects</h3><p className="discovery-note">Written scope and quote first. Professional and schedule confirmed after review.</p><div className="discovery-results">{results.home_services.map(s=><article className="discovery-card" key={s.id}><button className="discovery-card-open" onClick={()=>onHomeService(s.id)}><ShieldCheck size={22} aria-hidden="true"/><span><strong>{s.name}</strong><span>{s.recurring?'7 days · 1, 3 or 6 months':'Consultation & estimate'}</span></span><ArrowRight size={16}/></button></article>)}</div></section>}
      {!busy&&!error&&!packages.length&&!results?.home_services?.length&&<div className="discovery-empty"><h4>No services match these filters</h4><p>Try another service name or increase your budget.</p><button onClick={()=>{onQuery('');setFilters(defaultFilters);}}>Clear search filters</button></div>}
      <div className="discovery-heading"><h3>Professionals near you</h3><ShieldCheck size={18}/></div>
      {!hasLocation?<div className="discovery-empty"><p>Confirm your service location to check nearby skills and availability.</p><button onClick={onLocation}>Set location</button></div>:!busy&&!error&&!results?.professionals.length?<p className="discovery-empty">{results?.covered?'No available professionals match right now. Try another category or check again later.':'This city is outside current booking coverage.'}</p>:null}
      {!busy&&results?.professionals.map(w=><article className="discovery-worker" key={w.id}><div><h4>{w.name}</h4><span>{w.role==='specialist'?'Specialist':'Technician'} · {w.distance_km} km straight-line</span><p>{w.skills.join(' · ')}</p></div><details><summary>Experience & details</summary><p>{w.experience_years} years · {w.completed_tasks} completed tasks</p><p>{w.rating===null?'No reviews yet':`${w.rating} / 5 · ${w.rating_count} verified reviews`}</p><p>Tools: {w.tools.join(', ')}</p><p>Online recently. Assignment is confirmed after a booking request; this is not a reserved professional.</p><button onClick={()=>{setCategory(w.categories[0]||'');onQuery('');}}>See services in this category</button></details></article>)}
      <details className="discovery-ranking"><summary>How results are chosen</summary><p>{results?.ranking||'Results use the live service catalogue. Nearby professionals require a confirmed location.'}</p><p>Best match uses skills and a review-confidence adjustment, so a single rating does not outweigh a strong track record. Displayed ratings are actual averages. Prices and worker earnings are not changed by personalisation.</p></details>
    </>}
    {!!compare.length&&!detail&&!comparing&&<div className="discovery-compare-bar"><span role="status" aria-live="polite"><Scale size={16}/> {compare.length} of 3 selected</span><button className="discovery-primary" disabled={compare.length<2} onClick={()=>setComparing(true)}>Compare services</button><button aria-label="Clear compared services" onClick={()=>setCompare([])}><X size={18}/></button></div>}
    </div>
  </Modal>;
}
