import RepaidoBrand from './RepaidoBrand';
import {useState} from 'react';
import {ArrowDownWideNarrow,Clock3,GitCompareArrows,MapPin,SlidersHorizontal} from 'lucide-react';
import type {Service} from '../types';
import {formatDuration,formatMoney} from '../data';
import {Modal} from './ui';
import ServiceImage from './ServiceImage';
import './service-finder.css';
export default function ServiceFinder({services,sort,onSort,onFilters,onPreview,onReset,filtered}:{services:Service[];sort:string;onSort:(value:string)=>void;onFilters:()=>void;onPreview:(service:Service)=>void;onReset:()=>void;filtered:boolean}){
 const [comparing,setComparing]=useState(false),[choices,setChoices]=useState<string[]>(['','','']);
 const selected=choices.map(id=>services.find(s=>s.id===id)).filter((s):s is Service=>!!s);
 const minimum=services.length?Math.min(...services.map(s=>s.price)):null;
 return <section className="service-finder" aria-label="Find and compare services">
  <div className="finder-brand"><RepaidoBrand size="sm"/></div><div className="finder-summary"><span className="finder-count" aria-live="polite"><strong>{services.length}</strong> {services.length===1?'option':'options'}</span><span><strong>Find your fit</strong><small>{minimum===null?'Adjust your search to see services':`From ${formatMoney(minimum)} · compare scope & visit time`}</small></span>{filtered&&<button className="finder-reset" onClick={onReset}>Reset</button>}</div>
  <div className="finder-actions" role="group" aria-label="Quick service choices"><button aria-pressed={sort==='price-low'} onClick={()=>onSort(sort==='price-low'?'recommended':'price-low')}><ArrowDownWideNarrow size={14} aria-hidden="true"/>Lowest price</button><button aria-pressed={sort==='duration'} onClick={()=>onSort(sort==='duration'?'recommended':'duration')}><Clock3 size={14} aria-hidden="true"/>Shorter visits</button><button onClick={onFilters}><SlidersHorizontal size={14} aria-hidden="true"/>Budget & sort</button><button disabled={services.length<2} onClick={()=>setComparing(true)}><GitCompareArrows size={14} aria-hidden="true"/>Compare</button></div>
  <details className="finder-guide"><summary><MapPin size={13} aria-hidden="true"/>6 km matching · how to choose</summary><p>Compare the included work first, then the service price and estimated visit length. A shorter visit does not mean an earlier appointment.</p><p>Matching checks professionals within 6 km of your service address. Availability is confirmed when a professional accepts. Parts and extra work need your approval.</p></details>
  {comparing&&<Modal title="Compare service packages" className="finder-compare-modal" onClose={()=>setComparing(false)}><p className="finder-compare-intro">Choose up to three packages. Compare their scope before deciding.</p><div className="finder-selects">{choices.map((id,i)=><label key={i}>Service {i+1}{i===2?' (optional)':''}<select value={services.some(s=>s.id===id)?id:''} onChange={e=>setChoices(old=>old.map((v,n)=>n===i?e.target.value:v))}><option value="">Choose a service</option>{services.map(s=><option key={s.id} value={s.id} disabled={choices.includes(s.id)&&s.id!==id}>{s.name} · {formatMoney(s.price)}</option>)}</select></label>)}</div>{selected.length<2&&<p role="status" className="finder-compare-intro">Select at least two services for a side-by-side comparison.</p>}{selected.length>=2&&<div className="finder-comparison" role="region" aria-label="Service comparison; scroll horizontally" tabIndex={0}>{selected.map(s=><article key={s.id}><ServiceImage service={s} className="finder-compare-image" decorative/><h3>{s.name}</h3><dl><dt>Service price</dt><dd>{formatMoney(s.price)}</dd><dt>Estimated visit</dt><dd>{formatDuration(s.duration)}</dd><dt>Verified reviews</dt><dd>{s.reviewCount&&s.rating!==undefined?`${s.rating.toFixed(1)}/5 · ${s.reviewCount} reviews`:'No reviews yet'}</dd></dl><details open><summary>Included</summary><ul>{s.included.map((v,i)=><li key={i}>{v}</li>)}</ul></details><details><summary>Not included</summary>{s.excluded.length?<ul>{s.excluded.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p>Review the service terms for scope limitations.</p>}</details><button onClick={()=>{setComparing(false);onPreview(s);}}>Full details</button></article>)}</div>}</Modal>}
 </section>;
}
