import {ShopBankVerification} from './Procurement';
import {useEffect,useState} from 'react';
import {currentPosition,operation} from '../services/operations';
export type ShopRecord={id:string;name:string;owner_name:string;phone:string;address:string;city:string;postal_code:string;categories:string;business_reference:string;status:string;version:number;review_reason?:string;location:{lat:number;lng:number}};
export function ShopRegistration({children}:{children:(shop:ShopRecord)=>React.ReactNode}){
 const [shop,setShop]=useState<ShopRecord|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{setShop((await operation<{shop:ShopRecord|null}>('/shop/me')).shop);setLoaded(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 if(loaded&&shop?.status==='approved')return <>{children(shop)}</>;
 return <section className="portal-registration"><div className="ops-heading"><h1>{!loaded?'Connecting your shop':shop?.status==='pending_verification'?'Application under review':shop?.status==='suspended'?'Shop access suspended':'Register your shop'}</h1><button disabled={busy} onClick={()=>void load()}>Refresh status</button></div>{error&&<p role="alert" className="ops-error">{error}</p>}{loaded&&(!shop||shop.status==='rejected')?<><p>Tell us about your business. Your verified mobile is attached automatically. You cannot receive orders until the company completes its checks.</p>{shop?.review_reason&&<p className="ops-notice">Review feedback: {shop.review_reason}</p>}<ShopForm initial={shop} busy={busy} submit={async body=>{setBusy(true);setError('');try{await operation('/shop/application',{method:'POST',body:JSON.stringify(body)});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></>:loaded&&shop?<div className="ops-card"><span className="ops-badge">{shop.status.replaceAll('_',' ')}</span><h2>{shop.name}</h2><p>{shop.address}, {shop.city} {shop.postal_code}</p><p>{shop.review_reason||'The company team will verify the owner, business and shop address. Refresh this page to check the decision.'}</p><p>No orders or handovers are available until approval. If details need correction, contact the Repaido team handling your application.</p></div>:<p role="status">{busy?'Loading your account…':'Connection failed. Use Refresh status to retry.'}</p>}</section>;
}
function ShopForm({initial,busy,submit}:{initial:ShopRecord|null;busy:boolean;submit:(body:object)=>Promise<void>}){
 const [pin,setPin]=useState(initial?.location||{lat:'',lng:''} as {lat:number|string;lng:number|string}),[error,setError]=useState('');
 return <form className="ops-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({...Object.fromEntries(f),consent:true,location:{lat:Number(pin.lat),lng:Number(pin.lng)}});}}><div className="portal-form-grid">{[['owner_name','Owner’s full name'],['name','Shop name'],['city','City'],['postal_code','Postal code'],['categories','Products you sell'],['business_reference','Business registration / trade licence reference']].map(([name,label])=><label key={name}>{label}<input name={name} required minLength={name==='owner_name'||name==='city'?2:3} maxLength={name==='categories'?300:100} pattern={name==='postal_code'?'[0-9]{6}':undefined} defaultValue={String(initial?.[name as keyof ShopRecord]||'')}/></label>)}</div><label>Full shop address<textarea name="address" minLength={10} maxLength={500} required defaultValue={initial?.address}/></label><p>Enter the shop coordinates, or use location while at your shop. This is the parts pickup address.</p><button type="button" onClick={()=>void currentPosition().then(p=>{setPin(p);setError('');}).catch(e=>setError(e.message))}>Use shop’s current location</button><div className="ops-grid"><label>Latitude<input required type="number" min={-90} max={90} step="any" value={pin.lat} onChange={e=>setPin(p=>({...p,lat:e.target.value}))}/></label><label>Longitude<input required type="number" min={-180} max={180} step="any" value={pin.lng} onChange={e=>setPin(p=>({...p,lng:e.target.value}))}/></label></div><p>Do not enter Aadhaar, bank account numbers or passwords here. Supporting documents are checked by the company through its private review process; this form does not upload or verify them.</p><label className="ops-check"><input type="checkbox" required/>I confirm these details are correct and consent to company verification of my shop application.</label>{error&&<p role="alert" className="ops-error">{error}</p>}<button className="ops-primary" disabled={busy}>{busy?'Submitting…':'Send for company review'}</button></form>;
}
export function ShopReviewQueue(){
 const [shops,setShops]=useState<ShopRecord[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('pending_verification');
 const load=async()=>{setBusy(true);setError('');try{setShops((await operation<{shops:ShopRecord[]}>('/admin/shops')).shops);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 return <section><div className="ops-heading"><div><h2>Shop applications</h2><p>Complete the actual checks before recording approval.</p></div><button disabled={busy} onClick={()=>void load()}>Refresh</button></div><label>Application status<select value={filter} onChange={e=>setFilter(e.target.value)}>{['pending_verification','approved','rejected','suspended','all'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>{error&&<p role="alert" className="ops-error">{error}</p>}{!busy&&!shops.filter(s=>filter==='all'||s.status===filter).length&&<p className="ops-empty">No shops match this status. Choose another status or refresh the list.</p>}<div className="portal-card-grid">{shops.filter(s=>filter==='all'||s.status===filter).map(s=><article className="ops-card" key={s.id+':'+s.version}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');void operation(`/admin/shops/${encodeURIComponent(s.id)}/review`,{method:'POST',body:JSON.stringify({expected_version:s.version||1,decision:f.get('decision'),reason:f.get('reason'),evidence_reference:f.get('reference'),identity_checked:f.has('identity'),business_checked:f.has('business'),address_checked:f.has('address')})}).then(load).catch(e=>{setError(e.message);setBusy(false);});}}><span className="ops-badge">{s.status.replaceAll('_',' ')}</span><h3>{s.name}</h3><p>{s.owner_name} · {s.phone}</p><p>{s.address}, {s.city} {s.postal_code}</p><p>Supplies: {s.categories}</p><p>Business reference: {s.business_reference}</p><p>Pickup pin: {s.location.lat}, {s.location.lng}</p>{s.review_reason&&<p>Last decision: {s.review_reason}</p>}<details><summary>Verify and record a decision</summary>{[['identity','Owner identity checked'],['business','Business registration checked'],['address','Shop address checked']].map(([name,label])=><label className="ops-check" key={name}><input type="checkbox" name={name}/>{label}</label>)}<label>Private verification case reference<input name="reference" required minLength={8} maxLength={200}/></label><label>Decision reason<textarea name="reason" required minLength={10} maxLength={500}/></label><label>Decision<select name="decision"><option value="approved">Approve after verification</option>{s.status==='pending_verification'&&<option value="rejected">Reject with feedback</option>}{s.status==='approved'&&<option value="suspended">Suspend access</option>}</select></label><button disabled={busy}>Record decision</button></details></form>{s.status==='approved'&&<ShopBankVerification shopId={s.id}/>}</article>)}</div></section>;
}
