import {useEffect,useState} from 'react';
import {Gavel,MapPin,Users,ArrowUpRight,Building2,GraduationCap,Hotel,House,ShieldCheck,LockKeyhole,ChevronRight,Trophy,Clock,Calculator,Search,HeartPulse,Store,BriefcaseBusiness,Factory,Warehouse,Truck,HardHat,Zap,Droplets,AirVent,Sun,Radio,Shield,TreePine,Waves,Paintbrush,Boxes} from 'lucide-react';
import {apiFetch} from '../services/api';
import {auth} from '../firebase';
import {Modal} from './ui';
import './contract-work.css';
import './tender-market.css';
const sectors=[
 {name:'All sectors',Icon:Gavel,copy:'Explore project models across industries.'},
 {name:'Real estate',Icon:Building2,copy:'Coordinate property maintenance, fit-outs and handover work.'},
 {name:'Education',Icon:GraduationCap,copy:'Plan campus repairs, electrical upkeep and facility maintenance.'},
 {name:'Hospitality',Icon:Hotel,copy:'Build teams for property refreshes and recurring facility support.'},
 {name:'Home services',Icon:House,copy:'Organise long-term maintenance for homes and residential communities.'},
 {name:'Healthcare',Icon:HeartPulse,copy:'Plan non-clinical facility maintenance and fit-outs for healthcare properties.'},
 {name:'Retail',Icon:Store,copy:'Coordinate shop fit-outs, repairs and multi-location maintenance.'},
 {name:'Office spaces',Icon:BriefcaseBusiness,copy:'Organise office interiors, workspace repairs and recurring upkeep.'},
 {name:'Manufacturing',Icon:Factory,copy:'Explore industrial facility maintenance and installation scopes.'},
 {name:'Warehousing',Icon:Warehouse,copy:'Plan warehouse fit-outs, storage-area maintenance and facility repairs.'},
 {name:'Logistics',Icon:Truck,copy:'Coordinate depot facilities, loading areas and logistics-site maintenance.'},
 {name:'Construction',Icon:HardHat,copy:'Prepare teams for civil works, site execution and construction milestones.'},
 {name:'Electrical',Icon:Zap,copy:'Explore wiring, lighting, electrical installation and maintenance scopes.'},
 {name:'Plumbing',Icon:Droplets,copy:'Plan plumbing installations, pipe repairs and drainage maintenance.'},
 {name:'HVAC',Icon:AirVent,copy:'Coordinate cooling, ventilation and air-conditioning maintenance contracts.'},
 {name:'Solar energy',Icon:Sun,copy:'Explore solar installation, inspection and scheduled maintenance scopes.'},
 {name:'Telecom',Icon:Radio,copy:'Plan structured cabling, connectivity infrastructure and site support.'},
 {name:'Security systems',Icon:Shield,copy:'Coordinate CCTV, access-control installation and system maintenance.'},
 {name:'Landscaping',Icon:TreePine,copy:'Organise garden development, groundskeeping and outdoor maintenance.'},
 {name:'Water systems',Icon:Waves,copy:'Plan water storage, pumping, filtration and treatment-system maintenance.'},
 {name:'Interior design',Icon:Paintbrush,copy:'Explore interior planning, finishing, furnishing and renovation scopes.'},
];
const demos=[
 {id:'demo-estate',sector:'Real estate',title:'Residential handover support',scope:'Illustrative scope: coordinate a snag checklist, electrical checks and finishing repairs across a residential property.',tags:['Handover','Multi-trade'],duration:'Milestone-based'},
 {id:'demo-school',sector:'Education',title:'Campus maintenance programme',scope:'Illustrative scope: plan scheduled inspections, repair windows and a documented maintenance checklist for a campus.',tags:['Facilities','Planned upkeep'],duration:'Recurring contract'},
 {id:'demo-hotel',sector:'Hospitality',title:'Guest-room refresh programme',scope:'Illustrative scope: organise room-by-room repairs, painting and final quality checks around property access windows.',tags:['Renovation','Quality checks'],duration:'Phased delivery'},
 {id:'demo-home',sector:'Home services',title:'Community maintenance team',scope:'Illustrative scope: assemble a team for regular plumbing, electrical and common-area maintenance.',tags:['Maintenance','Team-based'],duration:'Long-term service'},
];
type Tender={id:string;title:string;city:string;sector:string;status:string;scope:string;site:string;budget_paise:number;manpower_needed:number;bids_count:number;opens_at:number;deadline:number;starts_at:number;ends_at:number;terms:string};
type Overview={contracts:{id:string;title:string;sector:string;city:string;status:string}[];leaders:{id:string;name:string;city:string;completed:number}[]};
export function TendersPlatform({onOpenContractorPortal,onOpenB2BMarket}:{onOpenContractorPortal:()=>void;onOpenB2BMarket?:()=>void}){
 const [showSectors,setShowSectors]=useState(false),[savedSectors,setSavedSectors]=useState<string[]>([]);
 useEffect(()=>{let active=true;const load=()=>{void apiFetch('/api/operations/contractor/sectors',{}, {background:true}).then(async r=>{if(r.ok&&active)setSavedSectors((await r.json()).sectors);}).catch(()=>{});};load();window.addEventListener('focus',load);return()=>{active=false;window.removeEventListener('focus',load);};},[]);
 const [rows,setRows]=useState<Tender[]>([]),[query,setQuery]=useState(''),[sector,setSector]=useState('All sectors'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[access,setAccess]=useState(false),[selected,setSelected]=useState<Tender|null>(null),[demo,setDemo]=useState<typeof demos[number]|null>(null),[overview,setOverview]=useState<Overview>({contracts:[],leaders:[]}),[estimate,setEstimate]=useState(false),[quote,setQuote]=useState(''),[cost,setCost]=useState(''),[reserve,setReserve]=useState('');
 useEffect(()=>{const controller=new AbortController();void(async()=>{try{
   await auth.authStateReady();const token=await auth.currentUser?.getIdToken();
   const results=await Promise.allSettled([apiFetch('/api/operations/contractor/overview',{signal:controller.signal}),apiFetch('/api/operations/contractor/opportunities',{signal:controller.signal,headers:token?{Authorization:`Bearer ${token}`}:{}})]);
   const publicResult=results[0];if(publicResult.status==='fulfilled'&&publicResult.value.ok)setOverview(await publicResult.value.json());else throw Error('Project overview could not load.');
   const privateResult=results[1];if(privateResult.status==='fulfilled'){if(privateResult.value.ok){setRows((await privateResult.value.json()).tenders);setAccess(true);}else if(![401,403].includes(privateResult.value.status))throw Error('Tender opportunities could not load.');}else if(!controller.signal.aborted)throw Error('Tender access could not be checked.');
 }catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setBusy(false);}})();return()=>controller.abort();},[]);
 const extraSectors=[...new Set([...savedSectors,...rows.map(t=>t.sector)])].filter(s=>!sectors.some(c=>c.name===s));
 const filtered=rows.filter(t=>(sector==='All sectors'||t.sector===sector)&&`${t.title} ${t.city} ${t.sector}`.toLowerCase().includes(query.toLowerCase()));
 const preview=demos.filter(t=>sector==='All sectors'||t.sector===sector);
 const amount=Number(quote)-Number(cost)-Number(reserve),valid=quote!==''&&cost!==''&&Number(quote)>0&&Number(cost)>=0&&Number(reserve)>=0;
 return <section className="tender-market">
 <header className="tender-hero"><span className="tender-eyebrow"><Gavel size={13}/> REPAIDO BUSINESS</span><h1>Build your next opportunity.</h1><p>Find the right scope. Plan your team. Bid with clarity.</p><div className="tender-hero-actions"><button onClick={onOpenContractorPortal}>{access?'Contractor workspace':'Create contractor profile'}<ArrowUpRight size={14}/></button>{onOpenB2BMarket&&<button onClick={onOpenB2BMarket} className="tender-hero-b2b-btn" title="Purchase bulk raw materials & commercial equipment for your tender or contract"><Boxes size={14}/>Procure tender raw materials</button>}<button onClick={()=>setEstimate(true)}><Calculator size={14}/>Plan a bid</button></div><div className="tender-trust"><span><ShieldCheck size={12}/>Reviewed contractors</span><span><Users size={12}/>Team planning</span><span><Clock size={12}/>Tracked milestones</span></div></header>
 <div className="tender-section-heading tender-sector-heading"><h2>{20+extraSectors.length} business sectors</h2><button aria-expanded={showSectors} aria-controls="contract-sector-options" onClick={()=>setShowSectors(v=>!v)}>{showSectors?'Compact rail':'Show all sectors'}</button></div><nav id="contract-sector-options" className={`tender-sector-rail ${showSectors?'tender-sector-grid':''}`} aria-label="Contract sectors">{sectors.map(({name,Icon})=><button key={name} aria-pressed={sector===name} onClick={()=>setSector(name)}><Icon size={18}/><span>{name}</span></button>)}{extraSectors.map(name=><button key={name} aria-pressed={sector===name} onClick={()=>setSector(name)}><Gavel size={18}/><span>{name}</span></button>)}</nav>
 <div className="tender-sector-note">{sectors.find(s=>s.name===sector)?.copy||'Explore published opportunities for this trade.'}</div>
 {busy&&<p className="tender-loading" role="status">Checking project opportunities…</p>}{error&&<p role="alert" className="tender-notice">{error} Refresh to retry.</p>}
 {!busy&&!access&&<section className="tender-access"><LockKeyhole size={20}/><div><h2>Contractor access</h2><p>Create your contractor profile and complete approval to view tender scopes, register interest and bid.</p></div><button onClick={onOpenContractorPortal} aria-label="Open contractor registration"><ChevronRight size={18}/></button></section>}
 {access&&<section><div className="tender-section-heading"><h2>Live tenders</h2><span>{filtered.length} opportunities</span></div><label className="tender-search"><Search size={15}/><input aria-label="Search contract opportunities" placeholder="Search city, trade or project" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="tender-cards">{filtered.map(t=><article className="tender-opportunity" key={t.id}><span className="tender-status">{t.status==='open'?(Date.now()/1000<t.opens_at?'Upcoming':Date.now()/1000>=t.deadline?'Awaiting decision':'Open for bidding'):t.status}</span><h3>{t.title}</h3><p><MapPin size={12}/>{t.city} · {t.sector}</p><strong>₹{(t.budget_paise/100).toLocaleString('en-IN')}</strong><small>Published budget · not guaranteed earnings</small><div className="tender-facts"><span><Users size={12}/>{t.manpower_needed} people</span><span>{t.bids_count} bids</span></div><button onClick={()=>setSelected(t)}>Scope & eligibility<ChevronRight size={14}/></button></article>)}</div>{!busy&&!filtered.length&&<p className="tender-notice">No matching live tenders. Explore project examples below or prepare your contractor profile.</p>}</section>}
 <section><div className="tender-section-heading"><h2>Explore contract models</h2><span>Illustrative demos</span></div><div className="tender-cards">{preview.map((p,i)=>{const Icon=sectors.find(s=>s.name===p.sector)!.Icon;return <article className={`tender-example tender-tone-${i%4}`} key={p.id}><div className="tender-example-top"><Icon size={23}/><span>DEMO · NOT OPEN FOR BIDS</span></div><small>{p.sector}</small><h3>{p.title}</h3><div className="tender-facts">{p.tags.map(t=><span key={t}>{t}</span>)}</div><p><Clock size={12}/>{p.duration}</p><button onClick={()=>setDemo(p)}>Explore scope<ChevronRight size={14}/></button></article>})}</div>{!preview.length&&<p className="tender-notice">No illustrative models for this trade yet.</p>}</section>
 <section><div className="tender-section-heading"><h2>Contracts in progress</h2><span>Platform records</span></div>{overview.contracts.filter(p=>(sector==='All sectors'||p.sector===sector)).map(p=><details className="tender-record" key={p.id}><summary>{p.title}<span>{p.status}</span></summary><p>{p.sector} · {p.city}</p></details>)}{!overview.contracts.some(p=>sector==='All sectors'||p.sector===sector)&&<p className="tender-notice">Awarded contract updates will appear here when available.</p>}</section>
 <section className="tender-leaders"><div className="tender-section-heading"><h2><Trophy size={16}/>Contractor leaderboard</h2></div><p>Ranked by recorded completed contracts awarded through Repaido.</p>{overview.leaders.map((p,i)=><div className="tender-leader" key={p.id}><b>#{i+1}</b><span><strong>{p.name}</strong><small>{p.city}</small></span><span>{p.completed}<small>completed</small></span></div>)}{!overview.leaders.length&&<p className="tender-notice">Rankings appear after completed awarded contracts are recorded. No ratings or success figures are estimated.</p>}</section>
 <details className="tender-record"><summary>From profile to project delivery<ChevronRight size={14}/></summary><ol><li>Create a contractor profile and complete review.</li><li>Review the scope, deadlines, terms and team requirements.</li><li>Invite agents; confirm their acceptance and availability.</li><li>Submit a costed proposal. Award decisions belong to the project owner.</li><li>Track goals, attendance and delivery in your workspace.</li></ol></details>
 {demo&&<Modal title={demo.title} className="tender-modal" onClose={()=>setDemo(null)}><span className="tender-status">Illustrative demo · no live client or bid</span><p>{demo.scope}</p><details open><summary>Plan before you quote</summary><ul><li>Confirm site access and the final work schedule.</li><li>Estimate labour, materials, travel and contingency.</li><li>Check team availability and agreed payment terms.</li></ul></details><button onClick={()=>{setDemo(null);setEstimate(true);}}>Open bid planner</button></Modal>}
 {estimate&&<Modal title="Bid planner" className="tender-modal" onClose={()=>setEstimate(false)}><p>Use your own estimates. This does not submit a bid.</p>{[['Your quote (₹)',quote,setQuote],['Estimated total costs (₹)',cost,setCost],['Contingency reserve (₹)',reserve,setReserve]].map(([label,value,setter])=><label key={label as string}>{label as string}<input type="number" min="0" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}{valid&&<output className="tender-estimate"><strong>₹{amount.toLocaleString('en-IN')}</strong> estimated balance · {(amount/Number(quote)*100).toFixed(1)}% of quote</output>}<small>Quote − costs − contingency. Include applicable taxes, fees and all delivery costs in your estimate. Actual profit can differ.</small></Modal>}
 {selected&&<Modal title={selected.title} className="tender-modal" onClose={()=>setSelected(null)}><details open><summary>Scope & location</summary><p>{selected.scope}</p><p>{selected.site}</p></details><details><summary>Dates & terms</summary><p>Bidding: {new Date(selected.opens_at*1000).toLocaleString('en-IN')} — {new Date(selected.deadline*1000).toLocaleString('en-IN')}</p><p>Work: {new Date(selected.starts_at*1000).toLocaleString('en-IN')} — {new Date(selected.ends_at*1000).toLocaleString('en-IN')}</p><p>{selected.terms}</p></details><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}><button onClick={onOpenContractorPortal} style={{flex:1}}>Prepare team & bid<ArrowUpRight size={14}/></button>{onOpenB2BMarket&&<button onClick={()=>{setSelected(null);onOpenB2BMarket();}} style={{flex:1,background:'linear-gradient(135deg,#059669,#047857)',color:'#fff',border:'none',boxShadow:'0 2px 8px rgba(5,150,105,0.25)'}} title="Source bulk raw materials and equipment"><Boxes size={14}/>Procure tender materials</button>}</div></Modal>}
 </section>;
}
