import {useEffect,useState} from 'react';
import {Bell,BellOff} from 'lucide-react';
import {bindTransportBell,transportBellEnabled,subscribeTransportBell,enableTransportBell,disableTransportBell} from '../services/transportBell';
import {enableWorkPush,disableWorkPush,workPushStatus,type WorkPushStatus} from '../services/repaidiansPushService';
import {enableNativePush,nativeAvailable} from '../services/native';
import {ContractError,useCustomContractAction} from './customContractUI';

export function TransportNotificationSettings({accountKey}:{accountKey:string}){
 const [sound,setSound]=useState(false),[push,setPush]=useState<WorkPushStatus|null>(null),[nativeEnabled,setNativeEnabled]=useState(false);const action=useCustomContractAction();
 useEffect(()=>{bindTransportBell(accountKey);setSound(transportBellEnabled());setNativeEnabled(false);const unsubscribe=subscribeTransportBell(()=>setSound(transportBellEnabled()));let alive=true;if(!nativeAvailable())void workPushStatus().then(next=>{if(alive)setPush(next);}).catch(()=>{});return()=>{alive=false;unsubscribe();};},[accountKey]);
 return <section className="transport-notification-settings" aria-label="Ride notification settings"><h3>Ride notifications</h3><p>Receive departure reminders, time changes and join requests.</p><div className="transport-setting-row"><div><strong>Sound while this app is open</strong><small>Enable sound for this session. Your device controls volume and Do Not Disturb.</small></div><button disabled={action.busy} aria-pressed={sound} onClick={()=>void action.run(async()=>{if(sound)disableTransportBell();else await enableTransportBell(accountKey);})}>{sound?<BellOff size={17}/>:<Bell size={17}/>} {sound?'Turn bell off':'Enable request bell'}</button></div>{sound&&<p role="status">Request bell on</p>}<div className="transport-setting-row"><div><strong>Push notifications</strong><small>{nativeAvailable()?'Receive alerts through the Android app.':'Receive alerts when this browser is in the background. Sound follows browser and device settings.'}</small></div>{nativeAvailable()?<button disabled={action.busy} onClick={()=>void action.run(async()=>{await enableNativePush();setNativeEnabled(true);},'Device notifications enabled.')}>{nativeEnabled?'Reconnect push notifications':'Enable push notifications'}</button>:push?.supported?<button disabled={action.busy} onClick={()=>void action.run(async()=>setPush(await(push.enabled?disableWorkPush():enableWorkPush())))}>{push.enabled?'Disable push notifications':'Enable push notifications'}</button>:<p>{push?'Push is unavailable in this browser. Updates remain in your notification bell.':'Checking browser support…'}</p>}</div>{push?.enabled&&<p role="status">Push notifications are enabled for this account.</p>}<ContractError error={action.error}/>{action.message&&<p role="status">{action.message}</p>}</section>;
}
