import {OnboardingSelfie} from './OnboardingSelfie';
import { apiFetch } from '../services/api';
import {useEffect,useState} from 'react';
import {auth} from '../firebase';
import {operation,money} from '../services/operations';

const documentSteps=[{kind:'identity',title:'Identity proof',hint:'Masked Aadhaar or another accepted government identity document.',icon:'ID'},{kind:'pan',title:'PAN card',hint:'A clear photo or PDF of your PAN card.',icon:'PAN'},{kind:'address',title:'Address proof',hint:'An accepted document showing your name and current address.',icon:'HOME'},{kind:'tools',title:'Tools photo',hint:'A clear photo of the tools you will use for your service.',icon:'KIT'}];
type Verification={documents:{id:string;kind:string;status:string;created_at:number;expires_at:number}[];verification:{identity_status:string;bank_status:string;review_reason?:string;submitted_at?:number};onboarding:{state:string;missing_documents:string[];completed_documents:number;required_documents:number;has_selfie:boolean;can_submit:boolean;review_reason?:string};private_documents:boolean};
export function VerificationPanel({onUpdated}:{onUpdated?:()=>void}){
 const [data,setData]=useState<Verification|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[consent,setConsent]=useState(false),[files,setFiles]=useState<Record<string,File|null>>({}),[reset,setReset]=useState<Record<string,number>>({});
 const load=async()=>{try{setData(await operation('/worker/verification'));setError('');}catch(e){setError((e as Error).message);}};
 useEffect(()=>{void load();const refresh=()=>{if(!document.hidden)void load();};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
 const upload=async(kind:string)=>{const file=files[kind];if(!file)return;setBusy(kind);setError('');setMessage('');try{if(file.size>5*1024*1024)throw new Error('Choose a file smaller than 5 MB.');const token=await auth.currentUser?.getIdToken();const r=await apiFetch(`/api/operations/worker/documents/${kind}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':file.type,'X-Verification-Consent':'private-review-v1'},body:file,signal:AbortSignal.timeout(60000)});const body=await r.json();if(!r.ok)throw new Error(body.detail?.message||'Upload failed. Your other uploads are saved; retry this file.');setFiles(f=>({...f,[kind]:null}));setReset(x=>({...x,[kind]:(x[kind]||0)+1}));await load();setMessage(`${documentSteps.find(d=>d.kind===kind)?.title} uploaded and saved.`);}catch(e){setError((e as Error).message);}finally{setBusy('');}};
 const pending=data?.onboarding.state!=='approved';
 return <section className="ops-card worker-verification" aria-label="Complete your onboarding"><div className="verification-heading"><div><span className="ops-eyebrow">Step 2 of 3 · Documents</span><h2>{pending?'Finish your application':'Your verification'}</h2></div><button disabled={!!busy} onClick={()=>void load()}>Refresh</button></div>
 {error&&<p className="ops-error" role="alert">{error}</p>}{message&&<p role="status" className="verification-success">{message}</p>}{data?<><div className={`onboarding-status-note ${data.onboarding.state==='approved'?'complete':''}`} role="status"><strong>{({missing_documents:'Action needed: upload your missing documents',needs_changes:'Your application needs an update',ready_to_submit:'Documents saved. Send your application for review.',in_review:'Application submitted — team review pending',approved:'Your joining application is approved'})[data.onboarding.state]||'Continue your application'}</strong><p>{data.onboarding.missing_documents.length?`Still needed: ${documentSteps.filter(d=>data.onboarding.missing_documents.includes(d.kind)).map(d=>d.title).join(', ')}.`:data.onboarding.state==='in_review'?'You can sign out safely. Your application and uploads are saved.':'Your saved details stay with this mobile account.'}</p>{data.onboarding.review_reason&&<p><strong>Reviewer’s note:</strong> {data.onboarding.review_reason}</p>}</div>
 {pending&&<><div className="verification-progress"><label htmlFor="onboarding-progress">{data.onboarding.completed_documents} of 4 required document types uploaded</label><progress id="onboarding-progress" max={4} value={data.onboarding.completed_documents}/></div><p className="ops-help">Upload each file under its matching heading. You can leave now and return with the same mobile number to continue.</p>
 <label className="ops-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to private review by the Repaido team and the 30-day document retention period.</label>
 <div className="verification-document-grid">{documentSteps.map(step=>{const received=data.documents.filter(d=>d.kind===step.kind&&d.status==='pending_review'&&d.expires_at>Date.now()/1000);return <article key={step.kind} className={`verification-upload-card ${received.length?'received':''}`}><div className="verification-card-title"><span className="verification-doc-icon" aria-hidden="true">{step.icon}</span><div><h3>{step.title}</h3><span className="verification-file-state">{received.length?'✓ Uploaded':'Upload needed'}</span></div></div><p>{step.hint}</p>{received.length>0&&<p className="ops-help">Saved {new Date(Math.max(...received.map(d=>d.created_at))*1000).toLocaleDateString()}. You may add a clearer copy.</p>}<label>{received.length?'Add another copy':'Choose file'}<input key={step.kind+(reset[step.kind]||0)} type="file" accept="image/jpeg,image/png,application/pdf" disabled={!!busy||!data.private_documents} onChange={e=>setFiles(f=>({...f,[step.kind]:e.target.files?.[0]||null}))}/></label><span className="ops-help">JPG, PNG or PDF · up to 5 MB</span><button disabled={!!busy||!consent||!files[step.kind]||!data.private_documents} onClick={()=>void upload(step.kind)}>{busy===step.kind?'Uploading…':`Upload ${step.title.toLowerCase()}`}</button></article>;})}</div>
 {!data.private_documents&&<p role="alert">Private upload is temporarily unavailable. Your profile is saved. Retry later; do not send documents in chat.</p>}
 <div className="verification-selfie"><h3>{data.onboarding.has_selfie?'✓ Identity photo saved':'Identity photo'}</h3><OnboardingSelfie consent={consent} onSaved={load}/><p className="ops-help">Unable to use a camera? You can submit the four required document types; the team will arrange a manual identity check before approval.</p></div>
 <div className="verification-submit"><span className="ops-eyebrow">Step 3 of 3 · Team review</span><h3>{data.onboarding.state==='in_review'?'You’re in the review queue':'Ready for the Repaido team?'}</h3><p>{data.onboarding.missing_documents.length?'Complete the missing uploads above to submit.':'Check your details and document photos before submitting. The team must approve your identity before you receive work.'}</p><button className="ops-primary" disabled={!!busy||!data.onboarding.can_submit||data.onboarding.state==='in_review'} onClick={async()=>{setBusy('submit');setError('');try{await operation('/worker/verification/submit',{method:'POST'});await load();setMessage("Application sent for review. We’ll show the decision here.");onUpdated?.();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>{busy==='submit'?'Sending…':data.onboarding.state==='in_review'?'Submitted for review':'Submit application for review'}</button></div></>}
 <details className="verification-privacy"><summary>Privacy & payouts</summary><p>Only authorized Repaido reviewers can access your documents. Copies expire after 30 days; review and audit records remain. Use masked Aadhaar where available. No automated face recognition. Never upload bank passwords, PINs or OTPs.</p><p>Bank verification is separate from joining approval. Payouts stay held until your bank account is verified.</p></details></>:<p role="status">Loading your saved application…</p>}</section>;
}

type Policy={version:string;worker_share_bps:number;penalty_cap_bps:number;stack_penalties:boolean;penalty_mode?:string;bonus_reserve_bps?:number};
export function WorkerEarnings(){
 const [data,setData]=useState<{policy:Policy|null;settlements:{id:string;gross_paise:number;deduction_paise:number;net_paise:number;status:string}[]}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>operation<NonNullable<typeof data>>('/worker/earnings').then(setData).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[]);
 return <section className="ops-card"><h2>Earnings and deductions</h2>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{data?.policy?<><p>Policy {data.policy.version}: {data.policy.worker_share_bps/100}% of the base service fee is your regular share. Parts charges are separate.</p><p>{data.policy.penalty_mode==='highest_single'?'Only the highest applicable deduction is applied: the reduction to 50% of the base fee or an attendance penalty. Penalties do not stack.':`Attendance deductions are capped at ${data.policy.penalty_cap_bps/100}% of eligible earnings.`} Deductions reduce payable earnings and credit the company ledger; they do not debit your bank account.</p><p>10% of the base fee is held in a bonus reserve. Awards need at least 5 paid completed tasks, 3 recent verified reviews averaging 4.2+, and reliable responses. The wallet shows the exact next milestone and unlock date.</p><button disabled={busy} onClick={async()=>{setBusy(true);try{await operation('/worker/settlement-policy/accept',{method:'POST',body:JSON.stringify({version:data.policy!.version,consent:true})});setMessage('Policy accepted for future assignments. Existing agreements are unchanged.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Accept this policy for future tasks</button></>:<p>The earnings policy is awaiting activation. No monetary deduction or payout is available yet.</p>}{data?.settlements.map(s=><div className="ops-bill" key={s.id}><p>Booking {s.id.slice(0,8)} · {s.status}</p><div>Regular earnings<strong>{money(s.gross_paise)}</strong></div><div>Company deduction<strong>{money(s.deduction_paise)}</strong></div><div>Amount to receive<strong>{money(s.net_paise)}</strong></div></div>)}{data&&!data.settlements.length&&<p>No settled earnings yet. Completed, paid tasks appear here after settlement.</p>}</section>;
}
