import {auth} from '../firebase';
import {startTaskBell} from '../services/taskBell.mjs';
import {useEffect,useRef,useState} from 'react';
import {operation,type Job} from '../services/operations';

/** Kept mounted across worker tabs. Sound requires a deliberate browser gesture. */
export function WorkerAssignmentAlerts({onOpen}:{onOpen:(id:string)=>void}){
 const [jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[sound,setSound]=useState(false),[muted,setMuted]=useState<string[]>([]),[now,setNow]=useState(Date.now()/1000);
 const audio=useRef<AudioContext|null>(null),inflight=useRef(false),offset=useRef(0);
 const refresh=async()=>{if(inflight.current)return;inflight.current=true;try{const r=await operation<{jobs:Job[]}>('/jobs',{}, {background:true});if(r.jobs[0])offset.current=r.jobs[0].server_time-Date.now()/1000;const hires=await operation<{requests:{id:string;worker_id:string;state:string;category:string;offer_expires_at:number;starts_at:string}[]}>('/hiring/requests',{}, {background:true});const hiring=hires.requests.filter(h=>h.worker_id===auth.currentUser?.uid&&h.state==='offered').map(h=>({id:'hire:'+h.id,state:'offered',service_name:'Day hire · '+h.category,offer_expires_at:h.offer_expires_at,starts_at:h.starts_at,allowed_actions:['accept'],reminder_at:0} as Job));setJobs([...r.jobs,...hiring]);setNow(Date.now()/1000+offset.current);setError('');}catch(e){setError((e as Error).message);}finally{inflight.current=false;}};
 useEffect(()=>{void refresh();const poll=setInterval(()=>{if(!document.hidden)void refresh();},5000);const clock=setInterval(()=>setNow(Date.now()/1000+offset.current),1000);const focus=()=>{if(!document.hidden)void refresh();};document.addEventListener('visibilitychange',focus);window.addEventListener('focus',focus);window.addEventListener('repaido:job-updated',focus);return()=>{clearInterval(poll);clearInterval(clock);document.removeEventListener('visibilitychange',focus);window.removeEventListener('focus',focus);window.removeEventListener('repaido:job-updated',focus);void audio.current?.close();};},[]);
 const offers=jobs.filter(j=>(j.state==='offered'&&j.allowed_actions.includes('accept')&&(j.offer_expires_at||0)>now)||j.allowed_actions.includes('ack_reminder')||j.state==='arrived');
 const key=(j:Job)=>`${j.id}:${j.visit_id}:${j.state}:${j.offer_expires_at||j.reminder_at}`;
 const attention=offers.find(j=>!muted.includes(key(j))),alertKey=attention?key(attention):'';
 useEffect(()=>{if(!sound||!alertKey||error)return;return startTaskBell(audio.current);},[sound,alertKey,error]);
 const enable=async()=>{try{audio.current ||= new AudioContext();await audio.current.resume();if(audio.current.state!=='running')throw Error('Sound is blocked. Enable this site’s audio permission and try again.');setSound(true);}catch(e){setError((e as Error).message);}};
 useEffect(()=>{const unlock=()=>{if(audio.current?.state!=='running')void enable();};document.addEventListener('pointerdown',unlock,{capture:true});document.addEventListener('keydown',unlock,{capture:true});return()=>{document.removeEventListener('pointerdown',unlock,{capture:true});document.removeEventListener('keydown',unlock,{capture:true});};},[]);
 if(!offers.length&&!error)return null;
 return <section className="worker-incoming" aria-label="Incoming task alerts">{error&&<div role="alert" className="ops-error">{error}<button onClick={()=>void refresh()}>Retry task updates</button></div>}{offers.length>0&&<div role="status">{offers.length} task{offers.length===1?'':'s'} need your response</div>}{offers.length>0&&!sound&&<button onClick={()=>void enable()}>Enable request bell</button>}{offers.map(j=><div className="ops-attention" key={key(j)}><div><strong>{j.state==='offered'?'New task request':j.state==='arrived'?'You are almost there':'Visit reminder'} · {j.service_name}</strong><p>{j.state==='offered'?`Respond within ${Math.max(0,Math.ceil(((j.offer_expires_at||0)-now)/60))} min`:j.state==='arrived'?'Arrival area reached. Continue with the customer code.':'Acknowledge that you are ready for this visit'} · {new Date(j.starts_at).toLocaleString()}</p></div><button className="ops-primary" onClick={()=>onOpen(j.id)}>Review task</button><button onClick={()=>setMuted(v=>[...v,key(j)])} disabled={muted.includes(key(j))}>{muted.includes(key(j))?'Bell silenced':'Silence this bell'}</button></div>)}</section>;
}
