import {useEffect,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Star,Wallet,RefreshCw} from 'lucide-react';
import {auth} from '../firebase';
import {money,operation} from '../services/operations';
import {Modal} from './ui';
import {TaskReport,type RecordRow} from './WorkerRecords';
import './worker-dashboard.css';
type Day={date:string;tasks:RecordRow[];presence:{at:number;online:boolean;kind:string}[];points:number;earned_paise:number;paid_paise:number;deduction_paise:number;completed:number;tone:string;online_recorded:boolean;offline_recorded:boolean};
type CalendarData={month:string;days:Day[];score:number|null;score_note:string;components:{label:string;weight:number;value:number;count:number}[];suggestions:string[];summary:{completed:number;points:number;earned_paise:number;paid_paise:number;deduction_paise:number;online_days:number;offline_days:number;working_days:number}};
const calendarCache=new Map<string,{data:CalendarData;at:number}>();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const label=(v:string)=>v.replaceAll('_',' ');
const dayMarks:Record<string,string>={earning:'E',mixed:'E/D',penalty:'D',worked:'C',online:'On',offline:'Off',scheduled:'T',unknown:'—'};
const date=(v:string)=>new Date(v+'T12:00:00+05:30').toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'long',year:'numeric'});
export function WorkerCalendar({compact=false,onActive}:{compact?:boolean;onActive:()=>void}){
 const [month,setMonth]=useState(()=>today().slice(0,7)),[data,setData]=useState<CalendarData|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setError('');const key=`${auth.currentUser?.uid}:${month}`,cached=calendarCache.get(key);setData(cached?.data||null);if(cached&&Date.now()-cached.at<60000&&revision===0)return;void operation<CalendarData>(`/worker/calendar?month=${month}`,{}, {background:true}).then(d=>{calendarCache.set(key,{data:d,at:Date.now()});if(live)setData(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[month,revision]);
 useEffect(()=>{const update=()=>{calendarCache.clear();setRevision(v=>v+1);};window.addEventListener('repaido:job-updated',update);return()=>window.removeEventListener('repaido:job-updated',update);},[]);
 const shift=(n:number)=>{const d=new Date(month+'-15T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));setSelected(null);};
 const selectedDay=data?.days.find(d=>d.date===selected);
 const monthTitle=new Date(month+'-15T12:00:00Z').toLocaleDateString('en-IN',{month:'long',year:'numeric'});
 const rows=data?Array.from(new Map(data.days.flatMap(d=>d.tasks).map(t=>[t.id,t])).values()).sort((a,b)=>b.starts_at.localeCompare(a.starts_at)):[];
 return <section className={`worker-calendar ${compact?'is-compact':''}`} aria-label="Work calendar and records">
  <header className="work-section-title"><div><span className="work-kicker">Your work record</span><h2><CalendarDays size={18}/> Calendar & earnings</h2></div><button aria-label="Refresh work records" onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/></button></header>
  <div className="work-month"><button aria-label="Previous month" onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><label><span className="sr-only">Calendar month</span><input type="month" min="2000-01" max={today().slice(0,7)} value={month} onChange={e=>{if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(e.target.value)){setMonth(e.target.value);setSelected(null);}}}/></label><button aria-label="Next month" disabled={month>=today().slice(0,7)} onClick={()=>shift(1)}><ChevronRight size={18}/></button></div>
  {error&&<p role="alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}
  {!data&&!error&&<p role="status">Loading work records…</p>}
  {data&&<><div className="work-month-metrics"><span><Wallet size={15}/>Calculated<strong>{money(data.summary.earned_paise)}</strong></span><span>Paid this month<strong>{money(data.summary.paid_paise)}</strong></span><span><Star size={15}/>Task points<strong>{data.summary.points}</strong></span></div>
   <div className="work-calendar-grid" role="group" aria-label={monthTitle+' · India time'}>{['M','T','W','T','F','S','S'].map((v,i)=><span className="weekday" key={i} aria-hidden="true">{v}</span>)}{Array.from({length:(new Date(month+'-01T12:00:00Z').getUTCDay()+6)%7},(_,i)=><span key={'pad'+i}/>)}{data.days.map(d=><button key={d.date} data-tone={d.tone} aria-current={d.date===today()?'date':undefined} aria-label={`${date(d.date)}: ${label(d.tone)}, ${d.tasks.length} task records, ${d.points} points`} onClick={()=>setSelected(d.date)}><span>{Number(d.date.slice(-2))}</span><small>{d.points?`+${d.points}`:d.tasks.length?`${d.tasks.length} task${d.tasks.length===1?'':'s'}`:dayMarks[d.tone]||'—'}</small></button>)}</div>
   <div className="work-legend">{[['earning','Earnings'],['mixed','Earnings + deduction'],['penalty','Deduction'],['worked','Completed'],['online','Online check'],['offline','Offline set'],['scheduled','Task'],['unknown','No record']].map(([tone,text])=><span key={tone}><i data-tone={tone} aria-hidden="true">{dayMarks[tone]}</i>{text}</span>)}</div>
   <p className="work-footnote">India time · Availability checks are recorded moments, not hours. Unrecorded days are never assumed offline.</p>
   <details className="work-accordion" open={!compact}><summary><span>Monthly quality score <small>Target 85% · {data.summary.completed} completed</small></span><strong>{data.score===null?'—':`${data.score}%`}</strong></summary><p>{data.score_note}</p>{data.components.map(c=><div className="work-score-row" key={c.label}><span>{c.label}<small>{c.count} records · {c.weight}% weight</small></span><strong>{c.value}%</strong></div>)}<dl className="work-day-stats"><div><dt>Worked days</dt><dd>{data.summary.working_days}</dd></div><div><dt>Online days recorded</dt><dd>{data.summary.online_days}</dd></div><div><dt>Offline changes recorded</dt><dd>{data.summary.offline_days}</dd></div><div><dt>Calculated deductions</dt><dd>{money(data.summary.deduction_paise)}</dd></div></dl><h3>Next steps</h3><ul>{data.suggestions.map(t=><li key={t}>{t}</li>)}</ul></details>
   <details className="work-accordion"><summary><span>Work, payments & reviews<small>{rows.length} task records this month</small></span><ChevronRight size={16}/></summary>{!rows.length&&<p>No recorded work this month.</p>}{rows.map(t=><TaskAccordion key={t.id} task={t} onActive={onActive}/>)}</details>
  </>}
  {selectedDay&&<Modal title={date(selectedDay.date)} className="worker-day-modal" onClose={()=>setSelected(null)}><div className="worker-day-detail"><div className="work-month-metrics"><span>Calculated<strong>{money(selectedDay.earned_paise)}</strong></span><span>Paid<strong>{money(selectedDay.paid_paise)}</strong></span><span>Task points<strong>{selectedDay.points}</strong></span></div><p className="work-footnote">Earnings belong to completed-work dates; payouts belong to their bank confirmation date. A completed task is not proof of payment.</p><details className="work-accordion"><summary>Availability · {selectedDay.presence.length} records</summary>{!selectedDay.presence.length?<p>No availability records for this day.</p>:<ol className="work-presence-list">{selectedDay.presence.map((p,i)=><li key={i}><time>{new Date(p.at*1000).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'})}</time><span>{p.online?'Online':'Offline'} · {p.kind==='location_check'?'location refreshed':'status changed'}</span></li>)}</ol>}</details><h3>Tasks & timeline</h3>{!selectedDay.tasks.length&&<p>No task activity recorded for this day.</p>}{selectedDay.tasks.map(t=><TaskAccordion key={t.id} task={t} onActive={()=>{setSelected(null);onActive();}}/>)}</div></Modal>}
 </section>;
}
function TaskAccordion({task:t,onActive}:{task:RecordRow;onActive:()=>void}){
 const [open,setOpen]=useState(false);
 return <details className="work-task-record" onToggle={e=>setOpen(e.currentTarget.open)}><summary><span>{t.service_name}<small>{label(t.state)} · {t.points_awarded||0} task points{t.review?` · ★ ${t.review.rating}`:''}</small></span><ChevronRight size={16}/></summary><p>{new Date(t.starts_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · India time</p>{t.schedule_history?.map((h,i)=><p key={i}>Rescheduled: {new Date(h.from).toLocaleString('en-IN')} → {new Date(h.to).toLocaleString('en-IN')}</p>)}{t.completed_at&&<p>Completed {new Date(t.completed_at*1000).toLocaleString('en-IN')}</p>}{!['completed','cancelled'].includes(t.state)&&<button onClick={onActive}>Continue in active tasks <ChevronRight size={16}/></button>}{open&&<TaskReport jobId={t.id}/>}</details>;
}
